/-
Generated by computer; every fact used is proved in Lean.
Certificates that `h mod 17` divides `X^(17^8) - X` and is coprime to `X^(17^4) - X`.
-/
module

public import X2Y5Z7.Fields.FrobeniusBridge

@[expose] public section

namespace X2Y5Z7
open Polynomial
noncomputable section

def f8R0 : P17 := X
private theorem f8Pow0 : h17 ∣ (X : P17)^1 - f8R0 := by simp [f8R0]
def f8R1 : P17 := X^3
private theorem f8Step1 : f8R0^2*X^1 - f8R1 = h17*(0) := by
  unfold f8R0 f8R1 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(0) + 17*(0) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow1 : h17 ∣ (X : P17)^3 - f8R1 := by
  have h := certificate_step _ _ _ _ 1 1 f8Pow0 f8Step1
  simp only [show 1*2+1 = 3 from by decide] at h
  exact h
def f8R2 : P17 := X^6
private theorem f8Step2 : f8R1^2*X^0 - f8R2 = h17*(0) := by
  unfold f8R1 f8R2 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(0) + 17*(0) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow2 : h17 ∣ (X : P17)^6 - f8R2 := by
  have h := certificate_step _ _ _ _ 3 0 f8Pow1 f8Step2
  simp only [show 3*2+0 = 6 from by decide] at h
  exact h
def f8R3 : P17 := 1 + (6)*X + (-3)*X^2 + (-3)*X^4 + (7)*X^5 + (6)*X^6 + (-6)*X^7
private theorem f8Step3 : f8R2^2*X^0 - f8R3 = h17*(1180 + (-120)*X + (44)*X^2 + (-4)*X^3 + X^4) := by
  unfold f8R2 f8R3 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(1180 + (-120)*X + (44)*X^2 + (-4)*X^3 + X^4) + 17*(65247 + (26682)*X + (-59261)*X^2 + (-31920)*X^3 + (11439)*X^4 + (9449)*X^5 + (1202)*X^6 + (-106)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow3 : h17 ∣ (X : P17)^12 - f8R3 := by
  have h := certificate_step _ _ _ _ 6 0 f8Pow2 f8Step3
  simp only [show 6*2+0 = 12 from by decide] at h
  exact h
def f8R4 : P17 := 8 + (5)*X^2 + (-1)*X^3 + (-5)*X^4 + (3)*X^5 + (-6)*X^6 + (2)*X^7
private theorem f8Step4 : f8R3^2*X^1 - f8R4 = h17*((-1789602) + (1055825)*X + (-139066)*X^2 + (48541)*X^3 + (-7176)*X^4 + (1824)*X^5 + (-216)*X^6 + (36)*X^7) := by
  unfold f8R3 f8R4 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*((-1789602) + (1055825)*X + (-139066)*X^2 + (48541)*X^3 + (-7176)*X^4 + (1824)*X^5 + (-216)*X^6 + (36)*X^7) + 17*((-98954464) + (7850973)*X + (110549391)*X^2 + (5538883)*X^3 + (-41672743)*X^4 + (-6909708)*X^5 + (5136344)*X^6 + (1327696)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow4 : h17 ∣ (X : P17)^25 - f8R4 := by
  have h := certificate_step _ _ _ _ 12 1 f8Pow3 f8Step4
  simp only [show 12*2+1 = 25 from by decide] at h
  exact h
def f8R5 : P17 := (-3) + (-8)*X + (4)*X^2 + (7)*X^3 + (3)*X^4 + X^5 + (4)*X^6 + (8)*X^7
private theorem f8Step5 : f8R4^2*X^1 - f8R5 = h17*((-827156) + (220251)*X + (-44034)*X^2 + (10001)*X^3 + (-1784)*X^4 + (320)*X^5 + (-40)*X^6 + (4)*X^7) := by
  unfold f8R4 f8R5 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*((-827156) + (220251)*X + (-44034)*X^2 + (10001)*X^3 + (-1784)*X^4 + (320)*X^5 + (-40)*X^6 + (4)*X^7) + 17*((-45736861) + (-11176404)*X + (44655268)*X^2 + (15674189)*X^3 + (-11707667)*X^4 + (-5436732)*X^5 + (217122)*X^6 + (246631)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow5 : h17 ∣ (X : P17)^51 - f8R5 := by
  have h := certificate_step _ _ _ _ 25 1 f8Pow4 f8Step5
  simp only [show 25*2+1 = 51 from by decide] at h
  exact h
def f8R6 : P17 := 1 + (-7)*X + (8)*X^2 + X^3 + (-5)*X^4 + (-2)*X^5 + X^6 + (3)*X^7
private theorem f8Step6 : f8R5^2*X^1 - f8R6 = h17*(1725558 + (1691787)*X + (-41990)*X^2 + (69161)*X^3 + (-4936)*X^4 + (2592)*X^5 + (-192)*X^6 + (64)*X^7) := by
  unfold f8R5 f8R6 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(1725558 + (1691787)*X + (-41990)*X^2 + (69161)*X^3 + (-4936)*X^4 + (2592)*X^5 + (-192)*X^6 + (64)*X^7) + 17*(95413207 + (142267508)*X + (-39816560)*X^2 + (-137797493)*X^3 + (-37764333)*X^4 + (28954716)*X^5 + (17243353)*X^6 + (2567702)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow6 : h17 ∣ (X : P17)^103 - f8R6 := by
  have h := certificate_step _ _ _ _ 51 1 f8Pow5 f8Step6
  simp only [show 51*2+1 = 103 from by decide] at h
  exact h
def f8R7 : P17 := (-7) + (-2)*X + (-8)*X^2 + (5)*X^3 + (-8)*X^4 + (7)*X^5 + (5)*X^6 + (-4)*X^7
private theorem f8Step7 : f8R6^2*X^1 - f8R7 = h17*(142802 + (229015)*X + (-9298)*X^2 + (9552)*X^3 + (-806)*X^4 + (361)*X^5 + (-30)*X^6 + (9)*X^7) := by
  unfold f8R6 f8R7 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(142802 + (229015)*X + (-9298)*X^2 + (9552)*X^3 + (-806)*X^4 + (361)*X^5 + (-30)*X^6 + (9)*X^7) + 17*(7896111 + (16695239)*X + (-1103918)*X^2 + (-15754460)*X^3 + (-5683446)*X^4 + (3128737)*X^5 + (2155549)*X^6 + (338739)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow7 : h17 ∣ (X : P17)^207 - f8R7 := by
  have h := certificate_step _ _ _ _ 103 1 f8Pow6 f8Step7
  simp only [show 103*2+1 = 207 from by decide] at h
  exact h
def f8R8 : P17 := (-3) + (-2)*X + (7)*X^2 + (-2)*X^3 + (8)*X^4 + (3)*X^5 + (-8)*X^6 + (-2)*X^7
private theorem f8Step8 : f8R7^2*X^1 - f8R8 = h17*((-895292) + (459350)*X + (-66226)*X^2 + (21709)*X^3 + (-3422)*X^4 + (833)*X^5 + (-104)*X^6 + (16)*X^7) := by
  unfold f8R7 f8R8 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*((-895292) + (459350)*X + (-66226)*X^2 + (21709)*X^3 + (-3422)*X^4 + (833)*X^5 + (-104)*X^6 + (16)*X^7) + 17*((-49504381) + (120523)*X + (53545933)*X^2 + (6125154)*X^3 + (-18808438)*X^4 + (-4006379)*X^5 + (1991198)*X^6 + (561061)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow8 : h17 ∣ (X : P17)^415 - f8R8 := by
  have h := certificate_step _ _ _ _ 207 1 f8Pow7 f8Step8
  simp only [show 207*2+1 = 415 from by decide] at h
  exact h
def f8R9 : P17 := (-1) + (6)*X + (-2)*X^2 + (-3)*X^3 + (-4)*X^4 + (-3)*X^5 + (-1)*X^6 + (3)*X^7
private theorem f8Step9 : f8R8^2*X^1 - f8R9 = h17*(710270 + (118648)*X + (21264)*X^2 + (3377)*X^3 + (640)*X^4 + (100)*X^5 + (16)*X^6 + (4)*X^7) := by
  unfold f8R8 f8R9 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(710270 + (118648)*X + (21264)*X^2 + (3377)*X^3 + (640)*X^4 + (100)*X^5 + (16)*X^6 + (4)*X^7) + 17*(39273753 + (26615219)*X + (-30569858)*X^2 + (-28472615)*X^3 + (1020924)*X^4 + (7152516)*X^5 + (2378331)*X^6 + (240905)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow9 : h17 ∣ (X : P17)^831 - f8R9 := by
  have h := certificate_step _ _ _ _ 415 1 f8Pow8 f8Step9
  simp only [show 415*2+1 = 831 from by decide] at h
  exact h
def f8R10 : P17 := (-6) + (2)*X + (4)*X^2 + (3)*X^3 + (-7)*X^4 + (6)*X^5 + (-6)*X^6 + (6)*X^7
private theorem f8Step10 : f8R9^2*X^1 - f8R10 = h17*((-161950) + (241954)*X + (-22082)*X^2 + (10663)*X^3 + (-1294)*X^4 + (403)*X^5 + (-42)*X^6 + (9)*X^7) := by
  unfold f8R9 f8R10 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*((-161950) + (241954)*X + (-22082)*X^2 + (10663)*X^3 + (-1294)*X^4 + (403)*X^5 + (-42)*X^6 + (9)*X^7) + 17*((-8954882) + (8805927)*X + (13612872)*X^2 + (-6654439)*X^3 + (-7983323)*X^4 + (578390)*X^5 + (1664224)*X^6 + (328233)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow10 : h17 ∣ (X : P17)^1663 - f8R10 := by
  have h := certificate_step _ _ _ _ 831 1 f8Pow9 f8Step10
  simp only [show 831*2+1 = 1663 from by decide] at h
  exact h
def f8R11 : P17 := (-8) + X + (-1)*X^2 + (3)*X^3 + (-8)*X^4 + (6)*X^5 + (-5)*X^6 + (6)*X^7
private theorem f8Step11 : f8R10^2*X^0 - f8R11 = h17*(1279741 + (-170568)*X + (56652)*X^2 + (-8076)*X^3 + (1980)*X^4 + (-216)*X^5 + (36)*X^6) := by
  unfold f8R10 f8R11 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(1279741 + (-170568)*X + (56652)*X^2 + (-8076)*X^3 + (1980)*X^4 + (-216)*X^5 + (36)*X^6) + 17*(70762152 + (26702455)*X + (-64917779)*X^2 + (-32575079)*X^3 + (13239940)*X^4 + (9818998)*X^5 + (1052834)*X^6 + (-142244)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow11 : h17 ∣ (X : P17)^3326 - f8R11 := by
  have h := certificate_step _ _ _ _ 1663 0 f8Pow10 f8Step11
  simp only [show 1663*2+0 = 3326 from by decide] at h
  exact h
def f8R12 : P17 := 3 + (-4)*X + X^2 + (8)*X^3 + (-6)*X^4 + (3)*X^5 + (-8)*X^6
private theorem f8Step12 : f8R11^2*X^0 - f8R12 = h17*(1245214 + (-155138)*X + (54724)*X^2 + (-7504)*X^3 + (1921)*X^4 + (-204)*X^5 + (36)*X^6) := by
  unfold f8R11 f8R12 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(1245214 + (-155138)*X + (54724)*X^2 + (-7504)*X^3 + (1921)*X^4 + (-204)*X^5 + (36)*X^6) + 17*(68853013 + (26580764)*X + (-62882672)*X^2 + (-32222954)*X^3 + (12555473)*X^4 + (9639103)*X^5 + (1116989)*X^6 + (-121702)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow12 : h17 ∣ (X : P17)^6652 - f8R12 := by
  have h := certificate_step _ _ _ _ 3326 0 f8Pow11 f8Step12
  simp only [show 3326*2+0 = 6652 from by decide] at h
  exact h
def f8R13 : P17 := 6 + X + (-6)*X^2 + (4)*X^3 + (5)*X^4 + (8)*X^5 + (-2)*X^6 + (-5)*X^7
private theorem f8Step13 : f8R12^2*X^1 - f8R13 = h17*((-192466) + (86624)*X + (-10376)*X^2 + (3113)*X^3 + (-304)*X^4 + (64)*X^5) := by
  unfold f8R12 f8R13 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*((-192466) + (86624)*X + (-10376)*X^2 + (3113)*X^3 + (-304)*X^4 + (64)*X^5) + 17*((-10642238) + (-644536)*X + (11382206)*X^2 + (1938974)*X^3 + (-3854725)*X^4 + (-1005715)*X^5 + (367884)*X^6 + (117909)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow13 : h17 ∣ (X : P17)^13305 - f8R13 := by
  have h := certificate_step _ _ _ _ 6652 1 f8Pow12 f8Step13
  simp only [show 6652*2+1 = 13305 from by decide] at h
  exact h
def f8R14 : P17 := 4 + (-4)*X^2 + (8)*X^3 + (-2)*X^4 + (-3)*X^5 + (-1)*X^6 + (-8)*X^7
private theorem f8Step14 : f8R13^2*X^0 - f8R14 = h17*(575583 + (-15980)*X + (24088)*X^2 + (-1898)*X^3 + (944)*X^4 + (-80)*X^5 + (25)*X^6) := by
  unfold f8R13 f8R14 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(575583 + (-15980)*X + (24088)*X^2 + (-1898)*X^3 + (944)*X^4 + (-80)*X^5 + (25)*X^6) + 17*(31826356 + (15368156)*X + (-27559851)*X^2 + (-17595596)*X^3 + (4074878)*X^4 + (4879045)*X^5 + (1003469)*X^6 + (34220)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow14 : h17 ∣ (X : P17)^26610 - f8R14 := by
  have h := certificate_step _ _ _ _ 13305 0 f8Pow13 f8Step14
  simp only [show 13305*2+0 = 26610 from by decide] at h
  exact h
def f8R15 : P17 := (-5) + (-5)*X + (-8)*X^2 + (-7)*X^3 + (-2)*X^5 + (8)*X^6
private theorem f8Step15 : f8R14^2*X^0 - f8R15 = h17*(1790004 + (-100520)*X + (75489)*X^2 + (-7134)*X^3 + (2801)*X^4 + (-240)*X^5 + (64)*X^6) := by
  unfold f8R14 f8R15 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(1790004 + (-100520)*X + (75489)*X^2 + (-7134)*X^3 + (2801)*X^4 + (-240)*X^5 + (64)*X^6) + 17*(98976693 + (44983125)*X + (-87111372)*X^2 + (-52260977)*X^3 + (14275860)*X^4 + (14793258)*X^5 + (2669908)*X^6 + (21912)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow15 : h17 ∣ (X : P17)^53220 - f8R15 := by
  have h := certificate_step _ _ _ _ 26610 0 f8Pow14 f8Step15
  simp only [show 26610*2+0 = 53220 from by decide] at h
  exact h
def f8R16 : P17 := 2 + X + (-3)*X^2 + (3)*X^3 + (-1)*X^4 + (-8)*X^5 + (5)*X^6 + (5)*X^7
private theorem f8Step16 : f8R15^2*X^1 - f8R16 = h17*((-158528) + (79884)*X + (-9216)*X^2 + (2948)*X^3 + (-288)*X^4 + (64)*X^5) := by
  unfold f8R15 f8R16 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*((-158528) + (79884)*X + (-9216)*X^2 + (2948)*X^3 + (-288)*X^4 + (64)*X^5) + 17*((-8765666) + (-58968)*X + (9579109)*X^2 + (1177686)*X^3 + (-3414297)*X^4 + (-755426)*X^5 + (371375)*X^6 + (108400)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow16 : h17 ∣ (X : P17)^106441 - f8R16 := by
  have h := certificate_step _ _ _ _ 53220 1 f8Pow15 f8Step16
  simp only [show 53220*2+1 = 106441 from by decide] at h
  exact h
def f8R17 : P17 := 2 + (-6)*X + (-1)*X^2 + (-1)*X^3 + (4)*X^4 + (-7)*X^5 + (7)*X^6 + (2)*X^7
private theorem f8Step17 : f8R16^2*X^1 - f8R17 = h17*(1351004 + (550865)*X + (16120)*X^2 + (21524)*X^3 + (-670)*X^4 + (845)*X^5 + (-50)*X^6 + (25)*X^7) := by
  unfold f8R16 f8R17 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(1351004 + (550865)*X + (16120)*X^2 + (21524)*X^3 + (-670)*X^4 + (845)*X^5 + (-50)*X^6 + (25)*X^7) + 17*(74702574 + (68605590)*X + (-50310315)*X^2 + (-70077570)*X^3 + (-7246054)*X^4 + (16320890)*X^5 + (7146949)*X^6 + (906273)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow17 : h17 ∣ (X : P17)^212883 - f8R17 := by
  have h := certificate_step _ _ _ _ 106441 1 f8Pow16 f8Step17
  simp only [show 106441*2+1 = 212883 from by decide] at h
  exact h
def f8R18 : P17 := 4 + (4)*X + (-1)*X^2 + (8)*X^3 + (-7)*X^5 + (-1)*X^6 + (7)*X^7
private theorem f8Step18 : f8R17^2*X^0 - f8R18 = h17*(99416 + (19202)*X + (2713)*X^2 + (586)*X^3 + (85)*X^4 + (12)*X^5 + (4)*X^6) := by
  unfold f8R17 f8R18 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(99416 + (19202)*X + (2713)*X^2 + (586)*X^3 + (85)*X^4 + (12)*X^5 + (4)*X^6) + 17*(5497120 + (3868796)*X + (-4220131)*X^2 + (-4114680)*X^3 + (73377)*X^4 + (1025333)*X^5 + (352910)*X^6 + (36587)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow18 : h17 ∣ (X : P17)^425766 - f8R18 := by
  have h := certificate_step _ _ _ _ 212883 0 f8Pow17 f8Step18
  simp only [show 212883*2+0 = 425766 from by decide] at h
  exact h
def f8R19 : P17 := 2 + (6)*X^2 + (6)*X^4 + (-8)*X^5 + (4)*X^6 + (-7)*X^7
private theorem f8Step19 : f8R18^2*X^0 - f8R19 = h17*(1272250 + (-93530)*X + (55337)*X^2 + (-6094)*X^3 + (2115)*X^4 + (-210)*X^5 + (49)*X^6) := by
  unfold f8R18 f8R19 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(1272250 + (-93530)*X + (55337)*X^2 + (-6094)*X^3 + (2115)*X^4 + (-210)*X^5 + (49)*X^6) + 17*(70347942 + (30750696)*X + (-62445154)*X^2 + (-36062432)*X^3 + (10768927)*X^4 + (10328928)*X^5 + (1719908)*X^6 + (-14635)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow19 : h17 ∣ (X : P17)^851532 - f8R19 := by
  have h := certificate_step _ _ _ _ 425766 0 f8Pow18 f8Step19
  simp only [show 425766*2+0 = 851532 from by decide] at h
  exact h
def f8R20 : P17 := (-1) + (-5)*X + (-4)*X^2 + (-7)*X^3 + (-3)*X^4 + (-7)*X^5 + (2)*X^6 + (2)*X^7
private theorem f8Step20 : f8R19^2*X^1 - f8R20 = h17*((-2010444) + (1631708)*X + (-177172)*X^2 + (70876)*X^3 + (-9004)*X^4 + (2508)*X^5 + (-252)*X^6 + (49)*X^7) := by
  unfold f8R19 f8R20 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*((-2010444) + (1631708)*X + (-177172)*X^2 + (70876)*X^3 + (-9004)*X^4 + (2508)*X^5 + (-252)*X^6 + (49)*X^7) + 17*((-111165727) + (33458377)*X + (135614772)*X^2 + (-15482657)*X^3 + (-60049261)*X^4 + (-4211725)*X^5 + (9521774)*X^6 + (2161650)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow20 : h17 ∣ (X : P17)^1703065 - f8R20 := by
  have h := certificate_step _ _ _ _ 851532 1 f8Pow19 f8Step20
  simp only [show 851532*2+1 = 1703065 from by decide] at h
  exact h
def f8R21 : P17 := (-5) + X + (4)*X^2 + (8)*X^3 + (-5)*X^4 + (-7)*X^6 + (2)*X^7
private theorem f8Step21 : f8R20^2*X^1 - f8R21 = h17*(213502 + (73179)*X + (3290)*X^2 + (2873)*X^3 + (-72)*X^4 + (120)*X^5 + (-8)*X^6 + (4)*X^7) := by
  unfold f8R20 f8R21 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(213502 + (73179)*X + (3290)*X^2 + (2873)*X^3 + (-72)*X^4 + (120)*X^5 + (-8)*X^6 + (4)*X^7) + 17*(11805405 + (10074660)*X + (-8301362)*X^2 + (-10397155)*X^3 + (-737773)*X^4 + (2466824)*X^5 + (1013795)*X^6 + (122913)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow21 : h17 ∣ (X : P17)^3406131 - f8R21 := by
  have h := certificate_step _ _ _ _ 1703065 1 f8Pow20 f8Step21
  simp only [show 1703065*2+1 = 3406131 from by decide] at h
  exact h
def f8R22 : P17 := (-7) + (7)*X + (-7)*X^2 + (-1)*X^3 + (7)*X^4 + (4)*X^5 + (-5)*X^7
private theorem f8Step22 : f8R21^2*X^1 - f8R22 = h17*((-906166) + (226377)*X + (-47536)*X^2 + (10418)*X^3 + (-1928)*X^4 + (337)*X^5 + (-44)*X^6 + (4)*X^7) := by
  unfold f8R21 f8R22 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*((-906166) + (226377)*X + (-47536)*X^2 + (10418)*X^3 + (-1928)*X^4 + (337)*X^5 + (-44)*X^6 + (4)*X^7) + 17*((-50105649) + (-13068546)*X + (48538621)*X^2 + (17898346)*X^3 + (-12383287)*X^4 + (-6075450)*X^5 + (112326)*X^6 + (247943)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow22 : h17 ∣ (X : P17)^6812263 - f8R22 := by
  have h := certificate_step _ _ _ _ 3406131 1 f8Pow21 f8Step22
  simp only [show 3406131*2+1 = 6812263 from by decide] at h
  exact h
def f8R23 : P17 := 7 + (5)*X + (2)*X^2 + (7)*X^3 + (8)*X^4 + (8)*X^5 + (5)*X^6 + (8)*X^7
private theorem f8Step23 : f8R22^2*X^0 - f8R23 = h17*(653611 + (-43458)*X + (28046)*X^2 + (-2910)*X^3 + (1060)*X^4 + (-100)*X^5 + (25)*X^6) := by
  unfold f8R22 f8R23 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(653611 + (-43458)*X + (28046)*X^2 + (-2910)*X^3 + (1060)*X^4 + (-100)*X^5 + (25)*X^6) + 17*(36140846 + (16051921)*X + (-31972335)*X^2 + (-18752403)*X^3 + (5404877)*X^4 + (5345648)*X^5 + (920074)*X^6 + (-1444)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow23 : h17 ∣ (X : P17)^13624526 - f8R23 := by
  have h := certificate_step _ _ _ _ 6812263 0 f8Pow22 f8Step23
  simp only [show 6812263*2+0 = 13624526 from by decide] at h
  exact h
def f8R24 : P17 := (-4) + (-3)*X + (-5)*X^2 + (-3)*X^3 + (-8)*X^4 + (3)*X^5 + (-4)*X^6 + (4)*X^7
private theorem f8Step24 : f8R23^2*X^0 - f8R24 = h17*(1792568 + (-31314)*X + (72076)*X^2 + (-4564)*X^3 + (2649)*X^4 + (-176)*X^5 + (64)*X^6) := by
  unfold f8R23 f8R24 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(1792568 + (-31314)*X + (72076)*X^2 + (-4564)*X^3 + (2649)*X^4 + (-176)*X^5 + (64)*X^6) + 17*(99118469 + (48882209)*X + (-85472726)*X^2 + (-55719287)*X^3 + (12250062)*X^4 + (15373233)*X^5 + (3254611)*X^6 + (124598)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow24 : h17 ∣ (X : P17)^27249052 - f8R24 := by
  have h := certificate_step _ _ _ _ 13624526 0 f8Pow23 f8Step24
  simp only [show 13624526*2+0 = 27249052 from by decide] at h
  exact h
def f8R25 : P17 := (-2) + (3)*X + (-3)*X^2 + (2)*X^3 + (-3)*X^4 + (8)*X^5 + (-4)*X^6 + (-6)*X^7
private theorem f8Step25 : f8R24^2*X^1 - f8R25 = h17*((-1081350) + (560842)*X + (-75620)*X^2 + (24881)*X^3 + (-3576)*X^4 + (872)*X^5 + (-96)*X^6 + (16)*X^7) := by
  unfold f8R24 f8R25 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*((-1081350) + (560842)*X + (-75620)*X^2 + (24881)*X^3 + (-3576)*X^4 + (872)*X^5 + (-96)*X^6 + (16)*X^7) + 17*((-59792294) + (479029)*X + (65085611)*X^2 + (7149371)*X^3 + (-23138719)*X^4 + (-4858733)*X^5 + (2515042)*X^6 + (708665)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow25 : h17 ∣ (X : P17)^54498105 - f8R25 := by
  have h := certificate_step _ _ _ _ 27249052 1 f8Pow24 f8Step25
  simp only [show 27249052*2+1 = 54498105 from by decide] at h
  exact h
def f8R26 : P17 := 7 + (3)*X + (7)*X^2 + (4)*X^3 + (8)*X^4 + (-1)*X^5 + (-5)*X^6 + (-4)*X^7
private theorem f8Step26 : f8R25^2*X^0 - f8R26 = h17*(821325 + (-364)*X + (33376)*X^2 + (-1916)*X^3 + (1312)*X^4 + (-96)*X^5 + (36)*X^6) := by
  unfold f8R25 f8R26 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(821325 + (-364)*X + (33376)*X^2 + (-1916)*X^3 + (1312)*X^4 + (-96)*X^5 + (36)*X^6) + 17*(45414441 + (23170225)*X + (-38747898)*X^2 + (-26200990)*X^3 + (5145125)*X^4 + (7140587)*X^5 + (1621607)*X^6 + (82740)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow26 : h17 ∣ (X : P17)^108996210 - f8R26 := by
  have h := certificate_step _ _ _ _ 54498105 0 f8Pow25 f8Step26
  simp only [show 54498105*2+0 = 108996210 from by decide] at h
  exact h
def f8R27 : P17 := 7 + (-8)*X + X^2 + (8)*X^3 + (-2)*X^4 + (8)*X^5 + (-1)*X^6 + (-5)*X^7
private theorem f8Step27 : f8R26^2*X^0 - f8R27 = h17*(411378 + (12268)*X + (15637)*X^2 + (-346)*X^3 + (577)*X^4 + (-24)*X^5 + (16)*X^6) := by
  unfold f8R26 f8R27 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(411378 + (12268)*X + (15637)*X^2 + (-346)*X^3 + (577)*X^4 + (-24)*X^5 + (16)*X^6) + 17*(22746786 + (12293730)*X + (-19115882)*X^2 + (-13735070)*X^3 + (2233191)*X^4 + (3683378)*X^5 + (910673)*X^6 + (57721)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow27 : h17 ∣ (X : P17)^217992420 - f8R27 := by
  have h := certificate_step _ _ _ _ 108996210 0 f8Pow26 f8Step27
  simp only [show 108996210*2+0 = 217992420 from by decide] at h
  exact h
def f8R28 : P17 := (-5)
private theorem f8Step28 : f8R27^2*X^0 - f8R28 = h17*(579934 + (-23754)*X + (24796)*X^2 + (-2240)*X^3 + (981)*X^4 + (-90)*X^5 + (25)*X^6) := by
  unfold f8R27 f8R28 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(579934 + (-23754)*X + (24796)*X^2 + (-2240)*X^3 + (981)*X^4 + (-90)*X^5 + (25)*X^6) + 17*(32066942 + (15061144)*X + (-27955186)*X^2 + (-17353712)*X^3 + (4324185)*X^4 + (4852096)*X^5 + (948794)*X^6 + (23850)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow28 : h17 ∣ (X : P17)^435984840 - f8R28 := by
  have h := certificate_step _ _ _ _ 217992420 0 f8Pow27 f8Step28
  simp only [show 217992420*2+0 = 435984840 from by decide] at h
  exact h
def f8R29 : P17 := 8
private theorem f8Step29 : f8R28^2*X^0 - f8R29 = h17*(0) := by
  unfold f8R28 f8R29 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(0) + 17*(1) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow29 : h17 ∣ (X : P17)^871969680 - f8R29 := by
  have h := certificate_step _ _ _ _ 435984840 0 f8Pow28 f8Step29
  simp only [show 435984840*2+0 = 871969680 from by decide] at h
  exact h
def f8R30 : P17 := (-4)
private theorem f8Step30 : f8R29^2*X^0 - f8R30 = h17*(0) := by
  unfold f8R29 f8R30 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(0) + 17*(4) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow30 : h17 ∣ (X : P17)^1743939360 - f8R30 := by
  have h := certificate_step _ _ _ _ 871969680 0 f8Pow29 f8Step30
  simp only [show 871969680*2+0 = 1743939360 from by decide] at h
  exact h
def f8R31 : P17 := (-1)
private theorem f8Step31 : f8R30^2*X^0 - f8R31 = h17*(0) := by
  unfold f8R30 f8R31 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(0) + 17*(1) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow31 : h17 ∣ (X : P17)^3487878720 - f8R31 := by
  have h := certificate_step _ _ _ _ 1743939360 0 f8Pow30 f8Step31
  simp only [show 1743939360*2+0 = 3487878720 from by decide] at h
  exact h
def f8R32 : P17 := X
private theorem f8Step32 : f8R31^2*X^1 - f8R32 = h17*(0) := by
  unfold f8R31 f8R32 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(0) + 17*(0) := by ring
    _ = _ := by rw [char17]; ring
private theorem f8Pow32 : h17 ∣ (X : P17)^6975757441 - f8R32 := by
  have h := certificate_step _ _ _ _ 3487878720 1 f8Pow31 f8Step32
  simp only [show 3487878720*2+1 = 6975757441 from by decide] at h
  exact h
theorem h17_dvd_frobenius8 : h17 ∣ (X : P17)^(17^8) - X :=
  certificate_finish h17 f8R32 (17^8) 6975757441 (by norm_num) rfl f8Pow32

def f4R0 : P17 := X
private theorem f4Pow0 : h17 ∣ (X : P17)^1 - f4R0 := by simp [f4R0]
def f4R1 : P17 := X^2
private theorem f4Step1 : f4R0^2*X^0 - f4R1 = h17*(0) := by
  unfold f4R0 f4R1 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(0) + 17*(0) := by ring
    _ = _ := by rw [char17]; ring
private theorem f4Pow1 : h17 ∣ (X : P17)^2 - f4R1 := by
  have h := certificate_step _ _ _ _ 1 0 f4Pow0 f4Step1
  simp only [show 1*2+0 = 2 from by decide] at h
  exact h
def f4R2 : P17 := X^5
private theorem f4Step2 : f4R1^2*X^1 - f4R2 = h17*(0) := by
  unfold f4R1 f4R2 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(0) + 17*(0) := by ring
    _ = _ := by rw [char17]; ring
private theorem f4Pow2 : h17 ∣ (X : P17)^5 - f4R2 := by
  have h := certificate_step _ _ _ _ 2 1 f4Pow1 f4Step2
  simp only [show 2*2+1 = 5 from by decide] at h
  exact h
def f4R3 : P17 := (-1) + (3)*X + (4)*X^2 + (8)*X^3 + (-5)*X^4 + (-1)*X^5 + (3)*X^6 + (-1)*X^7
private theorem f4Step3 : f4R2^2*X^0 - f4R3 = h17*(44 + (-4)*X + X^2) := by
  unfold f4R2 f4R3 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(44 + (-4)*X + X^2) + 17*(2433 + (1021)*X + (-2232)*X^2 + (-1224)*X^3 + (445)*X^4 + (369)*X^5 + (41)*X^6 + (-7)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f4Pow3 : h17 ∣ (X : P17)^10 - f4R3 := by
  have h := certificate_step _ _ _ _ 5 0 f4Pow2 f4Step3
  simp only [show 5*2+0 = 10 from by decide] at h
  exact h
def f4R4 : P17 := (-5) + (-3)*X + (4)*X^2 + (-3)*X^4 + (-7)*X^5 + (-4)*X^6 + (6)*X^7
private theorem f4Step4 : f4R3^2*X^0 - f4R4 = h17*(48867 + (-9802)*X + (2323)*X^2 + (-424)*X^3 + (79)*X^4 + (-10)*X^5 + X^6) := by
  unfold f4R3 f4R4 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(48867 + (-9802)*X + (2323)*X^2 + (-424)*X^3 + (79)*X^4 + (-10)*X^5 + X^6) + 17*(2702058 + (837781)*X + (-2562919)*X^2 + (-1083256)*X^3 + (602941)*X^4 + (348307)*X^5 + (12588)*X^6 + (-10262)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f4Pow4 : h17 ∣ (X : P17)^20 - f4R4 := by
  have h := certificate_step _ _ _ _ 10 0 f4Pow3 f4Step4
  simp only [show 10*2+0 = 20 from by decide] at h
  exact h
def f4R5 : P17 := 7 + (3)*X + (-2)*X^2 + (6)*X^3 + (8)*X^4 + (-8)*X^5 + (-1)*X^6 + (-7)*X^7
private theorem f4Step5 : f4R4^2*X^0 - f4R5 = h17*(1003129 + (-112890)*X + (45241)*X^2 + (-6140)*X^3 + (1708)*X^4 + (-192)*X^5 + (36)*X^6) := by
  unfold f4R4 f4R5 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(1003129 + (-112890)*X + (45241)*X^2 + (-6140)*X^3 + (1708)*X^4 + (-192)*X^5 + (36)*X^6) + 17*(55467134 + (22081491)*X + (-50252297)*X^2 + (-26528270)*X^3 + (9665434)*X^4 + (7834304)*X^5 + (1023603)*X^6 + (-71209)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f4Pow5 : h17 ∣ (X : P17)^40 - f4R5 := by
  have h := certificate_step _ _ _ _ 20 0 f4Pow4 f4Step5
  simp only [show 20*2+0 = 40 from by decide] at h
  exact h
def f4R6 : P17 := 6 + (-7)*X + (7)*X^2 + (7)*X^3 + (-7)*X^5 + X^6 + (5)*X^7
private theorem f4Step6 : f4R5^2*X^1 - f4R6 = h17*(36592 + (1474270)*X + (-89824)*X^2 + (61460)*X^3 + (-5812)*X^4 + (2213)*X^5 + (-182)*X^6 + (49)*X^7) := by
  unfold f4R5 f4R6 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(36592 + (1474270)*X + (-89824)*X^2 + (61460)*X^3 + (-5812)*X^4 + (2213)*X^5 + (-182)*X^6 + (49)*X^7) + 17*(2023322 + (82551648)*X + (34851635)*X^2 + (-73189498)*X^3 + (-42410504)*X^4 + (12382995)*X^5 + (12204831)*X^6 + (2117741)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f4Pow6 : h17 ∣ (X : P17)^81 - f4R6 := by
  have h := certificate_step _ _ _ _ 40 1 f4Pow5 f4Step6
  simp only [show 40*2+1 = 81 from by decide] at h
  exact h
def f4R7 : P17 := (-1) + (6)*X + (-1)*X^2 + (8)*X^3 + X^4 + (-7)*X^5 + (-8)*X^6 + (7)*X^7
private theorem f4Step7 : f4R6^2*X^1 - f4R7 = h17*(358132 + (598726)*X + (-26128)*X^2 + (25439)*X^3 + (-2298)*X^4 + (991)*X^5 + (-90)*X^6 + (25)*X^7) := by
  unfold f4R6 f4R7 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(358132 + (598726)*X + (-26128)*X^2 + (25439)*X^3 + (-2298)*X^4 + (991)*X^5 + (-90)*X^6 + (25)*X^7) + 17*(19802593 + (43217990)*X + (-2235459)*X^2 + (-40712495)*X^3 + (-14891175)*X^4 + (8063482)*X^5 + (5590078)*X^6 + (878744)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f4Pow7 : h17 ∣ (X : P17)^163 - f4R7 := by
  have h := certificate_step _ _ _ _ 81 1 f4Pow6 f4Step7
  simp only [show 81*2+1 = 163 from by decide] at h
  exact h
def f4R8 : P17 := (-4) + (2)*X + (-8)*X^2 + (4)*X^3 + (-5)*X^4 + (-7)*X^5 + (2)*X^6 + (-2)*X^7
private theorem f4Step8 : f4R7^2*X^0 - f4R8 = h17*(1510177 + (-211864)*X + (69405)*X^2 + (-10546)*X^3 + (2570)*X^4 + (-308)*X^5 + (49)*X^6) := by
  unfold f4R7 f4R8 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(1510177 + (-211864)*X + (69405)*X^2 + (-10546)*X^3 + (2570)*X^4 + (-308)*X^5 + (49)*X^6) + 17*(83503905 + (30925458)*X + (-76764862)*X^2 + (-37901896)*X^3 + (15830720)*X^4 + (11469689)*X^5 + (1179628)*X^6 + (-173314)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f4Pow8 : h17 ∣ (X : P17)^326 - f4R8 := by
  have h := certificate_step _ _ _ _ 163 0 f4Pow7 f4Step8
  simp only [show 163*2+0 = 326 from by decide] at h
  exact h
def f4R9 : P17 := 2 + (-1)*X + (-6)*X^2 + (5)*X^4 + (-3)*X^5 + (-7)*X^6 + (3)*X^7
private theorem f4Step9 : f4R8^2*X^0 - f4R9 = h17*(163901 + (-20798)*X + (7133)*X^2 + (-968)*X^3 + (240)*X^4 + (-24)*X^5 + (4)*X^6) := by
  unfold f4R8 f4R9 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(163901 + (-20798)*X + (7133)*X^2 + (-968)*X^3 + (240)*X^4 + (-24)*X^5 + (4)*X^6) + 17*(9062762 + (3477785)*X + (-8291458)*X^2 + (-4223552)*X^3 + (1668375)*X^4 + (1266759)*X^5 + (142739)*X^6 + (-16903)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f4Pow9 : h17 ∣ (X : P17)^652 - f4R9 := by
  have h := certificate_step _ _ _ _ 326 0 f4Pow8 f4Step9
  simp only [show 326*2+0 = 652 from by decide] at h
  exact h
def f4R10 : P17 := (-1)*X + (3)*X^2 + (-7)*X^3 + (4)*X^5 + (-1)*X^6
private theorem f4Step10 : f4R9^2*X^1 - f4R10 = h17*((-1135294) + (350607)*X + (-66206)*X^2 + (16675)*X^3 + (-2980)*X^4 + (595)*X^5 + (-78)*X^6 + (9)*X^7) := by
  unfold f4R9 f4R10 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*((-1135294) + (350607)*X + (-66206)*X^2 + (16675)*X^3 + (-2980)*X^4 + (595)*X^5 + (-78)*X^6 + (9)*X^7) + 17*((-62775080) + (-12668855)*X + (62335569)*X^2 + (19126492)*X^3 + (-17321484)*X^4 + (-7026300)*X^5 + (660139)*X^6 + (394706)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f4Pow10 : h17 ∣ (X : P17)^1305 - f4R10 := by
  have h := certificate_step _ _ _ _ 652 1 f4Pow9 f4Step10
  simp only [show 652*2+1 = 1305 from by decide] at h
  exact h
def f4R11 : P17 := (-4) + (-2)*X + (-3)*X^2 + X^3 + (-6)*X^4 + (-7)*X^5 + (4)*X^6 + (-4)*X^7
private theorem f4Step11 : f4R10^2*X^0 - f4R11 = h17*(2726 + (-522)*X + (92)*X^2 + (-12)*X^3 + X^4) := by
  unfold f4R10 f4R11 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(2726 + (-522)*X + (92)*X^2 + (-12)*X^3 + X^4) + 17*(150732 + (48106)*X + (-144348)*X^2 + (-62071)*X^3 + (34817)*X^4 + (20229)*X^5 + (437)*X^6 + (-722)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f4Pow11 : h17 ∣ (X : P17)^2610 - f4R11 := by
  have h := certificate_step _ _ _ _ 1305 0 f4Pow10 f4Step11
  simp only [show 1305*2+0 = 2610 from by decide] at h
  exact h
def f4R12 : P17 := 4 + (-5)*X + (-8)*X^2 + (-6)*X^3 + (3)*X^4 + X^5 + X^6 + (7)*X^7
private theorem f4Step12 : f4R11^2*X^0 - f4R12 = h17*(585770 + (-75536)*X + (25913)*X^2 + (-3624)*X^3 + (904)*X^4 + (-96)*X^5 + (16)*X^6) := by
  unfold f4R11 f4R12 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(585770 + (-75536)*X + (25913)*X^2 + (-3624)*X^3 + (904)*X^4 + (-96)*X^5 + (16)*X^6) + 17*(32389636 + (12362693)*X + (-29643872)*X^2 + (-15032310)*X^3 + (5979490)*X^4 + (4512409)*X^5 + (504612)*X^6 + (-60585)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f4Pow12 : h17 ∣ (X : P17)^5220 - f4R12 := by
  have h := certificate_step _ _ _ _ 2610 0 f4Pow11 f4Step12
  simp only [show 2610*2+0 = 5220 from by decide] at h
  exact h
def f4R13 : P17 := (-5) + (5)*X + (5)*X^2 + (-1)*X^3 + (7)*X^4 + (-4)*X^5 + X^6 + (5)*X^7
private theorem f4Step13 : f4R12^2*X^0 - f4R13 = h17*(1340031 + (-71746)*X + (56547)*X^2 + (-5280)*X^3 + (2115)*X^4 + (-182)*X^5 + (49)*X^6) := by
  unfold f4R12 f4R13 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(1340031 + (-71746)*X + (56547)*X^2 + (-5280)*X^3 + (2115)*X^4 + (-182)*X^5 + (49)*X^6) + 17*(74095833 + (33869035)*X + (-65112352)*X^2 + (-39292431)*X^3 + (10572733)*X^4 + (11099638)*X^5 + (2030765)*X^6 + (22569)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f4Pow13 : h17 ∣ (X : P17)^10440 - f4R13 := by
  have h := certificate_step _ _ _ _ 5220 0 f4Pow12 f4Step13
  simp only [show 5220*2+0 = 10440 from by decide] at h
  exact h
def f4R14 : P17 := (-8) + (2)*X + (-1)*X^2 + (6)*X^3 + X^4 + X^5 + (7)*X^6 + (-4)*X^7
private theorem f4Step14 : f4R13^2*X^0 - f4R14 = h17*(621289 + (-26080)*X + (26356)*X^2 + (-2342)*X^3 + (1021)*X^4 + (-90)*X^5 + (25)*X^6) := by
  unfold f4R13 f4R14 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(621289 + (-26080)*X + (26356)*X^2 + (-2342)*X^3 + (1021)*X^4 + (-90)*X^5 + (25)*X^6) + 17*(34353629 + (16100204)*X + (-29978032)*X^2 + (-18562658)*X^3 + (4663632)*X^4 + (5196403)*X^5 + (1008158)*X^6 + (23546)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f4Pow14 : h17 ∣ (X : P17)^20880 - f4R14 := by
  have h := certificate_step _ _ _ _ 10440 0 f4Pow13 f4Step14
  simp only [show 10440*2+0 = 20880 from by decide] at h
  exact h
def f4R15 : P17 := (-4) + (-6)*X + (4)*X^2 + (-2)*X^3 + (2)*X^6 + (-1)*X^7
private theorem f4Step15 : f4R14^2*X^0 - f4R15 = h17*(589815 + (-99438)*X + (27347)*X^2 + (-4542)*X^3 + (969)*X^4 + (-120)*X^5 + (16)*X^6) := by
  unfold f4R14 f4R15 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*(589815 + (-99438)*X + (27347)*X^2 + (-4542)*X^3 + (969)*X^4 + (-120)*X^5 + (16)*X^6) + 17*(32613304 + (11155262)*X + (-30439332)*X^2 + (-13994794)*X^3 + (6706977)*X^4 + (4354168)*X^5 + (313220)*X^6 + (-95245)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f4Pow15 : h17 ∣ (X : P17)^41760 - f4R15 := by
  have h := certificate_step _ _ _ _ 20880 0 f4Pow14 f4Step15
  simp only [show 20880*2+0 = 41760 from by decide] at h
  exact h
def f4R16 : P17 := 2 + (3)*X + (-3)*X^2 + (-6)*X^3 + (-5)*X^5 + (-2)*X^6 + (6)*X^7
private theorem f4Step16 : f4R15^2*X^1 - f4R16 = h17*((-119904) + (39892)*X + (-7040)*X^2 + (1840)*X^3 + (-312)*X^4 + (64)*X^5 + (-8)*X^6 + X^7) := by
  unfold f4R15 f4R16 h17
  calc
    _ = (X^8 + 4*X^7 + (-28)*X^6 + (-168)*X^5 + (-140)*X^4 + 560*X^3 + 840*X^2 + (-480)*X + (-940))*((-119904) + (39892)*X + (-7040)*X^2 + (1840)*X^3 + (-312)*X^4 + (64)*X^5 + (-8)*X^6 + X^7) + 17*((-6629986) + (-1179731)*X + (6661763)*X^2 + (1881610)*X^3 + (-1918976)*X^4 + (-720691)*X^5 + (94930)*X^6 + (46442)*X^7) := by ring
    _ = _ := by rw [char17]; ring
private theorem f4Pow16 : h17 ∣ (X : P17)^83521 - f4R16 := by
  have h := certificate_step _ _ _ _ 41760 1 f4Pow15 f4Step16
  simp only [show 41760*2+1 = 83521 from by decide] at h
  exact h
def bezU : P17 := (-6) + (-8)*X + (2)*X^2 + (-6)*X^3 + (-1)*X^4 + (2)*X^5 + (6)*X^6
def bezV : P17 := (-6) + (8)*X + (-7)*X^2 + (-2)*X^3 + (-5)*X^4 + (-2)*X^5 + X^6 + (-1)*X^7
theorem h17_bezout : bezU * h17 + bezV * (f4R16 - X) = 1 := by
  unfold bezU bezV h17 f4R16
  calc
    _ = 1 + 17*(331 + (612)*X + (-180)*X^2 + (-318)*X^3 + (107)*X^4 + (-184)*X^5 + (-563)*X^6 + (-61)*X^7 + (429)*X^8 + (200)*X^9 + (-68)*X^10 + (-65)*X^11 + (-10)*X^12 + (2)*X^13) := by ring
    _ = _ := by rw [char17]; ring

theorem h17_dvd_frobenius4 : h17 ∣ (X : P17)^(17^4) - f4R16 := by
  rw [show (17:ℕ)^4 = 83521 from by norm_num]
  exact f4Pow16

theorem h17_coprime_frobenius4 : ∃ R u v : P17, h17 ∣ (X : P17)^(17^4) - R ∧ u * h17 + v * (R - X) = 1 :=
  ⟨f4R16, bezU, bezV, h17_dvd_frobenius4, h17_bezout⟩

end
end X2Y5Z7
