/-
Generated by computer; every fact used is proved in Lean.
-/
import X2Y5Z7.Norm.Units
import X2Y5Z7.FiniteFields.Q181
import X2Y5Z7.FiniteFields.Q311
import X2Y5Z7.FiniteFields.Q131

/-! # Fifth-power symbols of `u₁, …, u₁₀` at ten primes of `L₈` (proof of Lemma 6.3(i))

`Pr k` are ten model primes of `L₈` (above 181, 311, 131); `Su k i` is the symbol of `u_i` at
`Pr k` (`sym_u`, checked by `decide +kernel`), and `SuInv * Su = 1` over `𝔽₅`. -/

namespace X2Y5Z7.Norm

open FiniteFields

/-- The ten model primes of `L₈`. -/
def Pr : Fin 10 → L8Prime := ![Q181.L8P0, Q181.L8P1, Q181.L8P2, Q181.L8P3, Q181.L8P4, Q311.L8P0, Q311.L8P1, Q311.L8P2, Q311.L8P3, Q131.L8P0]

/-- The symbols of `u₁, …, u₁₀` at `Pr k`, as a Boolean check. -/
def uRowCheck (D : L8Prime) (row : List ℕ) : Bool :=
  (List.finRange 10).all fun i => uCheck D.q D.P D.zeta (un i) (ud i) (row.getD i 0)

/-- The rows of the symbol matrix. -/
def Srows : List (List ℕ) := [[1, 3, 0, 1, 3, 4, 4, 3, 2, 1], [2, 1, 3, 0, 1, 3, 4, 2, 0, 2], [1, 1, 0, 4, 0, 3, 1, 2, 1, 0], [2, 1, 2, 2, 2, 4, 1, 0, 3, 3], [0, 0, 1, 4, 4, 1, 0, 3, 4, 4], [2, 3, 4, 0, 2, 3, 0, 2, 4, 3], [3, 3, 1, 2, 2, 0, 0, 2, 0, 0], [1, 1, 4, 0, 2, 2, 4, 0, 3, 0], [3, 1, 1, 1, 1, 0, 4, 2, 2, 4], [3, 4, 1, 4, 1, 3, 1, 0, 0, 3]]

/-- The symbol matrix: `Su k i` is the symbol of `u_i` at `Pr k`. -/
def Su : Matrix (Fin 10) (Fin 10) (ZMod 5) := Matrix.of fun k i => ((Srows.getD k []).getD i 0 : ZMod 5)

/-- An inverse of `Su` over `𝔽₅`. -/
def SuInv : Matrix (Fin 10) (Fin 10) (ZMod 5) :=
  !![0, 2, 4, 1, 3, 1, 4, 1, 2, 0;
    3, 2, 1, 4, 2, 0, 0, 3, 2, 0;
    0, 2, 0, 3, 3, 1, 2, 3, 3, 0;
    3, 0, 1, 3, 3, 3, 4, 3, 3, 0;
    3, 3, 3, 2, 2, 3, 0, 1, 1, 3;
    3, 2, 3, 0, 0, 4, 2, 2, 2, 1;
    4, 3, 0, 1, 1, 3, 4, 1, 0, 3;
    2, 0, 1, 1, 1, 2, 2, 1, 1, 2;
    3, 2, 1, 0, 0, 3, 1, 0, 1, 0;
    0, 4, 1, 1, 0, 2, 0, 4, 3, 4]

theorem SuInv_mul : SuInv * Su = 1 := by decide +kernel

theorem check0 : uRowCheck Q181.L8P0 [1, 3, 0, 1, 3, 4, 4, 3, 2, 1] = true := by decide +kernel

theorem check1 : uRowCheck Q181.L8P1 [2, 1, 3, 0, 1, 3, 4, 2, 0, 2] = true := by decide +kernel

theorem check2 : uRowCheck Q181.L8P2 [1, 1, 0, 4, 0, 3, 1, 2, 1, 0] = true := by decide +kernel

theorem check3 : uRowCheck Q181.L8P3 [2, 1, 2, 2, 2, 4, 1, 0, 3, 3] = true := by decide +kernel

theorem check4 : uRowCheck Q181.L8P4 [0, 0, 1, 4, 4, 1, 0, 3, 4, 4] = true := by decide +kernel

theorem check5 : uRowCheck Q311.L8P0 [2, 3, 4, 0, 2, 3, 0, 2, 4, 3] = true := by decide +kernel

theorem check6 : uRowCheck Q311.L8P1 [3, 3, 1, 2, 2, 0, 0, 2, 0, 0] = true := by decide +kernel

theorem check7 : uRowCheck Q311.L8P2 [1, 1, 4, 0, 2, 2, 4, 0, 3, 0] = true := by decide +kernel

theorem check8 : uRowCheck Q311.L8P3 [3, 1, 1, 1, 1, 0, 4, 2, 2, 4] = true := by decide +kernel

theorem check9 : uRowCheck Q131.L8P0 [3, 4, 1, 4, 1, 3, 1, 0, 0, 3] = true := by decide +kernel

theorem sym_u (k i : Fin 10) : uCheck (Pr k).q (Pr k).P (Pr k).zeta (un i) (ud i) ((Srows.getD k []).getD i 0) = true := by
  fin_cases k
  · exact List.all_eq_true.1 check0 i (List.mem_finRange i)
  · exact List.all_eq_true.1 check1 i (List.mem_finRange i)
  · exact List.all_eq_true.1 check2 i (List.mem_finRange i)
  · exact List.all_eq_true.1 check3 i (List.mem_finRange i)
  · exact List.all_eq_true.1 check4 i (List.mem_finRange i)
  · exact List.all_eq_true.1 check5 i (List.mem_finRange i)
  · exact List.all_eq_true.1 check6 i (List.mem_finRange i)
  · exact List.all_eq_true.1 check7 i (List.mem_finRange i)
  · exact List.all_eq_true.1 check8 i (List.mem_finRange i)
  · exact List.all_eq_true.1 check9 i (List.mem_finRange i)

/-- `n_i(a) ≠ 0`. -/
theorem un_ne (i : Fin 10) : ev8 (un i) ≠ 0 := un_ne_zero_of_uCheck (Pr 0) i _ (sym_u 0 i)

end X2Y5Z7.Norm
