name = "x2y5z7"
version = "0.1.0"
defaultTargets = ["X2Y5Z7"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.35.0-rc2"

[[lean_lib]]
name = "X2Y5Z7"
