/-
Generated by computer; every fact used is proved in Lean.
-/
import X2Y5Z7.SymbolSets.Q131.Data

/-! # Proposition 5.3 at `q = 131`: certificates for `η = 2 … 107` (72 R, 30 G, 4 F) -/

namespace X2Y5Z7.SymbolSets.Q131

open X2Y5Z7.SymbolSets

def k2 : Cert :=
  Cert.R [31]

theorem c2 : certCheck 131 D ILN 2 k2 = true := by decide +kernel

def k3 : Cert :=
  Cert.G 2 [1] [103, 119, 95, 121, 102, 73, 114] [90, 112, 45, 13, 108, 128, 2, 23]

theorem c3 : certCheck 131 D ILN 3 k3 = true := by decide +kernel

def k4 : Cert :=
  Cert.R [37]

theorem c4 : certCheck 131 D ILN 4 k4 = true := by decide +kernel

def k5 : Cert :=
  Cert.R [49]

theorem c5 : certCheck 131 D ILN 5 k5 = true := by decide +kernel

def k6 : Cert :=
  Cert.G 2 [1] [85, 95, 71, 72, 128, 77, 128] [60, 90, 53, 112, 125, 92, 91, 50]

theorem c6 : certCheck 131 D ILN 6 k6 = true := by decide +kernel

def k7 : Cert :=
  Cert.R [57]

theorem c7 : certCheck 131 D ILN 7 k7 = true := by decide +kernel

def k8 : Cert :=
  Cert.G 2 [1] [29, 17, 76, 6, 39, 84, 57] [94, 28, 15, 4, 113, 16, 5, 6]

theorem c8 : certCheck 131 D ILN 8 k8 = true := by decide +kernel

def k9 : Cert :=
  Cert.R [56]

theorem c9 : certCheck 131 D ILN 9 k9 = true := by decide +kernel

def k10 : Cert :=
  Cert.R [1]

theorem c10 : certCheck 131 D ILN 10 k10 = true := by decide +kernel

def k11 : Cert :=
  Cert.R [17]

theorem c11 : certCheck 131 D ILN 11 k11 = true := by decide +kernel

def k12 : Cert :=
  Cert.R [91]

theorem c12 : certCheck 131 D ILN 12 k12 = true := by decide +kernel

def k13 : Cert :=
  Cert.G 2 [1] [109, 94, 86, 51, 48, 116, 54] [41, 28, 73, 113, 27, 114, 111, 43]

theorem c13 : certCheck 131 D ILN 13 k13 = true := by decide +kernel

def k14 : Cert :=
  Cert.R [38]

theorem c14 : certCheck 131 D ILN 14 k14 = true := by decide +kernel

def k15 : Cert :=
  Cert.R [84]

theorem c15 : certCheck 131 D ILN 15 k15 = true := by decide +kernel

def k16 : Cert :=
  Cert.R [107]

theorem c16 : certCheck 131 D ILN 16 k16 = true := by decide +kernel

def k17 : Cert :=
  Cert.G 2 [62, 65, 1] [90, 3, 107, 56, 25] [93, 115, 89, 97, 78, 96]

theorem c17 : certCheck 131 D ILN 17 k17 = true := by decide +kernel

def k18 : Cert :=
  Cert.R [123]

theorem c18 : certCheck 131 D ILN 18 k18 = true := by decide +kernel

def k19 : Cert :=
  Cert.F [([44, 31, 1], [(1, [31, 2])]), ([48, 92, 1], [(1, [71, 124])]), ([127, 90, 119, 35, 1], [(2, [44, 80, 6, 27])])]
      [[(0, [([96, 4], [2, 3, 2, 0, 0, 0, 0, 0, 0]), ([4, 127], [2, 2, 3, 0, 0, 0, 0, 0, 0])]), (1, [([97, 58], [0, 3, 4, 0, 0, 0, 0, 0, 0]), ([73, 73], [0, 4, 3, 0, 0, 0, 0, 0, 0])])],
       [(0, [([38, 9], [0, 0, 0, 2, 2, 3, 0, 0, 0]), ([62, 122], [0, 0, 0, 2, 3, 2, 0, 0, 0])]), (1, [([42, 65], [0, 0, 0, 0, 4, 3, 0, 0, 0]), ([128, 66], [0, 0, 0, 0, 3, 4, 0, 0, 0])])],
       [(2, [([98, 91, 10, 29], [0, 0, 0, 0, 0, 0, 1, 4, 4]), ([32, 82, 77, 63], [0, 0, 0, 0, 0, 0, 1, 4, 4]), ([78, 126, 24, 67], [0, 0, 0, 0, 0, 0, 1, 4, 4]), ([19, 94, 20, 103], [0, 0, 0, 0, 0, 0, 1, 4, 4])])]]

theorem c19 : certCheck 131 D ILN 19 k19 = true := by decide +kernel

def k20 : Cert :=
  Cert.R [116]

theorem c20 : certCheck 131 D ILN 20 k20 = true := by decide +kernel

def k21 : Cert :=
  Cert.R [58]

theorem c21 : certCheck 131 D ILN 21 k21 = true := by decide +kernel

def k22 : Cert :=
  Cert.R [61]

theorem c22 : certCheck 131 D ILN 22 k22 = true := by decide +kernel

def k23 : Cert :=
  Cert.G 2 [83, 80, 1] [130, 69, 116, 0, 22] [6, 29, 127, 80, 98, 42]

theorem c23 : certCheck 131 D ILN 23 k23 = true := by decide +kernel

def k24 : Cert :=
  Cert.R [109]

theorem c24 : certCheck 131 D ILN 24 k24 = true := by decide +kernel

def k25 : Cert :=
  Cert.G 2 [1] [67, 17, 60, 1, 45, 98, 19] [68, 14, 3, 70, 35, 119, 5, 4]

theorem c25 : certCheck 131 D ILN 25 k25 = true := by decide +kernel

def k26 : Cert :=
  Cert.R [23]

theorem c26 : certCheck 131 D ILN 26 k26 = true := by decide +kernel

def k27 : Cert :=
  Cert.R [28]

theorem c27 : certCheck 131 D ILN 27 k27 = true := by decide +kernel

def k28 : Cert :=
  Cert.R [117]

theorem c28 : certCheck 131 D ILN 28 k28 = true := by decide +kernel

def k29 : Cert :=
  Cert.G 2 [1] [35, 91, 106, 91, 47, 1, 12] [21, 94, 8, 125, 13, 89, 85, 30]

theorem c29 : certCheck 131 D ILN 29 k29 = true := by decide +kernel

def k30 : Cert :=
  Cert.R [80]

theorem c30 : certCheck 131 D ILN 30 k30 = true := by decide +kernel

def k31 : Cert :=
  Cert.R [20]

theorem c31 : certCheck 131 D ILN 31 k31 = true := by decide +kernel

def k32 : Cert :=
  Cert.G 2 [78, 92, 1] [78, 85, 124, 96, 95] [51, 71, 73, 52, 119, 66]

theorem c32 : certCheck 131 D ILN 32 k32 = true := by decide +kernel

def k33 : Cert :=
  Cert.F [([83, 69, 1], [(1, [8, 42])]), ([112, 82, 1], [(1, [116, 22])]), ([116, 81, 65, 7, 1], [(2, [76, 15, 2, 24])])]
      [[(0, [([130, 20], [4, 3, 0, 0, 0, 0, 0, 0, 0]), ([63, 111], [4, 0, 3, 0, 0, 0, 0, 0, 0])]), (1, [([49, 42], [1, 2, 4, 0, 0, 0, 0, 0, 0]), ([0, 89], [1, 4, 2, 0, 0, 0, 0, 0, 0])])],
       [(0, [([102, 45], [0, 0, 0, 4, 0, 3, 0, 0, 0]), ([91, 86], [0, 0, 0, 4, 3, 0, 0, 0, 0])]), (1, [([95, 29], [0, 0, 0, 1, 4, 2, 0, 0, 0]), ([85, 102], [0, 0, 0, 1, 2, 4, 0, 0, 0])])],
       [(2, [([75, 63, 62, 30], [0, 0, 0, 0, 0, 0, 3, 0, 1]), ([99, 29, 28, 48], [0, 0, 0, 0, 0, 0, 3, 1, 0]), ([61, 0, 84, 91], [0, 0, 0, 0, 0, 0, 3, 1, 0]), ([20, 39, 88, 93], [0, 0, 0, 0, 0, 0, 3, 0, 1])])]]

theorem c33 : certCheck 131 D ILN 33 k33 = true := by decide +kernel

def k34 : Cert :=
  Cert.R [79]

theorem c34 : certCheck 131 D ILN 34 k34 = true := by decide +kernel

def k35 : Cert :=
  Cert.G 2 [1] [101, 103, 116, 83, 127, 108, 60] [77, 18, 54, 58, 93, 81, 24, 129]

theorem c35 : certCheck 131 D ILN 35 k35 = true := by decide +kernel

def k36 : Cert :=
  Cert.R [25]

theorem c36 : certCheck 131 D ILN 36 k36 = true := by decide +kernel

def k37 : Cert :=
  Cert.R [86]

theorem c37 : certCheck 131 D ILN 37 k37 = true := by decide +kernel

def k38 : Cert :=
  Cert.G 2 [1] [72, 23, 0, 109, 35, 88, 12] [40, 84, 78, 47, 80, 19, 89, 34]

theorem c38 : certCheck 131 D ILN 38 k38 = true := by decide +kernel

def k39 : Cert :=
  Cert.G 2 [1] [17, 16, 110, 58, 109, 41, 120] [97, 49, 103, 4, 104, 55, 39, 13]

theorem c39 : certCheck 131 D ILN 39 k39 = true := by decide +kernel

def k40 : Cert :=
  Cert.R [94]

theorem c40 : certCheck 131 D ILN 40 k40 = true := by decide +kernel

def k41 : Cert :=
  Cert.R [39]

theorem c41 : certCheck 131 D ILN 41 k41 = true := by decide +kernel

def k42 : Cert :=
  Cert.R [40]

theorem c42 : certCheck 131 D ILN 42 k42 = true := by decide +kernel

def k43 : Cert :=
  Cert.R [21]

theorem c43 : certCheck 131 D ILN 43 k43 = true := by decide +kernel

def k44 : Cert :=
  Cert.R [10]

theorem c44 : certCheck 131 D ILN 44 k44 = true := by decide +kernel

def k45 : Cert :=
  Cert.R [48]

theorem c45 : certCheck 131 D ILN 45 k45 = true := by decide +kernel

def k46 : Cert :=
  Cert.R [42]

theorem c46 : certCheck 131 D ILN 46 k46 = true := by decide +kernel

def k47 : Cert :=
  Cert.G 2 [1] [20, 60, 64, 129, 25, 18, 90] [104, 55, 58, 106, 91, 8, 115, 66]

theorem c47 : certCheck 131 D ILN 47 k47 = true := by decide +kernel

def k48 : Cert :=
  Cert.R [112]

theorem c48 : certCheck 131 D ILN 48 k48 = true := by decide +kernel

def k49 : Cert :=
  Cert.R [74]

theorem c49 : certCheck 131 D ILN 49 k49 = true := by decide +kernel

def k50 : Cert :=
  Cert.G 2 [108, 74, 1] [70, 36, 118, 59, 70] [44, 53, 11, 77, 43, 79]

theorem c50 : certCheck 131 D ILN 50 k50 = true := by decide +kernel

def k51 : Cert :=
  Cert.G 2 [1] [60, 83, 29, 69, 83, 80, 65] [78, 30, 127, 44, 62, 106, 8, 45]

theorem c51 : certCheck 131 D ILN 51 k51 = true := by decide +kernel

def k52 : Cert :=
  Cert.G 2 [1] [8, 85, 17, 109, 86, 107, 40] [45, 76, 130, 39, 6, 27, 13, 74]

theorem c52 : certCheck 131 D ILN 52 k52 = true := by decide +kernel

def k53 : Cert :=
  Cert.R [45]

theorem c53 : certCheck 131 D ILN 53 k53 = true := by decide +kernel

def k54 : Cert :=
  Cert.R [14]

theorem c54 : certCheck 131 D ILN 54 k54 = true := by decide +kernel

def k55 : Cert :=
  Cert.R [63]

theorem c55 : certCheck 131 D ILN 55 k55 = true := by decide +kernel

def k56 : Cert :=
  Cert.G 2 [1] [23, 41, 63, 52, 96, 22, 44] [121, 2, 90, 5, 102, 87, 6, 10]

theorem c56 : certCheck 131 D ILN 56 k56 = true := by decide +kernel

def k57 : Cert :=
  Cert.R [65]

theorem c57 : certCheck 131 D ILN 57 k57 = true := by decide +kernel

def k58 : Cert :=
  Cert.R [18]

theorem c58 : certCheck 131 D ILN 58 k58 = true := by decide +kernel

def k59 : Cert :=
  Cert.R [44]

theorem c59 : certCheck 131 D ILN 59 k59 = true := by decide +kernel

def k60 : Cert :=
  Cert.R [92]

theorem c60 : certCheck 131 D ILN 60 k60 = true := by decide +kernel

def k61 : Cert :=
  Cert.R [69]

theorem c61 : certCheck 131 D ILN 61 k61 = true := by decide +kernel

def k62 : Cert :=
  Cert.R [96]

theorem c62 : certCheck 131 D ILN 62 k62 = true := by decide +kernel

def k63 : Cert :=
  Cert.R [66]

theorem c63 : certCheck 131 D ILN 63 k63 = true := by decide +kernel

def k64 : Cert :=
  Cert.G 2 [1] [36, 39, 88, 20, 90, 4, 38] [105, 51, 29, 70, 40, 37, 4, 90]

theorem c64 : certCheck 131 D ILN 64 k64 = true := by decide +kernel

def k65 : Cert :=
  Cert.R [19]

theorem c65 : certCheck 131 D ILN 65 k65 = true := by decide +kernel

def k66 : Cert :=
  Cert.G 2 [1] [70, 89, 20, 64, 120, 121, 55] [30, 2, 87, 117, 11, 57, 66, 23]

theorem c66 : certCheck 131 D ILN 66 k66 = true := by decide +kernel

def k67 : Cert :=
  Cert.R [105]

theorem c67 : certCheck 131 D ILN 67 k67 = true := by decide +kernel

def k68 : Cert :=
  Cert.F [([28, 93, 1], [(1, [97, 119])]), ([5, 111, 1], [(1, [69, 111])]), ([127, 32, 108, 85, 1], [(2, [80, 37, 124, 31])])]
      [[(0, [([71, 33], [1, 2, 4, 0, 0, 0, 0, 0, 0]), ([98, 98], [1, 4, 2, 0, 0, 0, 0, 0, 0])]), (1, [([38, 48], [1, 2, 4, 0, 0, 0, 0, 0, 0]), ([113, 83], [1, 4, 2, 0, 0, 0, 0, 0, 0])])],
       [(0, [([118, 24], [0, 0, 0, 1, 2, 4, 0, 0, 0]), ([51, 107], [0, 0, 0, 1, 4, 2, 0, 0, 0])]), (1, [([23, 23], [0, 0, 0, 1, 2, 4, 0, 0, 0]), ([128, 108], [0, 0, 0, 1, 4, 2, 0, 0, 0])])],
       [(2, [([29, 64, 35, 25], [0, 0, 0, 0, 0, 0, 1, 3, 0]), ([81, 57, 47, 63], [0, 0, 0, 0, 0, 0, 1, 0, 3]), ([114, 34, 56, 66], [0, 0, 0, 0, 0, 0, 1, 0, 3]), ([84, 107, 124, 108], [0, 0, 0, 0, 0, 0, 1, 3, 0])])]]

theorem c68 : certCheck 131 D ILN 68 k68 = true := by decide +kernel

def k69 : Cert :=
  Cert.R [100]

theorem c69 : certCheck 131 D ILN 69 k69 = true := by decide +kernel

def k70 : Cert :=
  Cert.G 2 [1] [129, 125, 82, 40, 61, 30, 4] [89, 113, 11, 58, 26, 117, 29, 116]

theorem c70 : certCheck 131 D ILN 70 k70 = true := by decide +kernel

def k71 : Cert :=
  Cert.R [64]

theorem c71 : certCheck 131 D ILN 71 k71 = true := by decide +kernel

def k72 : Cert :=
  Cert.G 2 [1] [83, 58, 26, 104, 0, 25, 18] [49, 6, 82, 97, 62, 55, 27, 28]

theorem c72 : certCheck 131 D ILN 72 k72 = true := by decide +kernel

def k73 : Cert :=
  Cert.R [47]

theorem c73 : certCheck 131 D ILN 73 k73 = true := by decide +kernel

def k74 : Cert :=
  Cert.R [12]

theorem c74 : certCheck 131 D ILN 74 k74 = true := by decide +kernel

def k75 : Cert :=
  Cert.R [88]

theorem c75 : certCheck 131 D ILN 75 k75 = true := by decide +kernel

def k76 : Cert :=
  Cert.F [([99, 27, 1], [(1, [7, 83])]), ([12, 114, 1], [(1, [99, 50])]), ([88, 98, 79, 17, 1], [(2, [115, 16, 33, 74])])]
      [[(0, [([26, 49], [0, 2, 0, 0, 0, 0, 0, 0, 0]), ([78, 82], [0, 0, 2, 0, 0, 0, 0, 0, 0])]), (1, [([57, 27], [1, 2, 4, 0, 0, 0, 0, 0, 0]), ([91, 104], [1, 4, 2, 0, 0, 0, 0, 0, 0])])],
       [(0, [([36, 12], [0, 0, 0, 0, 0, 2, 0, 0, 0]), ([68, 119], [0, 0, 0, 0, 2, 0, 0, 0, 0])]), (1, [([124, 28], [0, 0, 0, 1, 4, 2, 0, 0, 0]), ([24, 103], [0, 0, 0, 1, 2, 4, 0, 0, 0])])],
       [(2, [([26, 24, 27, 67], [0, 0, 0, 0, 0, 0, 2, 4, 3]), ([11, 12, 62, 89], [0, 0, 0, 0, 0, 0, 2, 3, 4]), ([97, 98, 15, 113], [0, 0, 0, 0, 0, 0, 2, 3, 4]), ([111, 128, 27, 124], [0, 0, 0, 0, 0, 0, 2, 4, 3])])]]

theorem c76 : certCheck 131 D ILN 76 k76 = true := by decide +kernel

def k77 : Cert :=
  Cert.R [24]

theorem c77 : certCheck 131 D ILN 77 k77 = true := by decide +kernel

def k78 : Cert :=
  Cert.G 2 [1] [54, 29, 30, 96, 79, 123, 1] [95, 20, 5, 99, 73, 23, 107, 72]

theorem c78 : certCheck 131 D ILN 78 k78 = true := by decide +kernel

def k79 : Cert :=
  Cert.G 2 [1] [96, 17, 29, 36, 80, 11, 44] [90, 114, 96, 62, 25, 121, 42, 62]

theorem c79 : certCheck 131 D ILN 79 k79 = true := by decide +kernel

def k80 : Cert :=
  Cert.R [32]

theorem c80 : certCheck 131 D ILN 80 k80 = true := by decide +kernel

def k81 : Cert :=
  Cert.R [72]

theorem c81 : certCheck 131 D ILN 81 k81 = true := by decide +kernel

def k82 : Cert :=
  Cert.G 2 [41, 41, 1] [109, 92, 75, 38, 7] [13, 94, 98, 121, 97, 22]

theorem c82 : certCheck 131 D ILN 82 k82 = true := by decide +kernel

def k83 : Cert :=
  Cert.R [13]

theorem c83 : certCheck 131 D ILN 83 k83 = true := by decide +kernel

def k84 : Cert :=
  Cert.R [8]

theorem c84 : certCheck 131 D ILN 84 k84 = true := by decide +kernel

def k85 : Cert :=
  Cert.R [54]

theorem c85 : certCheck 131 D ILN 85 k85 = true := by decide +kernel

def k86 : Cert :=
  Cert.R [59]

theorem c86 : certCheck 131 D ILN 86 k86 = true := by decide +kernel

def k87 : Cert :=
  Cert.R [29]

theorem c87 : certCheck 131 D ILN 87 k87 = true := by decide +kernel

def k88 : Cert :=
  Cert.R [121]

theorem c88 : certCheck 131 D ILN 88 k88 = true := by decide +kernel

def k89 : Cert :=
  Cert.G 2 [1] [129, 63, 11, 84, 27, 128, 51] [66, 104, 109, 89, 70, 0, 21, 74]

theorem c89 : certCheck 131 D ILN 89 k89 = true := by decide +kernel

def k90 : Cert :=
  Cert.R [46]

theorem c90 : certCheck 131 D ILN 90 k90 = true := by decide +kernel

def k91 : Cert :=
  Cert.G 2 [1] [63, 89, 31, 89, 1, 118, 8] [0, 45, 6, 5, 35, 45, 94, 8]

theorem c91 : certCheck 131 D ILN 91 k91 = true := by decide +kernel

def k92 : Cert :=
  Cert.R [15]

theorem c92 : certCheck 131 D ILN 92 k92 = true := by decide +kernel

def k93 : Cert :=
  Cert.R [104]

theorem c93 : certCheck 131 D ILN 93 k93 = true := by decide +kernel

def k94 : Cert :=
  Cert.R [50]

theorem c94 : certCheck 131 D ILN 94 k94 = true := by decide +kernel

def k95 : Cert :=
  Cert.G 2 [1] [40, 62, 84, 60, 7, 112, 57] [66, 47, 81, 27, 60, 63, 84, 17]

theorem c95 : certCheck 131 D ILN 95 k95 = true := by decide +kernel

def k96 : Cert :=
  Cert.R [83]

theorem c96 : certCheck 131 D ILN 96 k96 = true := by decide +kernel

def k97 : Cert :=
  Cert.R [43]

theorem c97 : certCheck 131 D ILN 97 k97 = true := by decide +kernel

def k98 : Cert :=
  Cert.R [5]

theorem c98 : certCheck 131 D ILN 98 k98 = true := by decide +kernel

def k99 : Cert :=
  Cert.G 2 [1] [23, 77, 55, 70, 23, 75, 90] [42, 41, 61, 15, 121, 115, 101, 43]

theorem c99 : certCheck 131 D ILN 99 k99 = true := by decide +kernel

def k100 : Cert :=
  Cert.R [53]

theorem c100 : certCheck 131 D ILN 100 k100 = true := by decide +kernel

def k101 : Cert :=
  Cert.R [3]

theorem c101 : certCheck 131 D ILN 101 k101 = true := by decide +kernel

def k102 : Cert :=
  Cert.R [4]

theorem c102 : certCheck 131 D ILN 102 k102 = true := by decide +kernel

def k103 : Cert :=
  Cert.G 2 [1] [91, 33, 123, 66, 29, 114, 14] [130, 87, 53, 69, 80, 83, 112, 22]

theorem c103 : certCheck 131 D ILN 103 k103 = true := by decide +kernel

def k104 : Cert :=
  Cert.R [75]

theorem c104 : certCheck 131 D ILN 104 k104 = true := by decide +kernel

def k105 : Cert :=
  Cert.R [106]

theorem c105 : certCheck 131 D ILN 105 k105 = true := by decide +kernel

def k106 : Cert :=
  Cert.R [7]

theorem c106 : certCheck 131 D ILN 106 k106 = true := by decide +kernel

def k107 : Cert :=
  Cert.G 2 [1] [72, 37, 119, 106, 107, 51, 63] [116, 75, 14, 42, 35, 58, 92, 2]

theorem c107 : certCheck 131 D ILN 107 k107 = true := by decide +kernel

def certs0 : List (ℕ × Cert) := [(2, k2), (3, k3), (4, k4), (5, k5), (6, k6), (7, k7), (8, k8), (9, k9), (10, k10), (11, k11), (12, k12), (13, k13), (14, k14), (15, k15), (16, k16), (17, k17), (18, k18), (19, k19), (20, k20), (21, k21), (22, k22), (23, k23), (24, k24), (25, k25), (26, k26), (27, k27), (28, k28), (29, k29), (30, k30), (31, k31), (32, k32), (33, k33), (34, k34), (35, k35), (36, k36), (37, k37), (38, k38), (39, k39), (40, k40), (41, k41), (42, k42), (43, k43), (44, k44), (45, k45), (46, k46), (47, k47), (48, k48), (49, k49), (50, k50), (51, k51), (52, k52), (53, k53), (54, k54), (55, k55), (56, k56), (57, k57), (58, k58), (59, k59), (60, k60), (61, k61), (62, k62), (63, k63), (64, k64), (65, k65), (66, k66), (67, k67), (68, k68), (69, k69), (70, k70), (71, k71), (72, k72), (73, k73), (74, k74), (75, k75), (76, k76), (77, k77), (78, k78), (79, k79), (80, k80), (81, k81), (82, k82), (83, k83), (84, k84), (85, k85), (86, k86), (87, k87), (88, k88), (89, k89), (90, k90), (91, k91), (92, k92), (93, k93), (94, k94), (95, k95), (96, k96), (97, k97), (98, k98), (99, k99), (100, k100), (101, k101), (102, k102), (103, k103), (104, k104), (105, k105), (106, k106), (107, k107)]

theorem ok0 : certs0.all (fun p => certCheck 131 D ILN p.1 p.2) = true := by
  simp only [certs0, List.all_cons, List.all_nil, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31, c32, c33, c34, c35, c36, c37, c38, c39, c40, c41, c42, c43, c44, c45, c46, c47, c48, c49, c50, c51, c52, c53, c54, c55, c56, c57, c58, c59, c60, c61, c62, c63, c64, c65, c66, c67, c68, c69, c70, c71, c72, c73, c74, c75, c76, c77, c78, c79, c80, c81, c82, c83, c84, c85, c86, c87, c88, c89, c90, c91, c92, c93, c94, c95, c96, c97, c98, c99, c100, c101, c102, c103, c104, c105, c106, c107, Bool.and_self]

end X2Y5Z7.SymbolSets.Q131
