/-
Generated by computer; every fact used is proved in Lean.
-/
import X2Y5Z7.Primes.Basic
import X2Y5Z7.FiniteFields.Q131

/-! # The primes of `L8` above `131` as residue maps

`R : Fin 3 → Aux.ResidueMap L8 131`, `R t` built from `FiniteFields.Q131.L8P t` (file order), so that `(R t).k` is
`F_131[x]/(h_t)` and `(R t).r = (L8P t).res` definitionally (`r_eq<t>`). Residue degrees `dvec = [2, 2, 4]`
(`deg_R`, sum `8`), pairwise distinct kernels (`hker`, certified by `h_s(x_t) ≠ 0` in `F_q[x]/(h_t)`),
`(131 : (R t).k) = 0` (`char_R`) and `2, 5, 7 ≠ 0` in `(R t).k` (`ne_zero_R`). -/

namespace X2Y5Z7.Primes.Q131

open X2Y5Z7.FiniteFields X2Y5Z7.FiniteFields.Q131

noncomputable section

/-- The primes of `L8` above `131`, in the order of `FiniteFields.Q131.L8P`. -/
def R : Fin 3 → Aux.ResidueMap L8 131 := ![L8P0.toResidueMap, L8P1.toResidueMap, L8P2.toResidueMap]

/-- The residue degrees. -/
def dvec : Fin 3 → ℕ := ![2, 2, 4]

theorem r_eq0 : (R 0).r = (L8P0).res := rfl

theorem deg0 : (R 0).deg = 2 := (L8P0).deg_toResidueMap

theorem r_eq1 : (R 1).r = (L8P1).res := rfl

theorem deg1 : (R 1).deg = 2 := (L8P1).deg_toResidueMap

theorem r_eq2 : (R 2).r = (L8P2).res := rfl

theorem deg2 : (R 2).deg = 4 := (L8P2).deg_toResidueMap

theorem deg_R (i : Fin 3) : (R i).deg = dvec i := by
  fin_cases i
  exacts [deg0, deg1, deg2]

theorem sum_dvec : ∑ i, dvec i = 8 := by decide

theorem ker01 : RingHom.ker (R 0).r ≠ RingHom.ker (R 1).r :=
  (L8P0).ker_res_ne L8P1 (by decide +kernel)

theorem ker02 : RingHom.ker (R 0).r ≠ RingHom.ker (R 2).r :=
  (L8P0).ker_res_ne L8P2 (by decide +kernel)

theorem ker10 : RingHom.ker (R 1).r ≠ RingHom.ker (R 0).r :=
  (L8P1).ker_res_ne L8P0 (by decide +kernel)

theorem ker12 : RingHom.ker (R 1).r ≠ RingHom.ker (R 2).r :=
  (L8P1).ker_res_ne L8P2 (by decide +kernel)

theorem ker20 : RingHom.ker (R 2).r ≠ RingHom.ker (R 0).r :=
  (L8P2).ker_res_ne L8P0 (by decide +kernel)

theorem ker21 : RingHom.ker (R 2).r ≠ RingHom.ker (R 1).r :=
  (L8P2).ker_res_ne L8P1 (by decide +kernel)

theorem hker : Pairwise fun i j : Fin 3 => RingHom.ker (R i).r ≠ RingHom.ker (R j).r := by
  intro i j hij
  fin_cases i <;> fin_cases j
  exacts [(hij rfl).elim, ker01, ker02, ker10, (hij rfl).elim, ker12, ker20, ker21, (hij rfl).elim]

theorem char_R (i : Fin 3) : ((131 : ℕ) : (R i).k) = 0 := natCast_self (R i)

theorem ne_zero_R (i : Fin 3) : (2 : (R i).k) ≠ 0 ∧ (5 : (R i).k) ≠ 0 ∧ (7 : (R i).k) ≠ 0 := by
  refine ⟨?_, ?_, ?_⟩
  · exact_mod_cast natCast_ne_zero (R i) 2 (by decide)
  · exact_mod_cast natCast_ne_zero (R i) 5 (by decide)
  · exact_mod_cast natCast_ne_zero (R i) 7 (by decide)

end

end X2Y5Z7.Primes.Q131
