/-
Generated by computer; every fact used is proved in Lean.
-/
module

public import X2Y5Z7.Primes.Basic
public import X2Y5Z7.FiniteFields.Q181

@[expose] public section

/-! # The primes of `L8` above `181` as residue maps

`R : Fin 5 → Aux.ResidueMap L8 181`, `R t` built from `FiniteFields.Q181.L8P t` (file order), so that `(R t).k` is
`F_181[x]/(h_t)` and `(R t).r = (L8P t).res` definitionally (`r_eq<t>`). Residue degrees `dvec = [1, 1, 1, 2, 3]`
(`deg_R`, sum `8`), pairwise distinct kernels (`hker`, certified by `h_s(x_t) ≠ 0` in `F_q[x]/(h_t)`),
`(181 : (R t).k) = 0` (`char_R`) and `2, 5, 7 ≠ 0` in `(R t).k` (`ne_zero_R`). -/

namespace X2Y5Z7.Primes.Q181

open X2Y5Z7.FiniteFields X2Y5Z7.FiniteFields.Q181

noncomputable section

/-- The primes of `L8` above `181`, in the order of `FiniteFields.Q181.L8P`. -/
def R : Fin 5 → Aux.ResidueMap L8 181 := ![L8P0.toResidueMap, L8P1.toResidueMap, L8P2.toResidueMap, L8P3.toResidueMap, L8P4.toResidueMap]

/-- The residue degrees. -/
def dvec : Fin 5 → ℕ := ![1, 1, 1, 2, 3]

theorem r_eq0 : (R 0).r = (L8P0).res := rfl

theorem deg0 : (R 0).deg = 1 := (L8P0).deg_toResidueMap

theorem r_eq1 : (R 1).r = (L8P1).res := rfl

theorem deg1 : (R 1).deg = 1 := (L8P1).deg_toResidueMap

theorem r_eq2 : (R 2).r = (L8P2).res := rfl

theorem deg2 : (R 2).deg = 1 := (L8P2).deg_toResidueMap

theorem r_eq3 : (R 3).r = (L8P3).res := rfl

theorem deg3 : (R 3).deg = 2 := (L8P3).deg_toResidueMap

theorem r_eq4 : (R 4).r = (L8P4).res := rfl

theorem deg4 : (R 4).deg = 3 := (L8P4).deg_toResidueMap

theorem deg_R (i : Fin 5) : (R i).deg = dvec i := by
  fin_cases i
  exacts [deg0, deg1, deg2, deg3, deg4]

theorem sum_dvec : ∑ i, dvec i = 8 := by decide

theorem ker01 : RingHom.ker (R 0).r ≠ RingHom.ker (R 1).r :=
  (L8P0).ker_res_ne L8P1 (by decide +kernel)

theorem ker02 : RingHom.ker (R 0).r ≠ RingHom.ker (R 2).r :=
  (L8P0).ker_res_ne L8P2 (by decide +kernel)

theorem ker03 : RingHom.ker (R 0).r ≠ RingHom.ker (R 3).r :=
  (L8P0).ker_res_ne L8P3 (by decide +kernel)

theorem ker04 : RingHom.ker (R 0).r ≠ RingHom.ker (R 4).r :=
  (L8P0).ker_res_ne L8P4 (by decide +kernel)

theorem ker10 : RingHom.ker (R 1).r ≠ RingHom.ker (R 0).r :=
  (L8P1).ker_res_ne L8P0 (by decide +kernel)

theorem ker12 : RingHom.ker (R 1).r ≠ RingHom.ker (R 2).r :=
  (L8P1).ker_res_ne L8P2 (by decide +kernel)

theorem ker13 : RingHom.ker (R 1).r ≠ RingHom.ker (R 3).r :=
  (L8P1).ker_res_ne L8P3 (by decide +kernel)

theorem ker14 : RingHom.ker (R 1).r ≠ RingHom.ker (R 4).r :=
  (L8P1).ker_res_ne L8P4 (by decide +kernel)

theorem ker20 : RingHom.ker (R 2).r ≠ RingHom.ker (R 0).r :=
  (L8P2).ker_res_ne L8P0 (by decide +kernel)

theorem ker21 : RingHom.ker (R 2).r ≠ RingHom.ker (R 1).r :=
  (L8P2).ker_res_ne L8P1 (by decide +kernel)

theorem ker23 : RingHom.ker (R 2).r ≠ RingHom.ker (R 3).r :=
  (L8P2).ker_res_ne L8P3 (by decide +kernel)

theorem ker24 : RingHom.ker (R 2).r ≠ RingHom.ker (R 4).r :=
  (L8P2).ker_res_ne L8P4 (by decide +kernel)

theorem ker30 : RingHom.ker (R 3).r ≠ RingHom.ker (R 0).r :=
  (L8P3).ker_res_ne L8P0 (by decide +kernel)

theorem ker31 : RingHom.ker (R 3).r ≠ RingHom.ker (R 1).r :=
  (L8P3).ker_res_ne L8P1 (by decide +kernel)

theorem ker32 : RingHom.ker (R 3).r ≠ RingHom.ker (R 2).r :=
  (L8P3).ker_res_ne L8P2 (by decide +kernel)

theorem ker34 : RingHom.ker (R 3).r ≠ RingHom.ker (R 4).r :=
  (L8P3).ker_res_ne L8P4 (by decide +kernel)

theorem ker40 : RingHom.ker (R 4).r ≠ RingHom.ker (R 0).r :=
  (L8P4).ker_res_ne L8P0 (by decide +kernel)

theorem ker41 : RingHom.ker (R 4).r ≠ RingHom.ker (R 1).r :=
  (L8P4).ker_res_ne L8P1 (by decide +kernel)

theorem ker42 : RingHom.ker (R 4).r ≠ RingHom.ker (R 2).r :=
  (L8P4).ker_res_ne L8P2 (by decide +kernel)

theorem ker43 : RingHom.ker (R 4).r ≠ RingHom.ker (R 3).r :=
  (L8P4).ker_res_ne L8P3 (by decide +kernel)

theorem hker : Pairwise fun i j : Fin 5 => RingHom.ker (R i).r ≠ RingHom.ker (R j).r := by
  intro i j hij
  fin_cases i <;> fin_cases j
  exacts [(hij rfl).elim, ker01, ker02, ker03, ker04, ker10, (hij rfl).elim, ker12, ker13, ker14, ker20, ker21, (hij rfl).elim, ker23, ker24, ker30, ker31, ker32, (hij rfl).elim, ker34, ker40, ker41, ker42, ker43, (hij rfl).elim]

theorem char_R (i : Fin 5) : ((181 : ℕ) : (R i).k) = 0 := natCast_self (R i)

theorem ne_zero_R (i : Fin 5) : (2 : (R i).k) ≠ 0 ∧ (5 : (R i).k) ≠ 0 ∧ (7 : (R i).k) ≠ 0 := by
  refine ⟨?_, ?_, ?_⟩
  · exact_mod_cast natCast_ne_zero (R i) 2 (by decide)
  · exact_mod_cast natCast_ne_zero (R i) 5 (by decide)
  · exact_mod_cast natCast_ne_zero (R i) 7 (by decide)

end

end X2Y5Z7.Primes.Q181
