/-
Generated by computer; every fact used is proved in Lean.
-/
import X2Y5Z7.SymbolSets.Q181.Data

/-! # Proposition 5.3 at `q = 181`: certificates for `η = 2 … 88` (0 R, 84 G, 3 F) -/

namespace X2Y5Z7.SymbolSets.Q181

open X2Y5Z7.SymbolSets

def k2 : Cert :=
  Cert.G 1 [1] [18, 116, 102, 24, 38, 92, 38] [3, 33, 120, 101, 153, 124, 98, 8]

theorem c2 : certCheck 181 D ILN 2 k2 = true := by decide +kernel

def k3 : Cert :=
  Cert.F [([10, 1], []), ([15, 1], []), ([113, 1], []), ([91, 40, 1], [(1, [48, 111])]), ([128, 85, 40, 1], [(1, [131, 68, 69])])]
      [[(0, [([171], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([166], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([68], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([171], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])]), (1, [([166], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])]), (2, [([68], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([171], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])]), (1, [([166], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])]), (2, [([68], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])])],
       [(3, [([33, 64], [0, 0, 0, 0, 0, 0, 4, 3, 0, 0, 0]), ([108, 117], [0, 0, 0, 0, 0, 0, 4, 0, 3, 0, 0])])],
       [(4, [([108, 119, 90], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]), ([141, 53, 99], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]), ([73, 9, 173], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3])])]]

theorem c3 : certCheck 181 D ILN 3 k3 = true := by decide +kernel

def k4 : Cert :=
  Cert.G 1 [20, 1] [79, 159, 106, 38, 70, 143] [128, 47, 59, 53, 121, 146, 159]

theorem c4 : certCheck 181 D ILN 4 k4 = true := by decide +kernel

def k5 : Cert :=
  Cert.G 1 [82, 1] [161, 101, 167, 119, 62, 135] [180, 29, 123, 57, 138, 63, 64]

theorem c5 : certCheck 181 D ILN 5 k5 = true := by decide +kernel

def k6 : Cert :=
  Cert.G 1 [107, 1] [99, 35, 149, 31, 124, 84] [83, 162, 100, 131, 129, 53, 127]

theorem c6 : certCheck 181 D ILN 6 k6 = true := by decide +kernel

def k7 : Cert :=
  Cert.G 1 [48, 151, 1] [165, 149, 158, 164, 178] [109, 28, 35, 85, 47, 62]

theorem c7 : certCheck 181 D ILN 7 k7 = true := by decide +kernel

def k8 : Cert :=
  Cert.G 1 [101, 172, 1] [79, 47, 91, 172, 35] [165, 56, 93, 88, 0, 48]

theorem c8 : certCheck 181 D ILN 8 k8 = true := by decide +kernel

def k9 : Cert :=
  Cert.G 1 [1] [144, 21, 173, 146, 160, 3, 113] [161, 176, 10, 32, 96, 3, 136, 180]

theorem c9 : certCheck 181 D ILN 9 k9 = true := by decide +kernel

def k10 : Cert :=
  Cert.G 1 [1] [97, 163, 171, 120, 82, 110, 58] [32, 14, 34, 138, 48, 111, 71, 94]

theorem c10 : certCheck 181 D ILN 10 k10 = true := by decide +kernel

def k11 : Cert :=
  Cert.G 1 [95, 1] [79, 44, 15, 112, 95, 118] [63, 116, 56, 3, 8, 120, 12]

theorem c11 : certCheck 181 D ILN 11 k11 = true := by decide +kernel

def k12 : Cert :=
  Cert.G 1 [57, 1] [45, 44, 149, 104, 115, 145] [12, 71, 93, 170, 142, 143, 56]

theorem c12 : certCheck 181 D ILN 12 k12 = true := by decide +kernel

def k13 : Cert :=
  Cert.G 1 [1] [77, 57, 19, 164, 60, 60, 93] [172, 105, 97, 17, 112, 155, 38, 78]

theorem c13 : certCheck 181 D ILN 13 k13 = true := by decide +kernel

def k14 : Cert :=
  Cert.G 1 [7, 1] [4, 7, 5, 28, 115, 45] [162, 151, 21, 125, 42, 117, 6]

theorem c14 : certCheck 181 D ILN 14 k14 = true := by decide +kernel

def k15 : Cert :=
  Cert.G 1 [96, 8, 1] [33, 152, 121, 58, 33] [45, 176, 172, 129, 109, 87]

theorem c15 : certCheck 181 D ILN 15 k15 = true := by decide +kernel

def k16 : Cert :=
  Cert.G 1 [1] [55, 97, 109, 36, 8, 5, 139] [165, 61, 85, 149, 165, 55, 74, 36]

theorem c16 : certCheck 181 D ILN 16 k16 = true := by decide +kernel

def k17 : Cert :=
  Cert.G 1 [1] [25, 28, 112, 11, 171, 40, 81] [118, 110, 95, 121, 117, 68, 92, 60]

theorem c17 : certCheck 181 D ILN 17 k17 = true := by decide +kernel

def k18 : Cert :=
  Cert.G 1 [1] [143, 67, 40, 83, 81, 80, 82] [24, 107, 162, 136, 98, 171, 94, 14]

theorem c18 : certCheck 181 D ILN 18 k18 = true := by decide +kernel

def k19 : Cert :=
  Cert.G 1 [138, 1] [2, 124, 123, 59, 148, 40] [146, 89, 162, 85, 171, 67, 19]

theorem c19 : certCheck 181 D ILN 19 k19 = true := by decide +kernel

def k20 : Cert :=
  Cert.G 1 [169, 92, 1] [63, 151, 50, 3, 93] [47, 98, 169, 72, 67, 42]

theorem c20 : certCheck 181 D ILN 20 k20 = true := by decide +kernel

def k21 : Cert :=
  Cert.G 1 [179, 41, 1] [37, 149, 152, 4, 105] [106, 134, 63, 117, 29, 21]

theorem c21 : certCheck 181 D ILN 21 k21 = true := by decide +kernel

def k22 : Cert :=
  Cert.G 1 [1] [24, 52, 48, 56, 162, 28, 126] [104, 31, 91, 5, 1, 98, 66, 159]

theorem c22 : certCheck 181 D ILN 22 k22 = true := by decide +kernel

def k23 : Cert :=
  Cert.G 1 [121, 1] [135, 34, 150, 140, 12, 161] [79, 92, 91, 126, 137, 26, 121]

theorem c23 : certCheck 181 D ILN 23 k23 = true := by decide +kernel

def k24 : Cert :=
  Cert.G 1 [1] [60, 103, 32, 41, 20, 33, 41] [1, 30, 100, 99, 0, 135, 41, 15]

theorem c24 : certCheck 181 D ILN 24 k24 = true := by decide +kernel

def k25 : Cert :=
  Cert.G 1 [1] [39, 7, 128, 168, 55, 74, 129] [78, 51, 33, 134, 2, 43, 50, 89]

theorem c25 : certCheck 181 D ILN 25 k25 = true := by decide +kernel

def k26 : Cert :=
  Cert.G 1 [70, 62, 1] [124, 167, 171, 179, 100] [61, 11, 31, 91, 86, 32]

theorem c26 : certCheck 181 D ILN 26 k26 = true := by decide +kernel

def k27 : Cert :=
  Cert.G 1 [55, 1] [145, 140, 150, 83, 128, 84] [56, 78, 30, 82, 59, 43, 109]

theorem c27 : certCheck 181 D ILN 27 k27 = true := by decide +kernel

def k28 : Cert :=
  Cert.G 1 [72, 1] [151, 104, 93, 161, 89, 151] [45, 45, 0, 75, 28, 79, 160]

theorem c28 : certCheck 181 D ILN 28 k28 = true := by decide +kernel

def k29 : Cert :=
  Cert.G 1 [1] [97, 50, 113, 176, 94, 151, 43] [55, 126, 138, 142, 133, 55, 58, 46]

theorem c29 : certCheck 181 D ILN 29 k29 = true := by decide +kernel

def k30 : Cert :=
  Cert.G 1 [31, 1] [141, 133, 133, 154, 13, 131] [21, 124, 125, 87, 107, 5, 158]

theorem c30 : certCheck 181 D ILN 30 k30 = true := by decide +kernel

def k31 : Cert :=
  Cert.G 1 [1] [6, 39, 173, 180, 50, 129, 42] [89, 25, 58, 114, 112, 128, 97, 14]

theorem c31 : certCheck 181 D ILN 31 k31 = true := by decide +kernel

def k32 : Cert :=
  Cert.G 1 [81, 10, 1] [44, 177, 10, 100, 3] [59, 46, 146, 120, 38, 153]

theorem c32 : certCheck 181 D ILN 32 k32 = true := by decide +kernel

def k33 : Cert :=
  Cert.G 1 [1] [101, 42, 148, 3, 50, 161, 154] [7, 107, 18, 114, 143, 41, 94, 158]

theorem c33 : certCheck 181 D ILN 33 k33 = true := by decide +kernel

def k34 : Cert :=
  Cert.G 1 [50, 21, 1] [144, 101, 0, 131, 114] [167, 107, 12, 3, 84, 152]

theorem c34 : certCheck 181 D ILN 34 k34 = true := by decide +kernel

def k35 : Cert :=
  Cert.G 1 [162, 94, 1] [55, 110, 147, 46, 149] [41, 86, 120, 140, 3, 20]

theorem c35 : certCheck 181 D ILN 35 k35 = true := by decide +kernel

def k36 : Cert :=
  Cert.G 1 [1] [67, 86, 45, 63, 13, 161, 166] [58, 21, 83, 99, 81, 169, 77, 153]

theorem c36 : certCheck 181 D ILN 36 k36 = true := by decide +kernel

def k37 : Cert :=
  Cert.G 1 [88, 92, 1] [79, 111, 136, 110, 136] [168, 119, 158, 161, 97, 13]

theorem c37 : certCheck 181 D ILN 37 k37 = true := by decide +kernel

def k38 : Cert :=
  Cert.G 1 [110, 1] [34, 25, 3, 12, 22, 115] [29, 131, 84, 98, 147, 178, 2]

theorem c38 : certCheck 181 D ILN 38 k38 = true := by decide +kernel

def k39 : Cert :=
  Cert.G 1 [1] [21, 2, 121, 145, 35, 149, 170] [43, 117, 85, 136, 128, 162, 178, 2]

theorem c39 : certCheck 181 D ILN 39 k39 = true := by decide +kernel

def k40 : Cert :=
  Cert.G 1 [1] [84, 136, 161, 57, 127, 60, 48] [149, 90, 71, 48, 50, 95, 89, 166]

theorem c40 : certCheck 181 D ILN 40 k40 = true := by decide +kernel

def k41 : Cert :=
  Cert.G 1 [1] [162, 5, 133, 120, 17, 122, 8] [93, 21, 96, 53, 100, 82, 142, 125]

theorem c41 : certCheck 181 D ILN 41 k41 = true := by decide +kernel

def k42 : Cert :=
  Cert.F [([149, 1], []), ([157, 1], []), ([176, 1], []), ([55, 100, 1], [(1, [104, 60])]), ([142, 51, 179, 1], [(1, [127, 95, 143])])]
      [[(0, [([32], [3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([24], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([5], [4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([32], [0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0])]), (1, [([24], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])]), (2, [([5], [0, 0, 4, 2, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([32], [0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0])]), (1, [([24], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])]), (2, [([5], [0, 0, 0, 0, 4, 2, 0, 0, 0, 0, 0])])],
       [(3, [([33, 49], [0, 0, 0, 0, 0, 0, 3, 3, 1, 0, 0]), ([48, 132], [0, 0, 0, 0, 0, 0, 3, 1, 3, 0, 0])])],
       [(4, [([106, 90, 2], [0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4]), ([35, 162, 4], [0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4]), ([42, 110, 175], [0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4])])]]

theorem c42 : certCheck 181 D ILN 42 k42 = true := by decide +kernel

def k43 : Cert :=
  Cert.G 1 [33, 1] [154, 19, 58, 139, 89, 89] [44, 160, 95, 99, 66, 97, 180]

theorem c43 : certCheck 181 D ILN 43 k43 = true := by decide +kernel

def k44 : Cert :=
  Cert.G 1 [170, 1] [167, 58, 36, 109, 72, 166] [13, 104, 167, 44, 123, 81, 156]

theorem c44 : certCheck 181 D ILN 44 k44 = true := by decide +kernel

def k45 : Cert :=
  Cert.G 1 [98, 51, 1] [112, 142, 88, 1, 180] [1, 14, 170, 162, 75, 19]

theorem c45 : certCheck 181 D ILN 45 k45 = true := by decide +kernel

def k46 : Cert :=
  Cert.G 1 [118, 1] [62, 73, 80, 151, 21, 130] [116, 124, 133, 67, 144, 76, 111]

theorem c46 : certCheck 181 D ILN 46 k46 = true := by decide +kernel

def k47 : Cert :=
  Cert.G 1 [132, 1] [54, 168, 60, 123, 36, 16] [65, 33, 165, 138, 77, 152, 72]

theorem c47 : certCheck 181 D ILN 47 k47 = true := by decide +kernel

def k48 : Cert :=
  Cert.G 1 [81, 71, 1] [118, 23, 172, 93, 89] [134, 175, 19, 14, 49, 80]

theorem c48 : certCheck 181 D ILN 48 k48 = true := by decide +kernel

def k49 : Cert :=
  Cert.G 1 [151, 1] [68, 76, 179, 149, 36, 108] [105, 170, 40, 167, 76, 38, 75]

theorem c49 : certCheck 181 D ILN 49 k49 = true := by decide +kernel

def k50 : Cert :=
  Cert.G 1 [1] [33, 10, 112, 160, 74, 177, 129] [179, 30, 158, 105, 1, 173, 111, 149]

theorem c50 : certCheck 181 D ILN 50 k50 = true := by decide +kernel

def k51 : Cert :=
  Cert.G 1 [1] [38, 162, 164, 157, 50, 60, 18] [171, 157, 144, 128, 158, 31, 161, 116]

theorem c51 : certCheck 181 D ILN 51 k51 = true := by decide +kernel

def k52 : Cert :=
  Cert.G 1 [64, 1] [64, 46, 49, 145, 56, 18] [74, 81, 171, 33, 142, 73, 163]

theorem c52 : certCheck 181 D ILN 52 k52 = true := by decide +kernel

def k53 : Cert :=
  Cert.G 1 [178, 1] [95, 157, 67, 164, 139, 54] [90, 102, 0, 131, 117, 103, 4]

theorem c53 : certCheck 181 D ILN 53 k53 = true := by decide +kernel

def k54 : Cert :=
  Cert.G 1 [62, 1] [38, 118, 116, 28, 62, 159] [170, 22, 4, 75, 19, 168, 99]

theorem c54 : certCheck 181 D ILN 54 k54 = true := by decide +kernel

def k55 : Cert :=
  Cert.F [([68, 1], []), ([76, 1], []), ([148, 1], []), ([87, 146, 1], [(1, [44, 13])]), ([136, 55, 142, 1], [(1, [66, 3, 32])])]
      [[(0, [([113], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([105], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([33], [3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([113], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([105], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([33], [0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([113], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])]), (1, [([105], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])]), (2, [([33], [0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0])])],
       [(3, [([111, 89], [0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0]), ([105, 92], [0, 0, 0, 0, 0, 0, 3, 0, 4, 0, 0])])],
       [(4, [([39, 35, 111], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]), ([1, 139, 125], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]), ([180, 7, 126], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2])])]]

theorem c55 : certCheck 181 D ILN 55 k55 = true := by decide +kernel

def k56 : Cert :=
  Cert.G 1 [11, 1] [109, 170, 126, 45, 78, 54] [119, 147, 93, 57, 124, 100, 106]

theorem c56 : certCheck 181 D ILN 56 k56 = true := by decide +kernel

def k57 : Cert :=
  Cert.G 1 [1] [62, 4, 9, 58, 148, 12, 128] [42, 128, 17, 13, 61, 20, 17, 28]

theorem c57 : certCheck 181 D ILN 57 k57 = true := by decide +kernel

def k58 : Cert :=
  Cert.G 1 [71, 1] [23, 110, 104, 86, 145, 79] [86, 91, 30, 15, 165, 116, 23]

theorem c58 : certCheck 181 D ILN 58 k58 = true := by decide +kernel

def k59 : Cert :=
  Cert.G 1 [169, 1] [97, 116, 165, 0, 140, 8] [58, 65, 137, 150, 62, 77, 164]

theorem c59 : certCheck 181 D ILN 59 k59 = true := by decide +kernel

def k60 : Cert :=
  Cert.G 1 [1] [2, 135, 155, 32, 58, 96, 63] [36, 10, 6, 128, 96, 1, 113, 67]

theorem c60 : certCheck 181 D ILN 60 k60 = true := by decide +kernel

def k61 : Cert :=
  Cert.G 1 [159, 1] [175, 38, 179, 48, 38, 143] [106, 167, 92, 161, 35, 33, 149]

theorem c61 : certCheck 181 D ILN 61 k61 = true := by decide +kernel

def k62 : Cert :=
  Cert.G 1 [91, 82, 1] [175, 140, 135, 164, 145] [124, 19, 4, 129, 79, 74]

theorem c62 : certCheck 181 D ILN 62 k62 = true := by decide +kernel

def k63 : Cert :=
  Cert.G 1 [153, 1] [28, 73, 133, 169, 74, 126] [153, 106, 179, 71, 146, 61, 48]

theorem c63 : certCheck 181 D ILN 63 k63 = true := by decide +kernel

def k64 : Cert :=
  Cert.G 1 [12, 2, 1] [143, 168, 173, 98, 55] [128, 93, 74, 130, 56, 101]

theorem c64 : certCheck 181 D ILN 64 k64 = true := by decide +kernel

def k65 : Cert :=
  Cert.G 1 [173, 139, 1] [116, 123, 115, 147, 94] [177, 82, 1, 137, 41, 27]

theorem c65 : certCheck 181 D ILN 65 k65 = true := by decide +kernel

def k66 : Cert :=
  Cert.G 1 [104, 1] [164, 127, 163, 0, 34, 60] [65, 43, 1, 107, 43, 26, 69]

theorem c66 : certCheck 181 D ILN 66 k66 = true := by decide +kernel

def k67 : Cert :=
  Cert.G 1 [13, 1] [172, 119, 27, 92, 125, 100] [26, 104, 177, 20, 97, 0, 72]

theorem c67 : certCheck 181 D ILN 67 k67 = true := by decide +kernel

def k68 : Cert :=
  Cert.G 1 [112, 19, 1] [138, 88, 141, 143, 175] [123, 0, 174, 179, 48, 90]

theorem c68 : certCheck 181 D ILN 68 k68 = true := by decide +kernel

def k69 : Cert :=
  Cert.G 1 [86, 1] [57, 6, 67, 48, 1, 137] [145, 81, 147, 17, 125, 4, 132]

theorem c69 : certCheck 181 D ILN 69 k69 = true := by decide +kernel

def k70 : Cert :=
  Cert.G 1 [1] [129, 143, 158, 115, 162, 173, 29] [85, 81, 96, 149, 107, 4, 66, 175]

theorem c70 : certCheck 181 D ILN 70 k70 = true := by decide +kernel

def k71 : Cert :=
  Cert.G 1 [6, 1] [6, 150, 94, 33, 177, 70] [138, 52, 178, 1, 36, 1, 86]

theorem c71 : certCheck 181 D ILN 71 k71 = true := by decide +kernel

def k72 : Cert :=
  Cert.G 1 [1] [90, 143, 60, 67, 116, 171, 74] [56, 134, 52, 173, 179, 107, 109, 74]

theorem c72 : certCheck 181 D ILN 72 k72 = true := by decide +kernel

def k73 : Cert :=
  Cert.G 1 [1] [57, 155, 113, 140, 129, 129, 22] [31, 53, 65, 5, 141, 151, 113, 143]

theorem c73 : certCheck 181 D ILN 73 k73 = true := by decide +kernel

def k74 : Cert :=
  Cert.G 1 [1] [108, 130, 57, 29, 106, 79, 20] [148, 48, 51, 19, 75, 128, 169, 160]

theorem c74 : certCheck 181 D ILN 74 k74 = true := by decide +kernel

def k75 : Cert :=
  Cert.G 1 [1] [88, 122, 92, 173, 0, 107, 100] [23, 40, 146, 15, 158, 97, 20, 18]

theorem c75 : certCheck 181 D ILN 75 k75 = true := by decide +kernel

def k76 : Cert :=
  Cert.G 1 [1] [54, 10, 70, 93, 156, 169, 89] [71, 78, 66, 66, 1, 100, 48, 153]

theorem c76 : certCheck 181 D ILN 76 k76 = true := by decide +kernel

def k77 : Cert :=
  Cert.G 1 [37, 1] [95, 72, 75, 131, 145, 26] [125, 87, 61, 55, 136, 165, 124]

theorem c77 : certCheck 181 D ILN 77 k77 = true := by decide +kernel

def k78 : Cert :=
  Cert.G 1 [141, 157, 1] [146, 83, 0, 43, 45] [53, 47, 54, 104, 9, 47]

theorem c78 : certCheck 181 D ILN 78 k78 = true := by decide +kernel

def k79 : Cert :=
  Cert.G 1 [58, 123, 1] [88, 29, 176, 59, 13] [53, 84, 147, 66, 140, 60]

theorem c79 : certCheck 181 D ILN 79 k79 = true := by decide +kernel

def k80 : Cert :=
  Cert.G 1 [27, 36, 1] [75, 122, 26, 32, 47] [10, 14, 64, 116, 40, 22]

theorem c80 : certCheck 181 D ILN 80 k80 = true := by decide +kernel

def k81 : Cert :=
  Cert.G 1 [1] [164, 177, 174, 110, 82, 39, 117] [171, 117, 65, 18, 149, 94, 148, 102]

theorem c81 : certCheck 181 D ILN 81 k81 = true := by decide +kernel

def k82 : Cert :=
  Cert.G 1 [1] [170, 18, 100, 66, 21, 3, 66] [86, 148, 136, 126, 25, 44, 169, 38]

theorem c82 : certCheck 181 D ILN 82 k82 = true := by decide +kernel

def k83 : Cert :=
  Cert.G 1 [1] [125, 166, 41, 13, 129, 51, 92] [83, 44, 102, 178, 4, 55, 47, 26]

theorem c83 : certCheck 181 D ILN 83 k83 = true := by decide +kernel

def k84 : Cert :=
  Cert.G 1 [73, 1] [87, 161, 94, 6, 140, 140] [8, 147, 156, 131, 12, 50, 59]

theorem c84 : certCheck 181 D ILN 84 k84 = true := by decide +kernel

def k85 : Cert :=
  Cert.G 1 [1] [24, 60, 124, 83, 143, 111, 123] [119, 161, 92, 166, 151, 155, 110, 132]

theorem c85 : certCheck 181 D ILN 85 k85 = true := by decide +kernel

def k86 : Cert :=
  Cert.G 1 [1] [117, 66, 147, 32, 112, 1, 68] [95, 74, 116, 168, 79, 16, 159, 97]

theorem c86 : certCheck 181 D ILN 86 k86 = true := by decide +kernel

def k87 : Cert :=
  Cert.G 1 [1] [145, 119, 29, 133, 88, 60, 175] [6, 43, 64, 33, 141, 129, 155, 123]

theorem c87 : certCheck 181 D ILN 87 k87 = true := by decide +kernel

def k88 : Cert :=
  Cert.G 1 [1] [79, 97, 36, 75, 150, 37, 176] [155, 19, 153, 83, 129, 24, 87, 74]

theorem c88 : certCheck 181 D ILN 88 k88 = true := by decide +kernel

def certs0 : List (ℕ × Cert) := [(2, k2), (3, k3), (4, k4), (5, k5), (6, k6), (7, k7), (8, k8), (9, k9), (10, k10), (11, k11), (12, k12), (13, k13), (14, k14), (15, k15), (16, k16), (17, k17), (18, k18), (19, k19), (20, k20), (21, k21), (22, k22), (23, k23), (24, k24), (25, k25), (26, k26), (27, k27), (28, k28), (29, k29), (30, k30), (31, k31), (32, k32), (33, k33), (34, k34), (35, k35), (36, k36), (37, k37), (38, k38), (39, k39), (40, k40), (41, k41), (42, k42), (43, k43), (44, k44), (45, k45), (46, k46), (47, k47), (48, k48), (49, k49), (50, k50), (51, k51), (52, k52), (53, k53), (54, k54), (55, k55), (56, k56), (57, k57), (58, k58), (59, k59), (60, k60), (61, k61), (62, k62), (63, k63), (64, k64), (65, k65), (66, k66), (67, k67), (68, k68), (69, k69), (70, k70), (71, k71), (72, k72), (73, k73), (74, k74), (75, k75), (76, k76), (77, k77), (78, k78), (79, k79), (80, k80), (81, k81), (82, k82), (83, k83), (84, k84), (85, k85), (86, k86), (87, k87), (88, k88)]

theorem ok0 : certs0.all (fun p => certCheck 181 D ILN p.1 p.2) = true := by
  simp only [certs0, List.all_cons, List.all_nil, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31, c32, c33, c34, c35, c36, c37, c38, c39, c40, c41, c42, c43, c44, c45, c46, c47, c48, c49, c50, c51, c52, c53, c54, c55, c56, c57, c58, c59, c60, c61, c62, c63, c64, c65, c66, c67, c68, c69, c70, c71, c72, c73, c74, c75, c76, c77, c78, c79, c80, c81, c82, c83, c84, c85, c86, c87, c88, Bool.and_self]

end X2Y5Z7.SymbolSets.Q181
