/-
Generated by computer; every fact used is proved in Lean.
-/
module

public import X2Y5Z7.SymbolSets.Q181.C0

@[expose] public section

/-! # Proposition 5.3 at `q = 181`: certificates for `η = 89 … 150` (2 R, 56 G, 4 F) -/

namespace X2Y5Z7.SymbolSets.Q181

open X2Y5Z7.SymbolSets

def k89 : Cert :=
  Cert.F [([4, 1], []), ([67, 1], []), ([117, 1], []), ([140, 170, 1], [(1, [155, 87])]), ([136, 77, 41, 1], [(1, [174, 34, 22])])]
      [[(0, [([177], [4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([114], [3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([64], [3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([177], [0, 0, 4, 2, 0, 0, 0, 0, 0, 0, 0])]), (1, [([114], [0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0])]), (2, [([64], [0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([177], [0, 0, 0, 0, 4, 2, 0, 0, 0, 0, 0])]), (1, [([114], [0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0])]), (2, [([64], [0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0])])],
       [(3, [([62, 17], [0, 0, 0, 0, 0, 0, 4, 0, 3, 0, 0]), ([130, 164], [0, 0, 0, 0, 0, 0, 4, 3, 0, 0, 0])])],
       [(4, [([133, 74, 18], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]), ([112, 119, 76], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]), ([76, 169, 87], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3])])]]

theorem c89 : certCheck 181 D ILN 89 k89 = true := by decide +kernel

def k90 : Cert :=
  Cert.G 1 [72, 134, 1] [126, 153, 64, 173, 119] [113, 112, 137, 77, 147, 44]

theorem c90 : certCheck 181 D ILN 90 k90 = true := by decide +kernel

def k91 : Cert :=
  Cert.G 1 [1] [8, 120, 154, 94, 51, 172, 164] [103, 43, 84, 18, 113, 41, 26, 6]

theorem c91 : certCheck 181 D ILN 91 k91 = true := by decide +kernel

def k92 : Cert :=
  Cert.G 1 [1] [22, 155, 171, 142, 111, 1, 99] [146, 148, 56, 27, 1, 42, 99, 47]

theorem c92 : certCheck 181 D ILN 92 k92 = true := by decide +kernel

def k93 : Cert :=
  Cert.G 1 [24, 1] [78, 57, 169, 108, 82, 73] [82, 25, 94, 118, 31, 150, 117]

theorem c93 : certCheck 181 D ILN 93 k93 = true := by decide +kernel

def k94 : Cert :=
  Cert.G 1 [163, 1] [136, 170, 144, 132, 50, 93] [107, 12, 59, 168, 168, 171, 103]

theorem c94 : certCheck 181 D ILN 94 k94 = true := by decide +kernel

def k95 : Cert :=
  Cert.G 1 [101, 1] [163, 48, 30, 91, 114, 10] [112, 35, 109, 49, 26, 95, 84]

theorem c95 : certCheck 181 D ILN 95 k95 = true := by decide +kernel

def k96 : Cert :=
  Cert.G 1 [179, 1] [49, 96, 177, 63, 17, 78] [58, 155, 175, 132, 100, 39, 123]

theorem c96 : certCheck 181 D ILN 96 k96 = true := by decide +kernel

def k97 : Cert :=
  Cert.G 1 [171, 129, 1] [166, 137, 175, 24, 174] [179, 55, 109, 34, 12, 34]

theorem c97 : certCheck 181 D ILN 97 k97 = true := by decide +kernel

def k98 : Cert :=
  Cert.G 1 [158, 1] [69, 19, 58, 19, 32, 137] [113, 142, 35, 161, 176, 107, 11]

theorem c98 : certCheck 181 D ILN 98 k98 = true := by decide +kernel

def k99 : Cert :=
  Cert.G 1 [108, 1] [76, 26, 64, 106, 179, 86] [47, 80, 125, 80, 99, 84, 136]

theorem c99 : certCheck 181 D ILN 99 k99 = true := by decide +kernel

def k100 : Cert :=
  Cert.G 1 [1] [86, 1, 141, 126, 28, 178, 160] [133, 158, 160, 114, 48, 46, 126, 96]

theorem c100 : certCheck 181 D ILN 100 k100 = true := by decide +kernel

def k101 : Cert :=
  Cert.G 1 [177, 1] [26, 112, 77, 48, 97, 97] [49, 39, 51, 59, 128, 101, 79]

theorem c101 : certCheck 181 D ILN 101 k101 = true := by decide +kernel

def k102 : Cert :=
  Cert.G 1 [157, 77, 1] [51, 176, 81, 79, 160] [0, 83, 6, 107, 52, 178]

theorem c102 : certCheck 181 D ILN 102 k102 = true := by decide +kernel

def k103 : Cert :=
  Cert.G 1 [1] [56, 119, 148, 149, 67, 20, 79] [178, 137, 106, 143, 7, 4, 104, 105]

theorem c103 : certCheck 181 D ILN 103 k103 = true := by decide +kernel

def k104 : Cert :=
  Cert.G 1 [70, 19, 1] [79, 8, 34, 106, 103] [89, 106, 60, 76, 84, 3]

theorem c104 : certCheck 181 D ILN 104 k104 = true := by decide +kernel

def k105 : Cert :=
  Cert.G 1 [15, 1, 1] [127, 163, 38, 137, 26] [107, 63, 37, 162, 169, 166]

theorem c105 : certCheck 181 D ILN 105 k105 = true := by decide +kernel

def k106 : Cert :=
  Cert.G 1 [116, 158, 1] [102, 44, 105, 134, 109] [93, 73, 51, 118, 22, 126]

theorem c106 : certCheck 181 D ILN 106 k106 = true := by decide +kernel

def k107 : Cert :=
  Cert.G 1 [18, 40, 1] [172, 123, 96, 29, 72] [133, 166, 144, 56, 123, 166]

theorem c107 : certCheck 181 D ILN 107 k107 = true := by decide +kernel

def k108 : Cert :=
  Cert.G 1 [1] [65, 41, 69, 165, 142, 13, 76] [74, 7, 170, 162, 180, 158, 4, 109]

theorem c108 : certCheck 181 D ILN 108 k108 = true := by decide +kernel

def k109 : Cert :=
  Cert.G 1 [139, 1] [6, 40, 172, 66, 97, 157] [17, 133, 63, 63, 125, 133, 40]

theorem c109 : certCheck 181 D ILN 109 k109 = true := by decide +kernel

def k110 : Cert :=
  Cert.G 1 [42, 107, 1] [140, 15, 158, 28, 79] [55, 151, 11, 141, 75, 68]

theorem c110 : certCheck 181 D ILN 110 k110 = true := by decide +kernel

def k111 : Cert :=
  Cert.G 1 [1] [164, 163, 180, 175, 1, 161, 128] [168, 149, 180, 169, 177, 173, 87, 62]

theorem c111 : certCheck 181 D ILN 111 k111 = true := by decide +kernel

def k112 : Cert :=
  Cert.G 1 [1] [34, 96, 12, 123, 103, 9, 76] [96, 111, 106, 135, 35, 148, 177, 13]

theorem c112 : certCheck 181 D ILN 112 k112 = true := by decide +kernel

def k113 : Cert :=
  Cert.G 1 [1] [36, 33, 96, 97, 133, 173, 26] [7, 129, 19, 138, 121, 132, 24, 123]

theorem c113 : certCheck 181 D ILN 113 k113 = true := by decide +kernel

def k114 : Cert :=
  Cert.G 1 [26, 1] [78, 66, 132, 20, 150, 41] [127, 126, 31, 154, 100, 25, 117]

theorem c114 : certCheck 181 D ILN 114 k114 = true := by decide +kernel

def k115 : Cert :=
  Cert.G 1 [112, 15, 1] [73, 114, 161, 69, 69] [114, 61, 139, 114, 98, 156]

theorem c115 : certCheck 181 D ILN 115 k115 = true := by decide +kernel

def k116 : Cert :=
  Cert.F [([35, 1], []), ([43, 1], []), ([63, 1], []), ([93, 20, 1], [(1, [51, 168])]), ([97, 178, 57, 1], [(1, [113, 50, 68])])]
      [[(0, [([146], [3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([138], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([118], [3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([146], [0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0])]), (1, [([138], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])]), (2, [([118], [0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([146], [0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0])]), (1, [([138], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])]), (2, [([118], [0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0])])],
       [(3, [([47, 62], [0, 0, 0, 0, 0, 0, 0, 4, 3, 0, 0]), ([114, 119], [0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0])])],
       [(4, [([149, 121, 18], [0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0]), ([75, 44, 23], [0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0]), ([81, 16, 140], [0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0])])]]

theorem c116 : certCheck 181 D ILN 116 k116 = true := by decide +kernel

def k117 : Cert :=
  Cert.G 1 [146, 112, 1] [143, 5, 26, 15, 54] [37, 0, 84, 63, 27, 73]

theorem c117 : certCheck 181 D ILN 117 k117 = true := by decide +kernel

def k118 : Cert :=
  Cert.G 1 [29, 1] [37, 14, 93, 148, 145, 65] [4, 122, 69, 172, 16, 33, 109]

theorem c118 : certCheck 181 D ILN 118 k118 = true := by decide +kernel

def k119 : Cert :=
  Cert.G 1 [114, 1] [127, 28, 159, 151, 102, 173] [161, 80, 151, 108, 104, 92, 104]

theorem c119 : certCheck 181 D ILN 119 k119 = true := by decide +kernel

def k120 : Cert :=
  Cert.R [19, 93, 111, 120]

theorem c120 : certCheck 181 D ILN 120 k120 = true := by decide +kernel

def k121 : Cert :=
  Cert.G 1 [130, 176, 1] [59, 167, 13, 14, 171] [159, 89, 38, 14, 162, 176]

theorem c121 : certCheck 181 D ILN 121 k121 = true := by decide +kernel

def k122 : Cert :=
  Cert.G 1 [126, 1] [89, 39, 28, 122, 74, 107] [163, 109, 43, 90, 153, 54, 84]

theorem c122 : certCheck 181 D ILN 122 k122 = true := by decide +kernel

def k123 : Cert :=
  Cert.G 1 [29, 152, 1] [112, 162, 161, 29, 22] [180, 136, 78, 110, 124, 164]

theorem c123 : certCheck 181 D ILN 123 k123 = true := by decide +kernel

def k124 : Cert :=
  Cert.G 1 [92, 1] [63, 167, 13, 18, 95, 101] [11, 134, 170, 46, 157, 16, 72]

theorem c124 : certCheck 181 D ILN 124 k124 = true := by decide +kernel

def k125 : Cert :=
  Cert.G 1 [1] [117, 8, 102, 100, 121, 3, 19] [10, 141, 169, 153, 64, 104, 108, 71]

theorem c125 : certCheck 181 D ILN 125 k125 = true := by decide +kernel

def k126 : Cert :=
  Cert.G 1 [44, 1] [83, 28, 175, 30, 112, 50] [62, 172, 63, 134, 60, 80, 71]

theorem c126 : certCheck 181 D ILN 126 k126 = true := by decide +kernel

def k127 : Cert :=
  Cert.G 1 [1] [176, 161, 0, 176, 43, 21, 30] [28, 173, 124, 167, 148, 67, 91, 165]

theorem c127 : certCheck 181 D ILN 127 k127 = true := by decide +kernel

def k128 : Cert :=
  Cert.R [13, 46, 59, 82]

theorem c128 : certCheck 181 D ILN 128 k128 = true := by decide +kernel

def k129 : Cert :=
  Cert.G 1 [142, 1] [103, 47, 58, 137, 88, 34] [36, 54, 25, 109, 70, 140, 79]

theorem c129 : certCheck 181 D ILN 129 k129 = true := by decide +kernel

def k130 : Cert :=
  Cert.G 1 [1] [50, 138, 57, 157, 38, 49, 81] [149, 116, 16, 0, 52, 8, 32, 52]

theorem c130 : certCheck 181 D ILN 130 k130 = true := by decide +kernel

def k131 : Cert :=
  Cert.G 1 [160, 1] [61, 164, 88, 156, 167, 5] [38, 84, 88, 45, 7, 52, 120]

theorem c131 : certCheck 181 D ILN 131 k131 = true := by decide +kernel

def k132 : Cert :=
  Cert.G 1 [133, 1] [11, 133, 125, 54, 18, 67] [67, 121, 172, 138, 37, 79, 131]

theorem c132 : certCheck 181 D ILN 132 k132 = true := by decide +kernel

def k133 : Cert :=
  Cert.G 1 [34, 11, 1] [39, 112, 145, 149, 111] [27, 80, 61, 167, 81, 180]

theorem c133 : certCheck 181 D ILN 133 k133 = true := by decide +kernel

def k134 : Cert :=
  Cert.G 1 [1] [22, 175, 135, 34, 48, 133, 102] [43, 78, 8, 10, 141, 169, 134, 180]

theorem c134 : certCheck 181 D ILN 134 k134 = true := by decide +kernel

def k135 : Cert :=
  Cert.G 1 [1] [113, 50, 89, 1, 17, 14, 126] [66, 178, 14, 6, 36, 119, 112, 82]

theorem c135 : certCheck 181 D ILN 135 k135 = true := by decide +kernel

def k136 : Cert :=
  Cert.G 1 [89, 1] [163, 161, 5, 107, 43, 31] [133, 8, 3, 63, 6, 86, 47]

theorem c136 : certCheck 181 D ILN 136 k136 = true := by decide +kernel

def k137 : Cert :=
  Cert.G 1 [1] [23, 85, 91, 104, 92, 18, 59] [66, 68, 171, 142, 81, 86, 33, 17]

theorem c137 : certCheck 181 D ILN 137 k137 = true := by decide +kernel

def k138 : Cert :=
  Cert.G 1 [146, 1] [28, 67, 157, 104, 136, 164] [143, 74, 137, 138, 178, 24, 149]

theorem c138 : certCheck 181 D ILN 138 k138 = true := by decide +kernel

def k139 : Cert :=
  Cert.G 1 [50, 1] [158, 86, 149, 18, 101, 156] [90, 49, 142, 37, 167, 143, 178]

theorem c139 : certCheck 181 D ILN 139 k139 = true := by decide +kernel

def k140 : Cert :=
  Cert.G 1 [1] [76, 71, 179, 55, 106, 84, 5] [67, 157, 45, 38, 136, 36, 87, 104]

theorem c140 : certCheck 181 D ILN 140 k140 = true := by decide +kernel

def k141 : Cert :=
  Cert.G 1 [66, 1] [42, 143, 112, 19, 57, 11] [111, 88, 180, 77, 55, 167, 76]

theorem c141 : certCheck 181 D ILN 141 k141 = true := by decide +kernel

def k142 : Cert :=
  Cert.G 1 [111, 1] [150, 129, 123, 62, 127, 151] [88, 62, 134, 51, 68, 83, 114]

theorem c142 : certCheck 181 D ILN 142 k142 = true := by decide +kernel

def k143 : Cert :=
  Cert.F [([9, 1], []), ([145, 1], []), ([161, 1], []), ([123, 95, 1], [(1, [59, 167])]), ([69, 173, 170, 1], [(1, [121, 173, 112])])]
      [[(0, [([172], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([36], [3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([20], [3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([172], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])]), (1, [([36], [0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0])]), (2, [([20], [0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([172], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])]), (1, [([36], [0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0])]), (2, [([20], [0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0])])],
       [(3, [([60, 82], [0, 0, 0, 0, 0, 0, 3, 2, 2, 0, 0]), ([26, 99], [0, 0, 0, 0, 0, 0, 3, 2, 2, 0, 0])])],
       [(4, [([94, 162, 18], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]), ([113, 89, 75], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]), ([166, 111, 88], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3])])]]

theorem c143 : certCheck 181 D ILN 143 k143 = true := by decide +kernel

def k144 : Cert :=
  Cert.G 1 [174, 1] [144, 71, 121, 21, 96, 96] [168, 33, 28, 69, 60, 7, 116]

theorem c144 : certCheck 181 D ILN 144 k144 = true := by decide +kernel

def k145 : Cert :=
  Cert.F [([42, 1], []), ([60, 1], []), ([79, 1], []), ([24, 5, 1], [(1, [74, 102])]), ([151, 142, 32, 1], [(1, [49, 96, 122])])]
      [[(0, [([139], [2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([121], [2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([102], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([139], [0, 0, 2, 4, 0, 0, 0, 0, 0, 0, 0])]), (1, [([121], [0, 0, 2, 4, 0, 0, 0, 0, 0, 0, 0])]), (2, [([102], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([139], [0, 0, 0, 0, 2, 4, 0, 0, 0, 0, 0])]), (1, [([121], [0, 0, 0, 0, 2, 4, 0, 0, 0, 0, 0])]), (2, [([102], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])])],
       [(3, [([97, 86], [0, 0, 0, 0, 0, 0, 3, 3, 1, 0, 0]), ([79, 95], [0, 0, 0, 0, 0, 0, 3, 1, 3, 0, 0])])],
       [(4, [([168, 99, 36], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]), ([168, 37, 156], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]), ([175, 45, 170], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2])])]]

theorem c145 : certCheck 181 D ILN 145 k145 = true := by decide +kernel

def k146 : Cert :=
  Cert.G 1 [32, 1] [14, 168, 127, 141, 21, 10] [169, 59, 133, 163, 127, 80, 168]

theorem c146 : certCheck 181 D ILN 146 k146 = true := by decide +kernel

def k147 : Cert :=
  Cert.G 1 [98, 1] [94, 63, 52, 128, 100, 142] [39, 47, 65, 150, 118, 52, 124]

theorem c147 : certCheck 181 D ILN 147 k147 = true := by decide +kernel

def k148 : Cert :=
  Cert.G 1 [112, 1] [18, 140, 29, 129, 68, 23] [103, 101, 106, 67, 144, 91, 107]

theorem c148 : certCheck 181 D ILN 148 k148 = true := by decide +kernel

def k149 : Cert :=
  Cert.G 1 [1] [120, 176, 20, 93, 43, 114, 33] [137, 60, 3, 43, 154, 71, 156, 72]

theorem c149 : certCheck 181 D ILN 149 k149 = true := by decide +kernel

def k150 : Cert :=
  Cert.G 1 [47, 1] [73, 68, 15, 129, 28, 65] [50, 30, 78, 51, 149, 111, 54]

theorem c150 : certCheck 181 D ILN 150 k150 = true := by decide +kernel

def certs1 : List (ℕ × Cert) := [(89, k89), (90, k90), (91, k91), (92, k92), (93, k93), (94, k94), (95, k95), (96, k96), (97, k97), (98, k98), (99, k99), (100, k100), (101, k101), (102, k102), (103, k103), (104, k104), (105, k105), (106, k106), (107, k107), (108, k108), (109, k109), (110, k110), (111, k111), (112, k112), (113, k113), (114, k114), (115, k115), (116, k116), (117, k117), (118, k118), (119, k119), (120, k120), (121, k121), (122, k122), (123, k123), (124, k124), (125, k125), (126, k126), (127, k127), (128, k128), (129, k129), (130, k130), (131, k131), (132, k132), (133, k133), (134, k134), (135, k135), (136, k136), (137, k137), (138, k138), (139, k139), (140, k140), (141, k141), (142, k142), (143, k143), (144, k144), (145, k145), (146, k146), (147, k147), (148, k148), (149, k149), (150, k150)]

theorem ok1 : certs1.all (fun p => certCheck 181 D ILN p.1 p.2) = true := by
  simp only [certs1, List.all_cons, List.all_nil, c89, c90, c91, c92, c93, c94, c95, c96, c97, c98, c99, c100, c101, c102, c103, c104, c105, c106, c107, c108, c109, c110, c111, c112, c113, c114, c115, c116, c117, c118, c119, c120, c121, c122, c123, c124, c125, c126, c127, c128, c129, c130, c131, c132, c133, c134, c135, c136, c137, c138, c139, c140, c141, c142, c143, c144, c145, c146, c147, c148, c149, c150, Bool.and_self]

end X2Y5Z7.SymbolSets.Q181
