/-
Generated by computer; every fact used is proved in Lean.
-/
module

public import X2Y5Z7.SymbolSets.Q181.C1

@[expose] public section

/-! # Proposition 5.3 at `q = 181`: certificates for `η = 151 … 180` (0 R, 28 G, 2 F) -/

namespace X2Y5Z7.SymbolSets.Q181

open X2Y5Z7.SymbolSets

def k151 : Cert :=
  Cert.F [([19, 1], []), ([75, 1], []), ([131, 1], []), ([4, 151, 1], [(1, [102, 138])]), ([160, 150, 23, 1], [(1, [140, 12, 44])])]
      [[(0, [([162], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([106], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([50], [2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([162], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([106], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])]), (2, [([50], [0, 0, 2, 4, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([162], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])]), (1, [([106], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])]), (2, [([50], [0, 0, 0, 0, 2, 4, 0, 0, 0, 0, 0])])],
       [(3, [([56, 70], [0, 0, 0, 0, 0, 0, 2, 4, 1, 0, 0]), ([155, 111], [0, 0, 0, 0, 0, 0, 2, 1, 4, 0, 0])])],
       [(4, [([6, 162, 29], [0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4]), ([112, 163, 74], [0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4]), ([40, 37, 78], [0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4])])]]

theorem c151 : certCheck 181 D ILN 151 k151 = true := by decide +kernel

def k152 : Cert :=
  Cert.G 1 [103, 1] [118, 32, 142, 106, 44, 18] [164, 99, 52, 128, 119, 149, 7]

theorem c152 : certCheck 181 D ILN 152 k152 = true := by decide +kernel

def k153 : Cert :=
  Cert.G 1 [156, 1] [160, 87, 32, 108, 49, 165] [128, 165, 120, 30, 26, 153, 22]

theorem c153 : certCheck 181 D ILN 153 k153 = true := by decide +kernel

def k154 : Cert :=
  Cert.G 1 [69, 56, 1] [66, 27, 66, 169, 173] [86, 33, 72, 10, 76, 113]

theorem c154 : certCheck 181 D ILN 154 k154 = true := by decide +kernel

def k155 : Cert :=
  Cert.G 1 [1] [170, 105, 179, 153, 153, 110, 42] [41, 14, 35, 20, 29, 89, 115, 3]

theorem c155 : certCheck 181 D ILN 155 k155 = true := by decide +kernel

def k156 : Cert :=
  Cert.G 1 [69, 1] [81, 159, 68, 67, 137, 23] [157, 57, 107, 59, 130, 2, 155]

theorem c156 : certCheck 181 D ILN 156 k156 = true := by decide +kernel

def k157 : Cert :=
  Cert.G 1 [113, 76, 1] [27, 101, 92, 115, 171] [162, 9, 42, 107, 6, 147]

theorem c157 : certCheck 181 D ILN 157 k157 = true := by decide +kernel

def k158 : Cert :=
  Cert.G 1 [38, 1] [10, 105, 27, 48, 119, 95] [15, 98, 27, 130, 28, 1, 25]

theorem c158 : certCheck 181 D ILN 158 k158 = true := by decide +kernel

def k159 : Cert :=
  Cert.G 1 [1] [84, 159, 125, 156, 145, 118, 133] [3, 157, 176, 96, 0, 141, 109, 48]

theorem c159 : certCheck 181 D ILN 159 k159 = true := by decide +kernel

def k160 : Cert :=
  Cert.G 1 [1] [70, 82, 86, 105, 14, 50, 43] [16, 127, 126, 64, 168, 106, 180, 83]

theorem c160 : certCheck 181 D ILN 160 k160 = true := by decide +kernel

def k161 : Cert :=
  Cert.G 1 [141, 1] [99, 135, 140, 53, 175, 170] [71, 114, 112, 63, 133, 83, 140]

theorem c161 : certCheck 181 D ILN 161 k161 = true := by decide +kernel

def k162 : Cert :=
  Cert.G 1 [1] [178, 138, 101, 15, 174, 172, 135] [3, 4, 66, 158, 95, 13, 154, 84]

theorem c162 : certCheck 181 D ILN 162 k162 = true := by decide +kernel

def k163 : Cert :=
  Cert.G 1 [1] [135, 12, 119, 26, 112, 144, 8] [154, 135, 167, 51, 38, 27, 95, 28]

theorem c163 : certCheck 181 D ILN 163 k163 = true := by decide +kernel

def k164 : Cert :=
  Cert.G 1 [1] [150, 173, 92, 74, 84, 98, 90] [125, 46, 116, 105, 156, 134, 136, 28]

theorem c164 : certCheck 181 D ILN 164 k164 = true := by decide +kernel

def k165 : Cert :=
  Cert.G 1 [1] [5, 45, 179, 125, 165, 142, 89] [90, 58, 121, 139, 133, 73, 43, 157]

theorem c165 : certCheck 181 D ILN 165 k165 = true := by decide +kernel

def k166 : Cert :=
  Cert.F [([56, 1], []), ([84, 1], []), ([94, 1], []), ([141, 20, 1], [(1, [84, 117])]), ([99, 78, 145, 1], [(1, [156, 129, 57])])]
      [[(0, [([125], [2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([97], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([87], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([125], [0, 0, 2, 4, 0, 0, 0, 0, 0, 0, 0])]), (1, [([97], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([87], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([125], [0, 0, 0, 0, 2, 4, 0, 0, 0, 0, 0])]), (1, [([97], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])]), (2, [([87], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])])],
       [(3, [([172, 90], [0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0]), ([170, 91], [0, 0, 0, 0, 0, 0, 3, 0, 4, 0, 0])])],
       [(4, [([49, 117, 47], [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1]), ([0, 101, 146], [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1]), ([168, 144, 169], [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1])])]]

theorem c166 : certCheck 181 D ILN 166 k166 = true := by decide +kernel

def k167 : Cert :=
  Cert.G 1 [1] [58, 27, 141, 93, 114, 180, 156] [164, 11, 69, 173, 33, 18, 114, 29]

theorem c167 : certCheck 181 D ILN 167 k167 = true := by decide +kernel

def k168 : Cert :=
  Cert.G 1 [114, 112, 1] [116, 0, 111, 82, 73] [174, 119, 18, 44, 96, 179]

theorem c168 : certCheck 181 D ILN 168 k168 = true := by decide +kernel

def k169 : Cert :=
  Cert.G 1 [41, 1] [150, 112, 71, 119, 167, 20] [36, 98, 118, 178, 177, 178, 95]

theorem c169 : certCheck 181 D ILN 169 k169 = true := by decide +kernel

def k170 : Cert :=
  Cert.G 1 [1] [69, 41, 168, 152, 114, 150, 70] [82, 131, 137, 46, 175, 84, 99, 95]

theorem c170 : certCheck 181 D ILN 170 k170 = true := by decide +kernel

def k171 : Cert :=
  Cert.G 1 [91, 1] [128, 52, 72, 128, 20, 40] [141, 31, 66, 10, 102, 134, 179]

theorem c171 : certCheck 181 D ILN 171 k171 = true := by decide +kernel

def k172 : Cert :=
  Cert.G 1 [73, 36, 1] [145, 117, 126, 17, 57] [35, 152, 39, 123, 107, 113]

theorem c172 : certCheck 181 D ILN 172 k172 = true := by decide +kernel

def k173 : Cert :=
  Cert.G 1 [111, 44, 1] [71, 116, 73, 111, 75] [62, 84, 179, 42, 176, 130]

theorem c173 : certCheck 181 D ILN 173 k173 = true := by decide +kernel

def k174 : Cert :=
  Cert.G 1 [1] [73, 78, 128, 75, 92, 161, 36] [66, 115, 74, 88, 68, 58, 55, 38]

theorem c174 : certCheck 181 D ILN 174 k174 = true := by decide +kernel

def k175 : Cert :=
  Cert.G 1 [1] [119, 110, 55, 130, 161, 101, 57] [119, 101, 61, 121, 130, 10, 103, 93]

theorem c175 : certCheck 181 D ILN 175 k175 = true := by decide +kernel

def k176 : Cert :=
  Cert.G 1 [143, 1] [86, 78, 14, 133, 105, 70] [128, 112, 161, 79, 36, 50, 49]

theorem c176 : certCheck 181 D ILN 176 k176 = true := by decide +kernel

def k177 : Cert :=
  Cert.G 1 [34, 35, 1] [16, 173, 110, 12, 73] [16, 4, 174, 11, 122, 74]

theorem c177 : certCheck 181 D ILN 177 k177 = true := by decide +kernel

def k178 : Cert :=
  Cert.G 1 [1] [136, 63, 125, 85, 82, 142, 4] [54, 38, 1, 13, 40, 138, 161, 68]

theorem c178 : certCheck 181 D ILN 178 k178 = true := by decide +kernel

def k179 : Cert :=
  Cert.G 1 [83, 1] [56, 56, 156, 105, 30, 58] [7, 44, 111, 5, 131, 39, 163]

theorem c179 : certCheck 181 D ILN 179 k179 = true := by decide +kernel

def k180 : Cert :=
  Cert.G 1 [1] [59, 128, 12, 166, 172, 75, 52] [36, 131, 13, 55, 133, 172, 61, 47]

theorem c180 : certCheck 181 D ILN 180 k180 = true := by decide +kernel

def certs2 : List (ℕ × Cert) := [(151, k151), (152, k152), (153, k153), (154, k154), (155, k155), (156, k156), (157, k157), (158, k158), (159, k159), (160, k160), (161, k161), (162, k162), (163, k163), (164, k164), (165, k165), (166, k166), (167, k167), (168, k168), (169, k169), (170, k170), (171, k171), (172, k172), (173, k173), (174, k174), (175, k175), (176, k176), (177, k177), (178, k178), (179, k179), (180, k180)]

theorem ok2 : certs2.all (fun p => certCheck 181 D ILN p.1 p.2) = true := by
  simp only [certs2, List.all_cons, List.all_nil, c151, c152, c153, c154, c155, c156, c157, c158, c159, c160, c161, c162, c163, c164, c165, c166, c167, c168, c169, c170, c171, c172, c173, c174, c175, c176, c177, c178, c179, c180, Bool.and_self]

end X2Y5Z7.SymbolSets.Q181
