import X2Y5Z7.FiveAdic.Primes
import Mathlib.NumberTheory.RamificationInertia.Valuation

/-! # The primes of `L₈` above 5 and the valuations of elements of `L₈` (Lemmas 2.4, 2.5)

`L₈` has three primes above 5, `p_A, p_B, p_C` (ramification indices 5, 1, 2), generated by the relative norms
`n_a = N_{L₂₄/L₈}(B_a)` for `a = 6, 3, 2` (Table 2 numbering; `SUnits/ClassData.lean`). With
`Y_q · n_a = ∏_{P_i ∣ q} B_i^{e(P_i/q)}` (`relY_q`, `Y_q` integral) and the product formula, `ν_{Q k}(n_a)` is the
exponent of `B_{k}` in that product; so `n_a ∈ Q k` exactly for the primes `Q k` in the product, and `Q k` lies
over `p = (n_a)`:

* over `p_A`: `P₆, P₇` (`Q 4, Q 5`); over `p_B`: `P₃, P₅` (`Q 1, Q 3`); over `p_C`: `P₂, P₄, P₈` (`Q 0, Q 2, Q 6`).

For `x ∈ L₈` and `Q k` over `p`, `ν_{Q k}(x) = e(Q k/p) ν_p(x)` (Mathlib's `valuation_liesOver`); hence
`ν_{Q k}(x) e_l = ν_{Q l}(x) e_k` for `Q k, Q l` over the same prime of `L₈` (`group_rel`): the normalized
valuation `ν/e` of an element of `L₈` is the same at all primes of `L₂₄` over one prime of `L₈`. -/

namespace X2Y5Z7.FiveAdic

open IsDedekindDomain NumberField Integral SUnits

noncomputable section

instance : IsScalarTower (𝓞 L8) (𝓞 L24) L24 := IsScalarTower.of_algebraMap_eq (fun _ => rfl)

/-! ## A generator of a prime of `L₈` -/

section Gen

variable (a : Fin 24) (v8 : Fin 8 → ℤ) (hnorm : Algebra.norm L8 (B a) = evF v8 / 820)
  (hB : Algebra.norm ℚ (B a) = 5)
include hnorm

theorem gen_isIntegral : IsIntegral ℤ (evF v8 / 820) := by
  rw [← hnorm]
  exact Algebra.isIntegral_norm L8 (B_isIntegral a)

/-- `n_a` as an element of `𝓞 L₈`. -/
def genInt : 𝓞 L8 := ⟨evF v8 / 820, gen_isIntegral a v8 hnorm⟩

include hB

theorem gen_norm : Algebra.norm ℚ (evF v8 / 820 : L8) = 5 := by
  rw [← hnorm, Algebra.norm_norm, hB]

theorem absNorm_gen : Ideal.absNorm (Ideal.span {genInt a v8 hnorm}) = 5 := by
  rw [Ideal.absNorm_span_singleton]
  have h := Algebra.coe_norm_int (genInt a v8 hnorm)
  rw [show ((genInt a v8 hnorm : 𝓞 L8) : L8) = evF v8 / 820 from rfl, gen_norm a v8 hnorm hB] at h
  have : Algebra.norm ℤ (genInt a v8 hnorm) = 5 := by exact_mod_cast h
  rw [this]
  rfl

theorem gen_span_isPrime : (Ideal.span {genInt a v8 hnorm}).IsPrime := by
  apply Ideal.isPrime_of_irreducible_absNorm
  rw [absNorm_gen a v8 hnorm hB, Nat.irreducible_iff_nat_prime]
  exact Nat.prime_five

theorem gen_span_ne_bot : Ideal.span {genInt a v8 hnorm} ≠ ⊥ := by
  intro h
  have := absNorm_gen a v8 hnorm hB
  rw [h, Ideal.absNorm_bot] at this
  norm_num at this

/-- The prime `(n_a)` of `L₈`. -/
def genPrime : HeightOneSpectrum (𝓞 L8) where
  asIdeal := Ideal.span {genInt a v8 hnorm}
  isPrime := gen_span_isPrime a v8 hnorm hB
  ne_bot := gen_span_ne_bot a v8 hnorm hB

end Gen

/-! ## The valuations of the generators -/

theorem norm_algebraMap_L8 (x : L8) : Algebra.norm ℚ (algebraMap L8 L24 x) = Algebra.norm ℚ x ^ 3 := by
  rw [← Algebra.norm_norm (S := L8), Algebra.norm_algebraMap, L24_finrank_over_L8, map_pow]

theorem ν_nonneg_of_isIntegral (k : Fin 7) {y : L24} (hy : IsIntegral ℤ y) : 0 ≤ ν (Q k) y :=
  ν_intCast_nonneg (v := Q k) (⟨y, hy⟩ : 𝓞 L24)

/-- The multiplicity of `Q k` in a list of indices. -/
def mult (k : Fin 7) (l : List (Fin 24)) : ℤ := (l.map fun j => if idx k = j then (1 : ℤ) else 0).sum

/-- If `Y · n = ∏_{i ∈ l} B_i` with `Y` integral, `N_{L₈/ℚ}(n) = 5` and `l` of length 3 made of primes above 5, then
`ν_{Q k}(n)` is the multiplicity of `Q k` in `l`. -/
theorem ν_gen (n : L8) (hn : Algebra.norm ℚ n = 5) (Y : L24) (hY : IsIntegral ℤ Y)
    (l : List (Fin 24)) (hrel : Y * algebraMap L8 L24 n = (l.map B).prod)
    (hl : ∑ k : Fin 7, mult k l = 3) (k : Fin 7) : ν (Q k) (algebraMap L8 L24 n) = mult k l := by
  have hprod0 : (l.map B).prod ≠ 0 :=
    List.prod_ne_zero (by simp only [List.mem_map, not_exists, not_and]; exact fun i _ h => B_ne_zero i h)
  have hY0 : Y ≠ 0 := by rintro rfl; rw [zero_mul] at hrel; exact hprod0 hrel.symm
  have hn0 : algebraMap L8 L24 n ≠ 0 := by rintro h; rw [h, mul_zero] at hrel; exact hprod0 hrel.symm
  have hup : ∀ l' : Fin 7, ν (Q l') (algebraMap L8 L24 n) ≤ mult l' l := by
    intro l'
    have h := congrArg (ν (Q l')) hrel
    rw [ν_mul hY0 hn0, ν_list_prod] at h
    have := ν_nonneg_of_isIntegral l' hY
    unfold mult
    omega
  have hsum := prodF (algebraMap L8 L24 n) hn0
  rw [norm_algebraMap_L8, hn, padicValRat.pow] at hsum
  have h55 : padicValRat 5 (5 : ℚ) = 1 := by exact_mod_cast padicValRat.self (p := 5) (by norm_num)
  rw [h55] at hsum
  have h0 : ∑ l' : Fin 7, (mult l' l - ν (Q l') (algebraMap L8 L24 n)) = 0 := by
    rw [Finset.sum_sub_distrib, hl, ← hsum]; push_cast
  have := (Finset.sum_eq_zero_iff_of_nonneg (fun l' _ => sub_nonneg.mpr (hup l'))).mp h0 k (Finset.mem_univ k)
  omega

/-! ## The three primes of `L₈` above 5 -/

theorem normL8_B (a : Fin 24) (v8 : Fin 8 → ℤ)
    (h : Algebra.norm L8 (ev (Bnum a) / (((Bden a) : ℕ) : L24)) = evF v8 / 820) :
    Algebra.norm L8 (B a) = evF v8 / 820 := h

/-- `p_A = (N(B₆))`, the prime of `L₈` with `e = 5`. -/
def pA : HeightOneSpectrum (𝓞 L8) := genPrime 5 v_5 (normL8_B 5 v_5 normL8_5) B_norm_5

/-- `p_B = (N(B₃))`, the prime of `L₈` with `e = 1`. -/
def pB : HeightOneSpectrum (𝓞 L8) := genPrime 2 v_2 (normL8_B 2 v_2 normL8_2) B_norm_2

/-- `p_C = (N(B₂))`, the prime of `L₈` with `e = 2`. -/
def pC : HeightOneSpectrum (𝓞 L8) := genPrime 1 v_1 (normL8_B 1 v_1 normL8_1) B_norm_1

theorem ν_nA (k : Fin 7) : ν (Q k) (algebraMap L8 L24 (evF v_5 / 820)) = mult k l_q2 :=
  ν_gen _ (gen_norm 5 v_5 (normL8_B 5 v_5 normL8_5) B_norm_5) _ isIntegral_q2 l_q2
    (Yrel Ynum_q2 Yden_q2 (by decide) v_5 l_q2 relY_q2) (by decide) k

theorem ν_nB (k : Fin 7) : ν (Q k) (algebraMap L8 L24 (evF v_2 / 820)) = mult k l_q3 :=
  ν_gen _ (gen_norm 2 v_2 (normL8_B 2 v_2 normL8_2) B_norm_2) _ isIntegral_q3 l_q3
    (Yrel Ynum_q3 Yden_q3 (by decide) v_2 l_q3 relY_q3) (by decide) k

theorem ν_nC (k : Fin 7) : ν (Q k) (algebraMap L8 L24 (evF v_1 / 820)) = mult k l_q4 :=
  ν_gen _ (gen_norm 1 v_1 (normL8_B 1 v_1 normL8_1) B_norm_1) _ isIntegral_q4 l_q4
    (Yrel Ynum_q4 Yden_q4 (by decide) v_1 l_q4 relY_q4) (by decide) k

/-- If `ν_{Q k}(n) > 0` for the generator `n` of `p`, then `Q k` lies over `p`. -/
theorem liesOver_of_pos (p : HeightOneSpectrum (𝓞 L8)) (n : 𝓞 L8) (hp : p.asIdeal = Ideal.span {n}) (k : Fin 7)
    (hn : 0 < ν (Q k) (algebraMap L8 L24 (n : L8))) : (Q k).asIdeal.LiesOver p.asIdeal := by
  have hmem : algebraMap (𝓞 L8) (𝓞 L24) n ∈ (Q k).asIdeal := by
    have hne : ((algebraMap (𝓞 L8) (𝓞 L24) n : 𝓞 L24) : L24) ≠ 0 := by
      intro h0; rw [show ((algebraMap (𝓞 L8) (𝓞 L24) n : 𝓞 L24) : L24) = algebraMap L8 L24 (n : L8) from rfl] at h0
      rw [h0, ν_zero] at hn; exact lt_irrefl _ hn
    rw [← ν_pos_iff_mem hne]
    exact hn
  constructor
  refine (p.isMaximal.eq_of_le (Ideal.comap_ne_top _ (Q k).isPrime.ne_top) ?_)
  rw [hp, Ideal.span_le, Set.singleton_subset_iff]
  exact hmem

/-- `ν_{Q k}(x) = e(Q k / p) ν_p(x)` for `x ∈ L₈`. -/
theorem ν_liesOver (p : HeightOneSpectrum (𝓞 L8)) (k : Fin 7) [(Q k).asIdeal.LiesOver p.asIdeal] (x : L8) :
    ν (Q k) (algebraMap L8 L24 x) = (p.asIdeal.ramificationIdx' (Q k).asIdeal : ℤ) * ν p x := by
  rw [ν, ν, ← HeightOneSpectrum.valuation_liesOver L24 p (Q k) x, WithZero.log_pow, nsmul_eq_mul]
  ring

/-- Primes of `L₂₄` over the same prime of `L₈`: `ν_{Q k}(x) e_l = ν_{Q l}(x) e_k` for `x ∈ L₈`. -/
theorem group_rel (p : HeightOneSpectrum (𝓞 L8)) (k l : Fin 7) (hk : (Q k).asIdeal.LiesOver p.asIdeal)
    (hl : (Q l).asIdeal.LiesOver p.asIdeal) (x : L8) :
    ν (Q k) (algebraMap L8 L24 x) * eQ l = ν (Q l) (algebraMap L8 L24 x) * eQ k := by
  have h5k := ν_five k
  have h5l := ν_five l
  rw [← map_ofNat (algebraMap L8 L24) 5] at h5k h5l
  rw [ν_liesOver p k] at h5k ⊢
  rw [ν_liesOver p l] at h5l ⊢
  rw [← h5k, ← h5l]
  ring

end

end X2Y5Z7.FiveAdic
