/-
Generated by computer; every fact used is proved in Lean.
-/
import X2Y5Z7.SymbolSets.Q311.Data

/-! # Proposition 5.3 at `q = 311`: certificates for `η = 2 … 124` (0 R, 123 G, 0 F) -/

namespace X2Y5Z7.SymbolSets.Q311

open X2Y5Z7.SymbolSets

def k2 : Cert :=
  Cert.G 1 [125, 1] [44, 91, 0, 243, 3, 271] [6, 207, 193, 204, 272, 281, 122]

theorem c2 : certCheck 311 D ILN 2 k2 = true := by decide +kernel

def k3 : Cert :=
  Cert.G 1 [144, 1] [49, 130, 255, 9, 63, 11] [44, 235, 83, 209, 156, 200, 143]

theorem c3 : certCheck 311 D ILN 3 k3 = true := by decide +kernel

def k4 : Cert :=
  Cert.G 1 [111, 66, 1] [272, 64, 287, 296, 16] [108, 265, 293, 41, 43, 236]

theorem c4 : certCheck 311 D ILN 4 k4 = true := by decide +kernel

def k5 : Cert :=
  Cert.G 1 [1] [200, 80, 67, 210, 273, 17, 27] [204, 288, 254, 112, 24, 42, 199, 168]

theorem c5 : certCheck 311 D ILN 5 k5 = true := by decide +kernel

def k6 : Cert :=
  Cert.G 1 [1] [66, 39, 236, 295, 189, 153, 274] [278, 101, 159, 236, 24, 251, 203, 134]

theorem c6 : certCheck 311 D ILN 6 k6 = true := by decide +kernel

def k7 : Cert :=
  Cert.G 1 [231, 1] [189, 194, 75, 24, 231, 166] [201, 301, 101, 5, 22, 282, 291]

theorem c7 : certCheck 311 D ILN 7 k7 = true := by decide +kernel

def k8 : Cert :=
  Cert.G 1 [197, 1] [88, 295, 295, 146, 147, 177] [10, 67, 204, 280, 59, 279, 42]

theorem c8 : certCheck 311 D ILN 8 k8 = true := by decide +kernel

def k9 : Cert :=
  Cert.G 1 [1] [27, 248, 183, 114, 271, 78, 292] [140, 167, 156, 233, 104, 181, 218, 74]

theorem c9 : certCheck 311 D ILN 9 k9 = true := by decide +kernel

def k10 : Cert :=
  Cert.G 1 [1] [248, 58, 104, 59, 309, 207, 106] [241, 84, 167, 283, 223, 25, 188, 158]

theorem c10 : certCheck 311 D ILN 10 k10 = true := by decide +kernel

def k11 : Cert :=
  Cert.G 1 [14, 1] [151, 75, 56, 12, 267, 83] [207, 73, 140, 76, 243, 73, 207]

theorem c11 : certCheck 311 D ILN 11 k11 = true := by decide +kernel

def k12 : Cert :=
  Cert.G 1 [43, 42, 26, 1] [61, 3, 23, 295] [30, 190, 118, 199, 72]

theorem c12 : certCheck 311 D ILN 12 k12 = true := by decide +kernel

def k13 : Cert :=
  Cert.G 1 [1] [289, 182, 138, 56, 210, 209, 97] [147, 216, 62, 226, 206, 227, 74, 200]

theorem c13 : certCheck 311 D ILN 13 k13 = true := by decide +kernel

def k14 : Cert :=
  Cert.G 1 [1] [183, 90, 190, 115, 191, 263, 136] [230, 12, 133, 168, 266, 112, 177, 35]

theorem c14 : certCheck 311 D ILN 14 k14 = true := by decide +kernel

def k15 : Cert :=
  Cert.G 1 [1] [65, 130, 200, 155, 183, 127, 136] [191, 23, 265, 280, 232, 166, 272, 80]

theorem c15 : certCheck 311 D ILN 15 k15 = true := by decide +kernel

def k16 : Cert :=
  Cert.G 1 [112, 1] [45, 288, 233, 165, 259, 53] [299, 38, 273, 101, 304, 68, 306]

theorem c16 : certCheck 311 D ILN 16 k16 = true := by decide +kernel

def k17 : Cert :=
  Cert.G 1 [266, 1] [230, 271, 72, 113, 255, 31] [4, 92, 79, 286, 157, 282, 139]

theorem c17 : certCheck 311 D ILN 17 k17 = true := by decide +kernel

def k18 : Cert :=
  Cert.G 1 [1] [179, 112, 3, 273, 21, 234, 216] [138, 234, 37, 207, 177, 208, 302, 266]

theorem c18 : certCheck 311 D ILN 18 k18 = true := by decide +kernel

def k19 : Cert :=
  Cert.G 1 [1] [210, 183, 148, 223, 124, 217, 251] [130, 58, 201, 129, 18, 60, 243, 251]

theorem c19 : certCheck 311 D ILN 19 k19 = true := by decide +kernel

def k20 : Cert :=
  Cert.G 1 [1] [29, 107, 157, 219, 38, 264, 40] [132, 160, 53, 99, 99, 308, 82, 55]

theorem c20 : certCheck 311 D ILN 20 k20 = true := by decide +kernel

def k21 : Cert :=
  Cert.G 1 [1] [185, 283, 286, 62, 69, 46, 141] [295, 235, 231, 290, 21, 52, 143, 271]

theorem c21 : certCheck 311 D ILN 21 k21 = true := by decide +kernel

def k22 : Cert :=
  Cert.G 1 [71, 106, 1] [136, 227, 188, 63, 217] [92, 179, 37, 175, 83, 44]

theorem c22 : certCheck 311 D ILN 22 k22 = true := by decide +kernel

def k23 : Cert :=
  Cert.G 1 [254, 230, 10, 1] [54, 178, 41, 68] [176, 280, 114, 223, 43]

theorem c23 : certCheck 311 D ILN 23 k23 = true := by decide +kernel

def k24 : Cert :=
  Cert.G 1 [1] [123, 283, 4, 25, 263, 13, 266] [217, 230, 28, 7, 139, 110, 209, 95]

theorem c24 : certCheck 311 D ILN 24 k24 = true := by decide +kernel

def k25 : Cert :=
  Cert.G 1 [19, 1] [173, 163, 225, 134, 91, 87] [78, 25, 290, 97, 4, 302, 180]

theorem c25 : certCheck 311 D ILN 25 k25 = true := by decide +kernel

def k26 : Cert :=
  Cert.G 1 [177, 1] [68, 1, 214, 115, 150, 29] [178, 26, 47, 164, 13, 60, 28]

theorem c26 : certCheck 311 D ILN 26 k26 = true := by decide +kernel

def k27 : Cert :=
  Cert.G 1 [181, 1] [270, 230, 95, 1, 2, 252] [133, 267, 151, 44, 151, 114, 308]

theorem c27 : certCheck 311 D ILN 27 k27 = true := by decide +kernel

def k28 : Cert :=
  Cert.G 1 [1] [130, 44, 297, 68, 277, 22, 212] [66, 87, 95, 159, 121, 272, 303, 291]

theorem c28 : certCheck 311 D ILN 28 k28 = true := by decide +kernel

def k29 : Cert :=
  Cert.G 1 [1] [113, 272, 310, 234, 264, 157, 60] [60, 175, 88, 106, 199, 154, 240, 102]

theorem c29 : certCheck 311 D ILN 29 k29 = true := by decide +kernel

def k30 : Cert :=
  Cert.G 1 [287, 33, 1] [177, 120, 214, 306, 54] [266, 11, 33, 273, 191, 27]

theorem c30 : certCheck 311 D ILN 30 k30 = true := by decide +kernel

def k31 : Cert :=
  Cert.G 1 [160, 227, 1] [93, 210, 159, 51, 56] [218, 28, 95, 144, 110, 39]

theorem c31 : certCheck 311 D ILN 31 k31 = true := by decide +kernel

def k32 : Cert :=
  Cert.G 1 [100, 1] [165, 29, 106, 121, 248, 186] [196, 36, 264, 142, 248, 188, 87]

theorem c32 : certCheck 311 D ILN 32 k32 = true := by decide +kernel

def k33 : Cert :=
  Cert.G 1 [170, 1] [20, 45, 189, 110, 109, 251] [144, 299, 202, 268, 275, 23, 209]

theorem c33 : certCheck 311 D ILN 33 k33 = true := by decide +kernel

def k34 : Cert :=
  Cert.G 1 [106, 297, 17, 1] [233, 103, 29, 32] [184, 227, 186, 173, 180]

theorem c34 : certCheck 311 D ILN 34 k34 = true := by decide +kernel

def k35 : Cert :=
  Cert.G 1 [197, 240, 1] [153, 180, 143, 38, 238] [30, 218, 148, 242, 121, 91]

theorem c35 : certCheck 311 D ILN 35 k35 = true := by decide +kernel

def k36 : Cert :=
  Cert.G 1 [71, 1] [120, 4, 96, 262, 156, 192] [27, 116, 139, 276, 136, 273, 95]

theorem c36 : certCheck 311 D ILN 36 k36 = true := by decide +kernel

def k37 : Cert :=
  Cert.G 1 [1] [223, 182, 125, 300, 102, 208, 32] [120, 126, 111, 285, 169, 126, 160, 140]

theorem c37 : certCheck 311 D ILN 37 k37 = true := by decide +kernel

def k38 : Cert :=
  Cert.G 1 [1] [127, 17, 76, 2, 123, 43, 60] [93, 51, 115, 104, 278, 177, 104, 125]

theorem c38 : certCheck 311 D ILN 38 k38 = true := by decide +kernel

def k39 : Cert :=
  Cert.G 1 [88, 1] [172, 161, 72, 110, 101, 171] [65, 50, 69, 192, 43, 121, 58]

theorem c39 : certCheck 311 D ILN 39 k39 = true := by decide +kernel

def k40 : Cert :=
  Cert.G 1 [64, 1] [203, 144, 13, 51, 113, 216] [100, 155, 216, 308, 63, 148, 211]

theorem c40 : certCheck 311 D ILN 40 k40 = true := by decide +kernel

def k41 : Cert :=
  Cert.G 1 [1] [63, 272, 186, 272, 109, 119, 9] [91, 115, 167, 126, 250, 96, 206, 282]

theorem c41 : certCheck 311 D ILN 41 k41 = true := by decide +kernel

def k42 : Cert :=
  Cert.G 1 [174, 1] [303, 89, 99, 242, 94, 101] [98, 188, 255, 207, 242, 24, 116]

theorem c42 : certCheck 311 D ILN 42 k42 = true := by decide +kernel

def k43 : Cert :=
  Cert.G 1 [1] [110, 67, 79, 302, 0, 130, 38] [215, 164, 185, 271, 203, 78, 115, 73]

theorem c43 : certCheck 311 D ILN 43 k43 = true := by decide +kernel

def k44 : Cert :=
  Cert.G 1 [1] [182, 309, 0, 120, 163, 97, 50] [246, 99, 277, 118, 296, 256, 251, 230]

theorem c44 : certCheck 311 D ILN 44 k44 = true := by decide +kernel

def k45 : Cert :=
  Cert.G 1 [1] [53, 270, 129, 282, 285, 120, 5] [30, 0, 288, 296, 80, 159, 188, 278]

theorem c45 : certCheck 311 D ILN 45 k45 = true := by decide +kernel

def k46 : Cert :=
  Cert.G 1 [1] [247, 247, 255, 250, 99, 280, 50] [1, 299, 208, 117, 99, 310, 276, 273]

theorem c46 : certCheck 311 D ILN 46 k46 = true := by decide +kernel

def k47 : Cert :=
  Cert.G 1 [199, 1] [187, 235, 81, 61, 165, 148] [237, 132, 198, 298, 208, 256, 141]

theorem c47 : certCheck 311 D ILN 47 k47 = true := by decide +kernel

def k48 : Cert :=
  Cert.G 1 [1] [247, 56, 257, 7, 264, 70, 198] [45, 212, 0, 132, 283, 81, 64, 245]

theorem c48 : certCheck 311 D ILN 48 k48 = true := by decide +kernel

def k49 : Cert :=
  Cert.G 1 [207, 1] [55, 188, 61, 111, 123, 27] [91, 227, 190, 198, 14, 146, 30]

theorem c49 : certCheck 311 D ILN 49 k49 = true := by decide +kernel

def k50 : Cert :=
  Cert.G 1 [1] [304, 118, 76, 285, 292, 102, 138] [309, 310, 108, 105, 261, 65, 156, 237]

theorem c50 : certCheck 311 D ILN 50 k50 = true := by decide +kernel

def k51 : Cert :=
  Cert.G 1 [83, 306, 1] [64, 199, 74, 162, 37] [297, 179, 169, 4, 254, 178]

theorem c51 : certCheck 311 D ILN 51 k51 = true := by decide +kernel

def k52 : Cert :=
  Cert.G 1 [258, 1] [28, 133, 249, 44, 36, 195] [127, 259, 13, 254, 20, 288, 223]

theorem c52 : certCheck 311 D ILN 52 k52 = true := by decide +kernel

def k53 : Cert :=
  Cert.G 1 [135, 1] [89, 215, 289, 114, 180, 21] [211, 200, 247, 178, 99, 223, 99]

theorem c53 : certCheck 311 D ILN 53 k53 = true := by decide +kernel

def k54 : Cert :=
  Cert.G 1 [1] [135, 304, 78, 4, 213, 49, 265] [110, 9, 42, 123, 159, 150, 190, 246]

theorem c54 : certCheck 311 D ILN 54 k54 = true := by decide +kernel

def k55 : Cert :=
  Cert.G 1 [226, 1] [236, 78, 190, 256, 90, 195] [210, 2, 258, 38, 237, 226, 243]

theorem c55 : certCheck 311 D ILN 55 k55 = true := by decide +kernel

def k56 : Cert :=
  Cert.G 1 [28, 1] [17, 277, 303, 122, 149, 117] [12, 190, 187, 224, 133, 184, 14]

theorem c56 : certCheck 311 D ILN 56 k56 = true := by decide +kernel

def k57 : Cert :=
  Cert.G 1 [232, 1] [167, 168, 62, 167, 264, 112] [73, 43, 296, 140, 3, 310, 258]

theorem c57 : certCheck 311 D ILN 57 k57 = true := by decide +kernel

def k58 : Cert :=
  Cert.G 1 [1] [109, 14, 152, 27, 310, 175, 130] [99, 184, 131, 108, 183, 295, 42, 262]

theorem c58 : certCheck 311 D ILN 58 k58 = true := by decide +kernel

def k59 : Cert :=
  Cert.G 1 [82, 1] [289, 145, 308, 222, 290, 237] [88, 189, 206, 32, 9, 192, 223]

theorem c59 : certCheck 311 D ILN 59 k59 = true := by decide +kernel

def k60 : Cert :=
  Cert.G 1 [118, 1] [81, 278, 237, 43, 57, 281] [9, 216, 231, 124, 13, 108, 27]

theorem c60 : certCheck 311 D ILN 60 k60 = true := by decide +kernel

def k61 : Cert :=
  Cert.G 1 [1] [123, 189, 62, 79, 212, 267, 179] [198, 207, 36, 199, 265, 2, 133, 176]

theorem c61 : certCheck 311 D ILN 61 k61 = true := by decide +kernel

def k62 : Cert :=
  Cert.G 1 [171, 1] [123, 113, 222, 123, 242, 236] [135, 152, 42, 195, 227, 207, 249]

theorem c62 : certCheck 311 D ILN 62 k62 = true := by decide +kernel

def k63 : Cert :=
  Cert.G 1 [243, 190, 73, 1] [259, 19, 92, 94] [55, 59, 100, 215, 107]

theorem c63 : certCheck 311 D ILN 63 k63 = true := by decide +kernel

def k64 : Cert :=
  Cert.G 1 [1] [9, 267, 115, 21, 291, 191, 232] [85, 28, 29, 277, 7, 305, 76, 80]

theorem c64 : certCheck 311 D ILN 64 k64 = true := by decide +kernel

def k65 : Cert :=
  Cert.G 1 [186, 1] [177, 212, 209, 197, 48, 243] [31, 180, 11, 1, 133, 276, 224]

theorem c65 : certCheck 311 D ILN 65 k65 = true := by decide +kernel

def k66 : Cert :=
  Cert.G 1 [86, 1] [159, 186, 70, 73, 51, 232] [74, 293, 189, 174, 158, 86, 291]

theorem c66 : certCheck 311 D ILN 66 k66 = true := by decide +kernel

def k67 : Cert :=
  Cert.G 1 [265, 1] [250, 188, 261, 238, 28, 63] [306, 306, 51, 129, 94, 157, 199]

theorem c67 : certCheck 311 D ILN 67 k67 = true := by decide +kernel

def k68 : Cert :=
  Cert.G 1 [284, 42, 1] [83, 169, 146, 251, 36] [234, 216, 67, 211, 93, 32]

theorem c68 : certCheck 311 D ILN 68 k68 = true := by decide +kernel

def k69 : Cert :=
  Cert.G 1 [29, 217, 1] [21, 243, 131, 254, 31] [255, 265, 277, 307, 122, 19]

theorem c69 : certCheck 311 D ILN 69 k69 = true := by decide +kernel

def k70 : Cert :=
  Cert.G 1 [1] [27, 92, 71, 55, 135, 169, 83] [125, 193, 73, 145, 4, 12, 12, 142]

theorem c70 : certCheck 311 D ILN 70 k70 = true := by decide +kernel

def k71 : Cert :=
  Cert.G 1 [121, 1] [92, 11, 103, 203, 216, 126] [127, 89, 246, 220, 117, 254, 292]

theorem c71 : certCheck 311 D ILN 71 k71 = true := by decide +kernel

def k72 : Cert :=
  Cert.G 1 [283, 1] [248, 94, 39, 60, 5, 160] [44, 59, 128, 268, 81, 1, 11]

theorem c72 : certCheck 311 D ILN 72 k72 = true := by decide +kernel

def k73 : Cert :=
  Cert.G 1 [1] [203, 305, 142, 279, 95, 262, 84] [165, 169, 284, 156, 187, 157, 24, 123]

theorem c73 : certCheck 311 D ILN 73 k73 = true := by decide +kernel

def k74 : Cert :=
  Cert.G 1 [1] [92, 10, 191, 36, 178, 134, 259] [48, 307, 293, 253, 74, 275, 53, 295]

theorem c74 : certCheck 311 D ILN 74 k74 = true := by decide +kernel

def k75 : Cert :=
  Cert.G 1 [1] [4, 271, 223, 63, 84, 72, 265] [84, 184, 260, 196, 263, 103, 73, 178]

theorem c75 : certCheck 311 D ILN 75 k75 = true := by decide +kernel

def k76 : Cert :=
  Cert.G 1 [205, 158, 35, 1] [301, 34, 170, 169] [250, 214, 183, 234, 284]

theorem c76 : certCheck 311 D ILN 76 k76 = true := by decide +kernel

def k77 : Cert :=
  Cert.G 1 [1] [77, 55, 10, 139, 22, 176, 216] [290, 91, 283, 209, 301, 132, 61, 209]

theorem c77 : certCheck 311 D ILN 77 k77 = true := by decide +kernel

def k78 : Cert :=
  Cert.G 1 [296, 1] [142, 303, 115, 171, 15, 90] [217, 93, 258, 83, 57, 37, 266]

theorem c78 : certCheck 311 D ILN 78 k78 = true := by decide +kernel

def k79 : Cert :=
  Cert.G 1 [12, 71, 112, 1] [235, 205, 295, 224] [49, 88, 293, 150, 23]

theorem c79 : certCheck 311 D ILN 79 k79 = true := by decide +kernel

def k80 : Cert :=
  Cert.G 1 [1] [191, 272, 157, 101, 167, 267, 255] [116, 98, 28, 206, 31, 202, 163, 19]

theorem c80 : certCheck 311 D ILN 80 k80 = true := by decide +kernel

def k81 : Cert :=
  Cert.G 1 [58, 1] [42, 113, 148, 51, 93, 149] [29, 241, 220, 298, 2, 208, 98]

theorem c81 : certCheck 311 D ILN 81 k81 = true := by decide +kernel

def k82 : Cert :=
  Cert.G 1 [9, 30, 1] [231, 142, 226, 9, 209] [248, 119, 111, 35, 234, 90]

theorem c82 : certCheck 311 D ILN 82 k82 = true := by decide +kernel

def k83 : Cert :=
  Cert.G 1 [119, 1] [105, 117, 191, 202, 276, 18] [211, 139, 55, 12, 305, 239, 252]

theorem c83 : certCheck 311 D ILN 83 k83 = true := by decide +kernel

def k84 : Cert :=
  Cert.G 1 [149, 1] [275, 200, 254, 189, 198, 163] [161, 76, 48, 16, 68, 256, 171]

theorem c84 : certCheck 311 D ILN 84 k84 = true := by decide +kernel

def k85 : Cert :=
  Cert.G 1 [305, 267, 1] [43, 17, 178, 139, 165] [35, 66, 202, 173, 278, 258]

theorem c85 : certCheck 311 D ILN 85 k85 = true := by decide +kernel

def k86 : Cert :=
  Cert.G 1 [1] [265, 294, 307, 126, 255, 190, 191] [131, 297, 157, 186, 106, 183, 147, 82]

theorem c86 : certCheck 311 D ILN 86 k86 = true := by decide +kernel

def k87 : Cert :=
  Cert.G 1 [1] [290, 147, 150, 59, 127, 89, 198] [267, 187, 18, 11, 241, 287, 272, 34]

theorem c87 : certCheck 311 D ILN 87 k87 = true := by decide +kernel

def k88 : Cert :=
  Cert.G 1 [1] [138, 144, 185, 304, 233, 71] [4, 246, 69, 239, 8, 146, 300]

theorem c88 : certCheck 311 D ILN 88 k88 = true := by decide +kernel

def k89 : Cert :=
  Cert.G 1 [78, 1] [161, 83, 235, 231, 170, 187] [287, 280, 13, 34, 71, 179, 214]

theorem c89 : certCheck 311 D ILN 89 k89 = true := by decide +kernel

def k90 : Cert :=
  Cert.G 1 [193, 1] [48, 234, 182, 223, 257, 250] [106, 17, 303, 282, 296, 58, 117]

theorem c90 : certCheck 311 D ILN 90 k90 = true := by decide +kernel

def k91 : Cert :=
  Cert.G 1 [107, 1] [97, 265, 45, 303, 104, 278] [134, 49, 268, 28, 170, 278, 302]

theorem c91 : certCheck 311 D ILN 91 k91 = true := by decide +kernel

def k92 : Cert :=
  Cert.G 1 [1] [251, 289, 180, 273, 44, 165, 126] [41, 66, 18, 124, 97, 61, 15, 299]

theorem c92 : certCheck 311 D ILN 92 k92 = true := by decide +kernel

def k93 : Cert :=
  Cert.G 1 [251, 1] [116, 77, 295, 305, 113, 168] [189, 130, 248, 271, 175, 117, 85]

theorem c93 : certCheck 311 D ILN 93 k93 = true := by decide +kernel

def k94 : Cert :=
  Cert.G 1 [1] [140, 287, 280, 120, 196, 165, 66] [82, 290, 247, 6, 114, 8, 27, 159]

theorem c94 : certCheck 311 D ILN 94 k94 = true := by decide +kernel

def k95 : Cert :=
  Cert.G 1 [55, 112, 278, 1] [230, 181, 106, 274] [230, 303, 24, 188, 145]

theorem c95 : certCheck 311 D ILN 95 k95 = true := by decide +kernel

def k96 : Cert :=
  Cert.G 1 [135, 87, 1] [302, 211, 7, 198, 167] [144, 68, 144, 48, 71, 19]

theorem c96 : certCheck 311 D ILN 96 k96 = true := by decide +kernel

def k97 : Cert :=
  Cert.G 1 [179, 1] [45, 40, 201, 195, 106, 23] [75, 75, 299, 153, 308, 200, 168]

theorem c97 : certCheck 311 D ILN 97 k97 = true := by decide +kernel

def k98 : Cert :=
  Cert.G 1 [130, 1] [240, 95, 198, 19, 241, 232] [55, 243, 30, 158, 38, 89, 172]

theorem c98 : certCheck 311 D ILN 98 k98 = true := by decide +kernel

def k99 : Cert :=
  Cert.G 1 [136, 237, 1] [254, 28, 298, 188, 130] [272, 188, 205, 75, 41, 115]

theorem c99 : certCheck 311 D ILN 99 k99 = true := by decide +kernel

def k100 : Cert :=
  Cert.G 1 [1] [74, 157, 89, 248, 153, 54, 280] [247, 51, 173, 57, 98, 197, 210, 252]

theorem c100 : certCheck 311 D ILN 100 k100 = true := by decide +kernel

def k101 : Cert :=
  Cert.G 1 [1] [286, 202, 258, 258, 21, 168, 148] [191, 54, 195, 301, 150, 194, 2, 301]

theorem c101 : certCheck 311 D ILN 101 k101 = true := by decide +kernel

def k102 : Cert :=
  Cert.G 1 [16, 1] [28, 93, 278, 126, 111, 245] [283, 241, 19, 82, 153, 119, 170]

theorem c102 : certCheck 311 D ILN 102 k102 = true := by decide +kernel

def k103 : Cert :=
  Cert.G 1 [1] [111, 73, 95, 214, 236, 251, 284] [121, 206, 151, 20, 293, 148, 193, 37]

theorem c103 : certCheck 311 D ILN 103 k103 = true := by decide +kernel

def k104 : Cert :=
  Cert.G 1 [300, 106, 1] [112, 207, 155, 60, 35] [37, 235, 8, 297, 43, 221]

theorem c104 : certCheck 311 D ILN 104 k104 = true := by decide +kernel

def k105 : Cert :=
  Cert.G 1 [1] [233, 19, 227, 61, 170, 96, 151] [181, 214, 99, 266, 210, 229, 216, 29]

theorem c105 : certCheck 311 D ILN 105 k105 = true := by decide +kernel

def k106 : Cert :=
  Cert.G 1 [1] [250, 310, 268, 218, 299, 193, 83] [162, 205, 189, 265, 194, 186, 28, 125]

theorem c106 : certCheck 311 D ILN 106 k106 = true := by decide +kernel

def k107 : Cert :=
  Cert.G 1 [109, 160, 237, 1] [175, 30, 87, 45] [54, 189, 120, 67, 185]

theorem c107 : certCheck 311 D ILN 107 k107 = true := by decide +kernel

def k108 : Cert :=
  Cert.G 1 [1] [181, 253, 123, 176, 3, 143, 149] [72, 133, 6, 89, 234, 129, 298, 304]

theorem c108 : certCheck 311 D ILN 108 k108 = true := by decide +kernel

def k109 : Cert :=
  Cert.G 1 [184, 1] [165, 234, 171, 128, 229, 19] [38, 247, 290, 308, 274, 102, 131]

theorem c109 : certCheck 311 D ILN 109 k109 = true := by decide +kernel

def k110 : Cert :=
  Cert.G 1 [1] [229, 154, 244, 308, 187, 133, 186] [176, 221, 14, 206, 108, 164, 279, 110]

theorem c110 : certCheck 311 D ILN 110 k110 = true := by decide +kernel

def k111 : Cert :=
  Cert.G 1 [1] [136, 302, 11, 54, 265, 294, 107] [269, 288, 50, 123, 309, 258, 216, 240]

theorem c111 : certCheck 311 D ILN 111 k111 = true := by decide +kernel

def k112 : Cert :=
  Cert.G 1 [241, 1] [169, 55, 172, 145, 195, 105] [198, 15, 234, 210, 30, 195, 192]

theorem c112 : certCheck 311 D ILN 112 k112 = true := by decide +kernel

def k113 : Cert :=
  Cert.G 1 [1] [4, 32, 191, 165, 182, 152, 158] [177, 20, 234, 291, 110, 218, 309, 240]

theorem c113 : certCheck 311 D ILN 113 k113 = true := by decide +kernel

def k114 : Cert :=
  Cert.G 1 [208, 1] [112, 187, 35, 0, 104, 55] [98, 110, 176, 280, 240, 244, 113]

theorem c114 : certCheck 311 D ILN 114 k114 = true := by decide +kernel

def k115 : Cert :=
  Cert.G 1 [5, 1] [256, 163, 120, 181, 66, 125] [58, 125, 36, 64, 294, 73, 35]

theorem c115 : certCheck 311 D ILN 115 k115 = true := by decide +kernel

def k116 : Cert :=
  Cert.G 1 [260, 1] [4, 233, 44, 272, 298, 109] [243, 195, 242, 156, 90, 93, 8]

theorem c116 : certCheck 311 D ILN 116 k116 = true := by decide +kernel

def k117 : Cert :=
  Cert.G 1 [217, 237, 1] [29, 233, 135, 243, 192] [182, 69, 41, 21, 22, 13]

theorem c117 : certCheck 311 D ILN 117 k117 = true := by decide +kernel

def k118 : Cert :=
  Cert.G 1 [1] [180, 107, 218, 112, 126, 148, 121] [11, 233, 74, 102, 238, 162, 230, 58]

theorem c118 : certCheck 311 D ILN 118 k118 = true := by decide +kernel

def k119 : Cert :=
  Cert.G 1 [1] [141, 222, 277, 298, 34, 241, 18] [2, 177, 115, 251, 17, 242, 193, 38]

theorem c119 : certCheck 311 D ILN 119 k119 = true := by decide +kernel

def k120 : Cert :=
  Cert.G 1 [1] [229, 269, 156, 142, 69, 181, 232] [268, 139, 307, 139, 292, 113, 196, 272]

theorem c120 : certCheck 311 D ILN 120 k120 = true := by decide +kernel

def k121 : Cert :=
  Cert.G 1 [299, 215, 1] [246, 13, 185, 3, 177] [40, 131, 15, 11, 4, 118]

theorem c121 : certCheck 311 D ILN 121 k121 = true := by decide +kernel

def k122 : Cert :=
  Cert.G 1 [107, 136, 1] [80, 18, 251, 117, 123] [195, 133, 290, 284, 183, 129]

theorem c122 : certCheck 311 D ILN 122 k122 = true := by decide +kernel

def k123 : Cert :=
  Cert.G 1 [1] [36, 203, 124, 8, 266, 256, 129] [15, 54, 30, 238, 158, 114, 58, 105]

theorem c123 : certCheck 311 D ILN 123 k123 = true := by decide +kernel

def k124 : Cert :=
  Cert.G 1 [214, 1] [203, 250, 149, 134, 208, 106] [284, 0, 124, 81, 263, 277, 48]

theorem c124 : certCheck 311 D ILN 124 k124 = true := by decide +kernel

def certs0 : List (ℕ × Cert) := [(2, k2), (3, k3), (4, k4), (5, k5), (6, k6), (7, k7), (8, k8), (9, k9), (10, k10), (11, k11), (12, k12), (13, k13), (14, k14), (15, k15), (16, k16), (17, k17), (18, k18), (19, k19), (20, k20), (21, k21), (22, k22), (23, k23), (24, k24), (25, k25), (26, k26), (27, k27), (28, k28), (29, k29), (30, k30), (31, k31), (32, k32), (33, k33), (34, k34), (35, k35), (36, k36), (37, k37), (38, k38), (39, k39), (40, k40), (41, k41), (42, k42), (43, k43), (44, k44), (45, k45), (46, k46), (47, k47), (48, k48), (49, k49), (50, k50), (51, k51), (52, k52), (53, k53), (54, k54), (55, k55), (56, k56), (57, k57), (58, k58), (59, k59), (60, k60), (61, k61), (62, k62), (63, k63), (64, k64), (65, k65), (66, k66), (67, k67), (68, k68), (69, k69), (70, k70), (71, k71), (72, k72), (73, k73), (74, k74), (75, k75), (76, k76), (77, k77), (78, k78), (79, k79), (80, k80), (81, k81), (82, k82), (83, k83), (84, k84), (85, k85), (86, k86), (87, k87), (88, k88), (89, k89), (90, k90), (91, k91), (92, k92), (93, k93), (94, k94), (95, k95), (96, k96), (97, k97), (98, k98), (99, k99), (100, k100), (101, k101), (102, k102), (103, k103), (104, k104), (105, k105), (106, k106), (107, k107), (108, k108), (109, k109), (110, k110), (111, k111), (112, k112), (113, k113), (114, k114), (115, k115), (116, k116), (117, k117), (118, k118), (119, k119), (120, k120), (121, k121), (122, k122), (123, k123), (124, k124)]

theorem ok0 : certs0.all (fun p => certCheck 311 D ILN p.1 p.2) = true := by
  simp only [certs0, List.all_cons, List.all_nil, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31, c32, c33, c34, c35, c36, c37, c38, c39, c40, c41, c42, c43, c44, c45, c46, c47, c48, c49, c50, c51, c52, c53, c54, c55, c56, c57, c58, c59, c60, c61, c62, c63, c64, c65, c66, c67, c68, c69, c70, c71, c72, c73, c74, c75, c76, c77, c78, c79, c80, c81, c82, c83, c84, c85, c86, c87, c88, c89, c90, c91, c92, c93, c94, c95, c96, c97, c98, c99, c100, c101, c102, c103, c104, c105, c106, c107, c108, c109, c110, c111, c112, c113, c114, c115, c116, c117, c118, c119, c120, c121, c122, c123, c124, Bool.and_self]

end X2Y5Z7.SymbolSets.Q311
