/-
Generated by computer; every fact used is proved in Lean.
-/
module

public import X2Y5Z7.SymbolSets.Q311.C0

@[expose] public section

/-! # Proposition 5.3 at `q = 311`: certificates for `η = 125 … 191` (0 R, 64 G, 3 F) -/

namespace X2Y5Z7.SymbolSets.Q311

open X2Y5Z7.SymbolSets

def k125 : Cert :=
  Cert.F [([49, 1], []), ([72, 1], []), ([101, 1], []), ([254, 1], []), ([11, 277, 64, 209, 1], [(2, [22, 150, 51, 147])])]
      [[(0, [([262], [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([239], [3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([210], [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (3, [([57], [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([262], [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0])]), (1, [([239], [0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0])]), (2, [([210], [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0])]), (3, [([57], [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([262], [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0])]), (1, [([239], [0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0])]), (2, [([210], [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0])]), (3, [([57], [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0])])],
       [(0, [([262], [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0])]), (1, [([239], [0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0])]), (2, [([210], [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0])]), (3, [([57], [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0])])],
       [(4, [([35, 142, 182, 39], [0, 0, 0, 0, 0, 0, 0, 0, 2, 4, 2]), ([119, 276, 20, 135], [0, 0, 0, 0, 0, 0, 0, 0, 2, 4, 2]), ([210, 45, 129, 213], [0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 4]), ([49, 159, 291, 235], [0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 4])])]]

theorem c125 : certCheck 311 D ILN 125 k125 = true := by decide +kernel

def k126 : Cert :=
  Cert.G 1 [120, 1] [300, 266, 103, 252, 256, 279] [112, 101, 219, 46, 185, 152, 145]

theorem c126 : certCheck 311 D ILN 126 k126 = true := by decide +kernel

def k127 : Cert :=
  Cert.G 1 [283, 42, 1] [14, 36, 110, 215, 49] [277, 88, 218, 204, 280, 296]

theorem c127 : certCheck 311 D ILN 127 k127 = true := by decide +kernel

def k128 : Cert :=
  Cert.G 1 [55, 1] [201, 279, 126, 271, 20, 133] [149, 170, 89, 48, 216, 235, 67]

theorem c128 : certCheck 311 D ILN 128 k128 = true := by decide +kernel

def k129 : Cert :=
  Cert.G 1 [36, 1] [184, 47, 80, 97, 3, 187] [62, 243, 41, 59, 259, 93, 232]

theorem c129 : certCheck 311 D ILN 129 k129 = true := by decide +kernel

def k130 : Cert :=
  Cert.F [([66, 1], []), ([123, 1], []), ([172, 1], []), ([268, 1], []), ([92, 261, 20, 56, 1], [(2, [180, 293, 218, 146])])]
      [[(0, [([245], [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([188], [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([139], [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (3, [([43], [3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([245], [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([188], [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0])]), (2, [([139], [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0])]), (3, [([43], [0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([245], [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0])]), (1, [([188], [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0])]), (2, [([139], [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0])]), (3, [([43], [0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0])])],
       [(0, [([245], [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0])]), (1, [([188], [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0])]), (2, [([139], [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0])]), (3, [([43], [0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0])])],
       [(4, [([227, 292, 164, 92], [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1]), ([208, 208, 94, 256], [0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0]), ([61, 173, 105, 288], [0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0]), ([70, 260, 259, 297], [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1])])]]

theorem c130 : certCheck 311 D ILN 130 k130 = true := by decide +kernel

def k131 : Cert :=
  Cert.G 1 [1] [14, 238, 117, 310, 158, 229, 276] [123, 67, 177, 188, 265, 209, 105, 31]

theorem c131 : certCheck 311 D ILN 131 k131 = true := by decide +kernel

def k132 : Cert :=
  Cert.G 1 [135, 172, 1] [27, 132, 120, 166, 130] [108, 72, 88, 248, 33, 222]

theorem c132 : certCheck 311 D ILN 132 k132 = true := by decide +kernel

def k133 : Cert :=
  Cert.G 1 [190, 269, 89, 1] [147, 138, 256, 113] [9, 146, 261, 246, 188]

theorem c133 : certCheck 311 D ILN 133 k133 = true := by decide +kernel

def k134 : Cert :=
  Cert.G 1 [34, 1] [248, 82, 49, 217, 45, 8] [129, 201, 169, 192, 183, 19, 302]

theorem c134 : certCheck 311 D ILN 134 k134 = true := by decide +kernel

def k135 : Cert :=
  Cert.G 1 [284, 1] [48, 302, 278, 123, 302, 6] [289, 256, 173, 4, 270, 202, 138]

theorem c135 : certCheck 311 D ILN 135 k135 = true := by decide +kernel

def k136 : Cert :=
  Cert.G 1 [194, 1] [240, 229, 310, 207, 287, 45] [179, 293, 123, 246, 212, 195, 310]

theorem c136 : certCheck 311 D ILN 136 k136 = true := by decide +kernel

def k137 : Cert :=
  Cert.G 1 [18, 1] [128, 177, 251, 117, 223, 121] [240, 199, 166, 191, 61, 68, 287]

theorem c137 : certCheck 311 D ILN 137 k137 = true := by decide +kernel

def k138 : Cert :=
  Cert.G 1 [277, 310, 277, 1] [55, 27, 242, 99] [27, 126, 139, 274, 267]

theorem c138 : certCheck 311 D ILN 138 k138 = true := by decide +kernel

def k139 : Cert :=
  Cert.G 1 [1] [64, 160, 169, 187, 238, 74, 138] [64, 59, 40, 191, 173, 131, 164, 104]

theorem c139 : certCheck 311 D ILN 139 k139 = true := by decide +kernel

def k140 : Cert :=
  Cert.G 1 [1] [76, 141, 127, 9, 114, 192, 85] [165, 227, 264, 93, 65, 10, 260, 16]

theorem c140 : certCheck 311 D ILN 140 k140 = true := by decide +kernel

def k141 : Cert :=
  Cert.F [([4, 1], []), ([116, 1], []), ([271, 1], []), ([299, 1], []), ([118, 37, 51, 306, 1], [(2, [287, 110, 252, 275])])]
      [[(0, [([307], [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([195], [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([40], [3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (3, [([12], [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([307], [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0])]), (1, [([195], [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0])]), (2, [([40], [0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0])]), (3, [([12], [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([307], [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0])]), (1, [([195], [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0])]), (2, [([40], [0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0])]), (3, [([12], [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0])])],
       [(0, [([307], [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0])]), (1, [([195], [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0])]), (2, [([40], [0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0])]), (3, [([12], [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0])])],
       [(4, [([224, 285, 3, 125], [0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 0]), ([181, 159, 191, 165], [0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 4]), ([58, 28, 56, 166], [0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 0]), ([164, 150, 61, 166], [0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 4])])]]

theorem c141 : certCheck 311 D ILN 141 k141 = true := by decide +kernel

def k142 : Cert :=
  Cert.G 1 [106, 1] [42, 166, 278, 28, 220, 188] [178, 134, 117, 78, 58, 222, 250]

theorem c142 : certCheck 311 D ILN 142 k142 = true := by decide +kernel

def k143 : Cert :=
  Cert.G 1 [1] [265, 39, 83, 11, 179, 181, 89] [266, 264, 26, 256, 130, 21, 273, 117]

theorem c143 : certCheck 311 D ILN 143 k143 = true := by decide +kernel

def k144 : Cert :=
  Cert.G 1 [69, 1] [283, 268, 172, 48, 169, 215] [283, 75, 284, 155, 56, 24, 67]

theorem c144 : certCheck 311 D ILN 144 k144 = true := by decide +kernel

def k145 : Cert :=
  Cert.G 1 [1] [194, 53, 66, 222, 199, 136, 174] [17, 212, 112, 240, 288, 163, 29, 243]

theorem c145 : certCheck 311 D ILN 145 k145 = true := by decide +kernel

def k146 : Cert :=
  Cert.G 1 [1] [47, 273, 101, 220, 198, 160, 118] [128, 166, 16, 190, 21, 62, 27, 168]

theorem c146 : certCheck 311 D ILN 146 k146 = true := by decide +kernel

def k147 : Cert :=
  Cert.G 1 [33, 44, 1] [262, 142, 29, 305, 43] [152, 5, 77, 137, 146, 38]

theorem c147 : certCheck 311 D ILN 147 k147 = true := by decide +kernel

def k148 : Cert :=
  Cert.G 1 [1] [30, 256, 84, 208, 3, 101, 111] [275, 68, 201, 142, 194, 28, 238, 161]

theorem c148 : certCheck 311 D ILN 148 k148 = true := by decide +kernel

def k149 : Cert :=
  Cert.G 1 [1] [246, 273, 63, 151, 254, 181, 287] [162, 232, 114, 71, 215, 111, 4, 92]

theorem c149 : certCheck 311 D ILN 149 k149 = true := by decide +kernel

def k150 : Cert :=
  Cert.G 1 [257, 39, 1] [21, 261, 267, 26, 59] [158, 163, 300, 141, 84, 266]

theorem c150 : certCheck 311 D ILN 150 k150 = true := by decide +kernel

def k151 : Cert :=
  Cert.G 1 [1] [100, 270, 49, 213, 229, 288, 58] [50, 179, 134, 41, 97, 237, 229, 306]

theorem c151 : certCheck 311 D ILN 151 k151 = true := by decide +kernel

def k152 : Cert :=
  Cert.G 1 [1] [168, 26, 114, 148, 56, 78, 29] [177, 62, 121, 244, 269, 262, 168, 169]

theorem c152 : certCheck 311 D ILN 152 k152 = true := by decide +kernel

def k153 : Cert :=
  Cert.G 1 [234, 1] [283, 24, 49, 8, 150, 110] [220, 40, 117, 15, 307, 109, 295]

theorem c153 : certCheck 311 D ILN 153 k153 = true := by decide +kernel

def k154 : Cert :=
  Cert.G 1 [95, 1] [29, 36, 252, 237, 35, 218] [103, 259, 115, 174, 275, 155, 263]

theorem c154 : certCheck 311 D ILN 154 k154 = true := by decide +kernel

def k155 : Cert :=
  Cert.G 1 [216, 1] [149, 160, 160, 79, 307, 110] [6, 257, 57, 74, 127, 253, 153]

theorem c155 : certCheck 311 D ILN 155 k155 = true := by decide +kernel

def k156 : Cert :=
  Cert.G 1 [246, 1] [280, 136, 15, 227, 119, 31] [70, 88, 140, 83, 266, 140, 161]

theorem c156 : certCheck 311 D ILN 156 k156 = true := by decide +kernel

def k157 : Cert :=
  Cert.G 1 [1] [128, 185, 124, 94, 70, 184] [153, 94, 74, 52, 87, 177, 38]

theorem c157 : certCheck 311 D ILN 157 k157 = true := by decide +kernel

def k158 : Cert :=
  Cert.G 1 [1] [286, 53, 43, 163, 201, 136, 173] [258, 81, 14, 306, 154, 232, 70, 53]

theorem c158 : certCheck 311 D ILN 158 k158 = true := by decide +kernel

def k159 : Cert :=
  Cert.G 1 [1] [182, 17, 67, 176, 218, 235, 87] [65, 59, 166, 16, 161, 6, 178, 146]

theorem c159 : certCheck 311 D ILN 159 k159 = true := by decide +kernel

def k160 : Cert :=
  Cert.G 1 [1] [189, 21, 197, 11, 215, 24, 206] [155, 57, 45, 155, 167, 271, 206, 174]

theorem c160 : certCheck 311 D ILN 160 k160 = true := by decide +kernel

def k161 : Cert :=
  Cert.G 1 [89, 1] [81, 255, 81, 78, 41, 8] [52, 86, 191, 233, 97, 182, 23]

theorem c161 : certCheck 311 D ILN 161 k161 = true := by decide +kernel

def k162 : Cert :=
  Cert.G 1 [1] [244, 184, 69, 87, 274, 43, 178] [154, 177, 291, 170, 51, 143, 101, 132]

theorem c162 : certCheck 311 D ILN 162 k162 = true := by decide +kernel

def k163 : Cert :=
  Cert.G 1 [1, 111, 1] [60, 112, 117, 270, 273] [296, 94, 204, 168, 28, 299]

theorem c163 : certCheck 311 D ILN 163 k163 = true := by decide +kernel

def k164 : Cert :=
  Cert.G 1 [8, 139, 1] [93, 89, 299, 248, 138] [216, 109, 2, 51, 179, 155]

theorem c164 : certCheck 311 D ILN 164 k164 = true := by decide +kernel

def k165 : Cert :=
  Cert.G 1 [1] [149, 307, 85, 264, 77, 85, 185] [52, 167, 300, 295, 107, 124, 209, 187]

theorem c165 : certCheck 311 D ILN 165 k165 = true := by decide +kernel

def k166 : Cert :=
  Cert.G 1 [116, 296, 1] [136, 93, 267, 83, 294] [16, 253, 229, 271, 289, 291]

theorem c166 : certCheck 311 D ILN 166 k166 = true := by decide +kernel

def k167 : Cert :=
  Cert.G 1 [251, 230, 245, 1] [168, 182, 15, 218] [7, 151, 4, 175, 290]

theorem c167 : certCheck 311 D ILN 167 k167 = true := by decide +kernel

def k168 : Cert :=
  Cert.G 1 [190, 1] [151, 103, 260, 57, 281, 240] [71, 32, 182, 40, 300, 216, 117]

theorem c168 : certCheck 311 D ILN 168 k168 = true := by decide +kernel

def k169 : Cert :=
  Cert.G 1 [40, 1] [183, 98, 60, 221, 37, 303] [201, 4, 56, 26, 211, 82, 128]

theorem c169 : certCheck 311 D ILN 169 k169 = true := by decide +kernel

def k170 : Cert :=
  Cert.G 1 [1] [21, 227, 41, 125, 90, 99, 220] [218, 199, 5, 77, 280, 187, 289, 251]

theorem c170 : certCheck 311 D ILN 170 k170 = true := by decide +kernel

def k171 : Cert :=
  Cert.G 1 [1] [142, 104, 53, 174, 237, 17, 226] [118, 240, 116, 260, 13, 174, 186, 278]

theorem c171 : certCheck 311 D ILN 171 k171 = true := by decide +kernel

def k172 : Cert :=
  Cert.G 1 [1] [89, 284, 295, 210, 261, 50, 21] [255, 254, 111, 216, 284, 163, 239, 278]

theorem c172 : certCheck 311 D ILN 172 k172 = true := by decide +kernel

def k173 : Cert :=
  Cert.G 1 [22, 217, 1] [304, 294, 220, 32, 93] [67, 275, 294, 69, 277, 204]

theorem c173 : certCheck 311 D ILN 173 k173 = true := by decide +kernel

def k174 : Cert :=
  Cert.G 1 [252, 1] [254, 211, 284, 88, 224, 92] [34, 184, 286, 96, 254, 152, 178]

theorem c174 : certCheck 311 D ILN 174 k174 = true := by decide +kernel

def k175 : Cert :=
  Cert.G 1 [1] [104, 120, 23, 14, 281, 274, 141] [294, 87, 283, 246, 77, 95, 36, 18]

theorem c175 : certCheck 311 D ILN 175 k175 = true := by decide +kernel

def k176 : Cert :=
  Cert.G 1 [297, 277, 72, 1] [149, 14, 287, 270] [100, 256, 42, 261, 209]

theorem c176 : certCheck 311 D ILN 176 k176 = true := by decide +kernel

def k177 : Cert :=
  Cert.G 1 [283, 181, 1] [277, 139, 116, 224, 282] [175, 114, 103, 190, 274, 240]

theorem c177 : certCheck 311 D ILN 177 k177 = true := by decide +kernel

def k178 : Cert :=
  Cert.G 1 [1] [94, 77, 150, 73, 293, 228, 35] [250, 261, 250, 142, 85, 13, 25, 233]

theorem c178 : certCheck 311 D ILN 178 k178 = true := by decide +kernel

def k179 : Cert :=
  Cert.G 1 [70, 1] [190, 64, 227, 197, 284, 243] [145, 46, 226, 18, 251, 143, 306]

theorem c179 : certCheck 311 D ILN 179 k179 = true := by decide +kernel

def k180 : Cert :=
  Cert.G 1 [125, 207, 1] [190, 124, 291, 158, 247] [274, 305, 93, 137, 227, 216]

theorem c180 : certCheck 311 D ILN 180 k180 = true := by decide +kernel

def k181 : Cert :=
  Cert.G 1 [126, 303, 306, 1] [93, 105, 40, 303] [226, 2, 305, 84, 293]

theorem c181 : certCheck 311 D ILN 181 k181 = true := by decide +kernel

def k182 : Cert :=
  Cert.G 1 [176, 1] [18, 188, 155, 14, 177, 280] [240, 20, 192, 220, 284, 175, 92]

theorem c182 : certCheck 311 D ILN 182 k182 = true := by decide +kernel

def k183 : Cert :=
  Cert.G 1 [1] [150, 209, 105, 117, 143, 158, 278] [128, 31, 290, 183, 106, 289, 179, 251]

theorem c183 : certCheck 311 D ILN 183 k183 = true := by decide +kernel

def k184 : Cert :=
  Cert.G 1 [165, 1] [12, 128, 6, 37, 244, 129] [305, 242, 113, 140, 112, 45, 115]

theorem c184 : certCheck 311 D ILN 184 k184 = true := by decide +kernel

def k185 : Cert :=
  Cert.G 1 [1] [113, 176, 86, 54, 63, 272, 292] [205, 171, 76, 244, 156, 103, 152, 31]

theorem c185 : certCheck 311 D ILN 185 k185 = true := by decide +kernel

def k186 : Cert :=
  Cert.G 1 [194, 257, 1] [30, 286, 122, 148, 165] [210, 211, 306, 110, 214, 275]

theorem c186 : certCheck 311 D ILN 186 k186 = true := by decide +kernel

def k187 : Cert :=
  Cert.G 1 [280, 1] [304, 37, 223, 191, 197, 82] [97, 142, 119, 135, 163, 16, 231]

theorem c187 : certCheck 311 D ILN 187 k187 = true := by decide +kernel

def k188 : Cert :=
  Cert.G 1 [49, 196, 1] [241, 212, 289, 69, 206] [117, 279, 108, 289, 118, 88]

theorem c188 : certCheck 311 D ILN 188 k188 = true := by decide +kernel

def k189 : Cert :=
  Cert.G 1 [304, 269, 1] [285, 167, 73, 55, 245] [303, 72, 310, 195, 241, 125]

theorem c189 : certCheck 311 D ILN 189 k189 = true := by decide +kernel

def k190 : Cert :=
  Cert.G 1 [33, 1] [129, 26, 164, 140, 30, 83] [216, 247, 65, 42, 105, 221, 174]

theorem c190 : certCheck 311 D ILN 190 k190 = true := by decide +kernel

def k191 : Cert :=
  Cert.G 1 [59, 1] [156, 145, 53, 29, 25, 165] [27, 178, 58, 225, 21, 90, 236]

theorem c191 : certCheck 311 D ILN 191 k191 = true := by decide +kernel

def certs1 : List (ℕ × Cert) := [(125, k125), (126, k126), (127, k127), (128, k128), (129, k129), (130, k130), (131, k131), (132, k132), (133, k133), (134, k134), (135, k135), (136, k136), (137, k137), (138, k138), (139, k139), (140, k140), (141, k141), (142, k142), (143, k143), (144, k144), (145, k145), (146, k146), (147, k147), (148, k148), (149, k149), (150, k150), (151, k151), (152, k152), (153, k153), (154, k154), (155, k155), (156, k156), (157, k157), (158, k158), (159, k159), (160, k160), (161, k161), (162, k162), (163, k163), (164, k164), (165, k165), (166, k166), (167, k167), (168, k168), (169, k169), (170, k170), (171, k171), (172, k172), (173, k173), (174, k174), (175, k175), (176, k176), (177, k177), (178, k178), (179, k179), (180, k180), (181, k181), (182, k182), (183, k183), (184, k184), (185, k185), (186, k186), (187, k187), (188, k188), (189, k189), (190, k190), (191, k191)]

theorem ok1 : certs1.all (fun p => certCheck 311 D ILN p.1 p.2) = true := by
  simp only [certs1, List.all_cons, List.all_nil, c125, c126, c127, c128, c129, c130, c131, c132, c133, c134, c135, c136, c137, c138, c139, c140, c141, c142, c143, c144, c145, c146, c147, c148, c149, c150, c151, c152, c153, c154, c155, c156, c157, c158, c159, c160, c161, c162, c163, c164, c165, c166, c167, c168, c169, c170, c171, c172, c173, c174, c175, c176, c177, c178, c179, c180, c181, c182, c183, c184, c185, c186, c187, c188, c189, c190, c191, Bool.and_self]

end X2Y5Z7.SymbolSets.Q311
