/-
Generated by computer; every fact used is proved in Lean.
-/
import X2Y5Z7.SymbolSets.Q311.C1

/-! # Proposition 5.3 at `q = 311`: certificates for `η = 192 … 280` (0 R, 87 G, 2 F) -/

namespace X2Y5Z7.SymbolSets.Q311

open X2Y5Z7.SymbolSets

def k192 : Cert :=
  Cert.G 1 [263, 82, 67, 1] [226, 6, 136, 142] [227, 222, 93, 284, 59]

theorem c192 : certCheck 311 D ILN 192 k192 = true := by decide +kernel

def k193 : Cert :=
  Cert.G 1 [31, 92, 1] [127, 182, 174, 172, 50] [274, 266, 283, 165, 182, 54]

theorem c193 : certCheck 311 D ILN 193 k193 = true := by decide +kernel

def k194 : Cert :=
  Cert.G 1 [143, 1] [35, 59, 88, 309, 296, 167] [152, 265, 81, 165, 265, 249, 112]

theorem c194 : certCheck 311 D ILN 194 k194 = true := by decide +kernel

def k195 : Cert :=
  Cert.G 1 [113, 10, 1] [26, 148, 200, 286, 184] [187, 137, 68, 207, 25, 41]

theorem c195 : certCheck 311 D ILN 195 k195 = true := by decide +kernel

def k196 : Cert :=
  Cert.G 1 [1] [242, 209, 139, 166, 274, 218, 91] [169, 192, 293, 5, 123, 117, 240, 52]

theorem c196 : certCheck 311 D ILN 196 k196 = true := by decide +kernel

def k197 : Cert :=
  Cert.G 1 [28, 204, 1] [32, 21, 232, 217, 58] [282, 149, 249, 70, 17, 110]

theorem c197 : certCheck 311 D ILN 197 k197 = true := by decide +kernel

def k198 : Cert :=
  Cert.G 1 [1] [298, 257, 110, 187, 51, 247, 52] [105, 80, 233, 72, 15, 13, 268, 118]

theorem c198 : certCheck 311 D ILN 198 k198 = true := by decide +kernel

def k199 : Cert :=
  Cert.G 1 [195, 1] [293, 115, 242, 10, 132, 81] [150, 147, 127, 156, 310, 204, 249]

theorem c199 : certCheck 311 D ILN 199 k199 = true := by decide +kernel

def k200 : Cert :=
  Cert.G 1 [1] [87, 267, 6, 308, 47, 96, 214] [166, 208, 145, 158, 300, 32, 147, 134]

theorem c200 : certCheck 311 D ILN 200 k200 = true := by decide +kernel

def k201 : Cert :=
  Cert.G 1 [148, 162, 1] [25, 84, 161, 236, 21] [174, 42, 246, 110, 253, 190]

theorem c201 : certCheck 311 D ILN 201 k201 = true := by decide +kernel

def k202 : Cert :=
  Cert.G 1 [1] [110, 124, 271, 139, 35, 23, 241] [12, 28, 173, 300, 281, 5, 250, 228]

theorem c202 : certCheck 311 D ILN 202 k202 = true := by decide +kernel

def k203 : Cert :=
  Cert.G 1 [116, 4, 5, 1] [101, 20, 39, 109] [133, 279, 278, 82, 275]

theorem c203 : certCheck 311 D ILN 203 k203 = true := by decide +kernel

def k204 : Cert :=
  Cert.G 1 [1] [185, 176, 197, 172, 16, 88, 145] [272, 270, 221, 13, 197, 57, 265, 148]

theorem c204 : certCheck 311 D ILN 204 k204 = true := by decide +kernel

def k205 : Cert :=
  Cert.G 1 [29, 1] [247, 175, 273, 181, 88, 142] [251, 295, 112, 67, 41, 223, 114]

theorem c205 : certCheck 311 D ILN 205 k205 = true := by decide +kernel

def k206 : Cert :=
  Cert.G 1 [1] [177, 66, 261, 150, 192, 15, 245] [259, 189, 0, 19, 99, 194, 295, 61]

theorem c206 : certCheck 311 D ILN 206 k206 = true := by decide +kernel

def k207 : Cert :=
  Cert.G 1 [160, 235, 1] [188, 67, 228, 41, 21] [282, 46, 154, 200, 56, 95]

theorem c207 : certCheck 311 D ILN 207 k207 = true := by decide +kernel

def k208 : Cert :=
  Cert.F [([20, 1], []), ([61, 1], []), ([200, 1], []), ([300, 1], []), ([290, 231, 211, 104, 1], [(2, [37, 238, 70, 26])])]
      [[(0, [([291], [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([250], [4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([111], [4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (3, [([11], [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([291], [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0])]), (1, [([250], [0, 0, 4, 3, 0, 0, 0, 0, 0, 0, 0])]), (2, [([111], [0, 0, 4, 3, 0, 0, 0, 0, 0, 0, 0])]), (3, [([11], [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([291], [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0])]), (1, [([250], [0, 0, 0, 0, 4, 3, 0, 0, 0, 0, 0])]), (2, [([111], [0, 0, 0, 0, 4, 3, 0, 0, 0, 0, 0])]), (3, [([11], [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0])])],
       [(0, [([291], [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0])]), (1, [([250], [0, 0, 0, 0, 0, 0, 4, 3, 0, 0, 0])]), (2, [([111], [0, 0, 0, 0, 0, 0, 4, 3, 0, 0, 0])]), (3, [([11], [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0])])],
       [(4, [([242, 172, 114, 36], [0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0]), ([5, 168, 79, 157], [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1]), ([105, 266, 284, 168], [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1]), ([166, 16, 145, 261], [0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0])])]]

theorem c208 : certCheck 311 D ILN 208 k208 = true := by decide +kernel

def k209 : Cert :=
  Cert.G 1 [10, 1] [309, 217, 62, 191, 305, 100] [237, 117, 242, 253, 127, 132, 242]

theorem c209 : certCheck 311 D ILN 209 k209 = true := by decide +kernel

def k210 : Cert :=
  Cert.G 1 [1] [120, 4, 102, 158, 53, 49, 23] [50, 67, 297, 261, 97, 83, 128, 219]

theorem c210 : certCheck 311 D ILN 210 k210 = true := by decide +kernel

def k211 : Cert :=
  Cert.G 1 [1] [92, 142, 121, 110, 280, 118, 225] [209, 21, 25, 135, 277, 273, 47, 111]

theorem c211 : certCheck 311 D ILN 211 k211 = true := by decide +kernel

def k212 : Cert :=
  Cert.G 1 [253, 1] [68, 227, 2, 9, 93, 292] [146, 15, 261, 68, 75, 191, 86]

theorem c212 : certCheck 311 D ILN 212 k212 = true := by decide +kernel

def k213 : Cert :=
  Cert.G 1 [168, 1] [186, 135, 287, 75, 97, 160] [93, 133, 219, 134, 193, 284, 299]

theorem c213 : certCheck 311 D ILN 213 k213 = true := by decide +kernel

def k214 : Cert :=
  Cert.G 1 [30, 1] [47, 302, 275, 286, 262, 150] [87, 177, 10, 254, 294, 211, 306]

theorem c214 : certCheck 311 D ILN 214 k214 = true := by decide +kernel

def k215 : Cert :=
  Cert.G 1 [60, 1] [30, 76, 76, 197, 53, 93] [157, 91, 152, 89, 205, 222, 170]

theorem c215 : certCheck 311 D ILN 215 k215 = true := by decide +kernel

def k216 : Cert :=
  Cert.G 1 [305, 1] [43, 177, 154, 223, 262, 34] [140, 241, 170, 211, 28, 129, 209]

theorem c216 : certCheck 311 D ILN 216 k216 = true := by decide +kernel

def k217 : Cert :=
  Cert.G 1 [1] [270, 152, 53, 130, 235, 14, 199] [245, 105, 139, 120, 304, 59, 307, 8]

theorem c217 : certCheck 311 D ILN 217 k217 = true := by decide +kernel

def k218 : Cert :=
  Cert.G 1 [1] [28, 225, 199, 297, 275, 189, 142] [225, 301, 162, 190, 182, 53, 95, 224]

theorem c218 : certCheck 311 D ILN 218 k218 = true := by decide +kernel

def k219 : Cert :=
  Cert.G 1 [257, 257, 246, 1] [73, 274, 255, 265] [267, 266, 151, 127, 161]

theorem c219 : certCheck 311 D ILN 219 k219 = true := by decide +kernel

def k220 : Cert :=
  Cert.G 1 [160, 1] [98, 39, 48, 100, 44, 171] [73, 1, 201, 150, 57, 242, 39]

theorem c220 : certCheck 311 D ILN 220 k220 = true := by decide +kernel

def k221 : Cert :=
  Cert.G 1 [162, 1] [155, 279, 281, 201, 64, 67] [40, 307, 273, 180, 165, 70, 291]

theorem c221 : certCheck 311 D ILN 221 k221 = true := by decide +kernel

def k222 : Cert :=
  Cert.G 1 [306, 1] [15, 188, 124, 97, 264, 187] [168, 255, 64, 234, 304, 28, 113]

theorem c222 : certCheck 311 D ILN 222 k222 = true := by decide +kernel

def k223 : Cert :=
  Cert.G 1 [1] [102, 81, 152, 24, 21, 197, 1] [175, 277, 297, 180, 18, 142, 216, 262]

theorem c223 : certCheck 311 D ILN 223 k223 = true := by decide +kernel

def k224 : Cert :=
  Cert.G 1 [1] [39, 59, 192, 174, 194, 240, 173] [130, 217, 235, 92, 243, 172, 218, 21]

theorem c224 : certCheck 311 D ILN 224 k224 = true := by decide +kernel

def k225 : Cert :=
  Cert.G 1 [26, 176, 28, 1] [92, 121, 144, 255] [242, 187, 182, 168, 49]

theorem c225 : certCheck 311 D ILN 225 k225 = true := by decide +kernel

def k226 : Cert :=
  Cert.G 1 [220, 1] [271, 14, 180, 48, 114, 182] [156, 121, 2, 84, 205, 228, 278]

theorem c226 : certCheck 311 D ILN 226 k226 = true := by decide +kernel

def k227 : Cert :=
  Cert.F [([161, 1], []), ([209, 1], []), ([255, 1], []), ([279, 1], []), ([108, 135, 111, 92, 1], [(2, [68, 4, 118, 34])])]
      [[(0, [([150], [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([102], [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([56], [4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (3, [([32], [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([150], [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([102], [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0])]), (2, [([56], [0, 0, 4, 3, 0, 0, 0, 0, 0, 0, 0])]), (3, [([32], [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([150], [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0])]), (1, [([102], [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0])]), (2, [([56], [0, 0, 0, 0, 4, 3, 0, 0, 0, 0, 0])]), (3, [([32], [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0])])],
       [(0, [([150], [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0])]), (1, [([102], [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0])]), (2, [([56], [0, 0, 0, 0, 0, 0, 4, 3, 0, 0, 0])]), (3, [([32], [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0])])],
       [(4, [([188, 20, 294, 77], [0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 4]), ([241, 277, 163, 107], [0, 0, 0, 0, 0, 0, 0, 0, 1, 4, 3]), ([105, 251, 174, 211], [0, 0, 0, 0, 0, 0, 0, 0, 1, 4, 3]), ([307, 74, 302, 227], [0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 4])])]]

theorem c227 : certCheck 311 D ILN 227 k227 = true := by decide +kernel

def k228 : Cert :=
  Cert.G 1 [1] [69, 308, 165, 255, 205, 25, 111] [226, 155, 156, 221, 168, 56, 254, 306]

theorem c228 : certCheck 311 D ILN 228 k228 = true := by decide +kernel

def k229 : Cert :=
  Cert.G 1 [80, 1] [250, 75, 107, 239, 59, 69] [269, 258, 205, 197, 109, 147, 40]

theorem c229 : certCheck 311 D ILN 229 k229 = true := by decide +kernel

def k230 : Cert :=
  Cert.G 1 [13, 82, 1] [284, 121, 124, 229, 87] [160, 274, 208, 206, 97, 142]

theorem c230 : certCheck 311 D ILN 230 k230 = true := by decide +kernel

def k231 : Cert :=
  Cert.G 1 [164, 1] [248, 181, 212, 131, 202, 290] [88, 282, 3, 49, 287, 39, 173]

theorem c231 : certCheck 311 D ILN 231 k231 = true := by decide +kernel

def k232 : Cert :=
  Cert.G 1 [156, 1] [93, 150, 251, 265, 302, 267] [269, 200, 33, 250, 71, 16, 225]

theorem c232 : certCheck 311 D ILN 232 k232 = true := by decide +kernel

def k233 : Cert :=
  Cert.G 1 [308, 1] [19, 220, 273, 184, 73, 170] [96, 147, 147, 251, 307, 9, 253]

theorem c233 : certCheck 311 D ILN 233 k233 = true := by decide +kernel

def k234 : Cert :=
  Cert.G 1 [13, 1] [158, 70, 123, 77, 205, 212] [68, 288, 301, 169, 293, 93, 254]

theorem c234 : certCheck 311 D ILN 234 k234 = true := by decide +kernel

def k235 : Cert :=
  Cert.G 1 [1] [87, 231, 20, 200, 295, 168, 41] [163, 230, 123, 181, 251, 145, 164, 97]

theorem c235 : certCheck 311 D ILN 235 k235 = true := by decide +kernel

def k236 : Cert :=
  Cert.G 1 [225, 1] [180, 285, 271, 203, 307, 89] [17, 298, 221, 188, 267, 84, 115]

theorem c236 : certCheck 311 D ILN 236 k236 = true := by decide +kernel

def k237 : Cert :=
  Cert.G 1 [232, 153, 1] [228, 20, 275, 190, 72] [309, 166, 1, 143, 64, 99]

theorem c237 : certCheck 311 D ILN 237 k237 = true := by decide +kernel

def k238 : Cert :=
  Cert.G 1 [250, 1] [109, 256, 90, 238, 197, 61] [272, 78, 185, 31, 93, 184, 110]

theorem c238 : certCheck 311 D ILN 238 k238 = true := by decide +kernel

def k239 : Cert :=
  Cert.G 1 [293, 1] [83, 140, 188, 202, 162, 232] [56, 65, 99, 176, 17, 210, 135]

theorem c239 : certCheck 311 D ILN 239 k239 = true := by decide +kernel

def k240 : Cert :=
  Cert.G 1 [114, 1] [268, 123, 134, 95, 167, 19] [282, 0, 172, 252, 95, 42, 6]

theorem c240 : certCheck 311 D ILN 240 k240 = true := by decide +kernel

def k241 : Cert :=
  Cert.G 1 [169, 1] [9, 44, 8, 158, 163, 182] [57, 66, 272, 66, 219, 110, 43]

theorem c241 : certCheck 311 D ILN 241 k241 = true := by decide +kernel

def k242 : Cert :=
  Cert.G 1 [1] [291, 254, 231, 91, 304, 206, 287] [219, 33, 1, 275, 268, 190, 254, 291]

theorem c242 : certCheck 311 D ILN 242 k242 = true := by decide +kernel

def k243 : Cert :=
  Cert.G 1 [1] [259, 85, 291, 265, 307, 69, 223] [110, 248, 203, 38, 218, 100, 109, 223]

theorem c243 : certCheck 311 D ILN 243 k243 = true := by decide +kernel

def k244 : Cert :=
  Cert.G 1 [25, 1] [16, 175, 98, 171, 194, 265] [279, 107, 257, 294, 225, 9, 44]

theorem c244 : certCheck 311 D ILN 244 k244 = true := by decide +kernel

def k245 : Cert :=
  Cert.G 1 [1] [120, 109, 268, 310, 144, 73, 192] [255, 231, 96, 12, 137, 59, 101, 165]

theorem c245 : certCheck 311 D ILN 245 k245 = true := by decide +kernel

def k246 : Cert :=
  Cert.G 1 [133, 1] [50, 133, 221, 276, 192, 184] [52, 92, 88, 290, 37, 277, 72]

theorem c246 : certCheck 311 D ILN 246 k246 = true := by decide +kernel

def k247 : Cert :=
  Cert.G 1 [1] [301, 168, 66, 8, 35, 288, 228] [51, 38, 37, 171, 30, 294, 129, 14]

theorem c247 : certCheck 311 D ILN 247 k247 = true := by decide +kernel

def k248 : Cert :=
  Cert.G 1 [204, 1] [147, 159, 76, 11, 12, 114] [138, 289, 77, 98, 185, 249, 240]

theorem c248 : certCheck 311 D ILN 248 k248 = true := by decide +kernel

def k249 : Cert :=
  Cert.G 1 [115, 1] [185, 308, 225, 72, 305, 13] [24, 200, 30, 196, 53, 309, 162]

theorem c249 : certCheck 311 D ILN 249 k249 = true := by decide +kernel

def k250 : Cert :=
  Cert.G 1 [1] [86, 101, 268, 10, 78, 220, 90] [129, 9, 23, 178, 124, 59, 199, 182]

theorem c250 : certCheck 311 D ILN 250 k250 = true := by decide +kernel

def k251 : Cert :=
  Cert.G 1 [142, 1] [297, 22, 151, 176, 52, 239] [217, 50, 189, 246, 119, 15, 150]

theorem c251 : certCheck 311 D ILN 251 k251 = true := by decide +kernel

def k252 : Cert :=
  Cert.G 1 [146, 140, 1] [218, 244, 56, 32, 53] [61, 247, 263, 113, 251, 151]

theorem c252 : certCheck 311 D ILN 252 k252 = true := by decide +kernel

def k253 : Cert :=
  Cert.G 1 [1] [275, 240, 159, 285, 223, 197, 149] [233, 190, 129, 101, 85, 191, 292, 254]

theorem c253 : certCheck 311 D ILN 253 k253 = true := by decide +kernel

def k254 : Cert :=
  Cert.G 1 [1] [234, 215, 119, 176, 276, 226, 110] [57, 250, 274, 36, 3, 68, 221, 10]

theorem c254 : certCheck 311 D ILN 254 k254 = true := by decide +kernel

def k255 : Cert :=
  Cert.G 1 [164, 164, 196, 1] [10, 85, 244, 63] [264, 166, 203, 93, 188]

theorem c255 : certCheck 311 D ILN 255 k255 = true := by decide +kernel

def k256 : Cert :=
  Cert.G 1 [1] [305, 31, 47, 121, 140, 25, 52] [57, 310, 239, 219, 45, 120, 103, 306]

theorem c256 : certCheck 311 D ILN 256 k256 = true := by decide +kernel

def k257 : Cert :=
  Cert.G 1 [1] [98, 281, 23, 39, 309, 188, 35] [263, 185, 145, 103, 238, 110, 203, 222]

theorem c257 : certCheck 311 D ILN 257 k257 = true := by decide +kernel

def k258 : Cert :=
  Cert.G 1 [148, 1] [52, 14, 141, 29, 26, 252] [114, 89, 237, 255, 103, 243, 221]

theorem c258 : certCheck 311 D ILN 258 k258 = true := by decide +kernel

def k259 : Cert :=
  Cert.G 1 [1] [148, 185, 100, 117, 277, 147, 1] [144, 79, 196, 249, 232, 162, 131, 106]

theorem c259 : certCheck 311 D ILN 259 k259 = true := by decide +kernel

def k260 : Cert :=
  Cert.G 1 [175, 1] [0, 25, 239, 28, 63, 304] [245, 58, 238, 202, 112, 94, 306]

theorem c260 : certCheck 311 D ILN 260 k260 = true := by decide +kernel

def k261 : Cert :=
  Cert.G 1 [65, 1] [155, 278, 239, 187, 86, 209] [299, 222, 140, 128, 102, 278, 59]

theorem c261 : certCheck 311 D ILN 261 k261 = true := by decide +kernel

def k262 : Cert :=
  Cert.G 1 [1] [124, 119, 26, 206, 154, 230, 203] [43, 224, 123, 31, 151, 106, 252, 28]

theorem c262 : certCheck 311 D ILN 262 k262 = true := by decide +kernel

def k263 : Cert :=
  Cert.G 1 [1] [200, 308, 266, 189, 62, 232, 252] [286, 202, 133, 205, 143, 164, 296, 40]

theorem c263 : certCheck 311 D ILN 263 k263 = true := by decide +kernel

def k264 : Cert :=
  Cert.G 1 [1] [111, 23, 246, 229, 226, 13, 184] [44, 225, 151, 53, 275, 181, 274, 113]

theorem c264 : certCheck 311 D ILN 264 k264 = true := by decide +kernel

def k265 : Cert :=
  Cert.G 1 [1] [96, 98, 257, 109, 11, 153, 12] [77, 208, 216, 285, 223, 310, 102, 138]

theorem c265 : certCheck 311 D ILN 265 k265 = true := by decide +kernel

def k266 : Cert :=
  Cert.G 1 [277, 1] [130, 131, 76, 160, 5, 54] [94, 269, 128, 126, 126, 122, 16]

theorem c266 : certCheck 311 D ILN 266 k266 = true := by decide +kernel

def k267 : Cert :=
  Cert.G 1 [47, 1] [58, 167, 118, 129, 26, 187] [215, 169, 243, 199, 159, 107, 282]

theorem c267 : certCheck 311 D ILN 267 k267 = true := by decide +kernel

def k268 : Cert :=
  Cert.G 1 [94, 1] [9, 45, 266, 285, 144, 269] [243, 185, 281, 192, 58, 170, 127]

theorem c268 : certCheck 311 D ILN 268 k268 = true := by decide +kernel

def k269 : Cert :=
  Cert.G 1 [292, 1] [263, 246, 210, 224, 113, 299] [180, 204, 95, 142, 87, 138, 51]

theorem c269 : certCheck 311 D ILN 269 k269 = true := by decide +kernel

def k270 : Cert :=
  Cert.G 1 [91, 1] [97, 139, 28, 286, 45, 21] [103, 220, 260, 224, 187, 13, 245]

theorem c270 : certCheck 311 D ILN 270 k270 = true := by decide +kernel

def k271 : Cert :=
  Cert.G 1 [284, 36, 1] [229, 302, 7, 196, 81] [241, 197, 269, 242, 118, 178]

theorem c271 : certCheck 311 D ILN 271 k271 = true := by decide +kernel

def k272 : Cert :=
  Cert.G 1 [257, 1] [138, 308, 16, 2, 232, 85] [286, 83, 280, 138, 273, 18, 184]

theorem c272 : certCheck 311 D ILN 272 k272 = true := by decide +kernel

def k273 : Cert :=
  Cert.G 1 [1] [297, 79, 297, 6, 190, 115, 302] [128, 58, 217, 37, 25, 111, 190, 107]

theorem c273 : certCheck 311 D ILN 273 k273 = true := by decide +kernel

def k274 : Cert :=
  Cert.G 1 [87, 1] [260, 217, 273, 63, 80, 146] [252, 289, 169, 274, 68, 309, 216]

theorem c274 : certCheck 311 D ILN 274 k274 = true := by decide +kernel

def k275 : Cert :=
  Cert.G 1 [1] [306, 275, 138, 301, 249, 40, 261] [161, 243, 174, 204, 279, 172, 39, 207]

theorem c275 : certCheck 311 D ILN 275 k275 = true := by decide +kernel

def k276 : Cert :=
  Cert.G 1 [290, 296, 154, 1] [246, 8, 279, 2] [71, 176, 161, 9, 206]

theorem c276 : certCheck 311 D ILN 276 k276 = true := by decide +kernel

def k277 : Cert :=
  Cert.G 1 [1] [289, 225, 141, 5, 98, 290, 89] [172, 10, 164, 276, 126, 111, 170, 47]

theorem c277 : certCheck 311 D ILN 277 k277 = true := by decide +kernel

def k278 : Cert :=
  Cert.G 1 [289, 28, 1] [58, 24, 90, 142, 98] [145, 99, 140, 261, 133, 310]

theorem c278 : certCheck 311 D ILN 278 k278 = true := by decide +kernel

def k279 : Cert :=
  Cert.G 1 [198, 172, 1] [308, 206, 290, 147, 194] [154, 258, 198, 250, 288, 72]

theorem c279 : certCheck 311 D ILN 279 k279 = true := by decide +kernel

def k280 : Cert :=
  Cert.G 1 [199, 256, 1] [139, 272, 80, 248, 179] [269, 282, 30, 218, 47, 268]

theorem c280 : certCheck 311 D ILN 280 k280 = true := by decide +kernel

def certs2 : List (ℕ × Cert) := [(192, k192), (193, k193), (194, k194), (195, k195), (196, k196), (197, k197), (198, k198), (199, k199), (200, k200), (201, k201), (202, k202), (203, k203), (204, k204), (205, k205), (206, k206), (207, k207), (208, k208), (209, k209), (210, k210), (211, k211), (212, k212), (213, k213), (214, k214), (215, k215), (216, k216), (217, k217), (218, k218), (219, k219), (220, k220), (221, k221), (222, k222), (223, k223), (224, k224), (225, k225), (226, k226), (227, k227), (228, k228), (229, k229), (230, k230), (231, k231), (232, k232), (233, k233), (234, k234), (235, k235), (236, k236), (237, k237), (238, k238), (239, k239), (240, k240), (241, k241), (242, k242), (243, k243), (244, k244), (245, k245), (246, k246), (247, k247), (248, k248), (249, k249), (250, k250), (251, k251), (252, k252), (253, k253), (254, k254), (255, k255), (256, k256), (257, k257), (258, k258), (259, k259), (260, k260), (261, k261), (262, k262), (263, k263), (264, k264), (265, k265), (266, k266), (267, k267), (268, k268), (269, k269), (270, k270), (271, k271), (272, k272), (273, k273), (274, k274), (275, k275), (276, k276), (277, k277), (278, k278), (279, k279), (280, k280)]

theorem ok2 : certs2.all (fun p => certCheck 311 D ILN p.1 p.2) = true := by
  simp only [certs2, List.all_cons, List.all_nil, c192, c193, c194, c195, c196, c197, c198, c199, c200, c201, c202, c203, c204, c205, c206, c207, c208, c209, c210, c211, c212, c213, c214, c215, c216, c217, c218, c219, c220, c221, c222, c223, c224, c225, c226, c227, c228, c229, c230, c231, c232, c233, c234, c235, c236, c237, c238, c239, c240, c241, c242, c243, c244, c245, c246, c247, c248, c249, c250, c251, c252, c253, c254, c255, c256, c257, c258, c259, c260, c261, c262, c263, c264, c265, c266, c267, c268, c269, c270, c271, c272, c273, c274, c275, c276, c277, c278, c279, c280, Bool.and_self]

end X2Y5Z7.SymbolSets.Q311
