/-
Generated by computer; every fact used is proved in Lean.
-/
module

public import X2Y5Z7.SymbolSets.Q311.C2

@[expose] public section

/-! # Proposition 5.3 at `q = 311`: certificates for `η = 281 … 310` (0 R, 29 G, 1 F) -/

namespace X2Y5Z7.SymbolSets.Q311

open X2Y5Z7.SymbolSets

def k281 : Cert :=
  Cert.G 1 [1] [291, 64, 251, 55, 171, 133, 182] [81, 305, 226, 249, 75, 239, 38, 185]

theorem c281 : certCheck 311 D ILN 281 k281 = true := by decide +kernel

def k282 : Cert :=
  Cert.G 1 [1] [300, 93, 178, 27, 76, 76, 209] [213, 199, 93, 118, 35, 190, 304, 37]

theorem c282 : certCheck 311 D ILN 282 k282 = true := by decide +kernel

def k283 : Cert :=
  Cert.G 1 [31, 119, 1] [132, 224, 79, 51, 264] [119, 187, 4, 310, 202, 213]

theorem c283 : certCheck 311 D ILN 283 k283 = true := by decide +kernel

def k284 : Cert :=
  Cert.G 1 [180, 224, 1] [292, 247, 12, 229, 300] [227, 36, 281, 58, 195, 197]

theorem c284 : certCheck 311 D ILN 284 k284 = true := by decide +kernel

def k285 : Cert :=
  Cert.G 1 [43, 1] [104, 134, 243, 35, 307, 274] [13, 14, 61, 110, 135, 145, 11]

theorem c285 : certCheck 311 D ILN 285 k285 = true := by decide +kernel

def k286 : Cert :=
  Cert.G 1 [297, 1] [47, 3, 1, 120, 79, 45] [250, 10, 18, 226, 24, 137, 249]

theorem c286 : certCheck 311 D ILN 286 k286 = true := by decide +kernel

def k287 : Cert :=
  Cert.G 1 [98, 133, 1] [3, 37, 46, 216, 20] [70, 148, 285, 9, 235, 304]

theorem c287 : certCheck 311 D ILN 287 k287 = true := by decide +kernel

def k288 : Cert :=
  Cert.G 1 [187, 1] [193, 204, 252, 17, 247, 54] [24, 230, 12, 85, 73, 275, 99]

theorem c288 : certCheck 311 D ILN 288 k288 = true := by decide +kernel

def k289 : Cert :=
  Cert.G 1 [1] [146, 180, 218, 176, 223, 216, 120] [218, 38, 168, 26, 235, 112, 80, 228]

theorem c289 : certCheck 311 D ILN 289 k289 = true := by decide +kernel

def k290 : Cert :=
  Cert.G 1 [137, 170, 112, 1] [128, 283, 216, 136] [133, 212, 175, 30, 222]

theorem c290 : certCheck 311 D ILN 290 k290 = true := by decide +kernel

def k291 : Cert :=
  Cert.G 1 [1] [120, 73, 61, 130, 268, 58, 31] [71, 223, 231, 274, 246, 234, 267, 17]

theorem c291 : certCheck 311 D ILN 291 k291 = true := by decide +kernel

def k292 : Cert :=
  Cert.G 1 [1] [234, 275, 6, 41, 160, 4, 55] [218, 271, 77, 166, 214, 173, 139, 258]

theorem c292 : certCheck 311 D ILN 292 k292 = true := by decide +kernel

def k293 : Cert :=
  Cert.G 1 [169, 187, 1] [261, 77, 265, 176, 30] [257, 21, 135, 69, 210, 139]

theorem c293 : certCheck 311 D ILN 293 k293 = true := by decide +kernel

def k294 : Cert :=
  Cert.G 1 [278, 1] [229, 160, 216, 249, 282, 57] [198, 103, 72, 293, 139, 117, 14]

theorem c294 : certCheck 311 D ILN 294 k294 = true := by decide +kernel

def k295 : Cert :=
  Cert.G 1 [285, 166, 1] [232, 110, 127, 213, 280] [282, 46, 135, 150, 271, 63]

theorem c295 : certCheck 311 D ILN 295 k295 = true := by decide +kernel

def k296 : Cert :=
  Cert.G 1 [215, 228, 103, 1] [56, 128, 160, 293] [284, 78, 221, 273, 143]

theorem c296 : certCheck 311 D ILN 296 k296 = true := by decide +kernel

def k297 : Cert :=
  Cert.F [([3, 1], []), ([159, 1], []), ([178, 1], []), ([259, 1], []), ([162, 101, 310, 86, 1], [(2, [270, 282, 73, 15])])]
      [[(0, [([308], [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (1, [([152], [3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (2, [([133], [4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0])]), (3, [([52], [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([308], [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0])]), (1, [([152], [0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0])]), (2, [([133], [0, 0, 4, 3, 0, 0, 0, 0, 0, 0, 0])]), (3, [([52], [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([308], [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0])]), (1, [([152], [0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0])]), (2, [([133], [0, 0, 0, 0, 4, 3, 0, 0, 0, 0, 0])]), (3, [([52], [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0])])],
       [(0, [([308], [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0])]), (1, [([152], [0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0])]), (2, [([133], [0, 0, 0, 0, 0, 0, 4, 3, 0, 0, 0])]), (3, [([52], [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0])])],
       [(4, [([95, 248, 18, 10], [0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0]), ([215, 166, 88, 32], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]), ([73, 252, 115, 277], [0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0]), ([153, 267, 90, 303], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3])])]]

theorem c297 : certCheck 311 D ILN 297 k297 = true := by decide +kernel

def k298 : Cert :=
  Cert.G 1 [237, 1] [19, 40, 69, 196, 160, 280] [229, 201, 34, 50, 281, 157, 66]

theorem c298 : certCheck 311 D ILN 298 k298 = true := by decide +kernel

def k299 : Cert :=
  Cert.G 1 [1] [116, 162, 302, 218, 292, 153, 103] [300, 103, 229, 15, 116, 62, 272, 64]

theorem c299 : certCheck 311 D ILN 299 k299 = true := by decide +kernel

def k300 : Cert :=
  Cert.G 1 [1] [218, 164, 72, 25, 22, 207, 242] [252, 84, 3, 0, 176, 205, 215, 29]

theorem c300 : certCheck 311 D ILN 300 k300 = true := by decide +kernel

def k301 : Cert :=
  Cert.G 1 [218, 1] [103, 237, 143, 156, 247, 180] [15, 2, 19, 54, 192, 259, 116]

theorem c301 : certCheck 311 D ILN 301 k301 = true := by decide +kernel

def k302 : Cert :=
  Cert.G 1 [46, 105, 1] [218, 206, 213, 247, 128] [205, 0, 148, 208, 156, 34]

theorem c302 : certCheck 311 D ILN 302 k302 = true := by decide +kernel

def k303 : Cert :=
  Cert.G 1 [1] [35, 197, 156, 139, 115, 135, 36] [114, 159, 253, 224, 31, 147, 112, 237]

theorem c303 : certCheck 311 D ILN 303 k303 = true := by decide +kernel

def k304 : Cert :=
  Cert.G 1 [65, 125, 204, 1] [303, 215, 0, 160] [262, 99, 106, 164, 2]

theorem c304 : certCheck 311 D ILN 304 k304 = true := by decide +kernel

def k305 : Cert :=
  Cert.G 1 [272, 1] [163, 217, 50, 193, 264, 217] [97, 310, 102, 3, 65, 308, 123]

theorem c305 : certCheck 311 D ILN 305 k305 = true := by decide +kernel

def k306 : Cert :=
  Cert.G 1 [1] [162, 255, 309, 303, 222, 152, 160] [286, 238, 139, 223, 192, 301, 252, 34]

theorem c306 : certCheck 311 D ILN 306 k306 = true := by decide +kernel

def k307 : Cert :=
  Cert.G 1 [1, 1] [41, 203, 125, 141, 138, 136] [118, 109, 190, 114, 137, 100, 74]

theorem c307 : certCheck 311 D ILN 307 k307 = true := by decide +kernel

def k308 : Cert :=
  Cert.G 1 [105, 159, 1] [307, 63, 42, 127, 67] [125, 252, 246, 54, 286, 69]

theorem c308 : certCheck 311 D ILN 308 k308 = true := by decide +kernel

def k309 : Cert :=
  Cert.G 1 [264, 128, 125, 1] [197, 217, 139, 40] [198, 189, 263, 170, 76]

theorem c309 : certCheck 311 D ILN 309 k309 = true := by decide +kernel

def k310 : Cert :=
  Cert.G 1 [1] [222, 272, 140, 94, 106, 41, 210] [93, 282, 155, 91, 47, 267, 280, 37]

theorem c310 : certCheck 311 D ILN 310 k310 = true := by decide +kernel

def certs3 : List (ℕ × Cert) := [(281, k281), (282, k282), (283, k283), (284, k284), (285, k285), (286, k286), (287, k287), (288, k288), (289, k289), (290, k290), (291, k291), (292, k292), (293, k293), (294, k294), (295, k295), (296, k296), (297, k297), (298, k298), (299, k299), (300, k300), (301, k301), (302, k302), (303, k303), (304, k304), (305, k305), (306, k306), (307, k307), (308, k308), (309, k309), (310, k310)]

theorem ok3 : certs3.all (fun p => certCheck 311 D ILN p.1 p.2) = true := by
  simp only [certs3, List.all_cons, List.all_nil, c281, c282, c283, c284, c285, c286, c287, c288, c289, c290, c291, c292, c293, c294, c295, c296, c297, c298, c299, c300, c301, c302, c303, c304, c305, c306, c307, c308, c309, c310, Bool.and_self]

end X2Y5Z7.SymbolSets.Q311
