/-
Generated by computer; every fact used is proved in Lean.
-/
module

public import X2Y5Z7.SymbolSets.Q311.C3
public import X2Y5Z7.SymbolSets.Compat
public import X2Y5Z7.FiniteFields.Q311
public import X2Y5Z7.SymbolSets.Sets

@[expose] public section

/-! # Proposition 5.3 at `q = 311`

Proposition 5.3: for every `η ∈ F_311 ∖ {0, 1}` and every admissible family `t_i ∈ k_i = (L8P i).K` (roots of
`fb η t = 100t⁸ + 80t⁷ + 56t⁶ + 56t⁵ - 4ηt + η`, `deg minpoly t_i = d_i`, distinct minimal polynomials for primes of
the same degree), the elements `E_k = Ev<k> t_(i_k)` (`= 80000 (ι_k t - β_k) ψ(ι_k t)³`) are nonzero and the vector of
their symbols `(L24P k).sym` lies in `SymbolSets.I311`. Here `ι<k> : (L8P i_k).K →+* (L24P k).K` sends `x ↦ α_k`, and
`ι<k>_res` is its compatibility with the residue maps of `X2Y5Z7/FiniteFields/Residue.lean`. -/

namespace X2Y5Z7.SymbolSets.Q311

open X2Y5Z7.SymbolSets X2Y5Z7.FiniteFields X2Y5Z7.FiniteFields.Q311 Polynomial NumberField

noncomputable instance instAlgL8P0 : Algebra (ZMod 311) L8P0.K := inferInstanceAs (Algebra (ZMod 311) (AdjoinRoot (toPoly 311 (D.H 0))))
noncomputable instance instAlgL8P1 : Algebra (ZMod 311) L8P1.K := inferInstanceAs (Algebra (ZMod 311) (AdjoinRoot (toPoly 311 (D.H 1))))
noncomputable instance instAlgL8P2 : Algebra (ZMod 311) L8P2.K := inferInstanceAs (Algebra (ZMod 311) (AdjoinRoot (toPoly 311 (D.H 2))))
noncomputable instance instAlgL8P3 : Algebra (ZMod 311) L8P3.K := inferInstanceAs (Algebra (ZMod 311) (AdjoinRoot (toPoly 311 (D.H 3))))
noncomputable instance instAlgL8P4 : Algebra (ZMod 311) L8P4.K := inferInstanceAs (Algebra (ZMod 311) (AdjoinRoot (toPoly 311 (D.H 4))))

instance factH (i : Fin 5) : Fact (Irreducible (toPoly 311 (D.H i))) := ⟨by
  fin_cases i
  · exact L8P0.irred
  · exact L8P1.irred
  · exact L8P2.irred
  · exact L8P3.irred
  · exact L8P4.irred⟩

instance factP (k : Fin 11) : Fact (Irreducible (toPoly 311 (D.P k))) := ⟨by
  fin_cases k
  · exact L24P0.irred
  · exact L24P1.irred
  · exact L24P2.irred
  · exact L24P3.irred
  · exact L24P4.irred
  · exact L24P5.irred
  · exact L24P6.irred
  · exact L24P7.irred
  · exact L24P8.irred
  · exact L24P9.irred
  · exact L24P10.irred⟩

def certs : List (ℕ × Cert) := certs0 ++ certs1 ++ certs2 ++ certs3

theorem certsOK : certs.all (fun p => certCheck 311 D ILN p.1 p.2) = true := by
  simp only [certs, List.all_append, ok0, ok1, ok2, ok3, Bool.and_self]

theorem covOK (e : ℕ) (h2 : 2 ≤ e) (hq : e < 311) : e ∈ certs.map Prod.fst := by
  have h : certs.map Prod.fst = List.range' 2 309 := by decide +kernel
  rw [h, List.mem_range'_1]; omega

theorem ilOK : ilCheck 11 ILN SymbolSets.I311L = true := by decide +kernel

/-- `ι_0 : k_0 → K_0`, `x ↦ α`. -/
noncomputable def ι0 : L8P0.K →+* L24P0.K := iotaD 311 D dataOK 0

theorem ι0_x : ι0 L8P0.x = L24P0.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 311 D dataOK 0

theorem ι0_res (y : 𝓞 L8) : ι0 (L8P0.res y) = L24P0.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P0 L24P0 ι0 ι0_x y

/-- `E_0(t) = 80000 (ι_0 t - β) (25 (ι_0 t)³ + 20 (ι_0 t)² + 14 ι_0 t + 14)³`. -/
noncomputable def Ev0 (t : L8P0.K) : L24P0.K := EvD 311 D dataOK 0 t

theorem Ev0_eq (t : L8P0.K) : Ev0 t =
    80000 * (ι0 t - L24P0.β) * (25 * ι0 t ^ 3 + 20 * ι0 t ^ 2 + 14 * ι0 t + 14) ^ 3 := rfl

/-- `ι_1 : k_0 → K_1`, `x ↦ α`. -/
noncomputable def ι1 : L8P0.K →+* L24P1.K := iotaD 311 D dataOK 1

theorem ι1_x : ι1 L8P0.x = L24P1.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 311 D dataOK 1

theorem ι1_res (y : 𝓞 L8) : ι1 (L8P0.res y) = L24P1.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P0 L24P1 ι1 ι1_x y

/-- `E_1(t) = 80000 (ι_1 t - β) (25 (ι_1 t)³ + 20 (ι_1 t)² + 14 ι_1 t + 14)³`. -/
noncomputable def Ev1 (t : L8P0.K) : L24P1.K := EvD 311 D dataOK 1 t

theorem Ev1_eq (t : L8P0.K) : Ev1 t =
    80000 * (ι1 t - L24P1.β) * (25 * ι1 t ^ 3 + 20 * ι1 t ^ 2 + 14 * ι1 t + 14) ^ 3 := rfl

/-- `ι_2 : k_1 → K_2`, `x ↦ α`. -/
noncomputable def ι2 : L8P1.K →+* L24P2.K := iotaD 311 D dataOK 2

theorem ι2_x : ι2 L8P1.x = L24P2.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 311 D dataOK 2

theorem ι2_res (y : 𝓞 L8) : ι2 (L8P1.res y) = L24P2.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P1 L24P2 ι2 ι2_x y

/-- `E_2(t) = 80000 (ι_2 t - β) (25 (ι_2 t)³ + 20 (ι_2 t)² + 14 ι_2 t + 14)³`. -/
noncomputable def Ev2 (t : L8P1.K) : L24P2.K := EvD 311 D dataOK 2 t

theorem Ev2_eq (t : L8P1.K) : Ev2 t =
    80000 * (ι2 t - L24P2.β) * (25 * ι2 t ^ 3 + 20 * ι2 t ^ 2 + 14 * ι2 t + 14) ^ 3 := rfl

/-- `ι_3 : k_1 → K_3`, `x ↦ α`. -/
noncomputable def ι3 : L8P1.K →+* L24P3.K := iotaD 311 D dataOK 3

theorem ι3_x : ι3 L8P1.x = L24P3.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 311 D dataOK 3

theorem ι3_res (y : 𝓞 L8) : ι3 (L8P1.res y) = L24P3.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P1 L24P3 ι3 ι3_x y

/-- `E_3(t) = 80000 (ι_3 t - β) (25 (ι_3 t)³ + 20 (ι_3 t)² + 14 ι_3 t + 14)³`. -/
noncomputable def Ev3 (t : L8P1.K) : L24P3.K := EvD 311 D dataOK 3 t

theorem Ev3_eq (t : L8P1.K) : Ev3 t =
    80000 * (ι3 t - L24P3.β) * (25 * ι3 t ^ 3 + 20 * ι3 t ^ 2 + 14 * ι3 t + 14) ^ 3 := rfl

/-- `ι_4 : k_2 → K_4`, `x ↦ α`. -/
noncomputable def ι4 : L8P2.K →+* L24P4.K := iotaD 311 D dataOK 4

theorem ι4_x : ι4 L8P2.x = L24P4.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 311 D dataOK 4

theorem ι4_res (y : 𝓞 L8) : ι4 (L8P2.res y) = L24P4.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P2 L24P4 ι4 ι4_x y

/-- `E_4(t) = 80000 (ι_4 t - β) (25 (ι_4 t)³ + 20 (ι_4 t)² + 14 ι_4 t + 14)³`. -/
noncomputable def Ev4 (t : L8P2.K) : L24P4.K := EvD 311 D dataOK 4 t

theorem Ev4_eq (t : L8P2.K) : Ev4 t =
    80000 * (ι4 t - L24P4.β) * (25 * ι4 t ^ 3 + 20 * ι4 t ^ 2 + 14 * ι4 t + 14) ^ 3 := rfl

/-- `ι_5 : k_2 → K_5`, `x ↦ α`. -/
noncomputable def ι5 : L8P2.K →+* L24P5.K := iotaD 311 D dataOK 5

theorem ι5_x : ι5 L8P2.x = L24P5.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 311 D dataOK 5

theorem ι5_res (y : 𝓞 L8) : ι5 (L8P2.res y) = L24P5.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P2 L24P5 ι5 ι5_x y

/-- `E_5(t) = 80000 (ι_5 t - β) (25 (ι_5 t)³ + 20 (ι_5 t)² + 14 ι_5 t + 14)³`. -/
noncomputable def Ev5 (t : L8P2.K) : L24P5.K := EvD 311 D dataOK 5 t

theorem Ev5_eq (t : L8P2.K) : Ev5 t =
    80000 * (ι5 t - L24P5.β) * (25 * ι5 t ^ 3 + 20 * ι5 t ^ 2 + 14 * ι5 t + 14) ^ 3 := rfl

/-- `ι_6 : k_3 → K_6`, `x ↦ α`. -/
noncomputable def ι6 : L8P3.K →+* L24P6.K := iotaD 311 D dataOK 6

theorem ι6_x : ι6 L8P3.x = L24P6.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 311 D dataOK 6

theorem ι6_res (y : 𝓞 L8) : ι6 (L8P3.res y) = L24P6.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P3 L24P6 ι6 ι6_x y

/-- `E_6(t) = 80000 (ι_6 t - β) (25 (ι_6 t)³ + 20 (ι_6 t)² + 14 ι_6 t + 14)³`. -/
noncomputable def Ev6 (t : L8P3.K) : L24P6.K := EvD 311 D dataOK 6 t

theorem Ev6_eq (t : L8P3.K) : Ev6 t =
    80000 * (ι6 t - L24P6.β) * (25 * ι6 t ^ 3 + 20 * ι6 t ^ 2 + 14 * ι6 t + 14) ^ 3 := rfl

/-- `ι_7 : k_3 → K_7`, `x ↦ α`. -/
noncomputable def ι7 : L8P3.K →+* L24P7.K := iotaD 311 D dataOK 7

theorem ι7_x : ι7 L8P3.x = L24P7.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 311 D dataOK 7

theorem ι7_res (y : 𝓞 L8) : ι7 (L8P3.res y) = L24P7.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P3 L24P7 ι7 ι7_x y

/-- `E_7(t) = 80000 (ι_7 t - β) (25 (ι_7 t)³ + 20 (ι_7 t)² + 14 ι_7 t + 14)³`. -/
noncomputable def Ev7 (t : L8P3.K) : L24P7.K := EvD 311 D dataOK 7 t

theorem Ev7_eq (t : L8P3.K) : Ev7 t =
    80000 * (ι7 t - L24P7.β) * (25 * ι7 t ^ 3 + 20 * ι7 t ^ 2 + 14 * ι7 t + 14) ^ 3 := rfl

/-- `ι_8 : k_4 → K_8`, `x ↦ α`. -/
noncomputable def ι8 : L8P4.K →+* L24P8.K := iotaD 311 D dataOK 8

theorem ι8_x : ι8 L8P4.x = L24P8.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 311 D dataOK 8

theorem ι8_res (y : 𝓞 L8) : ι8 (L8P4.res y) = L24P8.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P4 L24P8 ι8 ι8_x y

/-- `E_8(t) = 80000 (ι_8 t - β) (25 (ι_8 t)³ + 20 (ι_8 t)² + 14 ι_8 t + 14)³`. -/
noncomputable def Ev8 (t : L8P4.K) : L24P8.K := EvD 311 D dataOK 8 t

theorem Ev8_eq (t : L8P4.K) : Ev8 t =
    80000 * (ι8 t - L24P8.β) * (25 * ι8 t ^ 3 + 20 * ι8 t ^ 2 + 14 * ι8 t + 14) ^ 3 := rfl

/-- `ι_9 : k_4 → K_9`, `x ↦ α`. -/
noncomputable def ι9 : L8P4.K →+* L24P9.K := iotaD 311 D dataOK 9

theorem ι9_x : ι9 L8P4.x = L24P9.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 311 D dataOK 9

theorem ι9_res (y : 𝓞 L8) : ι9 (L8P4.res y) = L24P9.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P4 L24P9 ι9 ι9_x y

/-- `E_9(t) = 80000 (ι_9 t - β) (25 (ι_9 t)³ + 20 (ι_9 t)² + 14 ι_9 t + 14)³`. -/
noncomputable def Ev9 (t : L8P4.K) : L24P9.K := EvD 311 D dataOK 9 t

theorem Ev9_eq (t : L8P4.K) : Ev9 t =
    80000 * (ι9 t - L24P9.β) * (25 * ι9 t ^ 3 + 20 * ι9 t ^ 2 + 14 * ι9 t + 14) ^ 3 := rfl

/-- `ι_10 : k_4 → K_10`, `x ↦ α`. -/
noncomputable def ι10 : L8P4.K →+* L24P10.K := iotaD 311 D dataOK 10

theorem ι10_x : ι10 L8P4.x = L24P10.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 311 D dataOK 10

theorem ι10_res (y : 𝓞 L8) : ι10 (L8P4.res y) = L24P10.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P4 L24P10 ι10 ι10_x y

/-- `E_10(t) = 80000 (ι_10 t - β) (25 (ι_10 t)³ + 20 (ι_10 t)² + 14 ι_10 t + 14)³`. -/
noncomputable def Ev10 (t : L8P4.K) : L24P10.K := EvD 311 D dataOK 10 t

theorem Ev10_eq (t : L8P4.K) : Ev10 t =
    80000 * (ι10 t - L24P10.β) * (25 * ι10 t ^ 3 + 20 * ι10 t ^ 2 + 14 * ι10 t + 14) ^ 3 := rfl

/-- The family as a dependent function on `Fin 5`. -/
noncomputable def tup (t0 : L8P0.K) (t1 : L8P1.K) (t2 : L8P2.K) (t3 : L8P3.K) (t4 : L8P4.K) : ∀ i : Fin 5, AdjoinRoot (toPoly 311 (D.H i))
  | ⟨0, _⟩ => t0
  | ⟨1, _⟩ => t1
  | ⟨2, _⟩ => t2
  | ⟨3, _⟩ => t3
  | ⟨4, _⟩ => t4
  | ⟨_ + 5, h⟩ => absurd h (by omega)

theorem symbols_mem (η : ZMod 311) (h0 : η ≠ 0) (h1 : η ≠ 1)
    (t0 : L8P0.K) (t1 : L8P1.K) (t2 : L8P2.K) (t3 : L8P3.K) (t4 : L8P4.K)
    (r0 : fb η t0 = 0) (r1 : fb η t1 = 0) (r2 : fb η t2 = 0) (r3 : fb η t3 = 0) (r4 : fb η t4 = 0)
    (d0 : (minpoly (ZMod 311) t0).natDegree = 1)
    (d1 : (minpoly (ZMod 311) t1).natDegree = 1)
    (d2 : (minpoly (ZMod 311) t2).natDegree = 1)
    (d3 : (minpoly (ZMod 311) t3).natDegree = 1)
    (d4 : (minpoly (ZMod 311) t4).natDegree = 4)
    (n01 : minpoly (ZMod 311) t0 ≠ minpoly (ZMod 311) t1)
    (n02 : minpoly (ZMod 311) t0 ≠ minpoly (ZMod 311) t2)
    (n03 : minpoly (ZMod 311) t0 ≠ minpoly (ZMod 311) t3)
    (n12 : minpoly (ZMod 311) t1 ≠ minpoly (ZMod 311) t2)
    (n13 : minpoly (ZMod 311) t1 ≠ minpoly (ZMod 311) t3)
    (n23 : minpoly (ZMod 311) t2 ≠ minpoly (ZMod 311) t3)
    :
    (Ev0 t0 ≠ 0 ∧ Ev1 t0 ≠ 0 ∧ Ev2 t1 ≠ 0 ∧ Ev3 t1 ≠ 0 ∧ Ev4 t2 ≠ 0 ∧ Ev5 t2 ≠ 0 ∧ Ev6 t3 ≠ 0 ∧ Ev7 t3 ≠ 0 ∧ Ev8 t4 ≠ 0 ∧ Ev9 t4 ≠ 0 ∧ Ev10 t4 ≠ 0) ∧
    ![L24P0.sym (Ev0 t0), L24P1.sym (Ev1 t0), L24P2.sym (Ev2 t1), L24P3.sym (Ev3 t1), L24P4.sym (Ev4 t2), L24P5.sym (Ev5 t2), L24P6.sym (Ev6 t3), L24P7.sym (Ev7 t3), L24P8.sym (Ev8 t4), L24P9.sym (Ev9 t4), L24P10.sym (Ev10 t4)] ∈ SymbolSets.I311 := by
  have hm := main 311 D dataOK ILN SymbolSets.I311L ilOK certs certsOK covOK η h0 h1 (tup t0 t1 t2 t3 t4)
    (by intro i; fin_cases i
        · exact r0
        · exact r1
        · exact r2
        · exact r3
        · exact r4
      )
    (by intro i; fin_cases i
        · exact d0
        · exact d1
        · exact d2
        · exact d3
        · exact d4
      )
    (by
      intro i j hij hdd
      fin_cases i <;> fin_cases j
      · exact absurd rfl hij
      · exact n01
      · exact n02
      · exact n03
      · exact absurd hdd (by decide)
      · exact (n01).symm
      · exact absurd rfl hij
      · exact n12
      · exact n13
      · exact absurd hdd (by decide)
      · exact (n02).symm
      · exact (n12).symm
      · exact absurd rfl hij
      · exact n23
      · exact absurd hdd (by decide)
      · exact (n03).symm
      · exact (n13).symm
      · exact (n23).symm
      · exact absurd rfl hij
      · exact absurd hdd (by decide)
      · exact absurd hdd (by decide)
      · exact absurd hdd (by decide)
      · exact absurd hdd (by decide)
      · exact absurd hdd (by decide)
      · exact absurd rfl hij
      )
  obtain ⟨hne, w, hw, hwe⟩ := hm
  refine ⟨⟨hne 0, hne 1, hne 2, hne 3, hne 4, hne 5, hne 6, hne 7, hne 8, hne 9, hne 10⟩, ?_⟩
  rw [SymbolSets.I311, List.mem_toFinset]
  convert hw using 1
  rw [hwe]
  funext k
  fin_cases k <;> rfl

end X2Y5Z7.SymbolSets.Q311
