/-
Generated by computer; every fact used is proved in Lean.
-/
import X2Y5Z7.NotDvd.Basic
import X2Y5Z7.Primes.Q131

/-! # Corollary 5.5 (`q ∤ XYZ`) at `q = 131`: `131` divides none of `X`, `Y`, `Z`

Residue degrees of the primes of `L8` above `131`: `[2, 2, 4]`.
* `q ∣ X`: no subset `T` with all degrees dividing 5, degree sum `≤ 5`, complement sum `≤ 3`.
* `q ∣ Z`: `7(131-1) ∣ 131^6 - 1`; no subset `T` with sum `≤ 1` whose complement has degrees dividing `6`
  and sum `≤ 7`.
* `q ∣ Y`, `c = 1`: `P_c` has factor degrees `[1, 1, 2, 2, 2]`.
* `q ∣ Y`, `c = 2`: `P_c` has factor degrees `[1, 1, 2, 2, 2]`.
`ν = 2` is a non-square mod `131`. -/

namespace X2Y5Z7.NotDvd.Q131

open Polynomial X2Y5Z7.FiniteFields X2Y5Z7.Aux X2Y5Z7.Primes.Q131

noncomputable section

theorem h70 : (70 : ZMod 131) ≠ 0 := by decide

theorem hdiv5 : 5 * (131 - 1) ∣ 131 ^ 5 - 1 := by norm_num

theorem hdiv7 : 7 * (131 - 1) ∣ 131 ^ 6 - 1 := by norm_num

theorem not_dvd_X (s : Solution) (Rt : Root s) : ¬ ((131 : ℕ) : ℤ) ∣ s.X :=
  NotDvd.not_dvd_X s Rt R hker h70 hdiv5 dvec deg_R (by decide +kernel)

theorem not_dvd_Z (s : Solution) (Rt : Root s) : ¬ ((131 : ℕ) : ℤ) ∣ s.Z :=
  NotDvd.not_dvd_Z s Rt R hker h70 6 hdiv7 dvec deg_R (by decide +kernel)

theorem hq : (131 : (ZMod 131)[X]) = 0 := by
  have h := (map_natCast (C : ZMod 131 →+* (ZMod 131)[X]) 131).symm
  rw [ZMod.natCast_self, map_zero] at h
  exact_mod_cast h

theorem irr1_0 : Irreducible (toPoly 131 [15, 1]) :=
  irreducible_of_irrCheck (cert := []) (by decide +kernel)

theorem irr1_1 : Irreducible (toPoly 131 [116, 1]) :=
  irreducible_of_irrCheck (cert := []) (by decide +kernel)

theorem irr1_2 : Irreducible (toPoly 131 [46, 0, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [0, 47])]) (by decide +kernel)

theorem irr1_3 : Irreducible (toPoly 131 [76, 47, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [51, 83])]) (by decide +kernel)

theorem irr1_4 : Irreducible (toPoly 131 [76, 84, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [80, 83])]) (by decide +kernel)

/-- The irreducible factors of `P_1` over `F_131`. -/
def φ1 : Fin 5 → (ZMod 131)[X] := ![toPoly 131 [15, 1], toPoly 131 [116, 1], toPoly 131 [46, 0, 1], toPoly 131 [76, 47, 1], toPoly 131 [76, 84, 1]]

theorem monic1 (j : Fin 5) : (φ1 j).Monic := by
  fin_cases j
  exacts [(toPoly_monic (q := 131) (P := [15, 1]) (by decide)).1, (toPoly_monic (q := 131) (P := [116, 1]) (by decide)).1, (toPoly_monic (q := 131) (P := [46, 0, 1]) (by decide)).1, (toPoly_monic (q := 131) (P := [76, 47, 1]) (by decide)).1, (toPoly_monic (q := 131) (P := [76, 84, 1]) (by decide)).1]

theorem irr1 (j : Fin 5) : Irreducible (φ1 j) := by
  fin_cases j
  exacts [irr1_0, irr1_1, irr1_2, irr1_3, irr1_4]

theorem natDegree1 (j : Fin 5) : (φ1 j).natDegree = ![1, 1, 2, 2, 2] j := by
  fin_cases j
  exacts [(toPoly_monic (q := 131) (P := [15, 1]) (by decide)).2, (toPoly_monic (q := 131) (P := [116, 1]) (by decide)).2, (toPoly_monic (q := 131) (P := [46, 0, 1]) (by decide)).2, (toPoly_monic (q := 131) (P := [76, 47, 1]) (by decide)).2, (toPoly_monic (q := 131) (P := [76, 84, 1]) (by decide)).2]

set_option linter.unusedSimpArgs false in
theorem prod1 : ∏ j, φ1 j = Pc (1 : ZMod 131) := by
  simp only [φ1, Fin.prod_univ_succ, Fin.prod_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ,
    toPoly, Pc, map_natCast, map_mul, map_pow, map_ofNat, map_one, Nat.cast_ofNat, Nat.cast_one, Nat.cast_zero,
    map_zero, mul_one, one_pow, mul_zero, add_zero]
  linear_combination ((3549965 : (ZMod 131)[X]) * 1 + (6348736 : (ZMod 131)[X]) * X + (3045132 : (ZMod 131)[X]) * X ^ 2 + (410152 : (ZMod 131)[X]) * X ^ 3 + (72468 : (ZMod 131)[X]) * X ^ 4 + (6008 : (ZMod 131)[X]) * X ^ 5 + (177 : (ZMod 131)[X]) * X ^ 6 + (2 : (ZMod 131)[X]) * X ^ 7) * hq

theorem irr2_0 : Irreducible (toPoly 131 [63, 1]) :=
  irreducible_of_irrCheck (cert := []) (by decide +kernel)

theorem irr2_1 : Irreducible (toPoly 131 [68, 1]) :=
  irreducible_of_irrCheck (cert := []) (by decide +kernel)

theorem irr2_2 : Irreducible (toPoly 131 [74, 0, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [0, 54])]) (by decide +kernel)

theorem irr2_3 : Irreducible (toPoly 131 [110, 50, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [96, 51])]) (by decide +kernel)

theorem irr2_4 : Irreducible (toPoly 131 [110, 81, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [35, 51])]) (by decide +kernel)

/-- The irreducible factors of `P_2` over `F_131`. -/
def φ2 : Fin 5 → (ZMod 131)[X] := ![toPoly 131 [63, 1], toPoly 131 [68, 1], toPoly 131 [74, 0, 1], toPoly 131 [110, 50, 1], toPoly 131 [110, 81, 1]]

theorem monic2 (j : Fin 5) : (φ2 j).Monic := by
  fin_cases j
  exacts [(toPoly_monic (q := 131) (P := [63, 1]) (by decide)).1, (toPoly_monic (q := 131) (P := [68, 1]) (by decide)).1, (toPoly_monic (q := 131) (P := [74, 0, 1]) (by decide)).1, (toPoly_monic (q := 131) (P := [110, 50, 1]) (by decide)).1, (toPoly_monic (q := 131) (P := [110, 81, 1]) (by decide)).1]

theorem irr2 (j : Fin 5) : Irreducible (φ2 j) := by
  fin_cases j
  exacts [irr2_0, irr2_1, irr2_2, irr2_3, irr2_4]

theorem natDegree2 (j : Fin 5) : (φ2 j).natDegree = ![1, 1, 2, 2, 2] j := by
  fin_cases j
  exacts [(toPoly_monic (q := 131) (P := [63, 1]) (by decide)).2, (toPoly_monic (q := 131) (P := [68, 1]) (by decide)).2, (toPoly_monic (q := 131) (P := [74, 0, 1]) (by decide)).2, (toPoly_monic (q := 131) (P := [110, 50, 1]) (by decide)).2, (toPoly_monic (q := 131) (P := [110, 81, 1]) (by decide)).2]

set_option linter.unusedSimpArgs false in
theorem prod2 : ∏ j, φ2 j = Pc (2 : ZMod 131) := by
  simp only [φ2, Fin.prod_univ_succ, Fin.prod_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ,
    toPoly, Pc, map_natCast, map_mul, map_pow, map_ofNat, map_one, Nat.cast_ofNat, Nat.cast_one, Nat.cast_zero,
    map_zero, mul_one, one_pow, mul_zero, add_zero]
  linear_combination ((29615600 : (ZMod 131)[X]) * 1 + (35767160 : (ZMod 131)[X]) * X + (11828860 : (ZMod 131)[X]) * X ^ 2 + (1124476 : (ZMod 131)[X]) * X ^ 3 + (168400 : (ZMod 131)[X]) * X ^ 4 + (8812 : (ZMod 131)[X]) * X ^ 5 + (199 : (ZMod 131)[X]) * X ^ 6 + (2 : (ZMod 131)[X]) * X ^ 7) * hq

theorem hν : (2 : ZMod 131) ^ (131 / 2) = -1 := by decide +kernel

set_option linter.unusedSimpArgs false in
theorem not_dvd_Y (s : Solution) (Rt : Root s) : ¬ ((131 : ℕ) : ℤ) ∣ s.Y :=
  NotDvd.not_dvd_Y s Rt R hker h70 dvec deg_R sum_dvec (2 : ZMod 131) (by decide) hν
    φ1 monic1 irr1 prod1 (by simp [natDegree1, Fin.sum_univ_succ]) (by simp [natDegree1, dvec, Fin.sum_univ_succ])
    φ2 monic2 irr2 prod2 (by simp [natDegree2, Fin.sum_univ_succ]) (by simp [natDegree2, dvec, Fin.sum_univ_succ])

/-- **Corollary 5.5 (`q ∤ XYZ`) at `q = 131`.** -/
theorem not_dvd (s : Solution) (Rt : Root s) :
    ¬ ((131 : ℕ) : ℤ) ∣ s.X ∧ ¬ ((131 : ℕ) : ℤ) ∣ s.Y ∧ ¬ ((131 : ℕ) : ℤ) ∣ s.Z :=
  ⟨not_dvd_X s Rt, not_dvd_Y s Rt, not_dvd_Z s Rt⟩

end

end X2Y5Z7.NotDvd.Q131
