/-
Generated by computer; every fact used is proved in Lean.
-/
import X2Y5Z7.NotDvd.Basic
import X2Y5Z7.Primes.Q181

/-! # Corollary 5.5 (`q ∤ XYZ`) at `q = 181`: `181` divides none of `X`, `Y`, `Z`

Residue degrees of the primes of `L8` above `181`: `[1, 1, 1, 2, 3]`.
* `q ∣ X`: no subset `T` with all degrees dividing 5, degree sum `≤ 5`, complement sum `≤ 3`.
* `q ∣ Z`: `7(181-1) ∣ 181^2 - 1`; no subset `T` with sum `≤ 1` whose complement has degrees dividing `2`
  and sum `≤ 7`.
* `q ∣ Y`, `c = 1`: `P_c` has factor degrees `[8]`.
* `q ∣ Y`, `c = 2`: `P_c` has factor degrees `[8]`.
`ν = 2` is a non-square mod `181`. -/

namespace X2Y5Z7.NotDvd.Q181

open Polynomial X2Y5Z7.FiniteFields X2Y5Z7.Aux X2Y5Z7.Primes.Q181

noncomputable section

theorem h70 : (70 : ZMod 181) ≠ 0 := by decide

theorem hdiv5 : 5 * (181 - 1) ∣ 181 ^ 5 - 1 := by norm_num

theorem hdiv7 : 7 * (181 - 1) ∣ 181 ^ 2 - 1 := by norm_num

theorem not_dvd_X (s : Solution) (Rt : Root s) : ¬ ((181 : ℕ) : ℤ) ∣ s.X :=
  NotDvd.not_dvd_X s Rt R hker h70 hdiv5 dvec deg_R (by decide +kernel)

theorem not_dvd_Z (s : Solution) (Rt : Root s) : ¬ ((181 : ℕ) : ℤ) ∣ s.Z :=
  NotDvd.not_dvd_Z s Rt R hker h70 2 hdiv7 dvec deg_R (by decide +kernel)

theorem hq : (181 : (ZMod 181)[X]) = 0 := by
  have h := (map_natCast (C : ZMod 181 →+* (ZMod 181)[X]) 181).symm
  rw [ZMod.natCast_self, map_zero] at h
  exact_mod_cast h

theorem irr1_0 : Irreducible (toPoly 181 [173, 0, 158, 0, 62, 0, 41, 0, 1]) :=
  irreducible_of_irrCheck (cert := [(4, [0, 58, 0, 64, 0, 54, 0, 147])]) (by decide +kernel)

/-- The irreducible factors of `P_1` over `F_181`. -/
def φ1 : Fin 1 → (ZMod 181)[X] := ![toPoly 181 [173, 0, 158, 0, 62, 0, 41, 0, 1]]

theorem monic1 (j : Fin 1) : (φ1 j).Monic := by
  fin_cases j
  exacts [(toPoly_monic (q := 181) (P := [173, 0, 158, 0, 62, 0, 41, 0, 1]) (by decide)).1]

theorem irr1 (j : Fin 1) : Irreducible (φ1 j) := by
  fin_cases j
  exacts [irr1_0]

theorem natDegree1 (j : Fin 1) : (φ1 j).natDegree = ![8] j := by
  fin_cases j
  exacts [(toPoly_monic (q := 181) (P := [173, 0, 158, 0, 62, 0, 41, 0, 1]) (by decide)).2]

set_option linter.unusedSimpArgs false in
theorem prod1 : ∏ j, φ1 j = Pc (1 : ZMod 181) := by
  simp only [φ1, Fin.prod_univ_succ, Fin.prod_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ,
    toPoly, Pc, map_natCast, map_mul, map_pow, map_ofNat, map_one, Nat.cast_ofNat, Nat.cast_one, Nat.cast_zero,
    map_zero, mul_one, one_pow, mul_zero, add_zero]
  linear_combination ((15108 : (ZMod 181)[X]) * 1 + (2418 : (ZMod 181)[X]) * X ^ 2 + (-48 : (ZMod 181)[X]) * X ^ 4 + (1 : (ZMod 181)[X]) * X ^ 6) * hq

theorem irr2_0 : Irreducible (toPoly 181 [53, 0, 178, 0, 67, 0, 82, 0, 1]) :=
  irreducible_of_irrCheck (cert := [(4, [0, 29, 0, 16, 0, 52, 0, 111])]) (by decide +kernel)

/-- The irreducible factors of `P_2` over `F_181`. -/
def φ2 : Fin 1 → (ZMod 181)[X] := ![toPoly 181 [53, 0, 178, 0, 67, 0, 82, 0, 1]]

theorem monic2 (j : Fin 1) : (φ2 j).Monic := by
  fin_cases j
  exacts [(toPoly_monic (q := 181) (P := [53, 0, 178, 0, 67, 0, 82, 0, 1]) (by decide)).1]

theorem irr2 (j : Fin 1) : Irreducible (φ2 j) := by
  fin_cases j
  exacts [irr2_0]

theorem natDegree2 (j : Fin 1) : (φ2 j).natDegree = ![8] j := by
  fin_cases j
  exacts [(toPoly_monic (q := 181) (P := [53, 0, 178, 0, 67, 0, 82, 0, 1]) (by decide)).2]

set_option linter.unusedSimpArgs false in
theorem prod2 : ∏ j, φ2 j = Pc (2 : ZMod 181) := by
  simp only [φ2, Fin.prod_univ_succ, Fin.prod_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ,
    toPoly, Pc, map_natCast, map_mul, map_pow, map_ofNat, map_one, Nat.cast_ofNat, Nat.cast_one, Nat.cast_zero,
    map_zero, mul_one, one_pow, mul_zero, add_zero]
  linear_combination ((241713 : (ZMod 181)[X]) * 1 + (19338 : (ZMod 181)[X]) * X ^ 2 + (-193 : (ZMod 181)[X]) * X ^ 4 + (2 : (ZMod 181)[X]) * X ^ 6) * hq

theorem hν : (2 : ZMod 181) ^ (181 / 2) = -1 := by decide +kernel

set_option linter.unusedSimpArgs false in
theorem not_dvd_Y (s : Solution) (Rt : Root s) : ¬ ((181 : ℕ) : ℤ) ∣ s.Y :=
  NotDvd.not_dvd_Y s Rt R hker h70 dvec deg_R sum_dvec (2 : ZMod 181) (by decide) hν
    φ1 monic1 irr1 prod1 (by simp [natDegree1, Fin.sum_univ_succ]) (by simp [natDegree1, dvec, Fin.sum_univ_succ])
    φ2 monic2 irr2 prod2 (by simp [natDegree2, Fin.sum_univ_succ]) (by simp [natDegree2, dvec, Fin.sum_univ_succ])

/-- **Corollary 5.5 (`q ∤ XYZ`) at `q = 181`.** -/
theorem not_dvd (s : Solution) (Rt : Root s) :
    ¬ ((181 : ℕ) : ℤ) ∣ s.X ∧ ¬ ((181 : ℕ) : ℤ) ∣ s.Y ∧ ¬ ((181 : ℕ) : ℤ) ∣ s.Z :=
  ⟨not_dvd_X s Rt, not_dvd_Y s Rt, not_dvd_Z s Rt⟩

end

end X2Y5Z7.NotDvd.Q181
