/-
Generated by computer; every fact used is proved in Lean.
-/
module

public import X2Y5Z7.NotDvd.Basic
public import X2Y5Z7.Primes.Q251

@[expose] public section

/-! # Corollary 5.5 (`q ∤ XYZ`) at `q = 251`: `251` divides none of `X`, `Y`, `Z`

Residue degrees of the primes of `L8` above `251`: `[2, 2, 4]`.
* `q ∣ X`: no subset `T` with all degrees dividing 5, degree sum `≤ 5`, complement sum `≤ 3`.
* `q ∣ Z`: `7(251-1) ∣ 251^2 - 1`; no subset `T` with sum `≤ 1` whose complement has degrees dividing `2`
  and sum `≤ 7`.
* `q ∣ Y`, `c = 1`: `P_c` has factor degrees `[1, 1, 2, 2, 2]`.
* `q ∣ Y`, `c = 2`: `P_c` has factor degrees `[1, 1, 2, 2, 2]`.
`ν = 2` is a non-square mod `251`. -/

namespace X2Y5Z7.NotDvd.Q251

open Polynomial X2Y5Z7.FiniteFields X2Y5Z7.Aux X2Y5Z7.Primes.Q251

noncomputable section

theorem h70 : (70 : ZMod 251) ≠ 0 := by decide

theorem hdiv5 : 5 * (251 - 1) ∣ 251 ^ 5 - 1 := by norm_num

theorem hdiv7 : 7 * (251 - 1) ∣ 251 ^ 2 - 1 := by norm_num

theorem not_dvd_X (s : Solution) (Rt : Root s) : ¬ ((251 : ℕ) : ℤ) ∣ s.X :=
  NotDvd.not_dvd_X s Rt R hker h70 hdiv5 dvec deg_R (by decide +kernel)

theorem not_dvd_Z (s : Solution) (Rt : Root s) : ¬ ((251 : ℕ) : ℤ) ∣ s.Z :=
  NotDvd.not_dvd_Z s Rt R hker h70 2 hdiv7 dvec deg_R (by decide +kernel)

theorem hq : (251 : (ZMod 251)[X]) = 0 := by
  have h := (map_natCast (C : ZMod 251 →+* (ZMod 251)[X]) 251).symm
  rw [ZMod.natCast_self, map_zero] at h
  exact_mod_cast h

theorem irr1_0 : Irreducible (toPoly 251 [76, 1]) :=
  irreducible_of_irrCheck (cert := []) (by decide +kernel)

theorem irr1_1 : Irreducible (toPoly 251 [175, 1]) :=
  irreducible_of_irrCheck (cert := []) (by decide +kernel)

theorem irr1_2 : Irreducible (toPoly 251 [119, 0, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [0, 193])]) (by decide +kernel)

theorem irr1_3 : Irreducible (toPoly 251 [20, 48, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [195, 165])]) (by decide +kernel)

theorem irr1_4 : Irreducible (toPoly 251 [20, 203, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [56, 165])]) (by decide +kernel)

/-- The irreducible factors of `P_1` over `F_251`. -/
def φ1 : Fin 5 → (ZMod 251)[X] := ![toPoly 251 [76, 1], toPoly 251 [175, 1], toPoly 251 [119, 0, 1], toPoly 251 [20, 48, 1], toPoly 251 [20, 203, 1]]

theorem monic1 (j : Fin 5) : (φ1 j).Monic := by
  fin_cases j
  exacts [(toPoly_monic (q := 251) (P := [76, 1]) (by decide)).1, (toPoly_monic (q := 251) (P := [175, 1]) (by decide)).1, (toPoly_monic (q := 251) (P := [119, 0, 1]) (by decide)).1, (toPoly_monic (q := 251) (P := [20, 48, 1]) (by decide)).1, (toPoly_monic (q := 251) (P := [20, 203, 1]) (by decide)).1]

theorem irr1 (j : Fin 5) : Irreducible (φ1 j) := by
  fin_cases j
  exacts [irr1_0, irr1_1, irr1_2, irr1_3, irr1_4]

theorem natDegree1 (j : Fin 5) : (φ1 j).natDegree = ![1, 1, 2, 2, 2] j := by
  fin_cases j
  exacts [(toPoly_monic (q := 251) (P := [76, 1]) (by decide)).2, (toPoly_monic (q := 251) (P := [175, 1]) (by decide)).2, (toPoly_monic (q := 251) (P := [119, 0, 1]) (by decide)).2, (toPoly_monic (q := 251) (P := [20, 48, 1]) (by decide)).2, (toPoly_monic (q := 251) (P := [20, 203, 1]) (by decide)).2]

set_option linter.unusedSimpArgs false in
theorem prod1 : ∏ j, φ1 j = Pc (1 : ZMod 251) := by
  simp only [φ1, Fin.prod_univ_succ, Fin.prod_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ,
    toPoly, Pc, map_natCast, map_mul, map_pow, map_ofNat, map_one, Nat.cast_ofNat, Nat.cast_one, Nat.cast_zero,
    map_zero, mul_one, one_pow, mul_zero, add_zero]
  linear_combination ((2533125 : (ZMod 251)[X]) * 1 + (31701600 : (ZMod 251)[X]) * X + (62314280 : (ZMod 251)[X]) * X ^ 2 + (3015776 : (ZMod 251)[X]) * X ^ 3 + (564235 : (ZMod 251)[X]) * X ^ 4 + (23342 : (ZMod 251)[X]) * X ^ 5 + (344 : (ZMod 251)[X]) * X ^ 6 + (2 : (ZMod 251)[X]) * X ^ 7) * hq

theorem irr2_0 : Irreducible (toPoly 251 [55, 1]) :=
  irreducible_of_irrCheck (cert := []) (by decide +kernel)

theorem irr2_1 : Irreducible (toPoly 251 [196, 1]) :=
  irreducible_of_irrCheck (cert := []) (by decide +kernel)

theorem irr2_2 : Irreducible (toPoly 251 [245, 0, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [0, 230])]) (by decide +kernel)

theorem irr2_3 : Irreducible (toPoly 251 [211, 92, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [144, 145])]) (by decide +kernel)

theorem irr2_4 : Irreducible (toPoly 251 [211, 159, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [107, 145])]) (by decide +kernel)

/-- The irreducible factors of `P_2` over `F_251`. -/
def φ2 : Fin 5 → (ZMod 251)[X] := ![toPoly 251 [55, 1], toPoly 251 [196, 1], toPoly 251 [245, 0, 1], toPoly 251 [211, 92, 1], toPoly 251 [211, 159, 1]]

theorem monic2 (j : Fin 5) : (φ2 j).Monic := by
  fin_cases j
  exacts [(toPoly_monic (q := 251) (P := [55, 1]) (by decide)).1, (toPoly_monic (q := 251) (P := [196, 1]) (by decide)).1, (toPoly_monic (q := 251) (P := [245, 0, 1]) (by decide)).1, (toPoly_monic (q := 251) (P := [211, 92, 1]) (by decide)).1, (toPoly_monic (q := 251) (P := [211, 159, 1]) (by decide)).1]

theorem irr2 (j : Fin 5) : Irreducible (φ2 j) := by
  fin_cases j
  exacts [irr2_0, irr2_1, irr2_2, irr2_3, irr2_4]

theorem natDegree2 (j : Fin 5) : (φ2 j).natDegree = ![1, 1, 2, 2, 2] j := by
  fin_cases j
  exacts [(toPoly_monic (q := 251) (P := [55, 1]) (by decide)).2, (toPoly_monic (q := 251) (P := [196, 1]) (by decide)).2, (toPoly_monic (q := 251) (P := [245, 0, 1]) (by decide)).2, (toPoly_monic (q := 251) (P := [211, 92, 1]) (by decide)).2, (toPoly_monic (q := 251) (P := [211, 159, 1]) (by decide)).2]

set_option linter.unusedSimpArgs false in
theorem prod2 : ∏ j, φ2 j = Pc (2 : ZMod 251) := by
  simp only [φ2, Fin.prod_univ_succ, Fin.prod_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ,
    toPoly, Pc, map_natCast, map_mul, map_pow, map_ofNat, map_one, Nat.cast_ofNat, Nat.cast_one, Nat.cast_zero,
    map_zero, mul_one, one_pow, mul_zero, add_zero]
  linear_combination ((468638100 : (ZMod 251)[X]) * 1 + (568179745 : (ZMod 251)[X]) * X + (173305720 : (ZMod 251)[X]) * X ^ 2 + (8699146 : (ZMod 251)[X]) * X ^ 3 + (786077 : (ZMod 251)[X]) * X ^ 4 + (26531 : (ZMod 251)[X]) * X ^ 5 + (356 : (ZMod 251)[X]) * X ^ 6 + (2 : (ZMod 251)[X]) * X ^ 7) * hq

theorem hν : (2 : ZMod 251) ^ (251 / 2) = -1 := by decide +kernel

set_option linter.unusedSimpArgs false in
theorem not_dvd_Y (s : Solution) (Rt : Root s) : ¬ ((251 : ℕ) : ℤ) ∣ s.Y :=
  NotDvd.not_dvd_Y s Rt R hker h70 dvec deg_R sum_dvec (2 : ZMod 251) (by decide) hν
    φ1 monic1 irr1 prod1 (by simp [natDegree1, Fin.sum_univ_succ]) (by simp [natDegree1, dvec, Fin.sum_univ_succ])
    φ2 monic2 irr2 prod2 (by simp [natDegree2, Fin.sum_univ_succ]) (by simp [natDegree2, dvec, Fin.sum_univ_succ])

/-- **Corollary 5.5 (`q ∤ XYZ`) at `q = 251`.** -/
theorem not_dvd (s : Solution) (Rt : Root s) :
    ¬ ((251 : ℕ) : ℤ) ∣ s.X ∧ ¬ ((251 : ℕ) : ℤ) ∣ s.Y ∧ ¬ ((251 : ℕ) : ℤ) ∣ s.Z :=
  ⟨not_dvd_X s Rt, not_dvd_Y s Rt, not_dvd_Z s Rt⟩

end

end X2Y5Z7.NotDvd.Q251
