/-
Generated by computer; every fact used is proved in Lean.
-/
import X2Y5Z7.NotDvd.Basic
import X2Y5Z7.Primes.Q311

/-! # Corollary 5.5 (`q ∤ XYZ`) at `q = 311`: `311` divides none of `X`, `Y`, `Z`

Residue degrees of the primes of `L8` above `311`: `[1, 1, 1, 1, 4]`.
* `q ∣ X`: no subset `T` with all degrees dividing 5, degree sum `≤ 5`, complement sum `≤ 3`.
* `q ∣ Z`: `7(311-1) ∣ 311^6 - 1`; no subset `T` with sum `≤ 1` whose complement has degrees dividing `6`
  and sum `≤ 7`.
* `q ∣ Y`, `c = 1`: `P_c` has factor degrees `[1, 1, 2, 2, 2]`.
* `q ∣ Y`, `c = 11`: `P_c` has factor degrees `[1, 1, 2, 2, 2]`.
`ν = 11` is a non-square mod `311`. -/

namespace X2Y5Z7.NotDvd.Q311

open Polynomial X2Y5Z7.FiniteFields X2Y5Z7.Aux X2Y5Z7.Primes.Q311

noncomputable section

theorem h70 : (70 : ZMod 311) ≠ 0 := by decide

theorem hdiv5 : 5 * (311 - 1) ∣ 311 ^ 5 - 1 := by norm_num

theorem hdiv7 : 7 * (311 - 1) ∣ 311 ^ 6 - 1 := by norm_num

theorem not_dvd_X (s : Solution) (Rt : Root s) : ¬ ((311 : ℕ) : ℤ) ∣ s.X :=
  NotDvd.not_dvd_X s Rt R hker h70 hdiv5 dvec deg_R (by decide +kernel)

theorem not_dvd_Z (s : Solution) (Rt : Root s) : ¬ ((311 : ℕ) : ℤ) ∣ s.Z :=
  NotDvd.not_dvd_Z s Rt R hker h70 6 hdiv7 dvec deg_R (by decide +kernel)

theorem hq : (311 : (ZMod 311)[X]) = 0 := by
  have h := (map_natCast (C : ZMod 311 →+* (ZMod 311)[X]) 311).symm
  rw [ZMod.natCast_self, map_zero] at h
  exact_mod_cast h

theorem irr1_0 : Irreducible (toPoly 311 [106, 1]) :=
  irreducible_of_irrCheck (cert := []) (by decide +kernel)

theorem irr1_1 : Irreducible (toPoly 311 [205, 1]) :=
  irreducible_of_irrCheck (cert := []) (by decide +kernel)

theorem irr1_2 : Irreducible (toPoly 311 [245, 0, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [0, 139])]) (by decide +kernel)

theorem irr1_3 : Irreducible (toPoly 311 [113, 142, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [153, 81])]) (by decide +kernel)

theorem irr1_4 : Irreducible (toPoly 311 [113, 169, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [158, 81])]) (by decide +kernel)

/-- The irreducible factors of `P_1` over `F_311`. -/
def φ1 : Fin 5 → (ZMod 311)[X] := ![toPoly 311 [106, 1], toPoly 311 [205, 1], toPoly 311 [245, 0, 1], toPoly 311 [113, 142, 1], toPoly 311 [113, 169, 1]]

theorem monic1 (j : Fin 5) : (φ1 j).Monic := by
  fin_cases j
  exacts [(toPoly_monic (q := 311) (P := [106, 1]) (by decide)).1, (toPoly_monic (q := 311) (P := [205, 1]) (by decide)).1, (toPoly_monic (q := 311) (P := [245, 0, 1]) (by decide)).1, (toPoly_monic (q := 311) (P := [113, 142, 1]) (by decide)).1, (toPoly_monic (q := 311) (P := [113, 169, 1]) (by decide)).1]

theorem irr1 (j : Fin 5) : Irreducible (φ1 j) := by
  fin_cases j
  exacts [irr1_0, irr1_1, irr1_2, irr1_3, irr1_4]

theorem natDegree1 (j : Fin 5) : (φ1 j).natDegree = ![1, 1, 2, 2, 2] j := by
  fin_cases j
  exacts [(toPoly_monic (q := 311) (P := [106, 1]) (by decide)).2, (toPoly_monic (q := 311) (P := [205, 1]) (by decide)).2, (toPoly_monic (q := 311) (P := [245, 0, 1]) (by decide)).2, (toPoly_monic (q := 311) (P := [113, 142, 1]) (by decide)).2, (toPoly_monic (q := 311) (P := [113, 169, 1]) (by decide)).2]

set_option linter.unusedSimpArgs false in
theorem prod1 : ∏ j, φ1 j = Pc (1 : ZMod 311) := by
  simp only [φ1, Fin.prod_univ_succ, Fin.prod_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ,
    toPoly, Pc, map_natCast, map_mul, map_pow, map_ofNat, map_one, Nat.cast_ofNat, Nat.cast_one, Nat.cast_zero,
    map_zero, mul_one, one_pow, mul_zero, add_zero]
  linear_combination ((218594775 : (ZMod 311)[X]) * 1 + (604723455 : (ZMod 311)[X]) * X + (424191960 : (ZMod 311)[X]) * X ^ 2 + (13754674 : (ZMod 311)[X]) * X ^ 3 + (1840117 : (ZMod 311)[X]) * X ^ 4 + (46557 : (ZMod 311)[X]) * X ^ 5 + (460 : (ZMod 311)[X]) * X ^ 6 + (2 : (ZMod 311)[X]) * X ^ 7) * hq

theorem irr2_0 : Irreducible (toPoly 311 [112, 1]) :=
  irreducible_of_irrCheck (cert := []) (by decide +kernel)

theorem irr2_1 : Irreducible (toPoly 311 [199, 1]) :=
  irreducible_of_irrCheck (cert := []) (by decide +kernel)

theorem irr2_2 : Irreducible (toPoly 311 [182, 0, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [0, 223])]) (by decide +kernel)

theorem irr2_3 : Irreducible (toPoly 311 [1, 71, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [111, 209])]) (by decide +kernel)

theorem irr2_4 : Irreducible (toPoly 311 [1, 240, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [200, 209])]) (by decide +kernel)

/-- The irreducible factors of `P_11` over `F_311`. -/
def φ2 : Fin 5 → (ZMod 311)[X] := ![toPoly 311 [112, 1], toPoly 311 [199, 1], toPoly 311 [182, 0, 1], toPoly 311 [1, 71, 1], toPoly 311 [1, 240, 1]]

theorem monic2 (j : Fin 5) : (φ2 j).Monic := by
  fin_cases j
  exacts [(toPoly_monic (q := 311) (P := [112, 1]) (by decide)).1, (toPoly_monic (q := 311) (P := [199, 1]) (by decide)).1, (toPoly_monic (q := 311) (P := [182, 0, 1]) (by decide)).1, (toPoly_monic (q := 311) (P := [1, 71, 1]) (by decide)).1, (toPoly_monic (q := 311) (P := [1, 240, 1]) (by decide)).1]

theorem irr2 (j : Fin 5) : Irreducible (φ2 j) := by
  fin_cases j
  exacts [irr2_0, irr2_1, irr2_2, irr2_3, irr2_4]

theorem natDegree2 (j : Fin 5) : (φ2 j).natDegree = ![1, 1, 2, 2, 2] j := by
  fin_cases j
  exacts [(toPoly_monic (q := 311) (P := [112, 1]) (by decide)).2, (toPoly_monic (q := 311) (P := [199, 1]) (by decide)).2, (toPoly_monic (q := 311) (P := [182, 0, 1]) (by decide)).2, (toPoly_monic (q := 311) (P := [1, 71, 1]) (by decide)).2, (toPoly_monic (q := 311) (P := [1, 240, 1]) (by decide)).2]

set_option linter.unusedSimpArgs false in
theorem prod2 : ∏ j, φ2 j = Pc (11 : ZMod 311) := by
  simp only [φ2, Fin.prod_univ_succ, Fin.prod_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ,
    toPoly, Pc, map_natCast, map_mul, map_pow, map_ofNat, map_one, Nat.cast_ofNat, Nat.cast_one, Nat.cast_zero,
    map_zero, mul_one, one_pow, mul_zero, add_zero]
  linear_combination ((128739681 : (ZMod 311)[X]) * 1 + (4056598 : (ZMod 311)[X]) * X + (224210224 : (ZMod 311)[X]) * X ^ 2 + (7180531 : (ZMod 311)[X]) * X ^ 3 + (1297850 : (ZMod 311)[X]) * X ^ 4 + (39695 : (ZMod 311)[X]) * X ^ 5 + (443 : (ZMod 311)[X]) * X ^ 6 + (2 : (ZMod 311)[X]) * X ^ 7) * hq

theorem hν : (11 : ZMod 311) ^ (311 / 2) = -1 := by decide +kernel

set_option linter.unusedSimpArgs false in
theorem not_dvd_Y (s : Solution) (Rt : Root s) : ¬ ((311 : ℕ) : ℤ) ∣ s.Y :=
  NotDvd.not_dvd_Y s Rt R hker h70 dvec deg_R sum_dvec (11 : ZMod 311) (by decide) hν
    φ1 monic1 irr1 prod1 (by simp [natDegree1, Fin.sum_univ_succ]) (by simp [natDegree1, dvec, Fin.sum_univ_succ])
    φ2 monic2 irr2 prod2 (by simp [natDegree2, Fin.sum_univ_succ]) (by simp [natDegree2, dvec, Fin.sum_univ_succ])

/-- **Corollary 5.5 (`q ∤ XYZ`) at `q = 311`.** -/
theorem not_dvd (s : Solution) (Rt : Root s) :
    ¬ ((311 : ℕ) : ℤ) ∣ s.X ∧ ¬ ((311 : ℕ) : ℤ) ∣ s.Y ∧ ¬ ((311 : ℕ) : ℤ) ∣ s.Z :=
  ⟨not_dvd_X s Rt, not_dvd_Y s Rt, not_dvd_Z s Rt⟩

end

end X2Y5Z7.NotDvd.Q311
