module

public import Mathlib.RingTheory.DedekindDomain.Different
public import Mathlib.NumberTheory.NumberField.Basic
public import Mathlib.RingTheory.Adjoin.PowerBasis
public import Mathlib.RingTheory.IntegralClosure.IsIntegralClosure.Basic
public import Mathlib.FieldTheory.Minpoly.IsIntegrallyClosed
public import Mathlib.FieldTheory.Finite.Basic

@[expose] public section

/-! # Residue fields generated by an integral generator with unit derivative

Let `K` be a number field and `θ ∈ 𝓞 K` generate `K` over `ℚ`. The element `D = f'(θ)` (with `f` the minimal
polynomial of `θ` over `ℤ`) lies in the conductor of `ℤ[θ]`, so `D · 𝓞 K ⊆ ℤ[θ]`. Consequently, for a residue map
`r : 𝓞 K →+* k` onto a finite field of characteristic `q` with `r D ≠ 0`, the residue field is generated by `r θ`. -/

namespace X2Y5Z7.Aux

open Polynomial
open scoped NumberField

noncomputable section

variable {K : Type*} [Field K] [NumberField K]

/-- `f'(θ)`, with `f = minpoly ℤ θ`. -/
def derivativeInteger (θ : 𝓞 K) : 𝓞 K := aeval θ (minpoly ℤ θ).derivative

/-- The derivative lies in the conductor of `ℤ[θ]`. -/
theorem derivative_mem_conductor (θ : 𝓞 K)
    (hθ : Algebra.adjoin ℚ ({(θ : K)} : Set K) = ⊤) : derivativeInteger θ ∈ conductor ℤ θ := by
  have he := conductor_mul_differentIdeal ℤ ℚ K θ hθ
  have hle : conductor ℤ θ * differentIdeal ℤ (𝓞 K) ≤ conductor ℤ θ := Ideal.mul_le_left
  rw [he] at hle
  exact hle (Ideal.subset_span (Set.mem_singleton _))

/-- `D · a ∈ ℤ[θ]` for every integer `a`. -/
theorem derivative_clears (θ a : 𝓞 K)
    (hθ : Algebra.adjoin ℚ ({(θ : K)} : Set K) = ⊤) :
    derivativeInteger θ * a ∈ Algebra.adjoin ℤ ({θ} : Set (𝓞 K)) :=
  (mem_conductor_iff.mp (derivative_mem_conductor θ hθ)) a

/-- A monic integral equation of the power-basis degree is the integer minimal polynomial. -/
theorem integer_minpoly_of_powerBasis (pb : PowerBasis ℚ K) (P : ℤ[X])
    (hm : P.Monic) (hp : aeval pb.gen P = 0) (hd : P.natDegree = pb.dim) : minpoly ℤ pb.gen = P := by
  have hi : IsIntegral ℤ pb.gen := ⟨P, hm, hp⟩
  apply Polynomial.map_injective (algebraMap ℤ ℚ) (IsFractionRing.injective ℤ ℚ)
  rw [← minpoly.isIntegrallyClosed_eq_field_fractions' ℚ hi]
  apply Eq.symm
  apply eq_of_monic_of_dvd_of_natDegree_le (minpoly.monic pb.isIntegral_gen) (hm.map _)
    (minpoly.dvd ℚ _ (by rw [aeval_map_algebraMap]; exact hp))
  rw [hm.natDegree_map, pb.natDegree_minpoly, hd]

/-- The integer minimal polynomial of `θ` is the same whether `θ` is viewed in `𝓞 K` or in `K`. -/
theorem integer_minpoly_eq_field (θ : 𝓞 K) : minpoly ℤ θ = minpoly ℤ (θ : K) :=
  (minpoly.algHom_eq (IsScalarTower.toAlgHom ℤ (𝓞 K) K)
    (IsFractionRing.injective (𝓞 K) K) θ).symm

/-- An explicit monic integer polynomial of degree `[K : ℚ]` killing a generator `θ` is its minimal polynomial. -/
theorem minpoly_eq_of_monic (θ : 𝓞 K) (hθ : Algebra.adjoin ℚ ({(θ : K)} : Set K) = ⊤)
    (G : ℤ[X]) (hm : G.Monic) (hG : aeval θ G = 0) (hd : G.natDegree = Module.finrank ℚ K) :
    minpoly ℤ θ = G := by
  have hint : IsIntegral ℚ (θ : K) := IsIntegral.of_finite ℚ _
  let pb : PowerBasis ℚ K := PowerBasis.ofAdjoinEqTop hint hθ
  have hgen : pb.gen = (θ : K) := rfl
  rw [integer_minpoly_eq_field, ← hgen]
  apply integer_minpoly_of_powerBasis pb G hm
  · rw [hgen]
    have := congrArg (algebraMap (𝓞 K) K) hG
    rwa [← aeval_algebraMap_apply, map_zero] at this
  · rw [hd, pb.finrank]

/-- With an explicit `G`, the derivative element is `G'(θ)`. -/
theorem derivativeInteger_eq (θ : 𝓞 K) (hθ : Algebra.adjoin ℚ ({(θ : K)} : Set K) = ⊤)
    (G : ℤ[X]) (hm : G.Monic) (hG : aeval θ G = 0) (hd : G.natDegree = Module.finrank ℚ K) :
    derivativeInteger θ = aeval θ G.derivative := by
  rw [derivativeInteger, minpoly_eq_of_monic θ hθ G hm hG hd]

variable {q : ℕ} [Fact q.Prime]

/-- For a map `r` to a finite commutative `ZMod q`-algebra `S` in which the image of the derivative is a unit,
every residue of an integer lies in `(ZMod q)[r θ]`. -/
theorem image_mem_adjoin_of_isUnit {S : Type*} [CommRing S] [Finite S] [Algebra (ZMod q) S]
    (θ a : 𝓞 K) (r : 𝓞 K →+* S)
    (hθ : Algebra.adjoin ℚ ({(θ : K)} : Set K) = ⊤) (hd : IsUnit (r (derivativeInteger θ))) :
    r a ∈ Algebra.adjoin (ZMod q) ({r θ} : Set S) := by
  classical
  let A := Algebra.adjoin (ZMod q) ({r θ} : Set S)
  have hle : Algebra.adjoin ℤ ({θ} : Set (𝓞 K)) ≤ (A.restrictScalars ℤ).comap r.toIntAlgHom := by
    apply Algebra.adjoin_le
    intro x hx
    have hx' : x = θ := Set.mem_singleton_iff.mp hx
    subst x
    exact Algebra.subset_adjoin (Set.mem_singleton _)
  have hmap (x : 𝓞 K) (hx : x ∈ Algebra.adjoin ℤ ({θ} : Set (𝓞 K))) : r x ∈ A := hle hx
  have hg : r (derivativeInteger θ) ∈ A := hmap _ (by
    simpa only [mul_one] using derivative_clears θ 1 hθ)
  obtain ⟨u, hu⟩ := hd
  have : Fintype Sˣ := Fintype.ofFinite _
  have hpow : ((u⁻¹ : Sˣ) : S) = (u : S) ^ (Fintype.card Sˣ - 1) := by
    have h1 : u ^ Fintype.card Sˣ = 1 := pow_card_eq_one
    have hpos : 0 < Fintype.card Sˣ := Fintype.card_pos
    have : u⁻¹ = u ^ (Fintype.card Sˣ - 1) := by
      rw [inv_eq_iff_mul_eq_one, ← pow_succ', Nat.sub_add_cancel hpos, h1]
    rw [this, Units.val_pow_eq_pow_val]
  have hi : ((u⁻¹ : Sˣ) : S) ∈ A := by
    rw [hpow]; exact A.pow_mem (hu ▸ hg) _
  have hm := A.mul_mem hi (hmap _ (derivative_clears θ a hθ))
  rw [map_mul, ← hu, ← mul_assoc, Units.inv_mul, one_mul] at hm
  exact hm

variable {k : Type*} [Field k] [Finite k] [Algebra (ZMod q) k]

/-- A local unit derivative forces every integer residue into `(ZMod q)[r θ]`. -/
theorem image_mem_adjoin (θ a : 𝓞 K) (r : 𝓞 K →+* k)
    (hθ : Algebra.adjoin ℚ ({(θ : K)} : Set K) = ⊤) (hd : r (derivativeInteger θ) ≠ 0) :
    r a ∈ Algebra.adjoin (ZMod q) ({r θ} : Set k) :=
  image_mem_adjoin_of_isUnit θ a r hθ (IsUnit.mk0 _ hd)

/-- The residue field is generated by `r θ`. -/
theorem generates (θ : 𝓞 K) (r : 𝓞 K →+* k) (hr : Function.Surjective r)
    (hθ : Algebra.adjoin ℚ ({(θ : K)} : Set K) = ⊤) (hd : r (derivativeInteger θ) ≠ 0) :
    Algebra.adjoin (ZMod q) ({r θ} : Set k) = ⊤ := by
  apply top_unique
  intro x _
  obtain ⟨a, rfl⟩ := hr x
  exact image_mem_adjoin θ a r hθ hd

/-- The power basis of the residue field generated by the residue of `θ`. -/
def residueBasis (θ : 𝓞 K) (r : 𝓞 K →+* k) (hr : Function.Surjective r)
    (hθ : Algebra.adjoin ℚ ({(θ : K)} : Set K) = ⊤) (hd : r (derivativeInteger θ) ≠ 0) :
    PowerBasis (ZMod q) k :=
  PowerBasis.ofAdjoinEqTop (IsIntegral.of_finite (R := ZMod q) (r θ)) (generates θ r hr hθ hd)

@[simp] theorem residueBasis_gen (θ : 𝓞 K) (r : 𝓞 K →+* k) (hr : Function.Surjective r)
    (hθ : Algebra.adjoin ℚ ({(θ : K)} : Set K) = ⊤) (hd : r (derivativeInteger θ) ≠ 0) :
    (residueBasis (q := q) θ r hr hθ hd).gen = r θ := rfl

/-- The residue degree equals the degree of the minimal polynomial of `r θ`. -/
theorem minpoly_degree (θ : 𝓞 K) (r : 𝓞 K →+* k) (hr : Function.Surjective r)
    (hθ : Algebra.adjoin ℚ ({(θ : K)} : Set K) = ⊤) (hd : r (derivativeInteger θ) ≠ 0) :
    (minpoly (ZMod q) (r θ)).natDegree = Module.finrank (ZMod q) k := by
  have h := (residueBasis (q := q) θ r hr hθ hd).natDegree_minpoly
  rw [residueBasis_gen] at h
  exact h.trans (residueBasis (q := q) θ r hr hθ hd).finrank.symm

omit [NumberField K] in
/-- Reduction of an integer polynomial commutes with evaluation at a residue. -/
theorem aeval_map_residue {S : Type*} [CommRing S] [Algebra (ZMod q) S] (r : 𝓞 K →+* S) (θ : 𝓞 K) (G : ℤ[X]) :
    aeval (r θ) (G.map (Int.castRingHom (ZMod q))) = r (aeval θ G) := by
  rw [aeval_def, eval₂_map, aeval_def, hom_eval₂]
  congr 1
  exact RingHom.ext_int _ _

omit [NumberField K] [Finite k] in
/-- The minimal polynomial of `r θ` divides the reduction of any integer polynomial killing `θ`. -/
theorem minpoly_dvd_map (θ : 𝓞 K) (r : 𝓞 K →+* k) (G : ℤ[X]) (hG : aeval θ G = 0) :
    minpoly (ZMod q) (r θ) ∣ G.map (Int.castRingHom (ZMod q)) :=
  minpoly.dvd _ _ (by rw [aeval_map_residue, hG, map_zero])

omit [NumberField K] [Finite k] in
/-- If `(ZMod q)[r α] = k` for some `α`, then `r` is surjective. -/
theorem surjective_of_adjoin (r : 𝓞 K →+* k) (α : 𝓞 K)
    (h : Algebra.adjoin (ZMod q) ({r α} : Set k) = ⊤) : Function.Surjective r := by
  let R : Subalgebra (ZMod q) k :=
    { r.range with
      algebraMap_mem' := fun c => ⟨((c.val : ℕ) : 𝓞 K), by
        rw [map_natCast]
        conv_rhs => rw [← ZMod.natCast_zmod_val c]
        rw [map_natCast]⟩ }
  have hle : Algebra.adjoin (ZMod q) ({r α} : Set k) ≤ R :=
    Algebra.adjoin_le (by
      intro x hx
      rw [Set.mem_singleton_iff.mp hx]
      exact ⟨α, rfl⟩)
  intro y
  have hy : y ∈ R := hle (h ▸ Algebra.mem_top)
  exact hy

/-- `AdjoinRoot P` has dimension `deg P` over `ZMod q` for irreducible `P`. -/
theorem finrank_adjoinRoot (P : (ZMod q)[X]) [Fact (Irreducible P)] :
    Module.finrank (ZMod q) (AdjoinRoot P) = P.natDegree := by
  rw [(AdjoinRoot.powerBasis (Irreducible.ne_zero Fact.out)).finrank, AdjoinRoot.powerBasis_dim]

end

end X2Y5Z7.Aux
