/-
Generated by computer; every fact used is proved in Lean.
-/
module

public import X2Y5Z7.Assembly.Basic
public import X2Y5Z7.NotDvd.Q131
public import X2Y5Z7.SymbolSets.Q131.Main

@[expose] public section

/-! # The auxiliary prime `q = 131`

For a solution with Putz root, `E` is a unit at the 9 primes of `L₂₄` above `131` and its symbol vector lies
in `SymbolSets.I131`: Corollary 5.5 (`q ∤ XYZ`) gives `131 ∤ 70XYZ`, the residues `t_i` of the Putz root at the 3 primes of `L₈`
form an admissible family (`Assembly.TFamily`), and Proposition 5.3 applies. -/

namespace X2Y5Z7.Assembly.Q131

open NumberField X2Y5Z7.FiniteFields X2Y5Z7.FiniteFields.Q131 X2Y5Z7.SymbolSets.Q131 X2Y5Z7.ResidueSymbols

theorem auxAt (s : Solution) (R : Aux.Root s) : Main.AuxAt L24P SymbolSets.I131 (Eu R) := by
  obtain ⟨hX, hY, hZ⟩ := NotDvd.Q131.not_dvd s R
  have g0 : (70 : L8P0.K) * s.X * s.Y * s.Z ≠ 0 := h70_of (q := 131) NotDvd.Q131.h70 hX hY hZ
  have g1 : (70 : L8P1.K) * s.X * s.Y * s.Z ≠ 0 := h70_of (q := 131) NotDvd.Q131.h70 hX hY hZ
  have g2 : (70 : L8P2.K) * s.X * s.Y * s.Z ≠ 0 := h70_of (q := 131) NotDvd.Q131.h70 hX hY hZ
  obtain ⟨hne, hI⟩ := symbols_mem (etaBar 131 s)
    (etaBar_ne_zero hX hZ)
    (etaBar_ne_one hY hZ)
    (tRes R L8P0.res)
    (tRes R L8P1.res)
    (tRes R L8P2.res)
    (fb_tRes (q := 131) R L8P0.res (h10_of g0))
    (fb_tRes (q := 131) R L8P1.res (h10_of g1))
    (fb_tRes (q := 131) R L8P2.res (h10_of g2))
    (by rw [t_natDegree (q := 131) R L8P0.res L8P0.res_surjective g0]; exact L8P0.finrank_K)
    (by rw [t_natDegree (q := 131) R L8P1.res L8P1.res_surjective g1]; exact L8P1.finrank_K)
    (by rw [t_natDegree (q := 131) R L8P2.res L8P2.res_surjective g2]; exact L8P2.finrank_K)
    (t_minpoly_ne (q := 131) R L8P0.res L8P1.res L8P0.res_surjective L8P1.res_surjective Primes.Q131.ker01 g0 g1)
  refine auxAt_of _ _ _ _ hI ?_
  intro j
  fin_cases j
  · exact unit_sym R L8P0 L24P0 ι0 ι0_res (h10_of g0) hne.1
  · exact unit_sym R L8P0 L24P1 ι1 ι1_res (h10_of g0) hne.2.1
  · exact unit_sym R L8P0 L24P2 ι2 ι2_res (h10_of g0) hne.2.2.1
  · exact unit_sym R L8P1 L24P3 ι3 ι3_res (h10_of g1) hne.2.2.2.1
  · exact unit_sym R L8P1 L24P4 ι4 ι4_res (h10_of g1) hne.2.2.2.2.1
  · exact unit_sym R L8P1 L24P5 ι5 ι5_res (h10_of g1) hne.2.2.2.2.2.1
  · exact unit_sym R L8P2 L24P6 ι6 ι6_res (h10_of g2) hne.2.2.2.2.2.2.1
  · exact unit_sym R L8P2 L24P7 ι7 ι7_res (h10_of g2) hne.2.2.2.2.2.2.2.1
  · exact unit_sym R L8P2 L24P8 ι8 ι8_res (h10_of g2) hne.2.2.2.2.2.2.2.2

end X2Y5Z7.Assembly.Q131
