/-
Generated by computer; every fact used is proved in Lean.
-/
import X2Y5Z7.Assembly.Basic
import X2Y5Z7.NotDvd.Q311
import X2Y5Z7.SymbolSets.Q311.Main

/-! # The auxiliary prime `q = 311`

For a solution with Putz root, `E` is a unit at the 11 primes of `L₂₄` above `311` and its symbol vector lies
in `SymbolSets.I311`: Corollary 5.5 (`q ∤ XYZ`) gives `311 ∤ 70XYZ`, the residues `t_i` of the Putz root at the 5 primes of `L₈`
form an admissible family (`Assembly.TFamily`), and Proposition 5.3 applies. -/

namespace X2Y5Z7.Assembly.Q311

open NumberField X2Y5Z7.FiniteFields X2Y5Z7.FiniteFields.Q311 X2Y5Z7.SymbolSets.Q311 X2Y5Z7.ResidueSymbols

theorem auxAt (s : Solution) (R : Aux.Root s) : Main.AuxAt L24P SymbolSets.I311 (Eu R) := by
  obtain ⟨hX, hY, hZ⟩ := NotDvd.Q311.not_dvd s R
  have g0 : (70 : L8P0.K) * s.X * s.Y * s.Z ≠ 0 := h70_of (q := 311) NotDvd.Q311.h70 hX hY hZ
  have g1 : (70 : L8P1.K) * s.X * s.Y * s.Z ≠ 0 := h70_of (q := 311) NotDvd.Q311.h70 hX hY hZ
  have g2 : (70 : L8P2.K) * s.X * s.Y * s.Z ≠ 0 := h70_of (q := 311) NotDvd.Q311.h70 hX hY hZ
  have g3 : (70 : L8P3.K) * s.X * s.Y * s.Z ≠ 0 := h70_of (q := 311) NotDvd.Q311.h70 hX hY hZ
  have g4 : (70 : L8P4.K) * s.X * s.Y * s.Z ≠ 0 := h70_of (q := 311) NotDvd.Q311.h70 hX hY hZ
  obtain ⟨hne, hI⟩ := symbols_mem (etaBar 311 s)
    (etaBar_ne_zero hX hZ)
    (etaBar_ne_one hY hZ)
    (tRes R L8P0.res)
    (tRes R L8P1.res)
    (tRes R L8P2.res)
    (tRes R L8P3.res)
    (tRes R L8P4.res)
    (fb_tRes (q := 311) R L8P0.res (h10_of g0))
    (fb_tRes (q := 311) R L8P1.res (h10_of g1))
    (fb_tRes (q := 311) R L8P2.res (h10_of g2))
    (fb_tRes (q := 311) R L8P3.res (h10_of g3))
    (fb_tRes (q := 311) R L8P4.res (h10_of g4))
    (by rw [t_natDegree (q := 311) R L8P0.res L8P0.res_surjective g0]; exact L8P0.finrank_K)
    (by rw [t_natDegree (q := 311) R L8P1.res L8P1.res_surjective g1]; exact L8P1.finrank_K)
    (by rw [t_natDegree (q := 311) R L8P2.res L8P2.res_surjective g2]; exact L8P2.finrank_K)
    (by rw [t_natDegree (q := 311) R L8P3.res L8P3.res_surjective g3]; exact L8P3.finrank_K)
    (by rw [t_natDegree (q := 311) R L8P4.res L8P4.res_surjective g4]; exact L8P4.finrank_K)
    (t_minpoly_ne (q := 311) R L8P0.res L8P1.res L8P0.res_surjective L8P1.res_surjective Primes.Q311.ker01 g0 g1)
    (t_minpoly_ne (q := 311) R L8P0.res L8P2.res L8P0.res_surjective L8P2.res_surjective Primes.Q311.ker02 g0 g2)
    (t_minpoly_ne (q := 311) R L8P0.res L8P3.res L8P0.res_surjective L8P3.res_surjective Primes.Q311.ker03 g0 g3)
    (t_minpoly_ne (q := 311) R L8P1.res L8P2.res L8P1.res_surjective L8P2.res_surjective Primes.Q311.ker12 g1 g2)
    (t_minpoly_ne (q := 311) R L8P1.res L8P3.res L8P1.res_surjective L8P3.res_surjective Primes.Q311.ker13 g1 g3)
    (t_minpoly_ne (q := 311) R L8P2.res L8P3.res L8P2.res_surjective L8P3.res_surjective Primes.Q311.ker23 g2 g3)
  refine auxAt_of _ _ _ _ hI ?_
  intro j
  fin_cases j
  · exact unit_sym R L8P0 L24P0 ι0 ι0_res (h10_of g0) hne.1
  · exact unit_sym R L8P0 L24P1 ι1 ι1_res (h10_of g0) hne.2.1
  · exact unit_sym R L8P1 L24P2 ι2 ι2_res (h10_of g1) hne.2.2.1
  · exact unit_sym R L8P1 L24P3 ι3 ι3_res (h10_of g1) hne.2.2.2.1
  · exact unit_sym R L8P2 L24P4 ι4 ι4_res (h10_of g2) hne.2.2.2.2.1
  · exact unit_sym R L8P2 L24P5 ι5 ι5_res (h10_of g2) hne.2.2.2.2.2.1
  · exact unit_sym R L8P3 L24P6 ι6 ι6_res (h10_of g3) hne.2.2.2.2.2.2.1
  · exact unit_sym R L8P3 L24P7 ι7 ι7_res (h10_of g3) hne.2.2.2.2.2.2.2.1
  · exact unit_sym R L8P4 L24P8 ι8 ι8_res (h10_of g4) hne.2.2.2.2.2.2.2.2.1
  · exact unit_sym R L8P4 L24P9 ι9 ι9_res (h10_of g4) hne.2.2.2.2.2.2.2.2.2.1
  · exact unit_sym R L8P4 L24P10 ι10 ι10_res (h10_of g4) hne.2.2.2.2.2.2.2.2.2.2

end X2Y5Z7.Assembly.Q311
