/-
Generated by computer; every fact used is proved in Lean.
-/
module

public import X2Y5Z7.SymbolSets.Q101.Data

@[expose] public section

/-! # Proposition 5.3 at `q = 101`: certificates for `η = 2 … 97` (61 R, 30 G, 5 F) -/

namespace X2Y5Z7.SymbolSets.Q101

open X2Y5Z7.SymbolSets

def k2 : Cert :=
  Cert.R [12]

theorem c2 : certCheck 101 D ILN 2 k2 = true := by decide +kernel

def k3 : Cert :=
  Cert.R [50]

theorem c3 : certCheck 101 D ILN 3 k3 = true := by decide +kernel

def k4 : Cert :=
  Cert.G 2 [1] [63, 91, 91, 12, 21, 41, 13] [68, 57, 1, 40, 57, 43, 78, 46]

theorem c4 : certCheck 101 D ILN 4 k4 = true := by decide +kernel

def k5 : Cert :=
  Cert.R [80]

theorem c5 : certCheck 101 D ILN 5 k5 = true := by decide +kernel

def k6 : Cert :=
  Cert.R [40]

theorem c6 : certCheck 101 D ILN 6 k6 = true := by decide +kernel

def k7 : Cert :=
  Cert.G 3 [1] [92, 45, 6, 78, 85, 39, 11] [31, 70, 57, 100, 13, 69, 32, 61]

theorem c7 : certCheck 101 D ILN 7 k7 = true := by decide +kernel

def k8 : Cert :=
  Cert.R [47]

theorem c8 : certCheck 101 D ILN 8 k8 = true := by decide +kernel

def k9 : Cert :=
  Cert.G 3 [1] [39, 7, 58, 81, 49, 70, 56] [91, 16, 3, 0, 100, 74, 60, 91]

theorem c9 : certCheck 101 D ILN 9 k9 = true := by decide +kernel

def k10 : Cert :=
  Cert.R [31]

theorem c10 : certCheck 101 D ILN 10 k10 = true := by decide +kernel

def k11 : Cert :=
  Cert.G 2 [1] [49, 0, 64, 92, 9, 3, 60] [94, 29, 2, 90, 7, 42, 85, 12]

theorem c11 : certCheck 101 D ILN 11 k11 = true := by decide +kernel

def k12 : Cert :=
  Cert.G 2 [1] [80, 4, 32, 34, 60, 70, 10] [82, 99, 50, 59, 6, 75, 18, 6]

theorem c12 : certCheck 101 D ILN 12 k12 = true := by decide +kernel

def k13 : Cert :=
  Cert.R [35]

theorem c13 : certCheck 101 D ILN 13 k13 = true := by decide +kernel

def k14 : Cert :=
  Cert.R [56]

theorem c14 : certCheck 101 D ILN 14 k14 = true := by decide +kernel

def k15 : Cert :=
  Cert.R [18]

theorem c15 : certCheck 101 D ILN 15 k15 = true := by decide +kernel

def k16 : Cert :=
  Cert.R [86]

theorem c16 : certCheck 101 D ILN 16 k16 = true := by decide +kernel

def k17 : Cert :=
  Cert.R [85]

theorem c17 : certCheck 101 D ILN 17 k17 = true := by decide +kernel

def k18 : Cert :=
  Cert.R [29]

theorem c18 : certCheck 101 D ILN 18 k18 = true := by decide +kernel

def k19 : Cert :=
  Cert.R [61]

theorem c19 : certCheck 101 D ILN 19 k19 = true := by decide +kernel

def k20 : Cert :=
  Cert.R [24]

theorem c20 : certCheck 101 D ILN 20 k20 = true := by decide +kernel

def k21 : Cert :=
  Cert.R [51]

theorem c21 : certCheck 101 D ILN 21 k21 = true := by decide +kernel

def k22 : Cert :=
  Cert.G 2 [1] [0, 70, 18, 43, 52, 38, 41] [35, 39, 41, 85, 39, 50, 55, 88]

theorem c22 : certCheck 101 D ILN 22 k22 = true := by decide +kernel

def k23 : Cert :=
  Cert.R [46]

theorem c23 : certCheck 101 D ILN 23 k23 = true := by decide +kernel

def k24 : Cert :=
  Cert.G 3 [1] [16, 63, 59, 78, 33, 34, 36] [72, 58, 53, 36, 97, 72, 91, 73]

theorem c24 : certCheck 101 D ILN 24 k24 = true := by decide +kernel

def k25 : Cert :=
  Cert.R [77]

theorem c25 : certCheck 101 D ILN 25 k25 = true := by decide +kernel

def k26 : Cert :=
  Cert.R [54]

theorem c26 : certCheck 101 D ILN 26 k26 = true := by decide +kernel

def k27 : Cert :=
  Cert.F [([24, 16, 1], [(1, [10, 77])]), ([70, 50, 28, 1], [(1, [83, 96, 33])]), ([99, 30, 78, 1], [(1, [40, 82, 83])])]
      [[(0, [([20, 10], [3, 4, 0, 0, 0, 0, 0]), ([65, 91], [3, 0, 4, 0, 0, 0, 0])])],
       [(1, [([15, 62, 42], [0, 0, 0, 2, 1, 0, 0]), ([9, 6, 71], [0, 0, 0, 2, 1, 0, 0]), ([49, 33, 89], [0, 0, 0, 2, 1, 0, 0])]), (2, [([21, 27, 13], [0, 0, 0, 2, 1, 0, 0]), ([50, 17, 91], [0, 0, 0, 2, 1, 0, 0]), ([53, 57, 98], [0, 0, 0, 2, 1, 0, 0])])],
       [(1, [([29, 50, 51], [0, 0, 0, 0, 0, 2, 1]), ([11, 78, 59], [0, 0, 0, 0, 0, 2, 1]), ([33, 74, 92], [0, 0, 0, 0, 0, 2, 1])]), (2, [([93, 1], [0, 0, 0, 0, 0, 2, 1]), ([46, 55, 28], [0, 0, 0, 0, 0, 2, 1]), ([86, 45, 73], [0, 0, 0, 0, 0, 2, 1])])]]

theorem c27 : certCheck 101 D ILN 27 k27 = true := by decide +kernel

def k28 : Cert :=
  Cert.R [25]

theorem c28 : certCheck 101 D ILN 28 k28 = true := by decide +kernel

def k29 : Cert :=
  Cert.R [28]

theorem c29 : certCheck 101 D ILN 29 k29 = true := by decide +kernel

def k30 : Cert :=
  Cert.R [1]

theorem c30 : certCheck 101 D ILN 30 k30 = true := by decide +kernel

def k31 : Cert :=
  Cert.G 2 [1] [92, 88, 50, 93, 72, 41, 77] [39, 32, 95, 82, 36, 74, 24, 69]

theorem c31 : certCheck 101 D ILN 31 k31 = true := by decide +kernel

def k32 : Cert :=
  Cert.G 3 [1] [66, 38, 2, 47, 4, 70, 19] [4, 32, 52, 59, 44, 95, 44, 36]

theorem c32 : certCheck 101 D ILN 32 k32 = true := by decide +kernel

def k33 : Cert :=
  Cert.F [([81, 29, 1], [(1, [6, 84])]), ([96, 72, 46, 1], [(1, [87, 70, 7])]), ([33, 83, 47, 1], [(1, [78, 1, 46])])]
      [[(0, [([69, 19], [2, 1, 4, 0, 0, 0, 0]), ([3, 82], [2, 4, 1, 0, 0, 0, 0])])],
       [(1, [([67, 28, 13], [0, 0, 0, 1, 2, 0, 0]), ([22, 89, 36], [0, 0, 0, 1, 2, 0, 0]), ([67, 85, 52], [0, 0, 0, 1, 2, 0, 0])]), (2, [([40, 69, 52], [0, 0, 0, 4, 4, 0, 0]), ([2, 45, 65], [0, 0, 0, 4, 4, 0, 0]), ([12, 88, 85], [0, 0, 0, 4, 4, 0, 0])])],
       [(1, [([27, 22, 8], [0, 0, 0, 0, 0, 1, 2]), ([83, 9, 26], [0, 0, 0, 0, 0, 1, 2]), ([46, 70, 67], [0, 0, 0, 0, 0, 1, 2])]), (2, [([18, 13, 21], [0, 0, 0, 0, 0, 4, 4]), ([49, 93, 84], [0, 0, 0, 0, 0, 4, 4]), ([88, 96, 97], [0, 0, 0, 0, 0, 4, 4])])]]

theorem c33 : certCheck 101 D ILN 33 k33 = true := by decide +kernel

def k34 : Cert :=
  Cert.R [6]

theorem c34 : certCheck 101 D ILN 34 k34 = true := by decide +kernel

def k35 : Cert :=
  Cert.G 2 [1] [12, 6, 72, 25, 56, 72, 76] [43, 60, 96, 83, 10, 59, 14, 85]

theorem c35 : certCheck 101 D ILN 35 k35 = true := by decide +kernel

def k36 : Cert :=
  Cert.R [14]

theorem c36 : certCheck 101 D ILN 36 k36 = true := by decide +kernel

def k37 : Cert :=
  Cert.G 2 [1] [100, 77, 84, 5, 30, 71, 92] [78, 63, 2, 21, 22, 10, 0, 43]

theorem c37 : certCheck 101 D ILN 37 k37 = true := by decide +kernel

def k38 : Cert :=
  Cert.G 2 [1] [11, 62, 66, 53, 14, 28, 76] [9, 13, 18, 57, 42, 30, 80, 24]

theorem c38 : certCheck 101 D ILN 38 k38 = true := by decide +kernel

def k39 : Cert :=
  Cert.R [3]

theorem c39 : certCheck 101 D ILN 39 k39 = true := by decide +kernel

def k40 : Cert :=
  Cert.R [58]

theorem c40 : certCheck 101 D ILN 40 k40 = true := by decide +kernel

def k41 : Cert :=
  Cert.R [69]

theorem c41 : certCheck 101 D ILN 41 k41 = true := by decide +kernel

def k42 : Cert :=
  Cert.G 3 [1] [62, 46, 33, 37, 46, 86, 6] [31, 22, 54, 14, 17, 71, 67, 70]

theorem c42 : certCheck 101 D ILN 42 k42 = true := by decide +kernel

def k43 : Cert :=
  Cert.R [79]

theorem c43 : certCheck 101 D ILN 43 k43 = true := by decide +kernel

def k44 : Cert :=
  Cert.R [71]

theorem c44 : certCheck 101 D ILN 44 k44 = true := by decide +kernel

def k45 : Cert :=
  Cert.G 2 [1] [19, 53, 57, 88, 17, 24, 97] [39, 25, 63, 19, 23, 42, 35, 67]

theorem c45 : certCheck 101 D ILN 45 k45 = true := by decide +kernel

def k46 : Cert :=
  Cert.R [5]

theorem c46 : certCheck 101 D ILN 46 k46 = true := by decide +kernel

def k47 : Cert :=
  Cert.G 2 [1] [21, 52, 3, 79, 30, 16] [24, 39, 98, 30, 42, 56, 75, 62]

theorem c47 : certCheck 101 D ILN 47 k47 = true := by decide +kernel

def k48 : Cert :=
  Cert.R [20]

theorem c48 : certCheck 101 D ILN 48 k48 = true := by decide +kernel

def k49 : Cert :=
  Cert.R [44]

theorem c49 : certCheck 101 D ILN 49 k49 = true := by decide +kernel

def k50 : Cert :=
  Cert.F [([33, 99, 1], [(1, [71, 30])]), ([57, 16, 54, 1], [(1, [92, 62, 100])]), ([97, 100, 70, 1], [(1, [73, 9, 39])])]
      [[(0, [([11, 18], [4, 3, 0, 0, 0, 0, 0]), ([92, 83], [4, 0, 3, 0, 0, 0, 0])])],
       [(1, [([24, 40, 8], [0, 0, 0, 1, 2, 0, 0]), ([75, 16, 44], [0, 0, 0, 1, 2, 0, 0]), ([49, 45, 49], [0, 0, 0, 1, 2, 0, 0])]), (2, [([67, 26, 53], [0, 0, 0, 2, 1, 0, 0]), ([75, 68, 54], [0, 0, 0, 2, 1, 0, 0]), ([91, 7, 95], [0, 0, 0, 2, 1, 0, 0])])],
       [(1, [([64, 9, 2], [0, 0, 0, 0, 0, 1, 2]), ([81, 8, 39], [0, 0, 0, 0, 0, 1, 2]), ([3, 84, 60], [0, 0, 0, 0, 0, 1, 2])]), (2, [([9, 62, 1], [0, 0, 0, 0, 0, 2, 1]), ([81, 54, 36], [0, 0, 0, 0, 0, 2, 1]), ([42, 86, 64], [0, 0, 0, 0, 0, 2, 1])])]]

theorem c50 : certCheck 101 D ILN 50 k50 = true := by decide +kernel

def k51 : Cert :=
  Cert.R [34]

theorem c51 : certCheck 101 D ILN 51 k51 = true := by decide +kernel

def k52 : Cert :=
  Cert.R [15]

theorem c52 : certCheck 101 D ILN 52 k52 = true := by decide +kernel

def k53 : Cert :=
  Cert.R [95]

theorem c53 : certCheck 101 D ILN 53 k53 = true := by decide +kernel

def k54 : Cert :=
  Cert.R [83]

theorem c54 : certCheck 101 D ILN 54 k54 = true := by decide +kernel

def k55 : Cert :=
  Cert.R [53]

theorem c55 : certCheck 101 D ILN 55 k55 = true := by decide +kernel

def k56 : Cert :=
  Cert.R [49]

theorem c56 : certCheck 101 D ILN 56 k56 = true := by decide +kernel

def k57 : Cert :=
  Cert.R [59]

theorem c57 : certCheck 101 D ILN 57 k57 = true := by decide +kernel

def k58 : Cert :=
  Cert.G 2 [1] [82, 53, 34, 64, 42, 16, 96] [42, 43, 98, 17, 3, 4, 74, 7]

theorem c58 : certCheck 101 D ILN 58 k58 = true := by decide +kernel

def k59 : Cert :=
  Cert.G 2 [1] [96, 87, 18, 56, 60, 31, 3] [90, 42, 53, 96, 0, 89, 22, 50]

theorem c59 : certCheck 101 D ILN 59 k59 = true := by decide +kernel

def k60 : Cert :=
  Cert.R [48]

theorem c60 : certCheck 101 D ILN 60 k60 = true := by decide +kernel

def k61 : Cert :=
  Cert.G 2 [1] [47, 12, 50, 100, 40, 92, 61] [76, 10, 1, 5, 30, 28, 92, 64]

theorem c61 : certCheck 101 D ILN 61 k61 = true := by decide +kernel

def k62 : Cert :=
  Cert.G 2 [1] [38, 30, 41, 23, 91, 16, 48] [31, 23, 81, 48, 79, 69, 14, 3]

theorem c62 : certCheck 101 D ILN 62 k62 = true := by decide +kernel

def k63 : Cert :=
  Cert.R [13]

theorem c63 : certCheck 101 D ILN 63 k63 = true := by decide +kernel

def k64 : Cert :=
  Cert.G 3 [1] [92, 57, 72, 95, 46, 3, 16] [89, 29, 12, 24, 30, 80, 57, 30]

theorem c64 : certCheck 101 D ILN 64 k64 = true := by decide +kernel

def k65 : Cert :=
  Cert.F [([5, 82, 1], [(1, [51, 85])]), ([8, 41, 6, 1], [(1, [77, 15, 37])]), ([11, 50, 34, 1], [(1, [33, 72, 73])])]
      [[(0, [([19, 7], [3, 2, 2, 0, 0, 0, 0]), ([0, 94], [3, 2, 2, 0, 0, 0, 0])])],
       [(1, [([67, 1], [0, 0, 0, 0, 3, 0, 0]), ([94, 72, 46], [0, 0, 0, 0, 3, 0, 0]), ([35, 28, 55], [0, 0, 0, 0, 3, 0, 0])]), (2, [([41, 66, 46], [0, 0, 0, 4, 4, 0, 0]), ([4, 35, 74], [0, 0, 0, 4, 4, 0, 0]), ([22, 0, 82], [0, 0, 0, 4, 4, 0, 0])])],
       [(1, [([11, 8, 26], [0, 0, 0, 0, 0, 0, 3]), ([2, 68, 81], [0, 0, 0, 0, 0, 0, 3]), ([82, 25, 95], [0, 0, 0, 0, 0, 0, 3])]), (2, [([61, 19, 16], [0, 0, 0, 0, 0, 4, 4]), ([62, 78, 40], [0, 0, 0, 0, 0, 4, 4]), ([45, 4, 45], [0, 0, 0, 0, 0, 4, 4])])]]

theorem c65 : certCheck 101 D ILN 65 k65 = true := by decide +kernel

def k66 : Cert :=
  Cert.G 2 [1] [86, 97, 1, 63, 51, 4, 67] [99, 14, 62, 46, 18, 46, 35, 2]

theorem c66 : certCheck 101 D ILN 66 k66 = true := by decide +kernel

def k67 : Cert :=
  Cert.R [7]

theorem c67 : certCheck 101 D ILN 67 k67 = true := by decide +kernel

def k68 : Cert :=
  Cert.R [32]

theorem c68 : certCheck 101 D ILN 68 k68 = true := by decide +kernel

def k69 : Cert :=
  Cert.G 2 [1] [56, 92, 64, 33, 41, 6, 17] [47, 80, 12, 2, 61, 17, 81, 43]

theorem c69 : certCheck 101 D ILN 69 k69 = true := by decide +kernel

def k70 : Cert :=
  Cert.R [19]

theorem c70 : certCheck 101 D ILN 70 k70 = true := by decide +kernel

def k71 : Cert :=
  Cert.R [22]

theorem c71 : certCheck 101 D ILN 71 k71 = true := by decide +kernel

def k72 : Cert :=
  Cert.G 2 [1] [52, 46, 46, 68, 19, 1, 30] [47, 26, 1, 35, 10, 95, 23, 9]

theorem c72 : certCheck 101 D ILN 72 k72 = true := by decide +kernel

def k73 : Cert :=
  Cert.R [26]

theorem c73 : certCheck 101 D ILN 73 k73 = true := by decide +kernel

def k74 : Cert :=
  Cert.G 2 [1] [96, 81, 15, 75, 22, 72, 18] [24, 94, 83, 27, 85, 36, 63, 30]

theorem c74 : certCheck 101 D ILN 74 k74 = true := by decide +kernel

def k75 : Cert :=
  Cert.R [17]

theorem c75 : certCheck 101 D ILN 75 k75 = true := by decide +kernel

def k76 : Cert :=
  Cert.R [23]

theorem c76 : certCheck 101 D ILN 76 k76 = true := by decide +kernel

def k77 : Cert :=
  Cert.G 2 [1] [12, 64, 87, 51, 83, 74, 9] [56, 82, 9, 82, 22, 69, 7, 32]

theorem c77 : certCheck 101 D ILN 77 k77 = true := by decide +kernel

def k78 : Cert :=
  Cert.G 2 [1] [36, 93, 80, 95, 38, 16, 58] [35, 97, 22, 16, 64, 97, 48, 54]

theorem c78 : certCheck 101 D ILN 78 k78 = true := by decide +kernel

def k79 : Cert :=
  Cert.R [67]

theorem c79 : certCheck 101 D ILN 79 k79 = true := by decide +kernel

def k80 : Cert :=
  Cert.R [11]

theorem c80 : certCheck 101 D ILN 80 k80 = true := by decide +kernel

def k81 : Cert :=
  Cert.R [90]

theorem c81 : certCheck 101 D ILN 81 k81 = true := by decide +kernel

def k82 : Cert :=
  Cert.R [45]

theorem c82 : certCheck 101 D ILN 82 k82 = true := by decide +kernel

def k83 : Cert :=
  Cert.R [72]

theorem c83 : certCheck 101 D ILN 83 k83 = true := by decide +kernel

def k84 : Cert :=
  Cert.G 3 [1] [56, 87, 72, 92, 72, 16, 37] [62, 4, 3, 17, 29, 85, 69, 30]

theorem c84 : certCheck 101 D ILN 84 k84 = true := by decide +kernel

def k85 : Cert :=
  Cert.R [92]

theorem c85 : certCheck 101 D ILN 85 k85 = true := by decide +kernel

def k86 : Cert :=
  Cert.G 2 [1] [98, 39, 26, 64, 81, 31, 25] [66, 34, 48, 79, 40, 27, 0, 19]

theorem c86 : certCheck 101 D ILN 86 k86 = true := by decide +kernel

def k87 : Cert :=
  Cert.G 2 [1] [9, 56, 70, 37, 94, 66, 29] [28, 3, 79, 20, 55, 37, 63, 60]

theorem c87 : certCheck 101 D ILN 87 k87 = true := by decide +kernel

def k88 : Cert :=
  Cert.R [8]

theorem c88 : certCheck 101 D ILN 88 k88 = true := by decide +kernel

def k89 : Cert :=
  Cert.F [([76, 25, 1], [(1, [94, 56])]), ([9, 43, 32, 1], [(1, [100, 13, 60])]), ([39, 67, 65, 1], [(1, [100, 98, 70])])]
      [[(0, [([25, 17], [0, 2, 0, 0, 0, 0, 0]), ([51, 84], [0, 0, 2, 0, 0, 0, 0])])],
       [(1, [([100, 47, 25], [0, 0, 0, 3, 0, 0, 0]), ([85, 90, 34], [0, 0, 0, 3, 0, 0, 0]), ([86, 65, 42], [0, 0, 0, 3, 0, 0, 0])]), (2, [([61, 40, 3], [0, 0, 0, 4, 4, 0, 0]), ([86, 89, 5], [0, 0, 0, 4, 4, 0, 0]), ([91, 73, 93], [0, 0, 0, 4, 4, 0, 0])])],
       [(1, [([33, 74, 28], [0, 0, 0, 0, 0, 3, 0]), ([48, 48, 74], [0, 0, 0, 0, 0, 3, 0]), ([89, 80, 100], [0, 0, 0, 0, 0, 3, 0])]), (2, [([86, 87, 7], [0, 0, 0, 0, 0, 4, 4]), ([62, 0, 24], [0, 0, 0, 0, 0, 4, 4]), ([90, 14, 70], [0, 0, 0, 0, 0, 4, 4])])]]

theorem c89 : certCheck 101 D ILN 89 k89 = true := by decide +kernel

def k90 : Cert :=
  Cert.R [4]

theorem c90 : certCheck 101 D ILN 90 k90 = true := by decide +kernel

def k91 : Cert :=
  Cert.R [9]

theorem c91 : certCheck 101 D ILN 91 k91 = true := by decide +kernel

def k92 : Cert :=
  Cert.R [30]

theorem c92 : certCheck 101 D ILN 92 k92 = true := by decide +kernel

def k93 : Cert :=
  Cert.R [60]

theorem c93 : certCheck 101 D ILN 93 k93 = true := by decide +kernel

def k94 : Cert :=
  Cert.R [88]

theorem c94 : certCheck 101 D ILN 94 k94 = true := by decide +kernel

def k95 : Cert :=
  Cert.G 2 [1] [30, 29, 24, 77, 95, 33, 85] [80, 82, 31, 26, 65, 76, 93, 90]

theorem c95 : certCheck 101 D ILN 95 k95 = true := by decide +kernel

def k96 : Cert :=
  Cert.R [27]

theorem c96 : certCheck 101 D ILN 96 k96 = true := by decide +kernel

def k97 : Cert :=
  Cert.R [39]

theorem c97 : certCheck 101 D ILN 97 k97 = true := by decide +kernel

def certs0 : List (ℕ × Cert) := [(2, k2), (3, k3), (4, k4), (5, k5), (6, k6), (7, k7), (8, k8), (9, k9), (10, k10), (11, k11), (12, k12), (13, k13), (14, k14), (15, k15), (16, k16), (17, k17), (18, k18), (19, k19), (20, k20), (21, k21), (22, k22), (23, k23), (24, k24), (25, k25), (26, k26), (27, k27), (28, k28), (29, k29), (30, k30), (31, k31), (32, k32), (33, k33), (34, k34), (35, k35), (36, k36), (37, k37), (38, k38), (39, k39), (40, k40), (41, k41), (42, k42), (43, k43), (44, k44), (45, k45), (46, k46), (47, k47), (48, k48), (49, k49), (50, k50), (51, k51), (52, k52), (53, k53), (54, k54), (55, k55), (56, k56), (57, k57), (58, k58), (59, k59), (60, k60), (61, k61), (62, k62), (63, k63), (64, k64), (65, k65), (66, k66), (67, k67), (68, k68), (69, k69), (70, k70), (71, k71), (72, k72), (73, k73), (74, k74), (75, k75), (76, k76), (77, k77), (78, k78), (79, k79), (80, k80), (81, k81), (82, k82), (83, k83), (84, k84), (85, k85), (86, k86), (87, k87), (88, k88), (89, k89), (90, k90), (91, k91), (92, k92), (93, k93), (94, k94), (95, k95), (96, k96), (97, k97)]

theorem ok0 : certs0.all (fun p => certCheck 101 D ILN p.1 p.2) = true := by
  simp only [certs0, List.all_cons, List.all_nil, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31, c32, c33, c34, c35, c36, c37, c38, c39, c40, c41, c42, c43, c44, c45, c46, c47, c48, c49, c50, c51, c52, c53, c54, c55, c56, c57, c58, c59, c60, c61, c62, c63, c64, c65, c66, c67, c68, c69, c70, c71, c72, c73, c74, c75, c76, c77, c78, c79, c80, c81, c82, c83, c84, c85, c86, c87, c88, c89, c90, c91, c92, c93, c94, c95, c96, c97, Bool.and_self]

end X2Y5Z7.SymbolSets.Q101
