/-
Generated by computer; every fact used is proved in Lean.
-/
import X2Y5Z7.SymbolSets.Q101.C0

/-! # Proposition 5.3 at `q = 101`: certificates for `η = 98 … 100` (2 R, 1 G, 0 F) -/

namespace X2Y5Z7.SymbolSets.Q101

open X2Y5Z7.SymbolSets

def k98 : Cert :=
  Cert.G 2 [1] [71, 3, 24, 43, 84, 26, 13] [21, 13, 92, 16, 62, 73, 90, 20]

theorem c98 : certCheck 101 D ILN 98 k98 = true := by decide +kernel

def k99 : Cert :=
  Cert.R [91]

theorem c99 : certCheck 101 D ILN 99 k99 = true := by decide +kernel

def k100 : Cert :=
  Cert.R [84]

theorem c100 : certCheck 101 D ILN 100 k100 = true := by decide +kernel

def certs1 : List (ℕ × Cert) := [(98, k98), (99, k99), (100, k100)]

theorem ok1 : certs1.all (fun p => certCheck 101 D ILN p.1 p.2) = true := by
  simp only [certs1, List.all_cons, List.all_nil, c98, c99, c100, Bool.and_self]

end X2Y5Z7.SymbolSets.Q101
