/-
Generated by computer; every fact used is proved in Lean.
-/
module

public import X2Y5Z7.SymbolSets.Check

@[expose] public section

/-! # Proposition 5.3 at `q = 101`: the residue-field data and the vectors of `I(101)` -/

namespace X2Y5Z7.SymbolSets.Q101

open X2Y5Z7.SymbolSets X2Y5Z7.FiniteFields

/-- The models of `X2Y5Z7/FiniteFields/Q101.lean`: `H i` = `(L8P i).P`, `P k` = `(L24P k).P`, `If k` = `(L24P k).i - 1`. -/
def D : Data 3 7 where
  zeta := 95
  H := ![[64, 46, 1], [81, 71, 5, 1], [97, 85, 54, 1]]
  P := ![[64, 46, 1], [64, 46, 1], [64, 46, 1], [81, 71, 5, 1], [1, 1, 1, 1, 1, 1, 1], [97, 85, 54, 1], [1, 1, 1, 1, 1, 1, 1]]
  If := ![0, 0, 0, 1, 1, 2, 2]
  alpha := ![[0, 1], [0, 1], [0, 1], [0, 1, 0], [40, 0, 1, 23, 23, 1], [0, 1, 0], [35, 0, 48, 10, 10, 48]]
  beta := ![[62, 0], [3, 70], [15, 31], [62, 0, 0], [24, 30, 30, 0, 30, 0], [62, 0, 0], [24, 30, 30, 0, 30, 0]]

/-- The vectors of `I(101)` (as in `SymbolSets.I101L`). -/
def ILN : List (List ℕ) :=
  [[0, 0, 2, 3, 0, 4, 4],
   [0, 0, 2, 4, 4, 3, 0],
   [0, 2, 0, 3, 0, 4, 4],
   [0, 2, 0, 4, 4, 3, 0],
   [2, 1, 4, 1, 2, 4, 4],
   [2, 1, 4, 4, 4, 1, 2],
   [2, 4, 1, 1, 2, 4, 4],
   [2, 4, 1, 4, 4, 1, 2],
   [3, 0, 4, 2, 1, 2, 1],
   [3, 2, 2, 0, 3, 4, 4],
   [3, 2, 2, 4, 4, 0, 3],
   [3, 4, 0, 2, 1, 2, 1],
   [4, 0, 3, 1, 2, 2, 1],
   [4, 0, 3, 2, 1, 1, 2],
   [4, 3, 0, 1, 2, 2, 1],
   [4, 3, 0, 2, 1, 1, 2]]

theorem dataOK : dataCheck 101 D = true := by decide +kernel

end X2Y5Z7.SymbolSets.Q101
