/-
Generated by computer; every fact used is proved in Lean.
-/
import X2Y5Z7.SymbolSets.Q101.C1
import X2Y5Z7.SymbolSets.Compat
import X2Y5Z7.FiniteFields.Q101
import X2Y5Z7.SymbolSets.Sets

/-! # Proposition 5.3 at `q = 101`

Proposition 5.3: for every `η ∈ F_101 ∖ {0, 1}` and every admissible family `t_i ∈ k_i = (L8P i).K` (roots of
`fb η t = 100t⁸ + 80t⁷ + 56t⁶ + 56t⁵ - 4ηt + η`, `deg minpoly t_i = d_i`, distinct minimal polynomials for primes of
the same degree), the elements `E_k = Ev<k> t_(i_k)` (`= 80000 (ι_k t - β_k) ψ(ι_k t)³`) are nonzero and the vector of
their symbols `(L24P k).sym` lies in `SymbolSets.I101`. Here `ι<k> : (L8P i_k).K →+* (L24P k).K` sends `x ↦ α_k`, and
`ι<k>_res` is its compatibility with the residue maps of `X2Y5Z7/FiniteFields/Residue.lean`. -/

namespace X2Y5Z7.SymbolSets.Q101

open X2Y5Z7.SymbolSets X2Y5Z7.FiniteFields X2Y5Z7.FiniteFields.Q101 Polynomial NumberField

noncomputable instance instAlgL8P0 : Algebra (ZMod 101) L8P0.K := inferInstanceAs (Algebra (ZMod 101) (AdjoinRoot (toPoly 101 (D.H 0))))
noncomputable instance instAlgL8P1 : Algebra (ZMod 101) L8P1.K := inferInstanceAs (Algebra (ZMod 101) (AdjoinRoot (toPoly 101 (D.H 1))))
noncomputable instance instAlgL8P2 : Algebra (ZMod 101) L8P2.K := inferInstanceAs (Algebra (ZMod 101) (AdjoinRoot (toPoly 101 (D.H 2))))

instance factH (i : Fin 3) : Fact (Irreducible (toPoly 101 (D.H i))) := ⟨by
  fin_cases i
  · exact L8P0.irred
  · exact L8P1.irred
  · exact L8P2.irred⟩

instance factP (k : Fin 7) : Fact (Irreducible (toPoly 101 (D.P k))) := ⟨by
  fin_cases k
  · exact L24P0.irred
  · exact L24P1.irred
  · exact L24P2.irred
  · exact L24P3.irred
  · exact L24P4.irred
  · exact L24P5.irred
  · exact L24P6.irred⟩

def certs : List (ℕ × Cert) := certs0 ++ certs1

theorem certsOK : certs.all (fun p => certCheck 101 D ILN p.1 p.2) = true := by
  simp only [certs, List.all_append, ok0, ok1, Bool.and_self]

theorem covOK (e : ℕ) (h2 : 2 ≤ e) (hq : e < 101) : e ∈ certs.map Prod.fst := by
  have h : certs.map Prod.fst = List.range' 2 99 := by decide +kernel
  rw [h, List.mem_range'_1]; omega

theorem ilOK : ilCheck 7 ILN SymbolSets.I101L = true := by decide +kernel

/-- `ι_0 : k_0 → K_0`, `x ↦ α`. -/
noncomputable def ι0 : L8P0.K →+* L24P0.K := iotaD 101 D dataOK 0

theorem ι0_x : ι0 L8P0.x = L24P0.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 101 D dataOK 0

theorem ι0_res (y : 𝓞 L8) : ι0 (L8P0.res y) = L24P0.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P0 L24P0 ι0 ι0_x y

/-- `E_0(t) = 80000 (ι_0 t - β) (25 (ι_0 t)³ + 20 (ι_0 t)² + 14 ι_0 t + 14)³`. -/
noncomputable def Ev0 (t : L8P0.K) : L24P0.K := EvD 101 D dataOK 0 t

theorem Ev0_eq (t : L8P0.K) : Ev0 t =
    80000 * (ι0 t - L24P0.β) * (25 * ι0 t ^ 3 + 20 * ι0 t ^ 2 + 14 * ι0 t + 14) ^ 3 := rfl

/-- `ι_1 : k_0 → K_1`, `x ↦ α`. -/
noncomputable def ι1 : L8P0.K →+* L24P1.K := iotaD 101 D dataOK 1

theorem ι1_x : ι1 L8P0.x = L24P1.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 101 D dataOK 1

theorem ι1_res (y : 𝓞 L8) : ι1 (L8P0.res y) = L24P1.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P0 L24P1 ι1 ι1_x y

/-- `E_1(t) = 80000 (ι_1 t - β) (25 (ι_1 t)³ + 20 (ι_1 t)² + 14 ι_1 t + 14)³`. -/
noncomputable def Ev1 (t : L8P0.K) : L24P1.K := EvD 101 D dataOK 1 t

theorem Ev1_eq (t : L8P0.K) : Ev1 t =
    80000 * (ι1 t - L24P1.β) * (25 * ι1 t ^ 3 + 20 * ι1 t ^ 2 + 14 * ι1 t + 14) ^ 3 := rfl

/-- `ι_2 : k_0 → K_2`, `x ↦ α`. -/
noncomputable def ι2 : L8P0.K →+* L24P2.K := iotaD 101 D dataOK 2

theorem ι2_x : ι2 L8P0.x = L24P2.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 101 D dataOK 2

theorem ι2_res (y : 𝓞 L8) : ι2 (L8P0.res y) = L24P2.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P0 L24P2 ι2 ι2_x y

/-- `E_2(t) = 80000 (ι_2 t - β) (25 (ι_2 t)³ + 20 (ι_2 t)² + 14 ι_2 t + 14)³`. -/
noncomputable def Ev2 (t : L8P0.K) : L24P2.K := EvD 101 D dataOK 2 t

theorem Ev2_eq (t : L8P0.K) : Ev2 t =
    80000 * (ι2 t - L24P2.β) * (25 * ι2 t ^ 3 + 20 * ι2 t ^ 2 + 14 * ι2 t + 14) ^ 3 := rfl

/-- `ι_3 : k_1 → K_3`, `x ↦ α`. -/
noncomputable def ι3 : L8P1.K →+* L24P3.K := iotaD 101 D dataOK 3

theorem ι3_x : ι3 L8P1.x = L24P3.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 101 D dataOK 3

theorem ι3_res (y : 𝓞 L8) : ι3 (L8P1.res y) = L24P3.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P1 L24P3 ι3 ι3_x y

/-- `E_3(t) = 80000 (ι_3 t - β) (25 (ι_3 t)³ + 20 (ι_3 t)² + 14 ι_3 t + 14)³`. -/
noncomputable def Ev3 (t : L8P1.K) : L24P3.K := EvD 101 D dataOK 3 t

theorem Ev3_eq (t : L8P1.K) : Ev3 t =
    80000 * (ι3 t - L24P3.β) * (25 * ι3 t ^ 3 + 20 * ι3 t ^ 2 + 14 * ι3 t + 14) ^ 3 := rfl

/-- `ι_4 : k_1 → K_4`, `x ↦ α`. -/
noncomputable def ι4 : L8P1.K →+* L24P4.K := iotaD 101 D dataOK 4

theorem ι4_x : ι4 L8P1.x = L24P4.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 101 D dataOK 4

theorem ι4_res (y : 𝓞 L8) : ι4 (L8P1.res y) = L24P4.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P1 L24P4 ι4 ι4_x y

/-- `E_4(t) = 80000 (ι_4 t - β) (25 (ι_4 t)³ + 20 (ι_4 t)² + 14 ι_4 t + 14)³`. -/
noncomputable def Ev4 (t : L8P1.K) : L24P4.K := EvD 101 D dataOK 4 t

theorem Ev4_eq (t : L8P1.K) : Ev4 t =
    80000 * (ι4 t - L24P4.β) * (25 * ι4 t ^ 3 + 20 * ι4 t ^ 2 + 14 * ι4 t + 14) ^ 3 := rfl

/-- `ι_5 : k_2 → K_5`, `x ↦ α`. -/
noncomputable def ι5 : L8P2.K →+* L24P5.K := iotaD 101 D dataOK 5

theorem ι5_x : ι5 L8P2.x = L24P5.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 101 D dataOK 5

theorem ι5_res (y : 𝓞 L8) : ι5 (L8P2.res y) = L24P5.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P2 L24P5 ι5 ι5_x y

/-- `E_5(t) = 80000 (ι_5 t - β) (25 (ι_5 t)³ + 20 (ι_5 t)² + 14 ι_5 t + 14)³`. -/
noncomputable def Ev5 (t : L8P2.K) : L24P5.K := EvD 101 D dataOK 5 t

theorem Ev5_eq (t : L8P2.K) : Ev5 t =
    80000 * (ι5 t - L24P5.β) * (25 * ι5 t ^ 3 + 20 * ι5 t ^ 2 + 14 * ι5 t + 14) ^ 3 := rfl

/-- `ι_6 : k_2 → K_6`, `x ↦ α`. -/
noncomputable def ι6 : L8P2.K →+* L24P6.K := iotaD 101 D dataOK 6

theorem ι6_x : ι6 L8P2.x = L24P6.α := by
  rw [L8Prime.x_eq_root]; exact iotaD_root 101 D dataOK 6

theorem ι6_res (y : 𝓞 L8) : ι6 (L8P2.res y) = L24P6.res (algebraMap (𝓞 L8) (𝓞 L24) y) :=
  iota_res L8P2 L24P6 ι6 ι6_x y

/-- `E_6(t) = 80000 (ι_6 t - β) (25 (ι_6 t)³ + 20 (ι_6 t)² + 14 ι_6 t + 14)³`. -/
noncomputable def Ev6 (t : L8P2.K) : L24P6.K := EvD 101 D dataOK 6 t

theorem Ev6_eq (t : L8P2.K) : Ev6 t =
    80000 * (ι6 t - L24P6.β) * (25 * ι6 t ^ 3 + 20 * ι6 t ^ 2 + 14 * ι6 t + 14) ^ 3 := rfl

/-- The family as a dependent function on `Fin 3`. -/
noncomputable def tup (t0 : L8P0.K) (t1 : L8P1.K) (t2 : L8P2.K) : ∀ i : Fin 3, AdjoinRoot (toPoly 101 (D.H i))
  | ⟨0, _⟩ => t0
  | ⟨1, _⟩ => t1
  | ⟨2, _⟩ => t2
  | ⟨_ + 3, h⟩ => absurd h (by omega)

theorem symbols_mem (η : ZMod 101) (h0 : η ≠ 0) (h1 : η ≠ 1)
    (t0 : L8P0.K) (t1 : L8P1.K) (t2 : L8P2.K)
    (r0 : fb η t0 = 0) (r1 : fb η t1 = 0) (r2 : fb η t2 = 0)
    (d0 : (minpoly (ZMod 101) t0).natDegree = 2)
    (d1 : (minpoly (ZMod 101) t1).natDegree = 3)
    (d2 : (minpoly (ZMod 101) t2).natDegree = 3)
    (n12 : minpoly (ZMod 101) t1 ≠ minpoly (ZMod 101) t2)
    :
    (Ev0 t0 ≠ 0 ∧ Ev1 t0 ≠ 0 ∧ Ev2 t0 ≠ 0 ∧ Ev3 t1 ≠ 0 ∧ Ev4 t1 ≠ 0 ∧ Ev5 t2 ≠ 0 ∧ Ev6 t2 ≠ 0) ∧
    ![L24P0.sym (Ev0 t0), L24P1.sym (Ev1 t0), L24P2.sym (Ev2 t0), L24P3.sym (Ev3 t1), L24P4.sym (Ev4 t1), L24P5.sym (Ev5 t2), L24P6.sym (Ev6 t2)] ∈ SymbolSets.I101 := by
  have hm := main 101 D dataOK ILN SymbolSets.I101L ilOK certs certsOK covOK η h0 h1 (tup t0 t1 t2)
    (by intro i; fin_cases i
        · exact r0
        · exact r1
        · exact r2
      )
    (by intro i; fin_cases i
        · exact d0
        · exact d1
        · exact d2
      )
    (by
      intro i j hij hdd
      fin_cases i <;> fin_cases j
      · exact absurd rfl hij
      · exact absurd hdd (by decide)
      · exact absurd hdd (by decide)
      · exact absurd hdd (by decide)
      · exact absurd rfl hij
      · exact n12
      · exact absurd hdd (by decide)
      · exact (n12).symm
      · exact absurd rfl hij
      )
  obtain ⟨hne, w, hw, hwe⟩ := hm
  refine ⟨⟨hne 0, hne 1, hne 2, hne 3, hne 4, hne 5, hne 6⟩, ?_⟩
  rw [SymbolSets.I101, List.mem_toFinset]
  convert hw using 1
  rw [hwe]
  funext k
  fin_cases k <;> rfl

end X2Y5Z7.SymbolSets.Q101
