/-
Generated by computer; every fact used is proved in Lean.
-/
import X2Y5Z7.FiniteFields.Model

/-! # Residue-field models at `q = 101`

`3` primes of `L8` (`L8P : Fin 3 → L8Prime`) and `7` primes of `L24` (`L24P : Fin 7 → L24Prime`),
in the order of `models.txt`; `M : Matrix (Fin 7) (Fin 24) (ZMod 5)` is the symbol matrix, and
`sym_M : (L24P k).sym ((L24P k).imgB j) = M k j`. Every fact is checked by `decide +kernel`. -/

namespace X2Y5Z7.FiniteFields.Q101

open X2Y5Z7.FiniteFields

theorem prime : Nat.Prime 101 := by norm_num

instance : Fact (Nat.Prime 101) := ⟨prime⟩

theorem irr0 : Irreducible (toPoly 101 [64, 46, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [47, 24])]) (by decide +kernel)

theorem irr1 : Irreducible (toPoly 101 [81, 71, 5, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [20, 24, 37])]) (by decide +kernel)

theorem irr2 : Irreducible (toPoly 101 [97, 85, 54, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [50, 67, 83])]) (by decide +kernel)

theorem irr3 : Irreducible (toPoly 101 [1, 1, 1, 1, 1, 1, 1]) :=
  irreducible_of_irrCheck (cert := [(2, [29, 58, 87, 15, 44, 73]), (3, [87, 73, 58, 44, 29, 15])]) (by decide +kernel)

theorem l8check0 : l8Check 101 [64, 46, 1] = true ∧ ffCheck 101 [64, 46, 1] 95 = true := by
  decide +kernel

/-- The prime `𝔮_1` of `L8` above 101: `k = F_101[x]/(h_1)`. -/
def L8P0 : L8Prime where
  q := 101
  P := [64, 46, 1]
  zeta := 95
  prime := prime
  irred := irr0
  fcheck := l8check0.2
  i := 1
  check := l8check0.1

theorem l8check1 : l8Check 101 [81, 71, 5, 1] = true ∧ ffCheck 101 [81, 71, 5, 1] 95 = true := by
  decide +kernel

/-- The prime `𝔮_2` of `L8` above 101: `k = F_101[x]/(h_2)`. -/
def L8P1 : L8Prime where
  q := 101
  P := [81, 71, 5, 1]
  zeta := 95
  prime := prime
  irred := irr1
  fcheck := l8check1.2
  i := 2
  check := l8check1.1

theorem l8check2 : l8Check 101 [97, 85, 54, 1] = true ∧ ffCheck 101 [97, 85, 54, 1] 95 = true := by
  decide +kernel

/-- The prime `𝔮_3` of `L8` above 101: `k = F_101[x]/(h_3)`. -/
def L8P2 : L8Prime where
  q := 101
  P := [97, 85, 54, 1]
  zeta := 95
  prime := prime
  irred := irr2
  fcheck := l8check2.2
  i := 3
  check := l8check2.1

/-- Row 0 of the symbol matrix. -/
def row0 : List ℕ := [3, 0, 3, 4, 4, 4, 2, 1, 3, 4, 2, 1, 3, 4, 4, 2, 1, 4, 4, 3, 3, 2, 2, 0]

theorem l24check0 : l24Check 101 [64, 46, 1] 95 [64, 46, 1] [0, 1] [62, 0] row0 = true ∧
    ffCheck 101 [64, 46, 1] 95 = true := by
  decide +kernel

/-- The prime `𝔔_{1,1}` of `L24` above 101 (residue degree 2). -/
def L24P0 : L24Prime where
  q := 101
  P := [64, 46, 1]
  zeta := 95
  prime := prime
  irred := irr0
  fcheck := l24check0.2
  i := 1
  l := 1
  hi := [64, 46, 1]
  alpha := [0, 1]
  beta := [62, 0]
  row := row0
  check := l24check0.1

/-- Row 1 of the symbol matrix. -/
def row1 : List ℕ := [2, 0, 0, 0, 1, 3, 1, 4, 3, 4, 1, 4, 1, 0, 4, 4, 0, 2, 4, 1, 1, 3, 2, 4]

theorem l24check1 : l24Check 101 [64, 46, 1] 95 [64, 46, 1] [0, 1] [3, 70] row1 = true ∧
    ffCheck 101 [64, 46, 1] 95 = true := by
  decide +kernel

/-- The prime `𝔔_{1,2}` of `L24` above 101 (residue degree 2). -/
def L24P1 : L24Prime where
  q := 101
  P := [64, 46, 1]
  zeta := 95
  prime := prime
  irred := irr0
  fcheck := l24check1.2
  i := 1
  l := 2
  hi := [64, 46, 1]
  alpha := [0, 1]
  beta := [3, 70]
  row := row1
  check := l24check1.1

/-- Row 2 of the symbol matrix. -/
def row2 : List ℕ := [3, 2, 1, 0, 2, 1, 2, 2, 3, 4, 1, 4, 1, 4, 2, 3, 3, 0, 4, 2, 4, 0, 1, 0]

theorem l24check2 : l24Check 101 [64, 46, 1] 95 [64, 46, 1] [0, 1] [15, 31] row2 = true ∧
    ffCheck 101 [64, 46, 1] 95 = true := by
  decide +kernel

/-- The prime `𝔔_{1,3}` of `L24` above 101 (residue degree 2). -/
def L24P2 : L24Prime where
  q := 101
  P := [64, 46, 1]
  zeta := 95
  prime := prime
  irred := irr0
  fcheck := l24check2.2
  i := 1
  l := 3
  hi := [64, 46, 1]
  alpha := [0, 1]
  beta := [15, 31]
  row := row2
  check := l24check2.1

/-- Row 3 of the symbol matrix. -/
def row3 : List ℕ := [2, 3, 0, 2, 1, 4, 0, 4, 0, 0, 2, 2, 2, 0, 4, 0, 1, 2, 4, 0, 0, 4, 4, 1]

theorem l24check3 : l24Check 101 [81, 71, 5, 1] 95 [81, 71, 5, 1] [0, 1, 0] [62, 0, 0] row3 = true ∧
    ffCheck 101 [81, 71, 5, 1] 95 = true := by
  decide +kernel

/-- The prime `𝔔_{2,1}` of `L24` above 101 (residue degree 3). -/
def L24P3 : L24Prime where
  q := 101
  P := [81, 71, 5, 1]
  zeta := 95
  prime := prime
  irred := irr1
  fcheck := l24check3.2
  i := 2
  l := 1
  hi := [81, 71, 5, 1]
  alpha := [0, 1, 0]
  beta := [62, 0, 0]
  row := row3
  check := l24check3.1

/-- Row 4 of the symbol matrix. -/
def row4 : List ℕ := [1, 3, 2, 3, 1, 3, 0, 2, 4, 1, 1, 2, 3, 4, 1, 2, 3, 4, 2, 1, 2, 0, 0, 1]

theorem l24check4 : l24Check 101 [1, 1, 1, 1, 1, 1, 1] 95 [81, 71, 5, 1] [40, 0, 1, 23, 23, 1] [24, 30, 30, 0, 30, 0] row4 = true ∧
    ffCheck 101 [1, 1, 1, 1, 1, 1, 1] 95 = true := by
  decide +kernel

/-- The prime `𝔔_{2,2}` of `L24` above 101 (residue degree 6). -/
def L24P4 : L24Prime where
  q := 101
  P := [1, 1, 1, 1, 1, 1, 1]
  zeta := 95
  prime := prime
  irred := irr3
  fcheck := l24check4.2
  i := 2
  l := 2
  hi := [81, 71, 5, 1]
  alpha := [40, 0, 1, 23, 23, 1]
  beta := [24, 30, 30, 0, 30, 0]
  row := row4
  check := l24check4.1

/-- Row 5 of the symbol matrix. -/
def row5 : List ℕ := [2, 1, 0, 3, 3, 1, 2, 0, 3, 0, 1, 0, 2, 2, 0, 0, 3, 1, 3, 2, 4, 0, 0, 4]

theorem l24check5 : l24Check 101 [97, 85, 54, 1] 95 [97, 85, 54, 1] [0, 1, 0] [62, 0, 0] row5 = true ∧
    ffCheck 101 [97, 85, 54, 1] 95 = true := by
  decide +kernel

/-- The prime `𝔔_{3,1}` of `L24` above 101 (residue degree 3). -/
def L24P5 : L24Prime where
  q := 101
  P := [97, 85, 54, 1]
  zeta := 95
  prime := prime
  irred := irr2
  fcheck := l24check5.2
  i := 3
  l := 1
  hi := [97, 85, 54, 1]
  alpha := [0, 1, 0]
  beta := [62, 0, 0]
  row := row5
  check := l24check5.1

/-- Row 6 of the symbol matrix. -/
def row6 : List ℕ := [3, 0, 3, 2, 2, 3, 2, 1, 3, 1, 1, 1, 3, 1, 0, 4, 4, 2, 4, 1, 1, 1, 1, 0]

theorem l24check6 : l24Check 101 [1, 1, 1, 1, 1, 1, 1] 95 [97, 85, 54, 1] [35, 0, 48, 10, 10, 48] [24, 30, 30, 0, 30, 0] row6 = true ∧
    ffCheck 101 [1, 1, 1, 1, 1, 1, 1] 95 = true := by
  decide +kernel

/-- The prime `𝔔_{3,2}` of `L24` above 101 (residue degree 6). -/
def L24P6 : L24Prime where
  q := 101
  P := [1, 1, 1, 1, 1, 1, 1]
  zeta := 95
  prime := prime
  irred := irr3
  fcheck := l24check6.2
  i := 3
  l := 2
  hi := [97, 85, 54, 1]
  alpha := [35, 0, 48, 10, 10, 48]
  beta := [24, 30, 30, 0, 30, 0]
  row := row6
  check := l24check6.1

/-- The primes of `L8` above 101, in file order. -/
def L8P : Fin 3 → L8Prime := ![L8P0, L8P1, L8P2]

/-- The primes of `L24` above 101, in file order. -/
def L24P : Fin 7 → L24Prime := ![L24P0, L24P1, L24P2, L24P3, L24P4, L24P5, L24P6]

/-- The rows of the symbol matrix. -/
def Mrows : List (List ℕ) := [row0, row1, row2, row3, row4, row5, row6]

/-- The symbol matrix at `q = 101`: `M k j = χ_{𝔔_k}(B_j)`. -/
def M : Matrix (Fin 7) (Fin 24) (ZMod 5) := Matrix.of fun k j => ((Mrows.getD k []).getD j 0 : ZMod 5)

theorem sym_M (k : Fin 7) (j : Fin 24) : (L24P k).sym ((L24P k).imgB j) = M k j := by
  rw [(L24P k).sym_imgB j]
  fin_cases k <;> rfl

theorem q_L8P (t : Fin 3) : (L8P t).q = 101 := by fin_cases t <;> rfl

theorem q_L24P (k : Fin 7) : (L24P k).q = 101 := by fin_cases k <;> rfl

end X2Y5Z7.FiniteFields.Q101
