/-
Generated by computer; every fact used is proved in Lean.
-/
module

public import X2Y5Z7.FiniteFields.Model

@[expose] public section

/-! # Residue-field models at `q = 311`

`5` primes of `L8` (`L8P : Fin 5 → L8Prime`) and `11` primes of `L24` (`L24P : Fin 11 → L24Prime`),
in the order of `models.txt`; `M : Matrix (Fin 11) (Fin 24) (ZMod 5)` is the symbol matrix, and
`sym_M : (L24P k).sym ((L24P k).imgB j) = M k j`. Every fact is checked by `decide +kernel`. -/

namespace X2Y5Z7.FiniteFields.Q311

open X2Y5Z7.FiniteFields

theorem prime : Nat.Prime 311 := by norm_num

instance : Fact (Nat.Prime 311) := ⟨prime⟩

theorem irr0 : Irreducible (toPoly 311 [44, 1]) :=
  irreducible_of_irrCheck (cert := []) (by decide +kernel)

theorem irr1 : Irreducible (toPoly 311 [122, 1]) :=
  irreducible_of_irrCheck (cert := []) (by decide +kernel)

theorem irr2 : Irreducible (toPoly 311 [249, 1]) :=
  irreducible_of_irrCheck (cert := []) (by decide +kernel)

theorem irr3 : Irreducible (toPoly 311 [301, 1]) :=
  irreducible_of_irrCheck (cert := []) (by decide +kernel)

theorem irr4 : Irreducible (toPoly 311 [25, 50, 90, 221, 1]) :=
  irreducible_of_irrCheck (cert := [(2, [241, 128, 254, 1])]) (by decide +kernel)

theorem irr5 : Irreducible (toPoly 311 [1, 1, 1]) :=
  irreducible_of_irrCheck (cert := [(1, [104, 208])]) (by decide +kernel)

theorem l8check0 : l8Check 311 [44, 1] = true ∧ ffCheck 311 [44, 1] 36 = true := by
  decide +kernel

/-- The prime `𝔮_1` of `L8` above 311: `k = F_311[x]/(h_1)`. -/
def L8P0 : L8Prime where
  q := 311
  P := [44, 1]
  zeta := 36
  prime := prime
  irred := irr0
  fcheck := l8check0.2
  i := 1
  check := l8check0.1

theorem l8check1 : l8Check 311 [122, 1] = true ∧ ffCheck 311 [122, 1] 36 = true := by
  decide +kernel

/-- The prime `𝔮_2` of `L8` above 311: `k = F_311[x]/(h_2)`. -/
def L8P1 : L8Prime where
  q := 311
  P := [122, 1]
  zeta := 36
  prime := prime
  irred := irr1
  fcheck := l8check1.2
  i := 2
  check := l8check1.1

theorem l8check2 : l8Check 311 [249, 1] = true ∧ ffCheck 311 [249, 1] 36 = true := by
  decide +kernel

/-- The prime `𝔮_3` of `L8` above 311: `k = F_311[x]/(h_3)`. -/
def L8P2 : L8Prime where
  q := 311
  P := [249, 1]
  zeta := 36
  prime := prime
  irred := irr2
  fcheck := l8check2.2
  i := 3
  check := l8check2.1

theorem l8check3 : l8Check 311 [301, 1] = true ∧ ffCheck 311 [301, 1] 36 = true := by
  decide +kernel

/-- The prime `𝔮_4` of `L8` above 311: `k = F_311[x]/(h_4)`. -/
def L8P3 : L8Prime where
  q := 311
  P := [301, 1]
  zeta := 36
  prime := prime
  irred := irr3
  fcheck := l8check3.2
  i := 4
  check := l8check3.1

theorem l8check4 : l8Check 311 [25, 50, 90, 221, 1] = true ∧ ffCheck 311 [25, 50, 90, 221, 1] 36 = true := by
  decide +kernel

/-- The prime `𝔮_5` of `L8` above 311: `k = F_311[x]/(h_5)`. -/
def L8P4 : L8Prime where
  q := 311
  P := [25, 50, 90, 221, 1]
  zeta := 36
  prime := prime
  irred := irr4
  fcheck := l8check4.2
  i := 5
  check := l8check4.1

/-- Row 0 of the symbol matrix. -/
def row0 : List ℕ := [2, 4, 4, 1, 3, 0, 3, 0, 0, 4, 2, 3, 1, 2, 3, 3, 2, 1, 3, 1, 0, 1, 0, 0]

theorem l24check0 : l24Check 311 [44, 1] 36 [44, 1] [267] [160] row0 = true ∧
    ffCheck 311 [44, 1] 36 = true := by
  decide +kernel

/-- The prime `𝔔_{1,1}` of `L24` above 311 (residue degree 1). -/
def L24P0 : L24Prime where
  q := 311
  P := [44, 1]
  zeta := 36
  prime := prime
  irred := irr0
  fcheck := l24check0.2
  i := 1
  l := 1
  hi := [44, 1]
  alpha := [267]
  beta := [160]
  row := row0
  check := l24check0.1

/-- Row 1 of the symbol matrix. -/
def row1 : List ℕ := [0, 1, 3, 0, 0, 0, 4, 0, 0, 1, 1, 2, 4, 2, 2, 4, 3, 1, 3, 4, 1, 2, 4, 2]

theorem l24check1 : l24Check 311 [1, 1, 1] 36 [44, 1] [267, 0] [256, 113] row1 = true ∧
    ffCheck 311 [1, 1, 1] 36 = true := by
  decide +kernel

/-- The prime `𝔔_{1,2}` of `L24` above 311 (residue degree 2). -/
def L24P1 : L24Prime where
  q := 311
  P := [1, 1, 1]
  zeta := 36
  prime := prime
  irred := irr5
  fcheck := l24check1.2
  i := 1
  l := 2
  hi := [44, 1]
  alpha := [267, 0]
  beta := [256, 113]
  row := row1
  check := l24check1.1

/-- Row 2 of the symbol matrix. -/
def row2 : List ℕ := [3, 2, 1, 0, 4, 0, 2, 2, 2, 3, 3, 1, 1, 0, 3, 2, 2, 2, 3, 4, 0, 4, 0, 4]

theorem l24check2 : l24Check 311 [122, 1] 36 [122, 1] [189] [160] row2 = true ∧
    ffCheck 311 [122, 1] 36 = true := by
  decide +kernel

/-- The prime `𝔔_{2,1}` of `L24` above 311 (residue degree 1). -/
def L24P2 : L24Prime where
  q := 311
  P := [122, 1]
  zeta := 36
  prime := prime
  irred := irr1
  fcheck := l24check2.2
  i := 2
  l := 1
  hi := [122, 1]
  alpha := [189]
  beta := [160]
  row := row2
  check := l24check2.1

/-- Row 3 of the symbol matrix. -/
def row3 : List ℕ := [0, 0, 3, 4, 2, 1, 1, 0, 3, 0, 2, 4, 4, 0, 2, 3, 3, 1, 2, 1, 0, 4, 2, 1]

theorem l24check3 : l24Check 311 [1, 1, 1] 36 [122, 1] [189, 0] [256, 113] row3 = true ∧
    ffCheck 311 [1, 1, 1] 36 = true := by
  decide +kernel

/-- The prime `𝔔_{2,2}` of `L24` above 311 (residue degree 2). -/
def L24P3 : L24Prime where
  q := 311
  P := [1, 1, 1]
  zeta := 36
  prime := prime
  irred := irr5
  fcheck := l24check3.2
  i := 2
  l := 2
  hi := [122, 1]
  alpha := [189, 0]
  beta := [256, 113]
  row := row3
  check := l24check3.1

/-- Row 4 of the symbol matrix. -/
def row4 : List ℕ := [1, 4, 2, 2, 4, 3, 3, 4, 1, 2, 1, 3, 1, 3, 4, 2, 0, 3, 0, 0, 2, 4, 1, 3]

theorem l24check4 : l24Check 311 [249, 1] 36 [249, 1] [62] [160] row4 = true ∧
    ffCheck 311 [249, 1] 36 = true := by
  decide +kernel

/-- The prime `𝔔_{3,1}` of `L24` above 311 (residue degree 1). -/
def L24P4 : L24Prime where
  q := 311
  P := [249, 1]
  zeta := 36
  prime := prime
  irred := irr2
  fcheck := l24check4.2
  i := 3
  l := 1
  hi := [249, 1]
  alpha := [62]
  beta := [160]
  row := row4
  check := l24check4.1

/-- Row 5 of the symbol matrix. -/
def row5 : List ℕ := [0, 1, 1, 4, 4, 1, 1, 1, 1, 1, 2, 4, 4, 0, 1, 1, 1, 0, 2, 4, 4, 4, 0, 2]

theorem l24check5 : l24Check 311 [1, 1, 1] 36 [249, 1] [62, 0] [256, 113] row5 = true ∧
    ffCheck 311 [1, 1, 1] 36 = true := by
  decide +kernel

/-- The prime `𝔔_{3,2}` of `L24` above 311 (residue degree 2). -/
def L24P5 : L24Prime where
  q := 311
  P := [1, 1, 1]
  zeta := 36
  prime := prime
  irred := irr5
  fcheck := l24check5.2
  i := 3
  l := 2
  hi := [249, 1]
  alpha := [62, 0]
  beta := [256, 113]
  row := row5
  check := l24check5.1

/-- Row 6 of the symbol matrix. -/
def row6 : List ℕ := [3, 1, 1, 3, 2, 1, 4, 1, 0, 1, 3, 2, 1, 0, 0, 1, 1, 4, 4, 1, 3, 4, 1, 0]

theorem l24check6 : l24Check 311 [301, 1] 36 [301, 1] [10] [160] row6 = true ∧
    ffCheck 311 [301, 1] 36 = true := by
  decide +kernel

/-- The prime `𝔔_{4,1}` of `L24` above 311 (residue degree 1). -/
def L24P6 : L24Prime where
  q := 311
  P := [301, 1]
  zeta := 36
  prime := prime
  irred := irr3
  fcheck := l24check6.2
  i := 4
  l := 1
  hi := [301, 1]
  alpha := [10]
  beta := [160]
  row := row6
  check := l24check6.1

/-- Row 7 of the symbol matrix. -/
def row7 : List ℕ := [0, 0, 2, 0, 2, 0, 4, 0, 4, 3, 3, 2, 4, 2, 0, 0, 0, 1, 4, 3, 4, 2, 3, 1]

theorem l24check7 : l24Check 311 [1, 1, 1] 36 [301, 1] [10, 0] [256, 113] row7 = true ∧
    ffCheck 311 [1, 1, 1] 36 = true := by
  decide +kernel

/-- The prime `𝔔_{4,2}` of `L24` above 311 (residue degree 2). -/
def L24P7 : L24Prime where
  q := 311
  P := [1, 1, 1]
  zeta := 36
  prime := prime
  irred := irr5
  fcheck := l24check7.2
  i := 4
  l := 2
  hi := [301, 1]
  alpha := [10, 0]
  beta := [256, 113]
  row := row7
  check := l24check7.1

/-- Row 8 of the symbol matrix. -/
def row8 : List ℕ := [0, 0, 4, 0, 4, 2, 4, 3, 0, 0, 1, 3, 4, 4, 2, 0, 0, 3, 4, 4, 3, 1, 2, 3]

theorem l24check8 : l24Check 311 [25, 50, 90, 221, 1] 36 [25, 50, 90, 221, 1] [0, 1, 0, 0] [160, 0, 0, 0] row8 = true ∧
    ffCheck 311 [25, 50, 90, 221, 1] 36 = true := by
  decide +kernel

/-- The prime `𝔔_{5,1}` of `L24` above 311 (residue degree 4). -/
def L24P8 : L24Prime where
  q := 311
  P := [25, 50, 90, 221, 1]
  zeta := 36
  prime := prime
  irred := irr4
  fcheck := l24check8.2
  i := 5
  l := 1
  hi := [25, 50, 90, 221, 1]
  alpha := [0, 1, 0, 0]
  beta := [160, 0, 0, 0]
  row := row8
  check := l24check8.1

/-- Row 9 of the symbol matrix. -/
def row9 : List ℕ := [3, 0, 3, 2, 4, 3, 3, 4, 4, 3, 3, 1, 3, 2, 3, 1, 0, 0, 3, 4, 0, 0, 2, 3]

theorem l24check9 : l24Check 311 [25, 50, 90, 221, 1] 36 [25, 50, 90, 221, 1] [0, 1, 0, 0] [73, 166, 232, 206] row9 = true ∧
    ffCheck 311 [25, 50, 90, 221, 1] 36 = true := by
  decide +kernel

/-- The prime `𝔔_{5,2}` of `L24` above 311 (residue degree 4). -/
def L24P9 : L24Prime where
  q := 311
  P := [25, 50, 90, 221, 1]
  zeta := 36
  prime := prime
  irred := irr4
  fcheck := l24check9.2
  i := 5
  l := 2
  hi := [25, 50, 90, 221, 1]
  alpha := [0, 1, 0, 0]
  beta := [73, 166, 232, 206]
  row := row9
  check := l24check9.1

/-- Row 10 of the symbol matrix. -/
def row10 : List ℕ := [0, 3, 2, 0, 2, 0, 2, 1, 0, 2, 4, 0, 3, 0, 0, 3, 3, 4, 2, 4, 3, 4, 0, 1]

theorem l24check10 : l24Check 311 [25, 50, 90, 221, 1] 36 [25, 50, 90, 221, 1] [0, 1, 0, 0] [15, 145, 79, 105] row10 = true ∧
    ffCheck 311 [25, 50, 90, 221, 1] 36 = true := by
  decide +kernel

/-- The prime `𝔔_{5,3}` of `L24` above 311 (residue degree 4). -/
def L24P10 : L24Prime where
  q := 311
  P := [25, 50, 90, 221, 1]
  zeta := 36
  prime := prime
  irred := irr4
  fcheck := l24check10.2
  i := 5
  l := 3
  hi := [25, 50, 90, 221, 1]
  alpha := [0, 1, 0, 0]
  beta := [15, 145, 79, 105]
  row := row10
  check := l24check10.1

/-- The primes of `L8` above 311, in file order. -/
def L8P : Fin 5 → L8Prime := ![L8P0, L8P1, L8P2, L8P3, L8P4]

/-- The primes of `L24` above 311, in file order. -/
def L24P : Fin 11 → L24Prime := ![L24P0, L24P1, L24P2, L24P3, L24P4, L24P5, L24P6, L24P7, L24P8, L24P9, L24P10]

/-- The rows of the symbol matrix. -/
def Mrows : List (List ℕ) := [row0, row1, row2, row3, row4, row5, row6, row7, row8, row9, row10]

/-- The symbol matrix at `q = 311`: `M k j = χ_{𝔔_k}(B_j)`. -/
def M : Matrix (Fin 11) (Fin 24) (ZMod 5) := Matrix.of fun k j => ((Mrows.getD k []).getD j 0 : ZMod 5)

theorem sym_M (k : Fin 11) (j : Fin 24) : (L24P k).sym ((L24P k).imgB j) = M k j := by
  rw [(L24P k).sym_imgB j]
  fin_cases k <;> rfl

theorem q_L8P (t : Fin 5) : (L8P t).q = 311 := by fin_cases t <;> rfl

theorem q_L24P (k : Fin 11) : (L24P k).q = 311 := by fin_cases k <;> rfl

end X2Y5Z7.FiniteFields.Q311
