/-
Generated by computer; every fact used is proved in Lean.
-/
module

public import X2Y5Z7.SymbolSets.Q251.Data

@[expose] public section

/-! # Proposition 5.3 at `q = 251`: certificates for `η = 2 … 120` (73 R, 43 G, 3 F) -/

namespace X2Y5Z7.SymbolSets.Q251

open X2Y5Z7.SymbolSets

def k2 : Cert :=
  Cert.R [154]

theorem c2 : certCheck 251 D ILN 2 k2 = true := by decide +kernel

def k3 : Cert :=
  Cert.G 2 [1] [2, 183, 7, 29, 154, 47, 236] [122, 77, 44, 30, 240, 198, 46, 122]

theorem c3 : certCheck 251 D ILN 3 k3 = true := by decide +kernel

def k4 : Cert :=
  Cert.G 2 [1] [22, 101, 137, 24, 228, 15, 59] [215, 16, 206, 195, 195, 62, 18, 34]

theorem c4 : certCheck 251 D ILN 4 k4 = true := by decide +kernel

def k5 : Cert :=
  Cert.R [86]

theorem c5 : certCheck 251 D ILN 5 k5 = true := by decide +kernel

def k6 : Cert :=
  Cert.R [45]

theorem c6 : certCheck 251 D ILN 6 k6 = true := by decide +kernel

def k7 : Cert :=
  Cert.G 2 [1] [84, 151, 247, 66, 18, 169, 142] [109, 210, 54, 38, 55, 128, 16, 177]

theorem c7 : certCheck 251 D ILN 7 k7 = true := by decide +kernel

def k8 : Cert :=
  Cert.R [102]

theorem c8 : certCheck 251 D ILN 8 k8 = true := by decide +kernel

def k9 : Cert :=
  Cert.R [81]

theorem c9 : certCheck 251 D ILN 9 k9 = true := by decide +kernel

def k10 : Cert :=
  Cert.R [168]

theorem c10 : certCheck 251 D ILN 10 k10 = true := by decide +kernel

def k11 : Cert :=
  Cert.R [213]

theorem c11 : certCheck 251 D ILN 11 k11 = true := by decide +kernel

def k12 : Cert :=
  Cert.G 2 [1] [45, 39, 0, 83, 126, 4, 215] [67, 229, 165, 105, 88, 245, 235, 142]

theorem c12 : certCheck 251 D ILN 12 k12 = true := by decide +kernel

def k13 : Cert :=
  Cert.R [80]

theorem c13 : certCheck 251 D ILN 13 k13 = true := by decide +kernel

def k14 : Cert :=
  Cert.G 2 [1] [41, 12, 195, 113, 190, 213, 62] [144, 212, 90, 179, 199, 147, 39, 76]

theorem c14 : certCheck 251 D ILN 14 k14 = true := by decide +kernel

def k15 : Cert :=
  Cert.G 2 [7, 169, 1] [174, 136, 123, 133, 140] [95, 216, 10, 2, 30, 247]

theorem c15 : certCheck 251 D ILN 15 k15 = true := by decide +kernel

def k16 : Cert :=
  Cert.G 2 [1] [168, 191, 156, 194, 226, 232, 72] [126, 142, 10, 126, 79, 175, 52, 15]

theorem c16 : certCheck 251 D ILN 16 k16 = true := by decide +kernel

def k17 : Cert :=
  Cert.R [57]

theorem c17 : certCheck 251 D ILN 17 k17 = true := by decide +kernel

def k18 : Cert :=
  Cert.R [188]

theorem c18 : certCheck 251 D ILN 18 k18 = true := by decide +kernel

def k19 : Cert :=
  Cert.R [48]

theorem c19 : certCheck 251 D ILN 19 k19 = true := by decide +kernel

def k20 : Cert :=
  Cert.R [116]

theorem c20 : certCheck 251 D ILN 20 k20 = true := by decide +kernel

def k21 : Cert :=
  Cert.G 2 [1] [137, 130, 105, 6, 140, 43, 8] [164, 168, 142, 162, 165, 193, 123, 17]

theorem c21 : certCheck 251 D ILN 21 k21 = true := by decide +kernel

def k22 : Cert :=
  Cert.G 2 [1] [133, 154, 104, 128, 154, 144, 68] [71, 175, 153, 245, 74, 4, 219, 213]

theorem c22 : certCheck 251 D ILN 22 k22 = true := by decide +kernel

def k23 : Cert :=
  Cert.R [21]

theorem c23 : certCheck 251 D ILN 23 k23 = true := by decide +kernel

def k24 : Cert :=
  Cert.G 2 [1] [10, 250, 131, 147, 71, 16] [51, 143, 42, 230, 172, 122, 72]

theorem c24 : certCheck 251 D ILN 24 k24 = true := by decide +kernel

def k25 : Cert :=
  Cert.G 2 [1] [111, 24, 167, 11, 117, 128, 157] [11, 98, 134, 118, 122, 3, 178, 219]

theorem c25 : certCheck 251 D ILN 25 k25 = true := by decide +kernel

def k26 : Cert :=
  Cert.G 2 [1] [171, 84, 76, 113, 200, 34, 159] [77, 63, 245, 203, 76, 100, 243, 73]

theorem c26 : certCheck 251 D ILN 26 k26 = true := by decide +kernel

def k27 : Cert :=
  Cert.G 2 [58, 177, 1] [152, 173, 67, 147, 39] [200, 141, 33, 137, 19, 149]

theorem c27 : certCheck 251 D ILN 27 k27 = true := by decide +kernel

def k28 : Cert :=
  Cert.R [205]

theorem c28 : certCheck 251 D ILN 28 k28 = true := by decide +kernel

def k29 : Cert :=
  Cert.R [26]

theorem c29 : certCheck 251 D ILN 29 k29 = true := by decide +kernel

def k30 : Cert :=
  Cert.R [233]

theorem c30 : certCheck 251 D ILN 30 k30 = true := by decide +kernel

def k31 : Cert :=
  Cert.R [69]

theorem c31 : certCheck 251 D ILN 31 k31 = true := by decide +kernel

def k32 : Cert :=
  Cert.R [7]

theorem c32 : certCheck 251 D ILN 32 k32 = true := by decide +kernel

def k33 : Cert :=
  Cert.G 2 [165, 82, 1] [181, 98, 229, 199, 21] [219, 207, 197, 177, 112, 132]

theorem c33 : certCheck 251 D ILN 33 k33 = true := by decide +kernel

def k34 : Cert :=
  Cert.R [239]

theorem c34 : certCheck 251 D ILN 34 k34 = true := by decide +kernel

def k35 : Cert :=
  Cert.R [245]

theorem c35 : certCheck 251 D ILN 35 k35 = true := by decide +kernel

def k36 : Cert :=
  Cert.G 2 [1] [199, 59, 88, 73, 233, 206, 165] [167, 31, 218, 1, 111, 142, 224, 188]

theorem c36 : certCheck 251 D ILN 36 k36 = true := by decide +kernel

def k37 : Cert :=
  Cert.R [84]

theorem c37 : certCheck 251 D ILN 37 k37 = true := by decide +kernel

def k38 : Cert :=
  Cert.R [12]

theorem c38 : certCheck 251 D ILN 38 k38 = true := by decide +kernel

def k39 : Cert :=
  Cert.R [149]

theorem c39 : certCheck 251 D ILN 39 k39 = true := by decide +kernel

def k40 : Cert :=
  Cert.G 2 [1] [145, 66, 52, 167, 166, 55, 245] [78, 244, 32, 117, 32, 87, 247, 173]

theorem c40 : certCheck 251 D ILN 40 k40 = true := by decide +kernel

def k41 : Cert :=
  Cert.R [118]

theorem c41 : certCheck 251 D ILN 41 k41 = true := by decide +kernel

def k42 : Cert :=
  Cert.G 2 [51, 240, 1] [192, 139, 103, 171, 148] [117, 232, 94, 220, 126, 21]

theorem c42 : certCheck 251 D ILN 42 k42 = true := by decide +kernel

def k43 : Cert :=
  Cert.G 2 [1] [207, 137, 6, 236, 137, 126, 233] [8, 181, 210, 192, 0, 78, 154, 80]

theorem c43 : certCheck 251 D ILN 43 k43 = true := by decide +kernel

def k44 : Cert :=
  Cert.R [87]

theorem c44 : certCheck 251 D ILN 44 k44 = true := by decide +kernel

def k45 : Cert :=
  Cert.G 2 [1] [19, 133, 26, 23, 191, 46, 186] [226, 0, 100, 53, 108, 31, 61, 234]

theorem c45 : certCheck 251 D ILN 45 k45 = true := by decide +kernel

def k46 : Cert :=
  Cert.G 2 [1] [8, 150, 113, 238, 184, 52, 234] [101, 70, 184, 127, 17, 202, 153, 41]

theorem c46 : certCheck 251 D ILN 46 k46 = true := by decide +kernel

def k47 : Cert :=
  Cert.G 2 [1] [130, 9, 205, 249, 93, 181, 130] [242, 56, 38, 215, 76, 126, 131, 211]

theorem c47 : certCheck 251 D ILN 47 k47 = true := by decide +kernel

def k48 : Cert :=
  Cert.R [58]

theorem c48 : certCheck 251 D ILN 48 k48 = true := by decide +kernel

def k49 : Cert :=
  Cert.R [75]

theorem c49 : certCheck 251 D ILN 49 k49 = true := by decide +kernel

def k50 : Cert :=
  Cert.R [19]

theorem c50 : certCheck 251 D ILN 50 k50 = true := by decide +kernel

def k51 : Cert :=
  Cert.R [106]

theorem c51 : certCheck 251 D ILN 51 k51 = true := by decide +kernel

def k52 : Cert :=
  Cert.F [([66, 38, 1], [(1, [208, 77])]), ([236, 194, 1], [(1, [94, 120])]), ([170, 181, 42, 70, 1], [(2, [132, 30, 169, 223])])]
      [[(0, [([204, 124], [1, 1, 3, 0, 0, 0, 0, 0, 0]), ([9, 127], [1, 3, 1, 0, 0, 0, 0, 0, 0])]), (1, [([64, 40], [4, 1, 0, 0, 0, 0, 0, 0, 0]), ([244, 211], [4, 0, 1, 0, 0, 0, 0, 0, 0])])],
       [(0, [([28, 39], [0, 0, 0, 1, 1, 3, 0, 0, 0]), ([185, 212], [0, 0, 0, 1, 3, 1, 0, 0, 0])]), (1, [([236, 36], [0, 0, 0, 4, 0, 1, 0, 0, 0]), ([72, 215], [0, 0, 0, 4, 1, 0, 0, 0, 0])])],
       [(2, [([111, 208, 143, 114], [0, 0, 0, 0, 0, 0, 2, 0, 3]), ([130, 179, 78, 174], [0, 0, 0, 0, 0, 0, 2, 3, 0]), ([88, 205, 168, 221], [0, 0, 0, 0, 0, 0, 2, 3, 0]), ([103, 161, 113, 244], [0, 0, 0, 0, 0, 0, 2, 0, 3])])]]

theorem c52 : certCheck 251 D ILN 52 k52 = true := by decide +kernel

def k53 : Cert :=
  Cert.F [([245, 165, 1], [(1, [127, 178])]), ([240, 248, 1], [(1, [19, 71])]), ([133, 43, 31, 140, 1], [(2, [114, 193, 176, 204])])]
      [[(0, [([195, 44], [1, 0, 4, 0, 0, 0, 0, 0, 0]), ([142, 207], [1, 4, 0, 0, 0, 0, 0, 0, 0])]), (1, [([30, 71], [1, 1, 3, 0, 0, 0, 0, 0, 0]), ([224, 180], [1, 3, 1, 0, 0, 0, 0, 0, 0])])],
       [(0, [([3, 111], [0, 0, 0, 1, 0, 4, 0, 0, 0]), ([83, 140], [0, 0, 0, 1, 4, 0, 0, 0, 0])]), (1, [([9, 89], [0, 0, 0, 1, 3, 1, 0, 0, 0]), ([245, 162], [0, 0, 0, 1, 1, 3, 0, 0, 0])])],
       [(2, [([35, 35, 246, 44], [0, 0, 0, 0, 0, 0, 0, 0, 0]), ([157, 125, 41, 79], [0, 0, 0, 0, 0, 0, 0, 0, 0]), ([170, 46, 96, 142], [0, 0, 0, 0, 0, 0, 0, 0, 0]), ([0, 45, 119, 237], [0, 0, 0, 0, 0, 0, 0, 0, 0])])]]

theorem c53 : certCheck 251 D ILN 53 k53 = true := by decide +kernel

def k54 : Cert :=
  Cert.R [95]

theorem c54 : certCheck 251 D ILN 54 k54 = true := by decide +kernel

def k55 : Cert :=
  Cert.R [41]

theorem c55 : certCheck 251 D ILN 55 k55 = true := by decide +kernel

def k56 : Cert :=
  Cert.G 2 [1] [218, 149, 187, 170, 75, 239, 176] [160, 202, 210, 36, 170, 136, 27, 215]

theorem c56 : certCheck 251 D ILN 56 k56 = true := by decide +kernel

def k57 : Cert :=
  Cert.G 2 [91, 175, 1] [34, 182, 133, 211, 40] [62, 161, 94, 197, 154, 158]

theorem c57 : certCheck 251 D ILN 57 k57 = true := by decide +kernel

def k58 : Cert :=
  Cert.R [92]

theorem c58 : certCheck 251 D ILN 58 k58 = true := by decide +kernel

def k59 : Cert :=
  Cert.G 2 [1] [246, 126, 116, 62, 247, 97, 191] [166, 7, 240, 25, 131, 208, 189, 236]

theorem c59 : certCheck 251 D ILN 59 k59 = true := by decide +kernel

def k60 : Cert :=
  Cert.R [28]

theorem c60 : certCheck 251 D ILN 60 k60 = true := by decide +kernel

def k61 : Cert :=
  Cert.R [129]

theorem c61 : certCheck 251 D ILN 61 k61 = true := by decide +kernel

def k62 : Cert :=
  Cert.G 2 [1] [5, 75, 87, 44, 242, 50, 78] [207, 155, 207, 29, 114, 219, 59, 47]

theorem c62 : certCheck 251 D ILN 62 k62 = true := by decide +kernel

def k63 : Cert :=
  Cert.R [230]

theorem c63 : certCheck 251 D ILN 63 k63 = true := by decide +kernel

def k64 : Cert :=
  Cert.R [101]

theorem c64 : certCheck 251 D ILN 64 k64 = true := by decide +kernel

def k65 : Cert :=
  Cert.R [184]

theorem c65 : certCheck 251 D ILN 65 k65 = true := by decide +kernel

def k66 : Cert :=
  Cert.R [176]

theorem c66 : certCheck 251 D ILN 66 k66 = true := by decide +kernel

def k67 : Cert :=
  Cert.G 2 [1] [51, 218, 16, 185, 195, 151, 140] [241, 40, 57, 160, 84, 64, 163, 38]

theorem c67 : certCheck 251 D ILN 67 k67 = true := by decide +kernel

def k68 : Cert :=
  Cert.G 2 [1] [161, 67, 136, 113, 79, 212, 107] [85, 246, 152, 51, 83, 221, 202, 188]

theorem c68 : certCheck 251 D ILN 68 k68 = true := by decide +kernel

def k69 : Cert :=
  Cert.R [64]

theorem c69 : certCheck 251 D ILN 69 k69 = true := by decide +kernel

def k70 : Cert :=
  Cert.R [143]

theorem c70 : certCheck 251 D ILN 70 k70 = true := by decide +kernel

def k71 : Cert :=
  Cert.R [248]

theorem c71 : certCheck 251 D ILN 71 k71 = true := by decide +kernel

def k72 : Cert :=
  Cert.G 2 [1] [214, 5, 160, 242, 13, 172, 65] [237, 26, 136, 248, 29, 72, 148, 65]

theorem c72 : certCheck 251 D ILN 72 k72 = true := by decide +kernel

def k73 : Cert :=
  Cert.R [11]

theorem c73 : certCheck 251 D ILN 73 k73 = true := by decide +kernel

def k74 : Cert :=
  Cert.G 2 [1] [155, 59, 235, 173, 131, 86] [101, 193, 180, 93, 123, 243, 166, 212]

theorem c74 : certCheck 251 D ILN 74 k74 = true := by decide +kernel

def k75 : Cert :=
  Cert.R [232]

theorem c75 : certCheck 251 D ILN 75 k75 = true := by decide +kernel

def k76 : Cert :=
  Cert.G 2 [1] [203, 98, 34, 81, 145, 19, 202] [153, 86, 73, 102, 157, 186, 193, 57]

theorem c76 : certCheck 251 D ILN 76 k76 = true := by decide +kernel

def k77 : Cert :=
  Cert.G 2 [159, 71, 1] [145, 98, 237, 237, 161] [220, 201, 181, 216, 62, 196]

theorem c77 : certCheck 251 D ILN 77 k77 = true := by decide +kernel

def k78 : Cert :=
  Cert.R [211]

theorem c78 : certCheck 251 D ILN 78 k78 = true := by decide +kernel

def k79 : Cert :=
  Cert.G 2 [1] [103, 125, 107, 85, 92, 6, 40] [111, 24, 165, 243, 124, 37, 164, 190]

theorem c79 : certCheck 251 D ILN 79 k79 = true := by decide +kernel

def k80 : Cert :=
  Cert.R [8]

theorem c80 : certCheck 251 D ILN 80 k80 = true := by decide +kernel

def k81 : Cert :=
  Cert.R [178]

theorem c81 : certCheck 251 D ILN 81 k81 = true := by decide +kernel

def k82 : Cert :=
  Cert.G 2 [1] [180, 113, 119, 89, 131, 70, 249] [230, 10, 109, 106, 171, 187, 32, 156]

theorem c82 : certCheck 251 D ILN 82 k82 = true := by decide +kernel

def k83 : Cert :=
  Cert.R [18]

theorem c83 : certCheck 251 D ILN 83 k83 = true := by decide +kernel

def k84 : Cert :=
  Cert.G 2 [1] [40, 155, 229, 97, 94, 248, 24] [182, 88, 83, 244, 21, 148, 48, 100]

theorem c84 : certCheck 251 D ILN 84 k84 = true := by decide +kernel

def k85 : Cert :=
  Cert.R [72]

theorem c85 : certCheck 251 D ILN 85 k85 = true := by decide +kernel

def k86 : Cert :=
  Cert.R [16]

theorem c86 : certCheck 251 D ILN 86 k86 = true := by decide +kernel

def k87 : Cert :=
  Cert.R [49]

theorem c87 : certCheck 251 D ILN 87 k87 = true := by decide +kernel

def k88 : Cert :=
  Cert.R [3]

theorem c88 : certCheck 251 D ILN 88 k88 = true := by decide +kernel

def k89 : Cert :=
  Cert.R [121]

theorem c89 : certCheck 251 D ILN 89 k89 = true := by decide +kernel

def k90 : Cert :=
  Cert.G 2 [1] [91, 109, 96, 15, 214, 113, 222] [75, 62, 206, 194, 185, 77, 199, 84]

theorem c90 : certCheck 251 D ILN 90 k90 = true := by decide +kernel

def k91 : Cert :=
  Cert.G 2 [1] [193, 65, 204, 146, 173, 183, 155] [144, 123, 130, 84, 46, 8, 8, 189]

theorem c91 : certCheck 251 D ILN 91 k91 = true := by decide +kernel

def k92 : Cert :=
  Cert.R [227]

theorem c92 : certCheck 251 D ILN 92 k92 = true := by decide +kernel

def k93 : Cert :=
  Cert.R [244]

theorem c93 : certCheck 251 D ILN 93 k93 = true := by decide +kernel

def k94 : Cert :=
  Cert.R [9]

theorem c94 : certCheck 251 D ILN 94 k94 = true := by decide +kernel

def k95 : Cert :=
  Cert.R [68]

theorem c95 : certCheck 251 D ILN 95 k95 = true := by decide +kernel

def k96 : Cert :=
  Cert.R [165]

theorem c96 : certCheck 251 D ILN 96 k96 = true := by decide +kernel

def k97 : Cert :=
  Cert.R [36]

theorem c97 : certCheck 251 D ILN 97 k97 = true := by decide +kernel

def k98 : Cert :=
  Cert.G 2 [1] [83, 20, 214, 26, 176, 210, 48] [120, 45, 184, 249, 146, 3, 189, 151]

theorem c98 : certCheck 251 D ILN 98 k98 = true := by decide +kernel

def k99 : Cert :=
  Cert.G 2 [167, 106, 1] [75, 147, 172, 242, 13] [118, 175, 64, 12, 150, 39]

theorem c99 : certCheck 251 D ILN 99 k99 = true := by decide +kernel

def k100 : Cert :=
  Cert.R [199]

theorem c100 : certCheck 251 D ILN 100 k100 = true := by decide +kernel

def k101 : Cert :=
  Cert.R [67]

theorem c101 : certCheck 251 D ILN 101 k101 = true := by decide +kernel

def k102 : Cert :=
  Cert.G 2 [1] [199, 151, 52, 53, 21, 56, 199] [233, 3, 70, 76, 240, 8, 12, 235]

theorem c102 : certCheck 251 D ILN 102 k102 = true := by decide +kernel

def k103 : Cert :=
  Cert.R [161]

theorem c103 : certCheck 251 D ILN 103 k103 = true := by decide +kernel

def k104 : Cert :=
  Cert.R [66]

theorem c104 : certCheck 251 D ILN 104 k104 = true := by decide +kernel

def k105 : Cert :=
  Cert.R [139]

theorem c105 : certCheck 251 D ILN 105 k105 = true := by decide +kernel

def k106 : Cert :=
  Cert.R [111]

theorem c106 : certCheck 251 D ILN 106 k106 = true := by decide +kernel

def k107 : Cert :=
  Cert.F [([222, 232, 1], [(1, [190, 231])]), ([210, 250, 1], [(1, [143, 216])]), ([63, 177, 76, 71, 1], [(2, [221, 167, 101, 74])])]
      [[(0, [([175, 38], [3, 0, 2, 0, 0, 0, 0, 0, 0]), ([95, 213], [3, 2, 0, 0, 0, 0, 0, 0, 0])]), (1, [([148, 46], [2, 2, 1, 0, 0, 0, 0, 0, 0]), ([104, 205], [2, 1, 2, 0, 0, 0, 0, 0, 0])])],
       [(0, [([32, 16], [0, 0, 0, 3, 0, 2, 0, 0, 0]), ([238, 235], [0, 0, 0, 3, 2, 0, 0, 0, 0])]), (1, [([107, 59], [0, 0, 0, 2, 2, 1, 0, 0, 0]), ([145, 192], [0, 0, 0, 2, 1, 2, 0, 0, 0])])],
       [(2, [([42, 180, 176, 33], [0, 0, 0, 0, 0, 0, 2, 0, 3]), ([210, 51, 172, 85], [0, 0, 0, 0, 0, 0, 2, 0, 3]), ([160, 129, 3, 142], [0, 0, 0, 0, 0, 0, 2, 3, 0]), ([19, 142, 151, 242], [0, 0, 0, 0, 0, 0, 2, 3, 0])])]]

theorem c107 : certCheck 251 D ILN 107 k107 = true := by decide +kernel

def k108 : Cert :=
  Cert.G 2 [1] [104, 203, 229, 26, 81, 165, 240] [165, 147, 236, 19, 154, 199, 207, 87]

theorem c108 : certCheck 251 D ILN 108 k108 = true := by decide +kernel

def k109 : Cert :=
  Cert.R [112]

theorem c109 : certCheck 251 D ILN 109 k109 = true := by decide +kernel

def k110 : Cert :=
  Cert.R [71]

theorem c110 : certCheck 251 D ILN 110 k110 = true := by decide +kernel

def k111 : Cert :=
  Cert.R [79]

theorem c111 : certCheck 251 D ILN 111 k111 = true := by decide +kernel

def k112 : Cert :=
  Cert.R [120]

theorem c112 : certCheck 251 D ILN 112 k112 = true := by decide +kernel

def k113 : Cert :=
  Cert.R [210]

theorem c113 : certCheck 251 D ILN 113 k113 = true := by decide +kernel

def k114 : Cert :=
  Cert.R [164]

theorem c114 : certCheck 251 D ILN 114 k114 = true := by decide +kernel

def k115 : Cert :=
  Cert.R [2]

theorem c115 : certCheck 251 D ILN 115 k115 = true := by decide +kernel

def k116 : Cert :=
  Cert.G 2 [1] [71, 149, 207, 184, 152, 187, 198] [240, 196, 211, 31, 72, 203, 112, 219]

theorem c116 : certCheck 251 D ILN 116 k116 = true := by decide +kernel

def k117 : Cert :=
  Cert.G 2 [1] [101, 201, 65, 83, 62, 110, 101] [133, 212, 83, 92, 213, 141, 201, 46]

theorem c117 : certCheck 251 D ILN 117 k117 = true := by decide +kernel

def k118 : Cert :=
  Cert.R [147]

theorem c118 : certCheck 251 D ILN 118 k118 = true := by decide +kernel

def k119 : Cert :=
  Cert.G 2 [1] [190, 206, 158, 224, 15, 49, 46] [190, 119, 109, 30, 213, 201, 79, 85]

theorem c119 : certCheck 251 D ILN 119 k119 = true := by decide +kernel

def k120 : Cert :=
  Cert.R [216]

theorem c120 : certCheck 251 D ILN 120 k120 = true := by decide +kernel

def certs0 : List (ℕ × Cert) := [(2, k2), (3, k3), (4, k4), (5, k5), (6, k6), (7, k7), (8, k8), (9, k9), (10, k10), (11, k11), (12, k12), (13, k13), (14, k14), (15, k15), (16, k16), (17, k17), (18, k18), (19, k19), (20, k20), (21, k21), (22, k22), (23, k23), (24, k24), (25, k25), (26, k26), (27, k27), (28, k28), (29, k29), (30, k30), (31, k31), (32, k32), (33, k33), (34, k34), (35, k35), (36, k36), (37, k37), (38, k38), (39, k39), (40, k40), (41, k41), (42, k42), (43, k43), (44, k44), (45, k45), (46, k46), (47, k47), (48, k48), (49, k49), (50, k50), (51, k51), (52, k52), (53, k53), (54, k54), (55, k55), (56, k56), (57, k57), (58, k58), (59, k59), (60, k60), (61, k61), (62, k62), (63, k63), (64, k64), (65, k65), (66, k66), (67, k67), (68, k68), (69, k69), (70, k70), (71, k71), (72, k72), (73, k73), (74, k74), (75, k75), (76, k76), (77, k77), (78, k78), (79, k79), (80, k80), (81, k81), (82, k82), (83, k83), (84, k84), (85, k85), (86, k86), (87, k87), (88, k88), (89, k89), (90, k90), (91, k91), (92, k92), (93, k93), (94, k94), (95, k95), (96, k96), (97, k97), (98, k98), (99, k99), (100, k100), (101, k101), (102, k102), (103, k103), (104, k104), (105, k105), (106, k106), (107, k107), (108, k108), (109, k109), (110, k110), (111, k111), (112, k112), (113, k113), (114, k114), (115, k115), (116, k116), (117, k117), (118, k118), (119, k119), (120, k120)]

theorem ok0 : certs0.all (fun p => certCheck 251 D ILN p.1 p.2) = true := by
  simp only [certs0, List.all_cons, List.all_nil, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31, c32, c33, c34, c35, c36, c37, c38, c39, c40, c41, c42, c43, c44, c45, c46, c47, c48, c49, c50, c51, c52, c53, c54, c55, c56, c57, c58, c59, c60, c61, c62, c63, c64, c65, c66, c67, c68, c69, c70, c71, c72, c73, c74, c75, c76, c77, c78, c79, c80, c81, c82, c83, c84, c85, c86, c87, c88, c89, c90, c91, c92, c93, c94, c95, c96, c97, c98, c99, c100, c101, c102, c103, c104, c105, c106, c107, c108, c109, c110, c111, c112, c113, c114, c115, c116, c117, c118, c119, c120, Bool.and_self]

end X2Y5Z7.SymbolSets.Q251
