/-
Generated by computer; every fact used is proved in Lean.
-/
module

public import X2Y5Z7.SymbolSets.Q251.C0

@[expose] public section

/-! # Proposition 5.3 at `q = 251`: certificates for `η = 121 … 171` (34 R, 12 G, 5 F) -/

namespace X2Y5Z7.SymbolSets.Q251

open X2Y5Z7.SymbolSets

def k121 : Cert :=
  Cert.F [([102, 1, 1], [(1, [214, 177])]), ([80, 77, 1], [(1, [2, 150])]), ([130, 58, 201, 224, 1], [(2, [165, 83, 140, 57])])]
      [[(0, [([239, 33], [0, 4, 1, 0, 0, 0, 0, 0, 0]), ([11, 218], [0, 1, 4, 0, 0, 0, 0, 0, 0])]), (1, [([13, 5], [2, 1, 2, 0, 0, 0, 0, 0, 0]), ([161, 246], [2, 2, 1, 0, 0, 0, 0, 0, 0])])],
       [(0, [([155, 105], [0, 0, 0, 0, 1, 4, 0, 0, 0]), ([95, 146], [0, 0, 0, 0, 4, 1, 0, 0, 0])]), (1, [([14, 121], [0, 0, 0, 2, 1, 2, 0, 0, 0]), ([160, 130], [0, 0, 0, 2, 2, 1, 0, 0, 0])])],
       [(2, [([174, 3, 232, 35], [0, 0, 0, 0, 0, 0, 0, 4, 1]), ([99, 136, 69, 70], [0, 0, 0, 0, 0, 0, 0, 1, 4]), ([19, 99, 109, 175], [0, 0, 0, 0, 0, 0, 0, 1, 4]), ([237, 13, 92, 222], [0, 0, 0, 0, 0, 0, 0, 4, 1])])]]

theorem c121 : certCheck 251 D ILN 121 k121 = true := by decide +kernel

def k122 : Cert :=
  Cert.R [85]

theorem c122 : certCheck 251 D ILN 122 k122 = true := by decide +kernel

def k123 : Cert :=
  Cert.R [30]

theorem c123 : certCheck 251 D ILN 123 k123 = true := by decide +kernel

def k124 : Cert :=
  Cert.R [17]

theorem c124 : certCheck 251 D ILN 124 k124 = true := by decide +kernel

def k125 : Cert :=
  Cert.R [198]

theorem c125 : certCheck 251 D ILN 125 k125 = true := by decide +kernel

def k126 : Cert :=
  Cert.G 2 [1] [7, 37, 77, 164, 71, 189, 181] [205, 16, 59, 168, 156, 149, 180, 106]

theorem c126 : certCheck 251 D ILN 126 k126 = true := by decide +kernel

def k127 : Cert :=
  Cert.F [([67, 44, 1], [(1, [71, 220])]), ([90, 50, 1], [(1, [224, 19])]), ([219, 126, 39, 208, 1], [(2, [16, 66, 112, 53])])]
      [[(0, [([4, 100], [3, 2, 0, 0, 0, 0, 0, 0, 0]), ([203, 151], [3, 0, 2, 0, 0, 0, 0, 0, 0])]), (1, [([35, 57], [0, 2, 3, 0, 0, 0, 0, 0, 0]), ([166, 194], [0, 3, 2, 0, 0, 0, 0, 0, 0])])],
       [(0, [([183, 90], [0, 0, 0, 3, 0, 2, 0, 0, 0]), ([24, 161], [0, 0, 0, 3, 2, 0, 0, 0, 0])]), (1, [([197, 24], [0, 0, 0, 0, 2, 3, 0, 0, 0]), ([4, 227], [0, 0, 0, 0, 3, 2, 0, 0, 0])])],
       [(2, [([104, 45, 125], [0, 0, 0, 0, 0, 0, 4, 4, 2]), ([89, 2, 11, 49], [0, 0, 0, 0, 0, 0, 4, 4, 2]), ([150, 63, 47, 59], [0, 0, 0, 0, 0, 0, 4, 2, 4]), ([202, 141, 68, 143], [0, 0, 0, 0, 0, 0, 4, 2, 4])])]]

theorem c127 : certCheck 251 D ILN 127 k127 = true := by decide +kernel

def k128 : Cert :=
  Cert.F [([110, 3, 1], [(1, [205, 53])]), ([46, 77, 1], [(1, [191, 18])]), ([243, 97, 36, 222, 1], [(2, [66, 21, 96, 231])])]
      [[(0, [([139, 77], [2, 4, 4, 0, 0, 0, 0, 0, 0]), ([109, 174], [2, 4, 4, 0, 0, 0, 0, 0, 0])]), (1, [([6, 36], [4, 2, 4, 0, 0, 0, 0, 0, 0]), ([168, 215], [4, 4, 2, 0, 0, 0, 0, 0, 0])])],
       [(0, [([54, 6], [0, 0, 0, 2, 4, 4, 0, 0, 0]), ([194, 245], [0, 0, 0, 2, 4, 4, 0, 0, 0])]), (1, [([214, 68], [0, 0, 0, 4, 2, 4, 0, 0, 0]), ([211, 183], [0, 0, 0, 4, 4, 2, 0, 0, 0])])],
       [(2, [([186, 153, 128, 90], [0, 0, 0, 0, 0, 0, 1, 0, 4]), ([230, 91, 41, 115], [0, 0, 0, 0, 0, 0, 1, 4, 0]), ([67, 184, 194, 145], [0, 0, 0, 0, 0, 0, 1, 4, 0]), ([48, 74, 139, 152], [0, 0, 0, 0, 0, 0, 1, 0, 4])])]]

theorem c128 : certCheck 251 D ILN 128 k128 = true := by decide +kernel

def k129 : Cert :=
  Cert.R [160]

theorem c129 : certCheck 251 D ILN 129 k129 = true := by decide +kernel

def k130 : Cert :=
  Cert.G 2 [1] [20, 107, 148, 169, 206, 98, 58] [230, 235, 129, 197, 92, 141, 54, 146]

theorem c130 : certCheck 251 D ILN 130 k130 = true := by decide +kernel

def k131 : Cert :=
  Cert.R [32]

theorem c131 : certCheck 251 D ILN 131 k131 = true := by decide +kernel

def k132 : Cert :=
  Cert.R [194]

theorem c132 : certCheck 251 D ILN 132 k132 = true := by decide +kernel

def k133 : Cert :=
  Cert.R [27]

theorem c133 : certCheck 251 D ILN 133 k133 = true := by decide +kernel

def k134 : Cert :=
  Cert.R [50]

theorem c134 : certCheck 251 D ILN 134 k134 = true := by decide +kernel

def k135 : Cert :=
  Cert.R [93]

theorem c135 : certCheck 251 D ILN 135 k135 = true := by decide +kernel

def k136 : Cert :=
  Cert.R [138]

theorem c136 : certCheck 251 D ILN 136 k136 = true := by decide +kernel

def k137 : Cert :=
  Cert.F [([145, 60, 1], [(1, [118, 188])]), ([105, 143, 1], [(1, [116, 128])]), ([93, 89, 49, 99, 1], [(2, [161, 124, 153, 26])])]
      [[(0, [([171, 78], [0, 1, 4, 0, 0, 0, 0, 0, 0]), ([20, 173], [0, 4, 1, 0, 0, 0, 0, 0, 0])]), (1, [([53, 112], [3, 0, 2, 0, 0, 0, 0, 0, 0]), ([55, 139], [3, 2, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([155, 20], [0, 0, 0, 0, 4, 1, 0, 0, 0]), ([36, 231], [0, 0, 0, 0, 1, 4, 0, 0, 0])]), (1, [([226, 100], [0, 0, 0, 3, 0, 2, 0, 0, 0]), ([133, 151], [0, 0, 0, 3, 2, 0, 0, 0, 0])])],
       [(2, [([66, 157, 106, 42], [0, 0, 0, 0, 0, 0, 4, 0, 1]), ([34, 130, 174, 74], [0, 0, 0, 0, 0, 0, 4, 1, 0]), ([93, 217, 63, 161], [0, 0, 0, 0, 0, 0, 4, 0, 1]), ([210, 249, 159, 225], [0, 0, 0, 0, 0, 0, 4, 1, 0])])]]

theorem c137 : certCheck 251 D ILN 137 k137 = true := by decide +kernel

def k138 : Cert :=
  Cert.R [15]

theorem c138 : certCheck 251 D ILN 138 k138 = true := by decide +kernel

def k139 : Cert :=
  Cert.G 2 [1] [245, 133, 15, 125, 131, 163, 54] [177, 91, 157, 61, 171, 163, 70, 143]

theorem c139 : certCheck 251 D ILN 139 k139 = true := by decide +kernel

def k140 : Cert :=
  Cert.G 2 [1] [197, 243, 2, 156, 131, 162, 138] [185, 227, 3, 137, 178, 248, 193, 152]

theorem c140 : certCheck 251 D ILN 140 k140 = true := by decide +kernel

def k141 : Cert :=
  Cert.R [114]

theorem c141 : certCheck 251 D ILN 141 k141 = true := by decide +kernel

def k142 : Cert :=
  Cert.R [145]

theorem c142 : certCheck 251 D ILN 142 k142 = true := by decide +kernel

def k143 : Cert :=
  Cert.G 2 [1] [83, 104, 103, 51, 15, 173, 206] [154, 127, 4, 0, 22, 92, 170, 233]

theorem c143 : certCheck 251 D ILN 143 k143 = true := by decide +kernel

def k144 : Cert :=
  Cert.R [42]

theorem c144 : certCheck 251 D ILN 144 k144 = true := by decide +kernel

def k145 : Cert :=
  Cert.R [123]

theorem c145 : certCheck 251 D ILN 145 k145 = true := by decide +kernel

def k146 : Cert :=
  Cert.G 2 [1] [42, 99, 165, 88, 115, 33, 7] [71, 187, 32, 163, 140, 173, 68, 136]

theorem c146 : certCheck 251 D ILN 146 k146 = true := by decide +kernel

def k147 : Cert :=
  Cert.R [140]

theorem c147 : certCheck 251 D ILN 147 k147 = true := by decide +kernel

def k148 : Cert :=
  Cert.R [131]

theorem c148 : certCheck 251 D ILN 148 k148 = true := by decide +kernel

def k149 : Cert :=
  Cert.G 2 [1] [241, 76, 49, 149, 118, 195, 69] [128, 214, 59, 199, 238, 134, 188, 109]

theorem c149 : certCheck 251 D ILN 149 k149 = true := by decide +kernel

def k150 : Cert :=
  Cert.G 2 [1] [240, 201, 33, 184, 2, 217, 142] [52, 250, 79, 241, 109, 231, 161, 176]

theorem c150 : certCheck 251 D ILN 150 k150 = true := by decide +kernel

def k151 : Cert :=
  Cert.R [162]

theorem c151 : certCheck 251 D ILN 151 k151 = true := by decide +kernel

def k152 : Cert :=
  Cert.G 2 [1] [95, 215, 148, 34, 86, 56, 44] [54, 236, 7, 121, 66, 88, 144, 215]

theorem c152 : certCheck 251 D ILN 152 k152 = true := by decide +kernel

def k153 : Cert :=
  Cert.R [10]

theorem c153 : certCheck 251 D ILN 153 k153 = true := by decide +kernel

def k154 : Cert :=
  Cert.R [207]

theorem c154 : certCheck 251 D ILN 154 k154 = true := by decide +kernel

def k155 : Cert :=
  Cert.R [4]

theorem c155 : certCheck 251 D ILN 155 k155 = true := by decide +kernel

def k156 : Cert :=
  Cert.R [44]

theorem c156 : certCheck 251 D ILN 156 k156 = true := by decide +kernel

def k157 : Cert :=
  Cert.R [55]

theorem c157 : certCheck 251 D ILN 157 k157 = true := by decide +kernel

def k158 : Cert :=
  Cert.R [38]

theorem c158 : certCheck 251 D ILN 158 k158 = true := by decide +kernel

def k159 : Cert :=
  Cert.R [158]

theorem c159 : certCheck 251 D ILN 159 k159 = true := by decide +kernel

def k160 : Cert :=
  Cert.R [105]

theorem c160 : certCheck 251 D ILN 160 k160 = true := by decide +kernel

def k161 : Cert :=
  Cert.R [54]

theorem c161 : certCheck 251 D ILN 161 k161 = true := by decide +kernel

def k162 : Cert :=
  Cert.R [108]

theorem c162 : certCheck 251 D ILN 162 k162 = true := by decide +kernel

def k163 : Cert :=
  Cert.R [24]

theorem c163 : certCheck 251 D ILN 163 k163 = true := by decide +kernel

def k164 : Cert :=
  Cert.R [25]

theorem c164 : certCheck 251 D ILN 164 k164 = true := by decide +kernel

def k165 : Cert :=
  Cert.G 2 [1] [179, 89, 169, 100, 149, 107, 237] [105, 32, 151, 77, 221, 11, 138, 109]

theorem c165 : certCheck 251 D ILN 165 k165 = true := by decide +kernel

def k166 : Cert :=
  Cert.R [35]

theorem c166 : certCheck 251 D ILN 166 k166 = true := by decide +kernel

def k167 : Cert :=
  Cert.R [206]

theorem c167 : certCheck 251 D ILN 167 k167 = true := by decide +kernel

def k168 : Cert :=
  Cert.G 2 [1] [214, 19, 65, 110, 71, 190, 195] [198, 216, 107, 86, 152, 171, 103, 240]

theorem c168 : certCheck 251 D ILN 168 k168 = true := by decide +kernel

def k169 : Cert :=
  Cert.G 2 [1] [77, 238, 192, 10, 57, 9, 211] [243, 55, 9, 162, 56, 80, 107, 79]

theorem c169 : certCheck 251 D ILN 169 k169 = true := by decide +kernel

def k170 : Cert :=
  Cert.F [([13, 2, 1], [(1, [136, 136])]), ([147, 88, 1], [(1, [15, 200])]), ([126, 8, 22, 212, 1], [(2, [104, 207, 32, 207])])]
      [[(0, [([77, 49], [4, 3, 3, 0, 0, 0, 0, 0, 0]), ([172, 202], [4, 3, 3, 0, 0, 0, 0, 0, 0])]), (1, [([7, 61], [2, 0, 3, 0, 0, 0, 0, 0, 0]), ([156, 190], [2, 3, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([112, 19], [0, 0, 0, 4, 3, 3, 0, 0, 0]), ([137, 232], [0, 0, 0, 4, 3, 3, 0, 0, 0])]), (1, [([194, 80], [0, 0, 0, 2, 3, 0, 0, 0, 0]), ([220, 171], [0, 0, 0, 2, 0, 3, 0, 0, 0])])],
       [(2, [([150, 74, 66, 58], [0, 0, 0, 0, 0, 0, 1, 4, 0]), ([101, 146, 128, 103], [0, 0, 0, 0, 0, 0, 1, 0, 4]), ([173, 24, 177, 149], [0, 0, 0, 0, 0, 0, 1, 0, 4]), ([117, 7, 131, 192], [0, 0, 0, 0, 0, 0, 1, 4, 0])])]]

theorem c170 : certCheck 251 D ILN 170 k170 = true := by decide +kernel

def k171 : Cert :=
  Cert.R [103]

theorem c171 : certCheck 251 D ILN 171 k171 = true := by decide +kernel

def certs1 : List (ℕ × Cert) := [(121, k121), (122, k122), (123, k123), (124, k124), (125, k125), (126, k126), (127, k127), (128, k128), (129, k129), (130, k130), (131, k131), (132, k132), (133, k133), (134, k134), (135, k135), (136, k136), (137, k137), (138, k138), (139, k139), (140, k140), (141, k141), (142, k142), (143, k143), (144, k144), (145, k145), (146, k146), (147, k147), (148, k148), (149, k149), (150, k150), (151, k151), (152, k152), (153, k153), (154, k154), (155, k155), (156, k156), (157, k157), (158, k158), (159, k159), (160, k160), (161, k161), (162, k162), (163, k163), (164, k164), (165, k165), (166, k166), (167, k167), (168, k168), (169, k169), (170, k170), (171, k171)]

theorem ok1 : certs1.all (fun p => certCheck 251 D ILN p.1 p.2) = true := by
  simp only [certs1, List.all_cons, List.all_nil, c121, c122, c123, c124, c125, c126, c127, c128, c129, c130, c131, c132, c133, c134, c135, c136, c137, c138, c139, c140, c141, c142, c143, c144, c145, c146, c147, c148, c149, c150, c151, c152, c153, c154, c155, c156, c157, c158, c159, c160, c161, c162, c163, c164, c165, c166, c167, c168, c169, c170, c171, Bool.and_self]

end X2Y5Z7.SymbolSets.Q251
