/-
Generated by computer; every fact used is proved in Lean.
-/
import X2Y5Z7.SymbolSets.Q251.C1

/-! # Proposition 5.3 at `q = 251`: certificates for `η = 172 … 216` (28 R, 11 G, 6 F) -/

namespace X2Y5Z7.SymbolSets.Q251

open X2Y5Z7.SymbolSets

def k172 : Cert :=
  Cert.F [([164, 24, 1], [(1, [176, 182])]), ([200, 107, 1], [(1, [250, 129])]), ([27, 146, 129, 171, 1], [(2, [96, 194, 155, 232])])]
      [[(0, [([229, 116], [1, 0, 4, 0, 0, 0, 0, 0, 0]), ([249, 135], [1, 4, 0, 0, 0, 0, 0, 0, 0])]), (1, [([168, 41], [3, 3, 4, 0, 0, 0, 0, 0, 0]), ([227, 210], [3, 4, 3, 0, 0, 0, 0, 0, 0])])],
       [(0, [([25, 4], [0, 0, 0, 1, 4, 0, 0, 0, 0]), ([202, 247], [0, 0, 0, 1, 0, 4, 0, 0, 0])]), (1, [([18, 62], [0, 0, 0, 3, 4, 3, 0, 0, 0]), ([126, 189], [0, 0, 0, 3, 3, 4, 0, 0, 0])])],
       [(2, [([78, 149, 225, 51], [0, 0, 0, 0, 0, 0, 3, 1, 1]), ([249, 35, 151, 130], [0, 0, 0, 0, 0, 0, 3, 1, 1]), ([240, 15, 84, 136], [0, 0, 0, 0, 0, 0, 3, 1, 1]), ([15, 52, 42, 185], [0, 0, 0, 0, 0, 0, 3, 1, 1])])]]

theorem c172 : certCheck 251 D ILN 172 k172 = true := by decide +kernel

def k173 : Cert :=
  Cert.R [77]

theorem c173 : certCheck 251 D ILN 173 k173 = true := by decide +kernel

def k174 : Cert :=
  Cert.F [([74, 159, 1], [(1, [200, 203])]), ([13, 209, 1], [(1, [66, 212])]), ([100, 241, 117, 185, 1], [(2, [23, 75, 208, 106])])]
      [[(0, [([37, 4], [0, 2, 3, 0, 0, 0, 0, 0, 0]), ([55, 247], [0, 3, 2, 0, 0, 0, 0, 0, 0])]), (1, [([139, 87], [1, 0, 4, 0, 0, 0, 0, 0, 0]), ([154, 164], [1, 4, 0, 0, 0, 0, 0, 0, 0])])],
       [(0, [([4, 104], [0, 0, 0, 0, 3, 2, 0, 0, 0]), ([88, 147], [0, 0, 0, 0, 2, 3, 0, 0, 0])]), (1, [([237, 3], [0, 0, 0, 1, 4, 0, 0, 0, 0]), ([56, 248], [0, 0, 0, 1, 0, 4, 0, 0, 0])])],
       [(2, [([128, 22, 83, 1], [0, 0, 0, 0, 0, 0, 1, 3, 1]), ([56, 169, 213, 74], [0, 0, 0, 0, 0, 0, 1, 1, 3]), ([61, 61, 29, 187], [0, 0, 0, 0, 0, 0, 1, 3, 1]), ([72, 250, 177, 240], [0, 0, 0, 0, 0, 0, 1, 1, 3])])]]

theorem c174 : certCheck 251 D ILN 174 k174 = true := by decide +kernel

def k175 : Cert :=
  Cert.G 2 [1] [199, 250, 174, 97, 100, 228, 27] [95, 37, 202, 64, 217, 144, 223, 172]

theorem c175 : certCheck 251 D ILN 175 k175 = true := by decide +kernel

def k176 : Cert :=
  Cert.R [83]

theorem c176 : certCheck 251 D ILN 176 k176 = true := by decide +kernel

def k177 : Cert :=
  Cert.G 2 [216, 144, 1] [88, 131, 166, 144, 225] [80, 249, 27, 246, 85, 90]

theorem c177 : certCheck 251 D ILN 177 k177 = true := by decide +kernel

def k178 : Cert :=
  Cert.G 2 [1] [222, 30, 149, 152, 8, 20, 163] [38, 85, 28, 167, 57, 22, 150, 71]

theorem c178 : certCheck 251 D ILN 178 k178 = true := by decide +kernel

def k179 : Cert :=
  Cert.R [167]

theorem c179 : certCheck 251 D ILN 179 k179 = true := by decide +kernel

def k180 : Cert :=
  Cert.F [([121, 135, 1], [(1, [237, 182])]), ([221, 230, 1], [(1, [145, 34])]), ([164, 83, 248, 188, 1], [(2, [250, 158, 125, 225])])]
      [[(0, [([48, 116], [3, 0, 2, 0, 0, 0, 0, 0, 0]), ([68, 135], [3, 2, 0, 0, 0, 0, 0, 0, 0])]), (1, [([41, 98], [3, 4, 3, 0, 0, 0, 0, 0, 0]), ([231, 153], [3, 3, 4, 0, 0, 0, 0, 0, 0])])],
       [(0, [([95, 4], [0, 0, 0, 3, 2, 0, 0, 0, 0]), ([21, 247], [0, 0, 0, 3, 0, 2, 0, 0, 0])]), (1, [([111, 38], [0, 0, 0, 3, 3, 4, 0, 0, 0]), ([161, 213], [0, 0, 0, 3, 4, 3, 0, 0, 0])])],
       [(2, [([176, 104, 87, 15], [0, 0, 0, 0, 0, 0, 1, 4, 0]), ([209, 249, 96, 86], [0, 0, 0, 0, 0, 0, 1, 4, 0]), ([175, 161, 60, 185], [0, 0, 0, 0, 0, 0, 1, 0, 4]), ([5, 239, 8, 216], [0, 0, 0, 0, 0, 0, 1, 0, 4])])]]

theorem c180 : certCheck 251 D ILN 180 k180 = true := by decide +kernel

def k181 : Cert :=
  Cert.R [1]

theorem c181 : certCheck 251 D ILN 181 k181 = true := by decide +kernel

def k182 : Cert :=
  Cert.G 2 [1] [182, 73, 234, 30, 0, 35, 175] [15, 212, 43, 245, 78, 179, 236, 240]

theorem c182 : certCheck 251 D ILN 182 k182 = true := by decide +kernel

def k183 : Cert :=
  Cert.G 2 [1] [50, 14, 5, 236, 3, 140, 169] [216, 130, 112, 150, 7, 46, 175, 171]

theorem c183 : certCheck 251 D ILN 183 k183 = true := by decide +kernel

def k184 : Cert :=
  Cert.R [220]

theorem c184 : certCheck 251 D ILN 184 k184 = true := by decide +kernel

def k185 : Cert :=
  Cert.R [62]

theorem c185 : certCheck 251 D ILN 185 k185 = true := by decide +kernel

def k186 : Cert :=
  Cert.R [47]

theorem c186 : certCheck 251 D ILN 186 k186 = true := by decide +kernel

def k187 : Cert :=
  Cert.R [5]

theorem c187 : certCheck 251 D ILN 187 k187 = true := by decide +kernel

def k188 : Cert :=
  Cert.R [228]

theorem c188 : certCheck 251 D ILN 188 k188 = true := by decide +kernel

def k189 : Cert :=
  Cert.R [113]

theorem c189 : certCheck 251 D ILN 189 k189 = true := by decide +kernel

def k190 : Cert :=
  Cert.R [182]

theorem c190 : certCheck 251 D ILN 190 k190 = true := by decide +kernel

def k191 : Cert :=
  Cert.G 2 [1] [124, 103, 95, 69, 208, 184, 82] [125, 135, 6, 198, 194, 42, 60, 59]

theorem c191 : certCheck 251 D ILN 191 k191 = true := by decide +kernel

def k192 : Cert :=
  Cert.R [22]

theorem c192 : certCheck 251 D ILN 192 k192 = true := by decide +kernel

def k193 : Cert :=
  Cert.R [136]

theorem c193 : certCheck 251 D ILN 193 k193 = true := by decide +kernel

def k194 : Cert :=
  Cert.R [141]

theorem c194 : certCheck 251 D ILN 194 k194 = true := by decide +kernel

def k195 : Cert :=
  Cert.F [([221, 115, 1], [(1, [63, 239])]), ([52, 154, 1], [(1, [66, 216])]), ([16, 246, 108, 33, 1], [(2, [161, 157, 229, 190])])]
      [[(0, [([50, 8], [0, 2, 3, 0, 0, 0, 0, 0, 0]), ([86, 243], [0, 3, 2, 0, 0, 0, 0, 0, 0])]), (1, [([196, 46], [1, 4, 0, 0, 0, 0, 0, 0, 0]), ([152, 205], [1, 0, 4, 0, 0, 0, 0, 0, 0])])],
       [(0, [([152, 43], [0, 0, 0, 0, 2, 3, 0, 0, 0]), ([235, 208], [0, 0, 0, 0, 3, 2, 0, 0, 0])]), (1, [([155, 59], [0, 0, 0, 1, 4, 0, 0, 0, 0]), ([193, 192], [0, 0, 0, 1, 0, 4, 0, 0, 0])])],
       [(2, [([4, 30, 172, 13], [0, 0, 0, 0, 0, 0, 1, 1, 3]), ([69, 110, 49, 59], [0, 0, 0, 0, 0, 0, 1, 3, 1]), ([89, 11, 205, 206], [0, 0, 0, 0, 0, 0, 1, 3, 1]), ([56, 100, 76, 224], [0, 0, 0, 0, 0, 0, 1, 1, 3])])]]

theorem c195 : certCheck 251 D ILN 195 k195 = true := by decide +kernel

def k196 : Cert :=
  Cert.R [99]

theorem c196 : certCheck 251 D ILN 196 k196 = true := by decide +kernel

def k197 : Cert :=
  Cert.R [180]

theorem c197 : certCheck 251 D ILN 197 k197 = true := by decide +kernel

def k198 : Cert :=
  Cert.R [39]

theorem c198 : certCheck 251 D ILN 198 k198 = true := by decide +kernel

def k199 : Cert :=
  Cert.R [98]

theorem c199 : certCheck 251 D ILN 199 k199 = true := by decide +kernel

def k200 : Cert :=
  Cert.R [107]

theorem c200 : certCheck 251 D ILN 200 k200 = true := by decide +kernel

def k201 : Cert :=
  Cert.R [159]

theorem c201 : certCheck 251 D ILN 201 k201 = true := by decide +kernel

def k202 : Cert :=
  Cert.G 2 [1] [59, 4, 230, 83, 91, 136, 136] [247, 84, 118, 122, 21, 18, 202, 208]

theorem c202 : certCheck 251 D ILN 202 k202 = true := by decide +kernel

def k203 : Cert :=
  Cert.R [125]

theorem c203 : certCheck 251 D ILN 203 k203 = true := by decide +kernel

def k204 : Cert :=
  Cert.F [([68, 130, 1], [(1, [6, 170])]), ([229, 214, 1], [(1, [240, 82])]), ([200, 45, 247, 209, 1], [(2, [51, 150, 7, 132])])]
      [[(0, [([239, 88], [2, 3, 0, 0, 0, 0, 0, 0, 0]), ([133, 163], [2, 0, 3, 0, 0, 0, 0, 0, 0])]), (1, [([200, 3], [2, 3, 0, 0, 0, 0, 0, 0, 0]), ([88, 248], [2, 0, 3, 0, 0, 0, 0, 0, 0])])],
       [(0, [([15, 29], [0, 0, 0, 2, 0, 3, 0, 0, 0]), ([106, 222], [0, 0, 0, 2, 3, 0, 0, 0, 0])]), (1, [([238, 78], [0, 0, 0, 2, 0, 3, 0, 0, 0]), ([50, 173], [0, 0, 0, 2, 3, 0, 0, 0, 0])])],
       [(2, [([219, 83, 168, 148], [0, 0, 0, 0, 0, 0, 3, 1, 1]), ([240, 207, 108, 171], [0, 0, 0, 0, 0, 0, 3, 1, 1]), ([37, 108, 123, 206], [0, 0, 0, 0, 0, 0, 3, 1, 1]), ([48, 104, 103, 228], [0, 0, 0, 0, 0, 0, 3, 1, 1])])]]

theorem c204 : certCheck 251 D ILN 204 k204 = true := by decide +kernel

def k205 : Cert :=
  Cert.G 2 [1] [68, 30, 157, 84, 178, 155, 169] [6, 116, 16, 197, 37, 89, 84, 131]

theorem c205 : certCheck 251 D ILN 205 k205 = true := by decide +kernel

def k206 : Cert :=
  Cert.G 2 [1] [84, 106, 107, 229, 219, 50, 88] [110, 181, 235, 153, 119, 173, 216, 8]

theorem c206 : certCheck 251 D ILN 206 k206 = true := by decide +kernel

def k207 : Cert :=
  Cert.R [89]

theorem c207 : certCheck 251 D ILN 207 k207 = true := by decide +kernel

def k208 : Cert :=
  Cert.R [185]

theorem c208 : certCheck 251 D ILN 208 k208 = true := by decide +kernel

def k209 : Cert :=
  Cert.R [157]

theorem c209 : certCheck 251 D ILN 209 k209 = true := by decide +kernel

def k210 : Cert :=
  Cert.G 2 [1] [118, 99, 68, 48, 248, 13, 225] [171, 200, 45, 163, 82, 119, 61, 28]

theorem c210 : certCheck 251 D ILN 210 k210 = true := by decide +kernel

def k211 : Cert :=
  Cert.R [82]

theorem c211 : certCheck 251 D ILN 211 k211 = true := by decide +kernel

def k212 : Cert :=
  Cert.R [61]

theorem c212 : certCheck 251 D ILN 212 k212 = true := by decide +kernel

def k213 : Cert :=
  Cert.R [179]

theorem c213 : certCheck 251 D ILN 213 k213 = true := by decide +kernel

def k214 : Cert :=
  Cert.R [46]

theorem c214 : certCheck 251 D ILN 214 k214 = true := by decide +kernel

def k215 : Cert :=
  Cert.F [([142, 45, 1], [(1, [88, 82])]), ([173, 92, 1], [(1, [66, 56])]), ([107, 2, 159, 165, 1], [(2, [18, 129, 244, 119])])]
      [[(0, [([159, 3], [1, 2, 2, 0, 0, 0, 0, 0, 0]), ([47, 248], [1, 2, 2, 0, 0, 0, 0, 0, 0])]), (1, [([229, 73], [3, 3, 4, 0, 0, 0, 0, 0, 0]), ([181, 178], [3, 4, 3, 0, 0, 0, 0, 0, 0])])],
       [(0, [([197, 78], [0, 0, 0, 1, 2, 2, 0, 0, 0]), ([9, 173], [0, 0, 0, 1, 2, 2, 0, 0, 0])]), (1, [([93, 110], [0, 0, 0, 3, 3, 4, 0, 0, 0]), ([66, 141], [0, 0, 0, 3, 4, 3, 0, 0, 0])])],
       [(2, [([171, 227, 29, 27], [0, 0, 0, 0, 0, 0, 3, 0, 2]), ([227, 181, 59, 31], [0, 0, 0, 0, 0, 0, 3, 2, 0]), ([126, 103, 170, 201], [0, 0, 0, 0, 0, 0, 3, 2, 0]), ([64, 242, 244, 243], [0, 0, 0, 0, 0, 0, 3, 0, 2])])]]

theorem c215 : certCheck 251 D ILN 215 k215 = true := by decide +kernel

def k216 : Cert :=
  Cert.G 2 [1] [133, 72, 109, 196, 242, 92, 182] [246, 104, 123, 245, 204, 102, 16, 115]

theorem c216 : certCheck 251 D ILN 216 k216 = true := by decide +kernel

def certs2 : List (ℕ × Cert) := [(172, k172), (173, k173), (174, k174), (175, k175), (176, k176), (177, k177), (178, k178), (179, k179), (180, k180), (181, k181), (182, k182), (183, k183), (184, k184), (185, k185), (186, k186), (187, k187), (188, k188), (189, k189), (190, k190), (191, k191), (192, k192), (193, k193), (194, k194), (195, k195), (196, k196), (197, k197), (198, k198), (199, k199), (200, k200), (201, k201), (202, k202), (203, k203), (204, k204), (205, k205), (206, k206), (207, k207), (208, k208), (209, k209), (210, k210), (211, k211), (212, k212), (213, k213), (214, k214), (215, k215), (216, k216)]

theorem ok2 : certs2.all (fun p => certCheck 251 D ILN p.1 p.2) = true := by
  simp only [certs2, List.all_cons, List.all_nil, c172, c173, c174, c175, c176, c177, c178, c179, c180, c181, c182, c183, c184, c185, c186, c187, c188, c189, c190, c191, c192, c193, c194, c195, c196, c197, c198, c199, c200, c201, c202, c203, c204, c205, c206, c207, c208, c209, c210, c211, c212, c213, c214, c215, c216, Bool.and_self]

end X2Y5Z7.SymbolSets.Q251
