/-
Generated by computer; every fact used is proved in Lean.
-/
module

public import X2Y5Z7.SymbolSets.Q251.C2

@[expose] public section

/-! # Proposition 5.3 at `q = 251`: certificates for `η = 217 … 250` (21 R, 11 G, 2 F) -/

namespace X2Y5Z7.SymbolSets.Q251

open X2Y5Z7.SymbolSets

def k217 : Cert :=
  Cert.R [60]

theorem c217 : certCheck 251 D ILN 217 k217 = true := by decide +kernel

def k218 : Cert :=
  Cert.R [70]

theorem c218 : certCheck 251 D ILN 218 k218 = true := by decide +kernel

def k219 : Cert :=
  Cert.G 2 [1] [65, 93, 169, 197, 212, 158, 38] [51, 54, 131, 73, 180, 235, 126, 36]

theorem c219 : certCheck 251 D ILN 219 k219 = true := by decide +kernel

def k220 : Cert :=
  Cert.R [33]

theorem c220 : certCheck 251 D ILN 220 k220 = true := by decide +kernel

def k221 : Cert :=
  Cert.G 2 [1] [192, 54, 93, 118, 228, 86, 144] [156, 225, 23, 201, 0, 215, 26, 218]

theorem c221 : certCheck 251 D ILN 221 k221 = true := by decide +kernel

def k222 : Cert :=
  Cert.R [34]

theorem c222 : certCheck 251 D ILN 222 k222 = true := by decide +kernel

def k223 : Cert :=
  Cert.F [([32, 5, 1], [(1, [195, 78])]), ([215, 228, 1], [(1, [166, 182])]), ([220, 92, 217, 69, 1], [(2, [47, 35, 75, 66])])]
      [[(0, [([221, 68], [0, 3, 2, 0, 0, 0, 0, 0, 0]), ([25, 183], [0, 2, 3, 0, 0, 0, 0, 0, 0])]), (1, [([127, 116], [1, 2, 2, 0, 0, 0, 0, 0, 0]), ([147, 135], [1, 2, 2, 0, 0, 0, 0, 0, 0])])],
       [(0, [([162, 11], [0, 0, 0, 0, 2, 3, 0, 0, 0]), ([84, 240], [0, 0, 0, 0, 3, 2, 0, 0, 0])]), (1, [([174, 4], [0, 0, 0, 1, 2, 2, 0, 0, 0]), ([100, 247], [0, 0, 0, 1, 2, 2, 0, 0, 0])])],
       [(2, [([24, 83, 177, 6], [0, 0, 0, 0, 0, 0, 1, 4, 0]), ([83, 228, 34, 142], [0, 0, 0, 0, 0, 0, 1, 4, 0]), ([169, 219, 86, 161], [0, 0, 0, 0, 0, 0, 1, 0, 4]), ([157, 223, 205, 193], [0, 0, 0, 0, 0, 0, 1, 0, 4])])]]

theorem c223 : certCheck 251 D ILN 223 k223 = true := by decide +kernel

def k224 : Cert :=
  Cert.G 2 [151, 54, 1] [58, 37, 112, 113, 230] [126, 250, 14, 195, 112, 173]

theorem c224 : certCheck 251 D ILN 224 k224 = true := by decide +kernel

def k225 : Cert :=
  Cert.R [109]

theorem c225 : certCheck 251 D ILN 225 k225 = true := by decide +kernel

def k226 : Cert :=
  Cert.R [171]

theorem c226 : certCheck 251 D ILN 226 k226 = true := by decide +kernel

def k227 : Cert :=
  Cert.G 2 [1] [146, 182, 205, 199, 63, 85, 59] [20, 178, 143, 125, 17, 35, 227, 208]

theorem c227 : certCheck 251 D ILN 227 k227 = true := by decide +kernel

def k228 : Cert :=
  Cert.G 2 [1] [30, 61, 0, 67, 151, 221, 126] [33, 10, 226, 137, 237, 135, 184, 157]

theorem c228 : certCheck 251 D ILN 228 k228 = true := by decide +kernel

def k229 : Cert :=
  Cert.R [74]

theorem c229 : certCheck 251 D ILN 229 k229 = true := by decide +kernel

def k230 : Cert :=
  Cert.R [40]

theorem c230 : certCheck 251 D ILN 230 k230 = true := by decide +kernel

def k231 : Cert :=
  Cert.R [51]

theorem c231 : certCheck 251 D ILN 231 k231 = true := by decide +kernel

def k232 : Cert :=
  Cert.R [134]

theorem c232 : certCheck 251 D ILN 232 k232 = true := by decide +kernel

def k233 : Cert :=
  Cert.R [23]

theorem c233 : certCheck 251 D ILN 233 k233 = true := by decide +kernel

def k234 : Cert :=
  Cert.G 2 [1] [2, 54, 190, 7, 149, 180, 198] [28, 1, 129, 183, 162, 53, 238, 49]

theorem c234 : certCheck 251 D ILN 234 k234 = true := by decide +kernel

def k235 : Cert :=
  Cert.G 2 [1] [141, 6, 207, 236, 178, 238, 209] [250, 202, 207, 107, 192, 179, 130, 236]

theorem c235 : certCheck 251 D ILN 235 k235 = true := by decide +kernel

def k236 : Cert :=
  Cert.F [([65, 2, 1], [(1, [151, 151])]), ([182, 116, 1], [(1, [146, 141])]), ([81, 13, 8, 184, 1], [(2, [41, 108, 240, 127])])]
      [[(0, [([122, 29], [1, 3, 1, 0, 0, 0, 0, 0, 0]), ([127, 222], [1, 1, 3, 0, 0, 0, 0, 0, 0])]), (1, [([49, 64], [1, 2, 2, 0, 0, 0, 0, 0, 0]), ([86, 187], [1, 2, 2, 0, 0, 0, 0, 0, 0])])],
       [(0, [([71, 1], [0, 0, 0, 1, 1, 3, 0, 0, 0]), ([178, 250], [0, 0, 0, 1, 3, 1, 0, 0, 0])]), (1, [([112, 93], [0, 0, 0, 1, 2, 2, 0, 0, 0]), ([23, 158], [0, 0, 0, 1, 2, 2, 0, 0, 0])])],
       [(2, [([150, 27, 240, 76], [0, 0, 0, 0, 0, 0, 0, 2, 3]), ([76, 86, 29, 86], [0, 0, 0, 0, 0, 0, 0, 3, 2]), ([155, 144, 148, 145], [0, 0, 0, 0, 0, 0, 0, 2, 3]), ([188, 245, 85, 195], [0, 0, 0, 0, 0, 0, 0, 3, 2])])]]

theorem c236 : certCheck 251 D ILN 236 k236 = true := by decide +kernel

def k237 : Cert :=
  Cert.R [73]

theorem c237 : certCheck 251 D ILN 237 k237 = true := by decide +kernel

def k238 : Cert :=
  Cert.R [13]

theorem c238 : certCheck 251 D ILN 238 k238 = true := by decide +kernel

def k239 : Cert :=
  Cert.G 2 [139, 56, 1] [230, 148, 38, 21, 206] [235, 184, 105, 168, 217, 182]

theorem c239 : certCheck 251 D ILN 239 k239 = true := by decide +kernel

def k240 : Cert :=
  Cert.R [97]

theorem c240 : certCheck 251 D ILN 240 k240 = true := by decide +kernel

def k241 : Cert :=
  Cert.R [115]

theorem c241 : certCheck 251 D ILN 241 k241 = true := by decide +kernel

def k242 : Cert :=
  Cert.R [132]

theorem c242 : certCheck 251 D ILN 242 k242 = true := by decide +kernel

def k243 : Cert :=
  Cert.R [96]

theorem c243 : certCheck 251 D ILN 243 k243 = true := by decide +kernel

def k244 : Cert :=
  Cert.G 2 [36, 197, 1] [20, 190, 83, 127, 82] [30, 84, 95, 96, 118, 35]

theorem c244 : certCheck 251 D ILN 244 k244 = true := by decide +kernel

def k245 : Cert :=
  Cert.R [191]

theorem c245 : certCheck 251 D ILN 245 k245 = true := by decide +kernel

def k246 : Cert :=
  Cert.R [6]

theorem c246 : certCheck 251 D ILN 246 k246 = true := by decide +kernel

def k247 : Cert :=
  Cert.R [122]

theorem c247 : certCheck 251 D ILN 247 k247 = true := by decide +kernel

def k248 : Cert :=
  Cert.R [214]

theorem c248 : certCheck 251 D ILN 248 k248 = true := by decide +kernel

def k249 : Cert :=
  Cert.G 2 [1] [121, 73, 3, 28, 4, 241, 198] [145, 51, 185, 176, 45, 234, 89, 102]

theorem c249 : certCheck 251 D ILN 249 k249 = true := by decide +kernel

def k250 : Cert :=
  Cert.G 2 [1] [213, 249, 132, 86, 123, 63, 91] [142, 90, 27, 57, 171, 174, 96, 7]

theorem c250 : certCheck 251 D ILN 250 k250 = true := by decide +kernel

def certs3 : List (ℕ × Cert) := [(217, k217), (218, k218), (219, k219), (220, k220), (221, k221), (222, k222), (223, k223), (224, k224), (225, k225), (226, k226), (227, k227), (228, k228), (229, k229), (230, k230), (231, k231), (232, k232), (233, k233), (234, k234), (235, k235), (236, k236), (237, k237), (238, k238), (239, k239), (240, k240), (241, k241), (242, k242), (243, k243), (244, k244), (245, k245), (246, k246), (247, k247), (248, k248), (249, k249), (250, k250)]

theorem ok3 : certs3.all (fun p => certCheck 251 D ILN p.1 p.2) = true := by
  simp only [certs3, List.all_cons, List.all_nil, c217, c218, c219, c220, c221, c222, c223, c224, c225, c226, c227, c228, c229, c230, c231, c232, c233, c234, c235, c236, c237, c238, c239, c240, c241, c242, c243, c244, c245, c246, c247, c248, c249, c250, Bool.and_self]

end X2Y5Z7.SymbolSets.Q251
